opendlv::logic::perception::GroundSurfaceProperty Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSurfaceProperty ()=default
GroundSurfaceProperty (const GroundSurfaceProperty &)=default
GroundSurfaceProperty & operator= (const GroundSurfaceProperty &)=default
GroundSurfaceProperty (GroundSurfaceProperty &&)=default
GroundSurfaceProperty & operator= (GroundSurfaceProperty &&)=default
~GroundSurfaceProperty ()=default
GroundSurfaceProperty & surfaceId (const uint32_t &v) noexcept
uint32_t surfaceId () const noexcept
GroundSurfaceProperty & property (const std::string &v) noexcept
std::string property () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_surfaceId { 0 }
std::string m_property { ``s }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSurfaceProperty`
static constexpr const char * TheLongName = `opendlv.logic.perception.GroundSurfaceProperty`
Constructor & Destructor Documentation
GroundSurfaceProperty() [1/3]
opendlv::logic::perception::GroundSurfaceProperty::GroundSurfaceProperty () [default]
GroundSurfaceProperty() [2/3]
opendlv::logic::perception::GroundSurfaceProperty::GroundSurfaceProperty (const GroundSurfaceProperty &) [default]
GroundSurfaceProperty() [3/3]
opendlv::logic::perception::GroundSurfaceProperty::GroundSurfaceProperty (GroundSurfaceProperty &&) [default]
 GroundSurfaceProperty()
opendlv::logic::perception::GroundSurfaceProperty::~GroundSurfaceProperty () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::GroundSurfaceProperty::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("std::string"s), std::move("property"s), m_property, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceProperty::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("std::string"s), std::move("property"s), m_property, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceProperty::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
            doVisit(2, std::move("std::string"s), std::move("property"s), m_property, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::GroundSurfaceProperty::ID () [inline], [static]
                                   {
            return 1142;
        }
LongName()
static const std::string opendlv::logic::perception::GroundSurfaceProperty::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSurfaceProperty & opendlv::logic::perception::GroundSurfaceProperty::operator= (const GroundSurfaceProperty &) [default]
operator=() [2/2]
GroundSurfaceProperty & opendlv::logic::perception::GroundSurfaceProperty::operator= (GroundSurfaceProperty &&) [default]
property() [1/2]
std::string opendlv::logic::perception::GroundSurfaceProperty::property () const [inline], [noexcept]
                                                   {
            return m_property;
        }
property() [2/2]
GroundSurfaceProperty & opendlv::logic::perception::GroundSurfaceProperty::property (const std::string & v) [inline], [noexcept]
                                                                            {
            m_property = v;
            return *this;
        }
ShortName()
static const std::string opendlv::logic::perception::GroundSurfaceProperty::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
surfaceId() [1/2]
uint32_t opendlv::logic::perception::GroundSurfaceProperty::surfaceId () const [inline], [noexcept]
                                                   {
            return m_surfaceId;
        }
surfaceId() [2/2]
GroundSurfaceProperty & opendlv::logic::perception::GroundSurfaceProperty::surfaceId (const uint32_t & v) [inline], [noexcept]
                                                                            {
            m_surfaceId = v;
            return *this;
        }
Member Data Documentation
m_property
std::string opendlv::logic::perception::GroundSurfaceProperty::m_property { ``s } [private]
m_surfaceId
uint32_t opendlv::logic::perception::GroundSurfaceProperty::m_surfaceId { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::GroundSurfaceProperty::TheLongName = `opendlv.logic.perception.GroundSurfaceProperty` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::GroundSurfaceProperty::TheShortName = `GroundSurfaceProperty` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp