opendlv::body::ComponentInfo Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ComponentInfo ()=default
ComponentInfo (const ComponentInfo &)=default
ComponentInfo & operator= (const ComponentInfo &)=default
ComponentInfo (ComponentInfo &&)=default
ComponentInfo & operator= (ComponentInfo &&)=default
~ComponentInfo ()=default
ComponentInfo & description (const std::string &v) noexcept
std::string description () const noexcept
ComponentInfo & x (const float &v) noexcept
float x () const noexcept
ComponentInfo & y (const float &v) noexcept
float y () const noexcept
ComponentInfo & z (const float &v) noexcept
float z () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_description { ``s }
float m_x { 0.0f }
float m_y { 0.0f }
float m_z { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `ComponentInfo`
static constexpr const char * TheLongName = `opendlv.body.ComponentInfo`
Constructor & Destructor Documentation
ComponentInfo() [1/3]
opendlv::body::ComponentInfo::ComponentInfo () [default]
ComponentInfo() [2/3]
opendlv::body::ComponentInfo::ComponentInfo (const ComponentInfo &) [default]
ComponentInfo() [3/3]
opendlv::body::ComponentInfo::ComponentInfo (ComponentInfo &&) [default]
 ComponentInfo()
opendlv::body::ComponentInfo::~ComponentInfo () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::body::ComponentInfo::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("x"s), m_x, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("y"s), m_y, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("z"s), m_z, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::body::ComponentInfo::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::body::ComponentInfo::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
            doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
            doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
            doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
            visitor.postVisit();
        }
References doVisit().
description() [1/2]
std::string opendlv::body::ComponentInfo::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
ComponentInfo & opendlv::body::ComponentInfo::description (const std::string & v) [inline], [noexcept]
                                                                       {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::body::ComponentInfo::ID () [inline], [static]
                                   {
            return 1021;
        }
LongName()
static const std::string opendlv::body::ComponentInfo::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
ComponentInfo & opendlv::body::ComponentInfo::operator= (ComponentInfo &&) [default]
operator=() [2/2]
ComponentInfo & opendlv::body::ComponentInfo::operator= (const ComponentInfo &) [default]
ShortName()
static const std::string opendlv::body::ComponentInfo::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
x() [1/2]
float opendlv::body::ComponentInfo::x () const [inline], [noexcept]
                                        {
            return m_x;
        }
x() [2/2]
ComponentInfo & opendlv::body::ComponentInfo::x (const float & v) [inline], [noexcept]
                                                         {
            m_x = v;
            return *this;
        }
y() [1/2]
float opendlv::body::ComponentInfo::y () const [inline], [noexcept]
                                        {
            return m_y;
        }
y() [2/2]
ComponentInfo & opendlv::body::ComponentInfo::y (const float & v) [inline], [noexcept]
                                                         {
            m_y = v;
            return *this;
        }
z() [1/2]
float opendlv::body::ComponentInfo::z () const [inline], [noexcept]
                                        {
            return m_z;
        }
z() [2/2]
ComponentInfo & opendlv::body::ComponentInfo::z (const float & v) [inline], [noexcept]
                                                         {
            m_z = v;
            return *this;
        }
Member Data Documentation
m_description
std::string opendlv::body::ComponentInfo::m_description { ``s } [private]
m_x
float opendlv::body::ComponentInfo::m_x { 0.0f } [private]
m_y
float opendlv::body::ComponentInfo::m_y { 0.0f } [private]
m_z
float opendlv::body::ComponentInfo::m_z { 0.0f } [private]
TheLongName
constexpr const char* opendlv::body::ComponentInfo::TheLongName = `opendlv.body.ComponentInfo` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::body::ComponentInfo::TheShortName = `ComponentInfo` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp