cluon::GenericMessage Class Reference
#include <cluon-complete.hpp>
Classes
class GenericMessageVisitor
Public Member Functions
GenericMessage ()=default
GenericMessage (GenericMessage &&)=default
GenericMessage (const GenericMessage &)=default
GenericMessage & operator= (const GenericMessage &)=default
int32_t ID ()
const std::string ShortName ()
const std::string LongName ()
template<typename T >
void createFrom (T &msg)
void createFrom (const MetaMessage &mm, const std::vector< MetaMessage > &mms) noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&_preVisit, Visitor &&_visit, PostVisitor &&_postVisit)
Private Member Functions
GenericMessage & operator= (GenericMessage &&)=delete
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor, bool visitAll)
Private Attributes
MetaMessage m_metaMessage {}
std::vector< MetaMessage > m_scopeOfMetaMessages {}
std::unordered_map< std::string, MetaMessage > m_mapForScopeOfMetaMessages {}
std::string m_longName {``}
std::unordered_map< uint32_t, linb::any, UseUInt32ValueAsHashKey > m_intermediateDataRepresentation
Detailed Description
GenericMessage is providing an abstraction level to work with concrete messages. Therefore, it is acting as both, a Visitor to turn concrete messages into GenericMessages or as Visitable to access the contained data. GenericMessage would use C++'s std::any type; to allow C++14 compilers, we use the backport from linb::any.
Creating a GenericMessage: There are several ways to create a GenericMessage. The first option is to provide a message specification in ODVD format as result from MessageParser, from which a GenericMessage is created. This instance can then be visited afterwards by, for instance, an instance of ProtoDecoder to set the GenericMessage's actual values.
1) This example demonstrates how to process a given message specification to decode a Proto-encoded byte sequence (in protoEncodedData). The message specification is given in messageSpecification that is parsed from MessageParser. On success, it is tried to decode the Proto-encoded data into a GenericMesssage representing an instance of `MyMessage`.
Using a message specification that does not match the serialized Proto data might result in unexpected behavior.
// protoEncodedData is provided from somewhere, i.e., via network for example
std::string protoEncodedData = <...>
std::stringstream sstr{protoEncodedData};
cluon::FromProtoVisitor protoDecoder;
protoDecoder.decodeFrom(sstr);
const char *messageSpecification = R"(
message MyMessage [id = 123] {
   int32 field1 [id = 1];
   int32 field2 [id = 2];
}
cluon::MessageParser mp;
auto retVal = mp.parse(std::string(messageSpecification));
if (cluon::MessageParser::MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR == retVal.second) {
    cluon::GenericMessage gm;
    auto listOfMetaMessages = retVal.first;
    gm.createFrom(listOfMetaMessages[0], listOfMetaMessages);
    // Set values in GenericMessage from protoDecoder.
    gm.accept(protoDecoder);
}
2) This example demonstrates how to turn a given concrete message into a GenericMessage. Afterwards, the GenericMessage can be post-processed with Visitors.
MyMessage msg;
// set some fields in msg.
cluon::GenericMessage gm;
gm.createFrom<MyMessage>(msg);
After an instance of GenericMessage is available, it can be post-processed into various representations:
1) Printing the contained data (`toString`; GenericMessage is being visited):
GenericMessage gm;
// gm is created using one of the aforementioned options.
std::stringstream buffer;
gm.accept([](uint32_t, const std::string &, const std::string &) {},
          [&buffer](uint32_t, std::string &&, std::string &&n, auto v) { buffer << n << " = " << v << std::endl; },
          []() {});
std::cout << buffer.str() << std::endl;
2) Filling the values of another concrete message (GenericMessage is acting as Visitor to another message):
GenericMessage gm;
// gm is created using one of the aforementioned options.
Message msg;
msg.accept(gm);
3) Serialize the GenericMessage gm into a Proto-format:
GenericMessage gm;
// gm is created using one of the aforementioned options.
cluon::ToProtoVisitor protoEncoder;
gm.accept(protoEncoder);
const std::string{protoEncoder.encodedData()};
4) Serialize the GenericMessage gm into JSON:
GenericMessage gm;
// gm is created using one of the aforementioned options.
cluon::ToJSONVisitor j;
gm.accept(j);
std::cout << j.json();
4) Dynamically transforming a given Proto-encoded byte sequence into JSON at runtime:
// protoEncodedData is provided from somewhere, i.e., via network for example
std::string protoEncodedData = <...>
std::stringstream sstr{protoEncodedData};
cluon::FromProtoVisitor protoDecoder;
protoDecoder.decodeFrom(sstr);
const char *messageSpecification = R"(
message MyMessage [id = 123] {
   int32 field1 [id = 1];
   int32 field2 [id = 2];
}
cluon::MessageParser mp;
auto retVal = mp.parse(std::string(messageSpecification));
if (cluon::MessageParser::MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR == retVal.second) {
    cluon::GenericMessage gm;
    auto listOfMetaMessages = retVal.first;
    gm.createFrom(listOfMetaMessages[0], listOfMetaMessages);
    // Set values in GenericMessage from protoDecoder.
    gm.accept(protoDecoder);
}
cluon::ToJSONVisitor j;
gm.accept(j);
std::cout << j.json();
Constructor & Destructor Documentation
GenericMessage() [1/3]
cluon::GenericMessage::GenericMessage () [default]
GenericMessage() [2/3]
cluon::GenericMessage::GenericMessage (GenericMessage &&) [default]
GenericMessage() [3/3]
cluon::GenericMessage::GenericMessage (const GenericMessage &) [default]
Member Function Documentation
accept() [1/4]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::GenericMessage::accept (PreVisitor && _preVisit, Visitor && _visit, PostVisitor && _postVisit) [inline]
This method allows other instances to visit this GenericMessage for post-processing the contained data.
Parameters
_preVisit Instance of the visitor pre-visiting this GenericMessage.
_visit Instance of the visitor visiting this GenericMessage.
_postVisit Instance of the visitor post-visiting this GenericMessage.
                                                                                    {
        std::forward<PreVisitor>(_preVisit)(m_metaMessage.messageIdentifier(), m_metaMessage.messageName(), m_longName);
        for (const auto &f : m_metaMessage.listOfMetaFields()) {
            if (f.fieldDataType() == MetaMessage::MetaField::BOOL_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<bool &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::CHAR_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<char &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::UINT8_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<uint8_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::INT8_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<int8_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::UINT16_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<uint16_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::INT16_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<int16_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::UINT32_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<uint32_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::INT32_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<int32_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::UINT64_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<uint64_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::INT64_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<int64_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::FLOAT_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<float &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::DOUBLE_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<double &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (((f.fieldDataType() == MetaMessage::MetaField::STRING_T) || (f.fieldDataType() == MetaMessage::MetaField::BYTES_T))
                       && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<std::string &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            } else if (f.fieldDataType() == MetaMessage::MetaField::MESSAGE_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                try {
                    auto &v = linb::any_cast<cluon::GenericMessage &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                    doTripletForwardVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, _preVisit, _visit, _postVisit);
                } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                }
            }
        }
        std::forward<PostVisitor>(_postVisit)();
    }
References cluon::MetaMessage::MetaField::BOOL_T, cluon::MetaMessage::MetaField::BYTES_T, cluon::MetaMessage::MetaField::CHAR_T, doTripletForwardVisit(), cluon::MetaMessage::MetaField::DOUBLE_T, cluon::MetaMessage::MetaField::FLOAT_T, cluon::MetaMessage::MetaField::INT16_T, cluon::MetaMessage::MetaField::INT32_T, cluon::MetaMessage::MetaField::INT64_T, cluon::MetaMessage::MetaField::INT8_T, cluon::MetaMessage::MetaField::MESSAGE_T, cluon::MetaMessage::MetaField::STRING_T, cluon::MetaMessage::MetaField::UINT16_T, cluon::MetaMessage::MetaField::UINT32_T, cluon::MetaMessage::MetaField::UINT64_T, and cluon::MetaMessage::MetaField::UINT8_T.
accept() [2/4]
template<class Visitor >
void cluon::GenericMessage::accept (uint32_t fieldId, Visitor & visitor) [inline]
This method allows other instances to visit this GenericMessage for post-processing the contained data on an individual field basis.
Parameters
fieldId Identifier for the field to visit.
visitor Instance of the visitor visiting this GenericMessage.
                                                           {
        const bool VISIT_ALL{false};
        accept<Visitor>(fieldId, visitor, VISIT_ALL);
    }
Referenced by cluon::LCMToGenericMessage::getGenericMessage(), cluon::EnvelopeConverter::getJSONFromEnvelope(), and cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON().
accept() [3/4]
template<class Visitor >
void cluon::GenericMessage::accept (uint32_t fieldId, Visitor & visitor, bool visitAll) [inline], [private]
                                                                          {
        visitor.preVisit(ID(), ShortName(), LongName());
        for (const auto &f : m_metaMessage.listOfMetaFields()) {
            if (visitAll || (fieldId == f.fieldIdentifier())) {
                if (f.fieldDataType() == MetaMessage::MetaField::BOOL_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<bool &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::CHAR_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<char &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::UINT8_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<uint8_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::INT8_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<int8_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::UINT16_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<uint16_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::INT16_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<int16_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::UINT32_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<uint32_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::INT32_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<int32_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::UINT64_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<uint64_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::INT64_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<int64_t &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::FLOAT_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<float &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::DOUBLE_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<double &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (((f.fieldDataType() == MetaMessage::MetaField::STRING_T) || (f.fieldDataType() == MetaMessage::MetaField::BYTES_T))
                           && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<std::string &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                } else if (f.fieldDataType() == MetaMessage::MetaField::MESSAGE_T && (0 < m_intermediateDataRepresentation.count(f.fieldIdentifier()))) {
                    try {
                        auto &v = linb::any_cast<cluon::GenericMessage &>(m_intermediateDataRepresentation[f.fieldIdentifier()]);
                        doVisit(f.fieldIdentifier(), std::move(f.fieldDataTypeName()), std::move(f.fieldName()), v, visitor);
                    } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
                    }
                }
                // End processing in case of visiting specific fields.
                if (!visitAll && (fieldId == f.fieldIdentifier())) {
                  break;
                }
            }
        }
        visitor.postVisit();
    }
References cluon::MetaMessage::MetaField::BOOL_T, cluon::MetaMessage::MetaField::BYTES_T, cluon::MetaMessage::MetaField::CHAR_T, cluon::MetaMessage::MetaField::DOUBLE_T, doVisit(), cluon::MetaMessage::MetaField::FLOAT_T, cluon::MetaMessage::MetaField::INT16_T, cluon::MetaMessage::MetaField::INT32_T, cluon::MetaMessage::MetaField::INT64_T, cluon::MetaMessage::MetaField::INT8_T, cluon::MetaMessage::MetaField::MESSAGE_T, cluon::MetaMessage::MetaField::STRING_T, cluon::MetaMessage::MetaField::UINT16_T, cluon::MetaMessage::MetaField::UINT32_T, cluon::MetaMessage::MetaField::UINT64_T, and cluon::MetaMessage::MetaField::UINT8_T.
accept() [4/4]
template<class Visitor >
void cluon::GenericMessage::accept (Visitor & visitor) [inline]
This method allows other instances to visit this GenericMessage for post-processing the contained data.
Parameters
visitor Instance of the visitor visiting this GenericMessage.
                                  {
        const uint32_t FIELD_ID{0};
        const bool VISIT_ALL{true};
        accept<Visitor>(FIELD_ID, visitor, VISIT_ALL);
    }
createFrom() [1/2]
void cluon::GenericMessage::createFrom (const MetaMessage & mm, const std::vector< MetaMessage > & mms) [inline], [noexcept]
This method creates an empty GenericMessage from a given message specification parsed from MessageParser.
Parameters
mm MetaMessage describing the fields for the message to be resolved.
mms List of MetaMessages that are known (used for resolving nested message).
                                                                                                        {
    m_metaMessage = mm;
    m_longName = m_metaMessage.messageName();
    m_scopeOfMetaMessages.clear();
    m_scopeOfMetaMessages = mms;
    m_mapForScopeOfMetaMessages.clear();
    for (const auto &e : m_scopeOfMetaMessages) { m_mapForScopeOfMetaMessages[e.messageName()] = e; }
    m_intermediateDataRepresentation.clear();
    for (const auto &f : m_metaMessage.listOfMetaFields()) {
        if (f.fieldDataType() == MetaMessage::MetaField::BOOL_T) {
            try {
                linb::any _v{false};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::CHAR_T) {
            try {
                linb::any _v{static_cast<char>('\0')};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::UINT8_T) {
            try {
                linb::any _v{static_cast<uint8_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::INT8_T) {
            try {
                linb::any _v{static_cast<int8_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::UINT16_T) {
            try {
                linb::any _v{static_cast<uint16_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::INT16_T) {
            try {
                linb::any _v{static_cast<int16_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::UINT32_T) {
            try {
                linb::any _v{static_cast<uint32_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::INT32_T) {
            try {
                linb::any _v{static_cast<int32_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::UINT64_T) {
            try {
                linb::any _v{static_cast<uint64_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::INT64_T) {
            try {
                linb::any _v{static_cast<int64_t>(0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::FLOAT_T) {
            try {
                linb::any _v{static_cast<float>(0.0f)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::DOUBLE_T) {
            try {
                linb::any _v{static_cast<double>(0.0)};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if ((f.fieldDataType() == MetaMessage::MetaField::STRING_T) || (f.fieldDataType() == MetaMessage::MetaField::BYTES_T)) {
            try {
                linb::any _v = std::string{};
                m_intermediateDataRepresentation[f.fieldIdentifier()] = _v;
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        } else if (f.fieldDataType() == MetaMessage::MetaField::MESSAGE_T) {
            if (0 < m_mapForScopeOfMetaMessages.count(f.fieldDataTypeName())) {
                // Create a GenericMessage from the decoded Proto-data.
                cluon::GenericMessage gm;
                gm.createFrom(m_mapForScopeOfMetaMessages[f.fieldDataTypeName()], m_scopeOfMetaMessages);
                m_intermediateDataRepresentation[f.fieldIdentifier()] = linb::any{gm};
            }
        }
    }
}
References cluon::MetaMessage::MetaField::BOOL_T, cluon::MetaMessage::MetaField::BYTES_T, cluon::MetaMessage::MetaField::CHAR_T, createFrom(), cluon::MetaMessage::MetaField::DOUBLE_T, cluon::MetaMessage::MetaField::FLOAT_T, cluon::MetaMessage::MetaField::INT16_T, cluon::MetaMessage::MetaField::INT32_T, cluon::MetaMessage::MetaField::INT64_T, cluon::MetaMessage::MetaField::INT8_T, cluon::MetaMessage::listOfMetaFields(), m_intermediateDataRepresentation, m_longName, m_mapForScopeOfMetaMessages, m_metaMessage, m_scopeOfMetaMessages, cluon::MetaMessage::MetaField::MESSAGE_T, cluon::MetaMessage::messageName(), mm, cluon::MetaMessage::MetaField::STRING_T, cluon::MetaMessage::MetaField::UINT16_T, cluon::MetaMessage::MetaField::UINT32_T, cluon::MetaMessage::MetaField::UINT64_T, and cluon::MetaMessage::MetaField::UINT8_T.
createFrom() [2/2]
template<typename T >
void cluon::GenericMessage::createFrom (T & msg) [inline]
This methods creates this GenericMessage from a given concrete message.
Parameters
msg Concrete message used to derive this GenericMessage from.
                            {
        GenericMessageVisitor gmv;
        msg.accept(gmv);
        m_metaMessage = gmv.metaMessage();
        m_intermediateDataRepresentation.clear();
        m_intermediateDataRepresentation = gmv.intermediateDataRepresentation();
    }
References cluon::GenericMessage::GenericMessageVisitor::intermediateDataRepresentation(), and cluon::GenericMessage::GenericMessageVisitor::metaMessage().
Referenced by createFrom(), cluon::LCMToGenericMessage::getGenericMessage(), cluon::EnvelopeConverter::getJSONFromEnvelope(), cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::GenericMessage::GenericMessageVisitor::visit().
ID()
int32_t cluon::GenericMessage::ID () [inline]
                                  {
    return m_metaMessage.messageIdentifier();
}
References m_metaMessage, and cluon::MetaMessage::messageIdentifier().
LongName()
const std::string cluon::GenericMessage::LongName () [inline]
                                                {
    return m_metaMessage.packageName() + (!m_metaMessage.packageName().empty() ? "." : "") + m_metaMessage.messageName();
}
References m_metaMessage, cluon::MetaMessage::messageName(), and cluon::MetaMessage::packageName().
Referenced by ShortName().
operator=() [1/2]
GenericMessage & cluon::GenericMessage::operator= (const GenericMessage &) [default]
operator=() [2/2]
GenericMessage & cluon::GenericMessage::operator= (GenericMessage &&) [private], [delete]
postVisit()
void cluon::GenericMessage::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::GenericMessage::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                               {
    (void)id;
    (void)shortName;
    (void)longName;
}
ShortName()
const std::string cluon::GenericMessage::ShortName () [inline]
                                                 {
    std::string tmp{LongName()};
    std::replace(tmp.begin(), tmp.end(), '.', ' ');
    std::istringstream sstr{tmp};
    std::vector<std::string> tokens{std::istream_iterator<std::string>(sstr), std::istream_iterator<std::string>()};
    return tokens.back();
}
References LongName().
visit() [1/14]
template<typename T >
void cluon::GenericMessage::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                        {
        (void)typeName;
        (void)name;
        if (0 < m_intermediateDataRepresentation.count(id)) {
            try {
                auto &v = linb::any_cast<cluon::GenericMessage &>(m_intermediateDataRepresentation[id]);
                value.accept(v);
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        }
    }
visit() [2/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                       {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<bool>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [3/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                       {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<char>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [4/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<double>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [5/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                        {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<float>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [6/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<int16_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [7/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<int32_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [8/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<int64_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [9/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<int8_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [10/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<std::string>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [11/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<uint16_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [12/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<uint32_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [13/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<uint64_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
visit() [14/14]
void cluon::GenericMessage::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    if (0 < m_intermediateDataRepresentation.count(id)) {
        try {
            v = linb::any_cast<uint8_t>(m_intermediateDataRepresentation[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
References m_intermediateDataRepresentation.
Member Data Documentation
m_intermediateDataRepresentation
std::unordered_map<uint32_t, linb::any, UseUInt32ValueAsHashKey> cluon::GenericMessage::m_intermediateDataRepresentation [private]
Referenced by createFrom(), cluon::GenericMessage::GenericMessageVisitor::intermediateDataRepresentation(), cluon::GenericMessage::GenericMessageVisitor::visit(), and visit().
m_longName
std::string cluon::GenericMessage::m_longName {``} [private]
Referenced by createFrom().
m_mapForScopeOfMetaMessages
std::unordered_map<std::string, MetaMessage> cluon::GenericMessage::m_mapForScopeOfMetaMessages {} [private]
Referenced by createFrom().
m_metaMessage
MetaMessage cluon::GenericMessage::m_metaMessage {} [private]
Referenced by createFrom(), ID(), LongName(), cluon::GenericMessage::GenericMessageVisitor::metaMessage(), and cluon::GenericMessage::GenericMessageVisitor::visit().
m_scopeOfMetaMessages
std::vector<MetaMessage> cluon::GenericMessage::m_scopeOfMetaMessages {} [private]
Referenced by createFrom().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp