opendlv::logic::action::AimDirection Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AimDirection ()=default
AimDirection (const AimDirection &)=default
AimDirection & operator= (const AimDirection &)=default
AimDirection (AimDirection &&)=default
AimDirection & operator= (AimDirection &&)=default
~AimDirection ()=default
AimDirection & azimuthAngle (const float &v) noexcept
float azimuthAngle () const noexcept
AimDirection & zenithAngle (const float &v) noexcept
float zenithAngle () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_azimuthAngle { 0.0f }
float m_zenithAngle { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AimDirection`
static constexpr const char * TheLongName = `opendlv.logic.action.AimDirection`
Constructor & Destructor Documentation
AimDirection() [1/3]
opendlv::logic::action::AimDirection::AimDirection () [default]
AimDirection() [2/3]
opendlv::logic::action::AimDirection::AimDirection (const AimDirection &) [default]
AimDirection() [3/3]
opendlv::logic::action::AimDirection::AimDirection (AimDirection &&) [default]
 AimDirection()
opendlv::logic::action::AimDirection::~AimDirection () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::action::AimDirection::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::action::AimDirection::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::action::AimDirection::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
            doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
            visitor.postVisit();
        }
References doVisit().
azimuthAngle() [1/2]
float opendlv::logic::action::AimDirection::azimuthAngle () const [inline], [noexcept]
                                                   {
            return m_azimuthAngle;
        }
azimuthAngle() [2/2]
AimDirection & opendlv::logic::action::AimDirection::azimuthAngle (const float & v) [inline], [noexcept]
                                                                   {
            m_azimuthAngle = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::action::AimDirection::ID () [inline], [static]
                                   {
            return 1171;
        }
LongName()
static const std::string opendlv::logic::action::AimDirection::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AimDirection & opendlv::logic::action::AimDirection::operator= (AimDirection &&) [default]
operator=() [2/2]
AimDirection & opendlv::logic::action::AimDirection::operator= (const AimDirection &) [default]
ShortName()
static const std::string opendlv::logic::action::AimDirection::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
zenithAngle() [1/2]
float opendlv::logic::action::AimDirection::zenithAngle () const [inline], [noexcept]
                                                  {
            return m_zenithAngle;
        }
zenithAngle() [2/2]
AimDirection & opendlv::logic::action::AimDirection::zenithAngle (const float & v) [inline], [noexcept]
                                                                  {
            m_zenithAngle = v;
            return *this;
        }
Member Data Documentation
m_azimuthAngle
float opendlv::logic::action::AimDirection::m_azimuthAngle { 0.0f } [private]
m_zenithAngle
float opendlv::logic::action::AimDirection::m_zenithAngle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::action::AimDirection::TheLongName = `opendlv.logic.action.AimDirection` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::action::AimDirection::TheShortName = `AimDirection` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp