opendlv::system::SystemOperationState Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
SystemOperationState ()=default
SystemOperationState (const SystemOperationState &)=default
SystemOperationState & operator= (const SystemOperationState &)=default
SystemOperationState (SystemOperationState &&)=default
SystemOperationState & operator= (SystemOperationState &&)=default
~SystemOperationState ()=default
SystemOperationState & code (const int32_t &v) noexcept
int32_t code () const noexcept
SystemOperationState & description (const std::string &v) noexcept
std::string description () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
int32_t m_code { 0 }
std::string m_description { ``s }
Static Private Attributes
static constexpr const char * TheShortName = `SystemOperationState`
static constexpr const char * TheLongName = `opendlv.system.SystemOperationState`
Constructor & Destructor Documentation
SystemOperationState() [1/3]
opendlv::system::SystemOperationState::SystemOperationState () [default]
SystemOperationState() [2/3]
opendlv::system::SystemOperationState::SystemOperationState (const SystemOperationState &) [default]
SystemOperationState() [3/3]
opendlv::system::SystemOperationState::SystemOperationState (SystemOperationState &&) [default]
 SystemOperationState()
opendlv::system::SystemOperationState::~SystemOperationState () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::system::SystemOperationState::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("int32_t"s), std::move("code"s), m_code, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::system::SystemOperationState::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("int32_t"s), std::move("code"s), m_code, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::system::SystemOperationState::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("int32_t"s), std::move("code"s), m_code, visitor);
            doVisit(2, std::move("std::string"s), std::move("description"s), m_description, visitor);
            visitor.postVisit();
        }
References doVisit().
code() [1/2]
int32_t opendlv::system::SystemOperationState::code () const [inline], [noexcept]
                                             {
            return m_code;
        }
code() [2/2]
SystemOperationState & opendlv::system::SystemOperationState::code (const int32_t & v) [inline], [noexcept]
                                                                     {
            m_code = v;
            return *this;
        }
description() [1/2]
std::string opendlv::system::SystemOperationState::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
SystemOperationState & opendlv::system::SystemOperationState::description (const std::string & v) [inline], [noexcept]
                                                                              {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::system::SystemOperationState::ID () [inline], [static]
                                   {
            return 1101;
        }
LongName()
static const std::string opendlv::system::SystemOperationState::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
SystemOperationState & opendlv::system::SystemOperationState::operator= (const SystemOperationState &) [default]
operator=() [2/2]
SystemOperationState & opendlv::system::SystemOperationState::operator= (SystemOperationState &&) [default]
ShortName()
static const std::string opendlv::system::SystemOperationState::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_code
int32_t opendlv::system::SystemOperationState::m_code { 0 } [private]
m_description
std::string opendlv::system::SystemOperationState::m_description { ``s } [private]
TheLongName
constexpr const char* opendlv::system::SystemOperationState::TheLongName = `opendlv.system.SystemOperationState` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::system::SystemOperationState::TheShortName = `SystemOperationState` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp