opendlv::proxy::GroundSteeringRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSteeringRequest ()=default
GroundSteeringRequest (const GroundSteeringRequest &)=default
GroundSteeringRequest & operator= (const GroundSteeringRequest &)=default
GroundSteeringRequest (GroundSteeringRequest &&)=default
GroundSteeringRequest & operator= (GroundSteeringRequest &&)=default
~GroundSteeringRequest ()=default
GroundSteeringRequest & groundSteering (const float &v) noexcept
float groundSteering () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundSteering { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSteeringRequest`
static constexpr const char * TheLongName = `opendlv.proxy.GroundSteeringRequest`
Constructor & Destructor Documentation
GroundSteeringRequest() [1/3]
opendlv::proxy::GroundSteeringRequest::GroundSteeringRequest () [default]
GroundSteeringRequest() [2/3]
opendlv::proxy::GroundSteeringRequest::GroundSteeringRequest (const GroundSteeringRequest &) [default]
GroundSteeringRequest() [3/3]
opendlv::proxy::GroundSteeringRequest::GroundSteeringRequest (GroundSteeringRequest &&) [default]
 GroundSteeringRequest()
opendlv::proxy::GroundSteeringRequest::~GroundSteeringRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundSteeringRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundSteeringRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundSteeringRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, visitor);
            visitor.postVisit();
        }
References doVisit().
groundSteering() [1/2]
float opendlv::proxy::GroundSteeringRequest::groundSteering () const [inline], [noexcept]
                                                     {
            return m_groundSteering;
        }
groundSteering() [2/2]
GroundSteeringRequest & opendlv::proxy::GroundSteeringRequest::groundSteering (const float & v) [inline], [noexcept]
                                                                              {
            m_groundSteering = v;
            return *this;
        }
Referenced by main().
ID()
static int32_t opendlv::proxy::GroundSteeringRequest::ID () [inline], [static]
                                   {
            return 1090;
        }
Referenced by main().
LongName()
static const std::string opendlv::proxy::GroundSteeringRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSteeringRequest & opendlv::proxy::GroundSteeringRequest::operator= (const GroundSteeringRequest &) [default]
operator=() [2/2]
GroundSteeringRequest & opendlv::proxy::GroundSteeringRequest::operator= (GroundSteeringRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundSteeringRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundSteering
float opendlv::proxy::GroundSteeringRequest::m_groundSteering { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundSteeringRequest::TheLongName = `opendlv.proxy.GroundSteeringRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundSteeringRequest::TheShortName = `GroundSteeringRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp