opendlv::proxy::GeodeticHeadingReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GeodeticHeadingReading ()=default
GeodeticHeadingReading (const GeodeticHeadingReading &)=default
GeodeticHeadingReading & operator= (const GeodeticHeadingReading &)=default
GeodeticHeadingReading (GeodeticHeadingReading &&)=default
GeodeticHeadingReading & operator= (GeodeticHeadingReading &&)=default
~GeodeticHeadingReading ()=default
GeodeticHeadingReading & northHeading (const float &v) noexcept
float northHeading () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_northHeading { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GeodeticHeadingReading`
static constexpr const char * TheLongName = `opendlv.proxy.GeodeticHeadingReading`
Constructor & Destructor Documentation
GeodeticHeadingReading() [1/3]
opendlv::proxy::GeodeticHeadingReading::GeodeticHeadingReading () [default]
GeodeticHeadingReading() [2/3]
opendlv::proxy::GeodeticHeadingReading::GeodeticHeadingReading (const GeodeticHeadingReading &) [default]
GeodeticHeadingReading() [3/3]
opendlv::proxy::GeodeticHeadingReading::GeodeticHeadingReading (GeodeticHeadingReading &&) [default]
 GeodeticHeadingReading()
opendlv::proxy::GeodeticHeadingReading::~GeodeticHeadingReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GeodeticHeadingReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("northHeading"s), m_northHeading, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GeodeticHeadingReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("northHeading"s), m_northHeading, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GeodeticHeadingReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("northHeading"s), m_northHeading, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::GeodeticHeadingReading::ID () [inline], [static]
                                   {
            return 1051;
        }
LongName()
static const std::string opendlv::proxy::GeodeticHeadingReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
northHeading() [1/2]
float opendlv::proxy::GeodeticHeadingReading::northHeading () const [inline], [noexcept]
                                                   {
            return m_northHeading;
        }
northHeading() [2/2]
GeodeticHeadingReading & opendlv::proxy::GeodeticHeadingReading::northHeading (const float & v) [inline], [noexcept]
                                                                             {
            m_northHeading = v;
            return *this;
        }
operator=() [1/2]
GeodeticHeadingReading & opendlv::proxy::GeodeticHeadingReading::operator= (const GeodeticHeadingReading &) [default]
operator=() [2/2]
GeodeticHeadingReading & opendlv::proxy::GeodeticHeadingReading::operator= (GeodeticHeadingReading &&) [default]
ShortName()
static const std::string opendlv::proxy::GeodeticHeadingReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_northHeading
float opendlv::proxy::GeodeticHeadingReading::m_northHeading { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GeodeticHeadingReading::TheLongName = `opendlv.proxy.GeodeticHeadingReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GeodeticHeadingReading::TheShortName = `GeodeticHeadingReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp