cluon::data::PlayerStatus Class Reference
#include <cluon-complete.hpp>
Public Member Functions
PlayerStatus ()=default
PlayerStatus (const PlayerStatus &)=default
PlayerStatus & operator= (const PlayerStatus &)=default
PlayerStatus (PlayerStatus &&)=default
PlayerStatus & operator= (PlayerStatus &&)=default
~PlayerStatus ()=default
PlayerStatus & state (const uint8_t &v) noexcept
uint8_t state () const noexcept
PlayerStatus & numberOfEntries (const uint32_t &v) noexcept
uint32_t numberOfEntries () const noexcept
PlayerStatus & currentEntryForPlayback (const uint32_t &v) noexcept
uint32_t currentEntryForPlayback () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint8_t m_state { 0 }
uint32_t m_numberOfEntries { 0 }
uint32_t m_currentEntryForPlayback { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `PlayerStatus`
static constexpr const char * TheLongName = `cluon.data.PlayerStatus`
Constructor & Destructor Documentation
PlayerStatus() [1/3]
cluon::data::PlayerStatus::PlayerStatus () [default]
PlayerStatus() [2/3]
cluon::data::PlayerStatus::PlayerStatus (const PlayerStatus &) [default]
PlayerStatus() [3/3]
cluon::data::PlayerStatus::PlayerStatus (PlayerStatus &&) [default]
 PlayerStatus()
cluon::data::PlayerStatus::~PlayerStatus () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::data::PlayerStatus::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("uint8_t"s), std::move("state"s), m_state, preVisit, visit, postVisit);
            
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("numberOfEntries"s), m_numberOfEntries, preVisit, visit, postVisit);
            
            doTripletForwardVisit(3, std::move("uint32_t"s), std::move("currentEntryForPlayback"s), m_currentEntryForPlayback, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void cluon::data::PlayerStatus::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("uint8_t"s), std::move("state"s), m_state, visitor);
                return;
            }
            
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("numberOfEntries"s), m_numberOfEntries, visitor);
                return;
            }
            
            if (3 == fieldId) {
                doVisit(3, std::move("uint32_t"s), std::move("currentEntryForPlayback"s), m_currentEntryForPlayback, visitor);
                return;
            }
            
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void cluon::data::PlayerStatus::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("uint8_t"s), std::move("state"s), m_state, visitor);
            
            doVisit(2, std::move("uint32_t"s), std::move("numberOfEntries"s), m_numberOfEntries, visitor);
            
            doVisit(3, std::move("uint32_t"s), std::move("currentEntryForPlayback"s), m_currentEntryForPlayback, visitor);
            
            visitor.postVisit();
        }
References doVisit().
currentEntryForPlayback() [1/2]
uint32_t cluon::data::PlayerStatus::currentEntryForPlayback () const [inline], [noexcept]
                                                                 {
            return m_currentEntryForPlayback;
        }
currentEntryForPlayback() [2/2]
PlayerStatus & cluon::data::PlayerStatus::currentEntryForPlayback (const uint32_t & v) [inline], [noexcept]
                                                                                 {
            m_currentEntryForPlayback = v;
            return *this;
        }
Referenced by cluon::Player::manageCache().
ID()
static int32_t cluon::data::PlayerStatus::ID () [inline], [static]
                                   {
            return 10;
        }
LongName()
static const std::string cluon::data::PlayerStatus::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
numberOfEntries() [1/2]
uint32_t cluon::data::PlayerStatus::numberOfEntries () const [inline], [noexcept]
                                                         {
            return m_numberOfEntries;
        }
numberOfEntries() [2/2]
PlayerStatus & cluon::data::PlayerStatus::numberOfEntries (const uint32_t & v) [inline], [noexcept]
                                                                         {
            m_numberOfEntries = v;
            return *this;
        }
Referenced by cluon::Player::manageCache().
operator=() [1/2]
PlayerStatus & cluon::data::PlayerStatus::operator= (const PlayerStatus &) [default]
operator=() [2/2]
PlayerStatus & cluon::data::PlayerStatus::operator= (PlayerStatus &&) [default]
ShortName()
static const std::string cluon::data::PlayerStatus::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
state() [1/2]
uint8_t cluon::data::PlayerStatus::state () const [inline], [noexcept]
                                              {
            return m_state;
        }
state() [2/2]
PlayerStatus & cluon::data::PlayerStatus::state (const uint8_t & v) [inline], [noexcept]
                                                              {
            m_state = v;
            return *this;
        }
Referenced by cluon::Player::manageCache().
Member Data Documentation
m_currentEntryForPlayback
uint32_t cluon::data::PlayerStatus::m_currentEntryForPlayback { 0 } [private]
m_numberOfEntries
uint32_t cluon::data::PlayerStatus::m_numberOfEntries { 0 } [private]
m_state
uint8_t cluon::data::PlayerStatus::m_state { 0 } [private]
TheLongName
constexpr const char* cluon::data::PlayerStatus::TheLongName = `cluon.data.PlayerStatus` [static], [constexpr], [private]
TheShortName
constexpr const char* cluon::data::PlayerStatus::TheShortName = `PlayerStatus` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp