cluon::MessageParser Class Reference
#include <cluon-complete.hpp>
Public Types
enum MessageParserErrorCodes : uint8_t { NO_MESSAGEPARSER_ERROR = 0
, SYNTAX_ERROR = 1
, DUPLICATE_IDENTIFIERS = 2
 }
Public Member Functions
MessageParser ()=default
std::pair< std::vector< MetaMessage >, MessageParserErrorCodes > parse (const std::string &input)
Private Member Functions
MessageParser (const MessageParser &)=delete
MessageParser (MessageParser &&)=delete
MessageParser & operator= (const MessageParser &)=delete
MessageParser & operator= (MessageParser &&)=delete
Detailed Description
This class provides a parser for message specifications in .odvd format. The format is inspired by Google Protobuf (https://developers.google.com/protocol-buffers/) but simplified to enforce backwards and forwards compatibility next to numerical message identifiers.
This message specification format is also used by OpenDaVINCI (http://code.opendavinci.org).
The parser is based on https://github.com/yhirose/cpp-peglib.
An example for a .odvd compliant message is demonstrated in the following:
const char *spec = R"(
message myMessage.SubName [id = 1] {
    uint8 field1 [id = 1];
    uint32 field2 [id = 2];
    int64 field3 [id = 3];
    string field4 [id = 4];
}
)";
cluon::MessageParser mp;
auto retVal = mp.parse(std::string(spec));
if (retVal.second == cluon::MessageParser::MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR) {
    auto listOfMessages = retVal.first;
    for (auto message : listOfMessages) {
        message.accept([](const cluon::MetaMessage &mm){ std::cout << "Message name = " << mm.messageName() <<
std::endl; });
    }
}
Member Enumeration Documentation
MessageParserErrorCodes
enum cluon::MessageParser::MessageParserErrorCodes : uint8_t
Enumerator
NO_MESSAGEPARSER_ERROR
SYNTAX_ERROR
DUPLICATE_IDENTIFIERS
: uint8_t { NO_MESSAGEPARSER_ERROR = 0, SYNTAX_ERROR = 1, DUPLICATE_IDENTIFIERS = 2 };
Constructor & Destructor Documentation
MessageParser() [1/3]
cluon::MessageParser::MessageParser (const MessageParser &) [private], [delete]
MessageParser() [2/3]
cluon::MessageParser::MessageParser (MessageParser &&) [private], [delete]
MessageParser() [3/3]
cluon::MessageParser::MessageParser () [default]
Member Function Documentation
operator=() [1/2]
MessageParser & cluon::MessageParser::operator= (const MessageParser &) [private], [delete]
operator=() [2/2]
MessageParser & cluon::MessageParser::operator= (MessageParser &&) [private], [delete]
parse()
std::pair< std::vector< MetaMessage >, MessageParser::MessageParserErrorCodes > cluon::MessageParser::parse (const std::string & input) [inline]
This method tries to parse the given message specification.
Parameters
input Message specification.
Returns
Pair: List of cluon::MetaMessages describing the specified messages and error code: NO_MESSAGEPARSER_ERROR: The given specification could be parsed successfully (list moght be non-empty). SYNTAX_ERROR: The given specification could not be parsed successfully (list is empty). DUPLICATE_IDENTIFIERS: The given specification contains ambiguous names or identifiers (list is empty).
                                                                                                                        {
    const char *grammarMessageSpecificationLanguage = R"(
        MESSAGES_SPECIFICATION <- PACKAGE_DECLARATION? MESSAGE_DECLARATION*
        PACKAGE_DECLARATION <- 'package' PACKAGE_IDENTIFIER ';'
        PACKAGE_IDENTIFIER <- < IDENTIFIER ('.' IDENTIFIER)* >
        MESSAGE_DECLARATION <- 'message' MESSAGE_IDENTIFIER MESSAGE_OPTIONS '{' FIELD* '}'
        MESSAGE_IDENTIFIER <- < IDENTIFIER ('.' IDENTIFIER)* >
        MESSAGE_OPTIONS <- '[' 'id' '=' NATURAL_NUMBER ','? ']'
        FIELD <- PRIMITIVE_FIELD
        PRIMITIVE_FIELD <- PRIMITIVE_TYPE IDENTIFIER ('[' PRIMITIVE_FIELD_OPTIONS ']')? ';'
        PRIMITIVE_FIELD_OPTIONS <- PRIMITIVE_FIELD_DEFAULT? ','? NUMERICAL_FIELD_IDENTIFIER?
        NUMERICAL_FIELD_IDENTIFIER <- 'id' '=' NATURAL_NUMBER
        PRIMITIVE_FIELD_DEFAULT <- 'default' '=' (FLOAT_NUMBER / BOOL / CHARACTER / STRING)
        PRIMITIVE_TYPE <- < 'bool' / 'float' / 'double' /
                                         'char' /
                                         'bytes' / 'string' /
                                         'int8' / 'uint8' /
                                         'int16' / 'uint16' /
                                         'int32' / 'uint32' /
                                         'int64' / 'uint64' /
                                         MESSAGE_TYPE >
        MESSAGE_TYPE <- < IDENTIFIER ('.' IDENTIFIER)* >
        IDENTIFIER <- < [a-zA-Z][a-zA-Z0-9_]* >
        DIGIT <- < [0-9] >
        NATURAL_NUMBER <- < [1-9] DIGIT* >
        FLOAT_NUMBER <- < ('+' / '-')? DIGIT DIGIT* (('.') DIGIT*)? >
        BOOL <- < 'true' > / < 'false' >
        STRING <- '"' < (!'"'.)* > '"'
        CHARACTER <- '\'' < (!'\'' .) > '\''
        %whitespace <- [ \t\r\n]*
    )";
    // Function to check for unique field names.
    std::function<bool(const peg::Ast &, std::string &, std::vector<std::string> &, std::vector<std::string> &, std::vector<int32_t> &, std::vector<int32_t> &)>
        check4UniqueFieldNames = [&checkForUniqueFieldNames = check4UniqueFieldNames](const peg::Ast &ast,
                                                                                      std::string &prefix,
                                                                                      std::vector<std::string> &messageNames,
                                                                                      std::vector<std::string> &fieldNames,
                                                                                      std::vector<int32_t> &numericalMessageIdentifiers,
                                                                                      std::vector<int32_t> &numericalFieldIdentifiers) {
            bool retVal = true;
            // First, we need to visit the children of AST node MESSAGES_SPECIFICATION.
            if ("MESSAGES_SPECIFICATION" == ast.name) {
                for (const auto &node : ast.nodes) {
                    retVal &= checkForUniqueFieldNames(*node, prefix, messageNames, fieldNames, numericalMessageIdentifiers, numericalFieldIdentifiers);
                }
                // Try finding duplicated message identifiers.
                if (retVal) {
                    std::sort(std::begin(numericalMessageIdentifiers), std::end(numericalMessageIdentifiers));
                    int32_t duplicatedMessageIdentifier{-1};
                    for (auto it{std::begin(numericalMessageIdentifiers)}; it != std::end(numericalMessageIdentifiers); it++) {
                        if (it + 1 != std::end(numericalMessageIdentifiers)) {
                            if (std::find(it + 1, std::end(numericalMessageIdentifiers), *it) != std::end(numericalMessageIdentifiers)) {
                                duplicatedMessageIdentifier = *it;
                            }
                        }
                    }
                    retVal &= (-1 == duplicatedMessageIdentifier);
                    if (!retVal) {
                        std::cerr << "[cluon::MessageParser] Found duplicated numerical message identifier: " << duplicatedMessageIdentifier << '\n';
                    }
                }
                // Try finding duplicated message names.
                if (retVal) {
                    std::sort(std::begin(messageNames), std::end(messageNames));
                    std::string duplicatedMessageName;
                    for (auto it{std::begin(messageNames)}; it != std::end(messageNames); it++) {
                        if (it + 1 != std::end(messageNames)) {
                            if (std::find(it + 1, std::end(messageNames), *it) != std::end(messageNames)) {
                                duplicatedMessageName = *it;
                            }
                        }
                    }
                    retVal &= (duplicatedMessageName.empty());
                    if (!retVal) {
                        std::cerr << "[cluon::MessageParser] Found duplicated message name '" << duplicatedMessageName << "'" << '\n';
                    }
                }
            }
            // Second, we need to visit the children of AST node MESSAGE_DECLARATION.
            if ("MESSAGE_DECLARATION" == ast.name) {
                fieldNames.clear();
                numericalFieldIdentifiers.clear();
                prefix = "";
                retVal = true;
                for (const auto &node : ast.nodes) {
                    if ("MESSAGE_IDENTIFIER" == node->name) {
                        prefix = node->token;
                        messageNames.push_back(::stringtoolbox::trim(prefix));
                    } else if ("NATURAL_NUMBER" == node->name) {
                        numericalMessageIdentifiers.push_back(std::stoi(node->token));
                    } else if ("PRIMITIVE_FIELD" == node->name) {
                        retVal &= checkForUniqueFieldNames(*node, prefix, messageNames, fieldNames, numericalMessageIdentifiers, numericalFieldIdentifiers);
                    }
                }
                // Try finding duplicated numerical field identifiers.
                if (retVal) {
                    std::sort(std::begin(numericalFieldIdentifiers), std::end(numericalFieldIdentifiers));
                    int32_t duplicatedFieldIdentifier{-1};
                    for (auto it{std::begin(numericalFieldIdentifiers)}; it != std::end(numericalFieldIdentifiers); it++) {
                        if (it + 1 != std::end(numericalFieldIdentifiers)) {
                            if (std::find(it + 1, std::end(numericalFieldIdentifiers), *it) != std::end(numericalFieldIdentifiers)) {
                                duplicatedFieldIdentifier = *it;
                            }
                        }
                    }
                    retVal &= (-1 == duplicatedFieldIdentifier);
                    if (!retVal) {
                        std::cerr << "[cluon::MessageParser] Found duplicated numerical field identifier in message "
                                  << "'" << ::stringtoolbox::trim(prefix) << "': " << duplicatedFieldIdentifier << '\n';
                    }
                }
                // Try finding duplicated field names.
                if (retVal) {
                    std::sort(std::begin(fieldNames), std::end(fieldNames));
                    std::string duplicatedFieldName;
                    for (auto it{std::begin(fieldNames)}; it != std::end(fieldNames); it++) {
                        if (it + 1 != std::end(fieldNames)) {
                            if (std::find(it + 1, std::end(fieldNames), *it) != std::end(fieldNames)) {
                                duplicatedFieldName = *it;
                            }
                        }
                    }
                    retVal &= (duplicatedFieldName.empty());
                    if (!retVal) {
                        std::cerr << "[cluon::MessageParser] Found duplicated field name in message '" << ::stringtoolbox::trim(prefix) << "': '"
                                  << duplicatedFieldName << "'" << '\n';
                    }
                }
            }
            // Within AST node MESSAGE_DECLARATION, we have PRIMITIVE_FIELD from
            // which we need to extract the field "token".
            if (ast.name == "PRIMITIVE_FIELD") {
                // Extract the value of entry "IDENTIFIER".
                auto nodeIdentifier = std::find_if(std::begin(ast.nodes), std::end(ast.nodes), [](auto a) { return (a->name == "IDENTIFIER"); });
                if (nodeIdentifier != std::end(ast.nodes)) {
                    fieldNames.push_back((*nodeIdentifier)->token);
                }
                // Visit this node's children to check for duplicated numerical identifiers.
                for (const auto &node : ast.nodes) {
                    retVal &= checkForUniqueFieldNames(*node, prefix, messageNames, fieldNames, numericalMessageIdentifiers, numericalFieldIdentifiers);
                }
            }
            // Within AST node PRIMITIVE_FIELD, we have PRIMITIVE_FIELD_OPTIONS from
            // which we need to extract the field "token".
            if (ast.name == "PRIMITIVE_FIELD_OPTIONS") {
                // Extract the value of entry "IDENTIFIER".
                auto nodeNumericalFieldIdentifier
                    = std::find_if(std::begin(ast.nodes), std::end(ast.nodes), [](auto a) { return (a->name == "NATURAL_NUMBER"); });
                if (nodeNumericalFieldIdentifier != std::end(ast.nodes)) {
                    numericalFieldIdentifiers.push_back(std::stoi((*nodeNumericalFieldIdentifier)->token));
                }
            }
            return retVal;
        };
    // Function to transform AST into list of MetaMessages.
    std::function<void(const peg::Ast &, std::vector<MetaMessage> &)> transform2MetaMessages
        = [](const peg::Ast &ast, std::vector<MetaMessage> &listOfMetaMessages) {
              // "Inner"-lambda to handle various types of message declarations.
              auto createMetaMessage = [](const peg::Ast &_node, std::string _packageName) -> MetaMessage {
                  MetaMessage mm;
                  mm.packageName(::stringtoolbox::trim(_packageName));
                  uint32_t fieldIdentifierCounter{0};
                  for (const auto &e : _node.nodes) {
                      if ("MESSAGE_IDENTIFIER" == e->name) {
                          std::string _messageName = e->token;
                          mm.messageName(::stringtoolbox::trim(_messageName));
                      } else if ("NATURAL_NUMBER" == e->name) {
                          mm.messageIdentifier(std::stoi(e->token));
                      } else if ("PRIMITIVE_FIELD" == e->name) {
                          std::string _fieldName;
                          auto fieldName = std::find_if(std::begin(e->nodes), std::end(e->nodes), [](auto a) { return (a->name == "IDENTIFIER"); });
                          if (fieldName != std::end(e->nodes)) {
                              _fieldName = (*fieldName)->token;
                          }
                          std::string _fieldDataType;
                          auto fieldDataType = std::find_if(std::begin(e->nodes), std::end(e->nodes), [](auto a) { return (a->name == "PRIMITIVE_TYPE"); });
                          if (fieldDataType != std::end(e->nodes)) {
                              _fieldDataType = (*fieldDataType)->token;
                          }
                          fieldIdentifierCounter++; // Automatically count expected field identifiers in case of missing
                                                    // field options.
                          std::string _fieldIdentifier;
                          auto fieldIdentifier = std::find_if(std::begin(e->nodes), std::end(e->nodes), [](auto a) { return (a->name == "NATURAL_NUMBER"); });
                          if (fieldIdentifier != std::end(e->nodes)) {
                              _fieldIdentifier = (*fieldIdentifier)->token;
                          }
                          std::string _fieldDefaultInitializerValue;
                          auto primitiveFieldOptions
                              = std::find_if(std::begin(e->nodes), std::end(e->nodes), [](auto a) { return (a->name == "PRIMITIVE_FIELD_OPTIONS"); });
                          if (primitiveFieldOptions != std::end(e->nodes)) {
                              for (const auto &f : (*primitiveFieldOptions)->nodes) {
                                  if ("NATURAL_NUMBER" != f->name) {
                                      if ("STRING" == f->name) {
                                          _fieldDefaultInitializerValue = "\"" + f->token + "\""; // NOLINT
                                      } else if ("CHARACTER" == f->name) {
References ast, fieldIdentifier(), fieldName(), mm, peg::AstBase< Annotation >::nodes, retVal, and stringtoolbox::trim().
Referenced by cluon::EnvelopeConverter::setMessageSpecification(), and cluon::LCMToGenericMessage::setMessageSpecification().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp