opendlv::proxy::WheelSpeedReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
WheelSpeedReading ()=default
WheelSpeedReading (const WheelSpeedReading &)=default
WheelSpeedReading & operator= (const WheelSpeedReading &)=default
WheelSpeedReading (WheelSpeedReading &&)=default
WheelSpeedReading & operator= (WheelSpeedReading &&)=default
~WheelSpeedReading ()=default
WheelSpeedReading & wheelSpeed (const float &v) noexcept
float wheelSpeed () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_wheelSpeed { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `WheelSpeedReading`
static constexpr const char * TheLongName = `opendlv.proxy.WheelSpeedReading`
Constructor & Destructor Documentation
WheelSpeedReading() [1/3]
opendlv::proxy::WheelSpeedReading::WheelSpeedReading () [default]
WheelSpeedReading() [2/3]
opendlv::proxy::WheelSpeedReading::WheelSpeedReading (const WheelSpeedReading &) [default]
WheelSpeedReading() [3/3]
opendlv::proxy::WheelSpeedReading::WheelSpeedReading (WheelSpeedReading &&) [default]
 WheelSpeedReading()
opendlv::proxy::WheelSpeedReading::~WheelSpeedReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::WheelSpeedReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::WheelSpeedReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::WheelSpeedReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::WheelSpeedReading::ID () [inline], [static]
                                   {
            return 1047;
        }
LongName()
static const std::string opendlv::proxy::WheelSpeedReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
WheelSpeedReading & opendlv::proxy::WheelSpeedReading::operator= (const WheelSpeedReading &) [default]
operator=() [2/2]
WheelSpeedReading & opendlv::proxy::WheelSpeedReading::operator= (WheelSpeedReading &&) [default]
ShortName()
static const std::string opendlv::proxy::WheelSpeedReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
wheelSpeed() [1/2]
float opendlv::proxy::WheelSpeedReading::wheelSpeed () const [inline], [noexcept]
                                                 {
            return m_wheelSpeed;
        }
wheelSpeed() [2/2]
WheelSpeedReading & opendlv::proxy::WheelSpeedReading::wheelSpeed (const float & v) [inline], [noexcept]
                                                                      {
            m_wheelSpeed = v;
            return *this;
        }
Member Data Documentation
m_wheelSpeed
float opendlv::proxy::WheelSpeedReading::m_wheelSpeed { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::WheelSpeedReading::TheLongName = `opendlv.proxy.WheelSpeedReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::WheelSpeedReading::TheShortName = `WheelSpeedReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp