opendlv::proxy::AngleReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AngleReading ()=default
AngleReading (const AngleReading &)=default
AngleReading & operator= (const AngleReading &)=default
AngleReading (AngleReading &&)=default
AngleReading & operator= (AngleReading &&)=default
~AngleReading ()=default
AngleReading & angle (const float &v) noexcept
float angle () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_angle { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AngleReading`
static constexpr const char * TheLongName = `opendlv.proxy.AngleReading`
Constructor & Destructor Documentation
AngleReading() [1/3]
opendlv::proxy::AngleReading::AngleReading () [default]
AngleReading() [2/3]
opendlv::proxy::AngleReading::AngleReading (const AngleReading &) [default]
AngleReading() [3/3]
opendlv::proxy::AngleReading::AngleReading (AngleReading &&) [default]
 AngleReading()
opendlv::proxy::AngleReading::~AngleReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::AngleReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("angle"s), m_angle, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::AngleReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("angle"s), m_angle, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::AngleReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("angle"s), m_angle, visitor);
            visitor.postVisit();
        }
References doVisit().
angle() [1/2]
float opendlv::proxy::AngleReading::angle () const [inline], [noexcept]
                                            {
            return m_angle;
        }
angle() [2/2]
AngleReading & opendlv::proxy::AngleReading::angle (const float & v) [inline], [noexcept]
                                                            {
            m_angle = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::AngleReading::ID () [inline], [static]
                                   {
            return 1038;
        }
LongName()
static const std::string opendlv::proxy::AngleReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AngleReading & opendlv::proxy::AngleReading::operator= (AngleReading &&) [default]
operator=() [2/2]
AngleReading & opendlv::proxy::AngleReading::operator= (const AngleReading &) [default]
ShortName()
static const std::string opendlv::proxy::AngleReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_angle
float opendlv::proxy::AngleReading::m_angle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::AngleReading::TheLongName = `opendlv.proxy.AngleReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::AngleReading::TheShortName = `AngleReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp