cluon::FromProtoVisitor Class Reference
#include <cluon-complete.hpp>
Classes
union DoubleValue
union FloatValue
Public Member Functions
FromProtoVisitor ()=default
~FromProtoVisitor ()=default
FromProtoVisitor & operator= (const FromProtoVisitor &other) noexcept
void decodeFrom (std::istream &in) noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &v) noexcept
template<typename T >
void decodeFrom (std::istream &in, T &v) noexcept
Private Member Functions
FromProtoVisitor (const FromProtoVisitor &)=delete
FromProtoVisitor (FromProtoVisitor &&)=delete
FromProtoVisitor & operator= (FromProtoVisitor &&)=delete
int8_t fromZigZag8 (uint8_t v) noexcept
int16_t fromZigZag16 (uint16_t v) noexcept
int32_t fromZigZag32 (uint32_t v) noexcept
int64_t fromZigZag64 (uint64_t v) noexcept
std::size_t fromVarInt (std::istream &in, uint64_t &value) noexcept
void readBytesFromStream (std::istream &in, std::size_t bytesToReadFromStream, char *buffer) noexcept
Private Attributes
bool m_callToDecodeFromWithDirectVisit {false}
std::unordered_map< uint32_t, linb::any, UseUInt32ValueAsHashKey > m_mapOfKeyValues {}
uint64_t m_value {0}
union cluon::FromProtoVisitor::DoubleValue m_doubleValue
union cluon::FromProtoVisitor::FloatValue m_floatValue
std::vector< char > m_stringValue
uint64_t m_keyFieldType {0}
ProtoConstants m_protoType {ProtoConstants::VARINT}
uint32_t m_fieldId {0}
Detailed Description
This class decodes a given message from Proto format.
Constructor & Destructor Documentation
FromProtoVisitor() [1/3]
cluon::FromProtoVisitor::FromProtoVisitor (const FromProtoVisitor &) [private], [delete]
FromProtoVisitor() [2/3]
cluon::FromProtoVisitor::FromProtoVisitor (FromProtoVisitor &&) [private], [delete]
FromProtoVisitor() [3/3]
cluon::FromProtoVisitor::FromProtoVisitor () [default]
 FromProtoVisitor()
cluon::FromProtoVisitor::~FromProtoVisitor () [default]
Member Function Documentation
decodeFrom() [1/2]
void cluon::FromProtoVisitor::decodeFrom (std::istream & in) [inline], [noexcept]
This method decodes a given istream into Proto.
Parameters
in istream to decode.
                                                                {
    // Reset internal states as this deserializer could be reused.
    m_mapOfKeyValues.clear();
    while (in.good()) {
        // First stage: Read keyFieldType (encoded as VarInt).
        if (0 < fromVarInt(in, m_keyFieldType)) {
            // Succeeded to read keyFieldType entry; extract information.
            m_protoType = static_cast<ProtoConstants>(m_keyFieldType & 0x7);
            m_fieldId = static_cast<uint32_t>(m_keyFieldType >> 3);
            switch (m_protoType) {
                case ProtoConstants::VARINT:
                {
                    // Directly decode VarInt value.
                    fromVarInt(in, m_value);
                    m_mapOfKeyValues.emplace(m_fieldId, linb::any(m_value));
                }
                break;
                case ProtoConstants::EIGHT_BYTES:
                {
                    readBytesFromStream(in, sizeof(double), m_doubleValue.buffer.data());
                    m_doubleValue.uint64Value = le64toh(m_doubleValue.uint64Value);
                    m_mapOfKeyValues.emplace(m_fieldId, linb::any(m_doubleValue.doubleValue));
                }
                break;
                case ProtoConstants::FOUR_BYTES:
                {
                    readBytesFromStream(in, sizeof(float), m_floatValue.buffer.data());
                    m_floatValue.uint32Value = le32toh(m_floatValue.uint32Value);
                    m_mapOfKeyValues.emplace(m_fieldId, linb::any(m_floatValue.floatValue));
                }
                break;
                case ProtoConstants::LENGTH_DELIMITED:
                {
                    fromVarInt(in, m_value);
                    const std::size_t BYTES_TO_READ_FROM_STREAM{static_cast<std::size_t>(m_value)};
                    if (m_stringValue.capacity() < BYTES_TO_READ_FROM_STREAM) {
                        m_stringValue.reserve(BYTES_TO_READ_FROM_STREAM);
                    }
                    readBytesFromStream(in, BYTES_TO_READ_FROM_STREAM, m_stringValue.data());
                    m_mapOfKeyValues.emplace(m_fieldId, linb::any(std::string(m_stringValue.data(), static_cast<std::size_t>(m_value))));
                }
                break;
            }
        }
    }
}
References cluon::EIGHT_BYTES, cluon::FOUR_BYTES, cluon::LENGTH_DELIMITED, and cluon::VARINT.
Referenced by cluon::extractEnvelope(), cluon::extractMessage(), cluon::EnvelopeConverter::getJSONFromEnvelope(), cluon::EnvelopeConverter::getJSONFromProtoEncodedEnvelope(), and visit().
decodeFrom() [2/2]
template<typename T >
void cluon::FromProtoVisitor::decodeFrom (std::istream & in, T & v) [inline], [noexcept]
This method decodes a given istream into corresponding fields of v.
Parameters
in istream to decode.
v Data structure to receive the decoded values.
                                                   {
        m_callToDecodeFromWithDirectVisit = true;
        while (in.good()) {
            // First stage: Read keyFieldType (encoded as VarInt).
            if (0 < fromVarInt(in, m_keyFieldType)) {
                // Succeeded to read keyFieldType entry; extract information.
                m_protoType = static_cast<ProtoConstants>(m_keyFieldType & 0x7);
                m_fieldId = static_cast<uint32_t>(m_keyFieldType >> 3);
                switch (m_protoType) {
                    case ProtoConstants::VARINT:
                    {
                        // Directly decode VarInt value.
                        fromVarInt(in, m_value);
                        v.accept(m_fieldId, *this);
                    }
                    break;
                    case ProtoConstants::EIGHT_BYTES:
                    {
                        readBytesFromStream(in, sizeof(double), m_doubleValue.buffer.data());
                        m_doubleValue.uint64Value = le64toh(m_doubleValue.uint64Value);
                        v.accept(m_fieldId, *this);
                    }
                    break;
                    case ProtoConstants::FOUR_BYTES:
                    {
                        readBytesFromStream(in, sizeof(float), m_floatValue.buffer.data());
                        m_floatValue.uint32Value = le32toh(m_floatValue.uint32Value);
                        v.accept(m_fieldId, *this);
                    }
                    break;
                    case ProtoConstants::LENGTH_DELIMITED:
                    {
                        fromVarInt(in, m_value);
                        const std::size_t BYTES_TO_READ_FROM_STREAM{static_cast<std::size_t>(m_value)};
                        if (m_stringValue.capacity() < BYTES_TO_READ_FROM_STREAM) {
                            m_stringValue.reserve(BYTES_TO_READ_FROM_STREAM);
                        }
                        readBytesFromStream(in, BYTES_TO_READ_FROM_STREAM, m_stringValue.data());
                        v.accept(m_fieldId, *this);
                    }
                    break;
                }
            }
        }
        m_callToDecodeFromWithDirectVisit = false;
    }
References cluon::EIGHT_BYTES, cluon::FOUR_BYTES, cluon::LENGTH_DELIMITED, and cluon::VARINT.
fromVarInt()
std::size_t cluon::FromProtoVisitor::fromVarInt (std::istream & in, uint64_t & value) [inline], [private], [noexcept]
                                                                                      {
    value = 0;
    constexpr uint64_t MASK = 0x7f;
    constexpr uint64_t SHIFT = 0x7;
    constexpr uint64_t MSB = 0x80;
    std::size_t size = 0;
    uint64_t C{0};
    while (in.good()) {
        auto x = in.get();
        C = static_cast<uint64_t>(x);
        value |= (C & MASK) << (SHIFT * size++);
        if (!(C & MSB)) { // NOLINT
            break;
        }
    }
    return size;
}
fromZigZag16()
int16_t cluon::FromProtoVisitor::fromZigZag16 (uint16_t v) [inline], [private], [noexcept]
                                                                 {
    return static_cast<int16_t>((v >> 1) ^ -(v & 1));
}
fromZigZag32()
int32_t cluon::FromProtoVisitor::fromZigZag32 (uint32_t v) [inline], [private], [noexcept]
                                                                 {
    return static_cast<int32_t>((v >> 1) ^ -(v & 1));
}
fromZigZag64()
int64_t cluon::FromProtoVisitor::fromZigZag64 (uint64_t v) [inline], [private], [noexcept]
                                                                 {
    return static_cast<int64_t>((v >> 1) ^ -(v & 1));
}
fromZigZag8()
int8_t cluon::FromProtoVisitor::fromZigZag8 (uint8_t v) [inline], [private], [noexcept]
                                                              {
    return static_cast<int8_t>((v >> 1) ^ -(v & 1));
}
operator=() [1/2]
FromProtoVisitor & cluon::FromProtoVisitor::operator= (const FromProtoVisitor & other) [inline], [noexcept]
                                                                                           {
    m_mapOfKeyValues = other.m_mapOfKeyValues;
    return *this;
}
References m_mapOfKeyValues.
operator=() [2/2]
FromProtoVisitor & cluon::FromProtoVisitor::operator= (FromProtoVisitor &&) [private], [delete]
postVisit()
void cluon::FromProtoVisitor::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::FromProtoVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                                 {
    (void)id;
    (void)shortName;
    (void)longName;
}
readBytesFromStream()
void cluon::FromProtoVisitor::readBytesFromStream (std::istream & in, std::size_t bytesToReadFromStream, char * buffer) [inline], [private], [noexcept]
                                                                                                                        {
    if (nullptr != buffer) {
        const constexpr std::size_t CHUNK_SIZE{1024};
        std::streamsize bufferPosition{0};
        std::streamsize extractedBytes{0};
        while ((0 < bytesToReadFromStream) && in.good()) {
            // clang-format off
            in.read(&buffer[static_cast<std::size_t>(bufferPosition)], /* Flawfinder: ignore */ /* Cf. buffer.reserve(...) above. */
                    (bytesToReadFromStream > CHUNK_SIZE) ? CHUNK_SIZE : static_cast<std::streamsize>(bytesToReadFromStream));
            // clang-format on
            extractedBytes = in.gcount();
            bufferPosition += extractedBytes;
            bytesToReadFromStream -= static_cast<std::size_t>(extractedBytes);
        }
    }
}
visit() [1/14]
template<typename T >
void cluon::FromProtoVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & v) [inline], [noexcept]
                                                                                    {
        (void)typeName;
        (void)name;
        if (m_callToDecodeFromWithDirectVisit) {
            std::stringstream sstr{std::move(std::string(m_stringValue.data(), static_cast<std::size_t>(m_value)))};
            cluon::FromProtoVisitor nestedProtoDecoder;
            nestedProtoDecoder.decodeFrom(sstr, v);
        }
        else if (0 < m_mapOfKeyValues.count(id)) {
            try {
                std::stringstream sstr{linb::any_cast<std::string>(m_mapOfKeyValues[id])};
                cluon::FromProtoVisitor nestedProtoDecoder;
                nestedProtoDecoder.decodeFrom(sstr);
                v.accept(nestedProtoDecoder);
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        }
    }
References decodeFrom().
visit() [2/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = (0 != m_value);
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            v = (0 != linb::any_cast<uint64_t>(m_mapOfKeyValues[id]));
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [3/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<char>(m_value);
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<char>(_v);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [4/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = m_doubleValue.doubleValue;
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            v = linb::any_cast<double>(m_mapOfKeyValues[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [5/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = m_floatValue.floatValue;
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            v = linb::any_cast<float>(m_mapOfKeyValues[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [6/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<int16_t>(fromZigZag16(static_cast<uint16_t>(m_value)));
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<int16_t>(fromZigZag16(static_cast<uint16_t>(_v)));
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [7/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<int32_t>(fromZigZag32(static_cast<uint32_t>(m_value)));
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<int32_t>(fromZigZag32(static_cast<uint32_t>(_v)));
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [8/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<int64_t>(fromZigZag64(static_cast<uint64_t>(m_value)));
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<int64_t>(fromZigZag64(_v));
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [9/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<int8_t>(fromZigZag8(static_cast<uint8_t>(m_value)));
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<int8_t>(fromZigZag8(static_cast<uint8_t>(_v)));
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [10/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                              {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = std::string(m_stringValue.data(), static_cast<std::size_t>(m_value));
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            v = linb::any_cast<std::string>(m_mapOfKeyValues[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [11/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                             {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<uint16_t>(m_value);
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<uint16_t>(_v);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [12/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                             {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<uint32_t>(m_value);
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<uint32_t>(_v);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [13/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                             {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = m_value;
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
visit() [14/14]
void cluon::FromProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    if (m_callToDecodeFromWithDirectVisit) {
        v = static_cast<uint8_t>(m_value);
    }
    else if (m_mapOfKeyValues.count(id) > 0) {
        try {
            uint64_t _v = linb::any_cast<uint64_t>(m_mapOfKeyValues[id]);
            v = static_cast<uint8_t>(_v);
        } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
        }
    }
}
Member Data Documentation
m_callToDecodeFromWithDirectVisit
bool cluon::FromProtoVisitor::m_callToDecodeFromWithDirectVisit {false} [private]
m_doubleValue
union cluon::FromProtoVisitor::DoubleValue cluon::FromProtoVisitor::m_doubleValue [private]
m_fieldId
uint32_t cluon::FromProtoVisitor::m_fieldId {0} [private]
m_floatValue
union cluon::FromProtoVisitor::FloatValue cluon::FromProtoVisitor::m_floatValue [private]
m_keyFieldType
uint64_t cluon::FromProtoVisitor::m_keyFieldType {0} [private]
m_mapOfKeyValues
std::unordered_map<uint32_t, linb::any, UseUInt32ValueAsHashKey> cluon::FromProtoVisitor::m_mapOfKeyValues {} [private]
Referenced by operator=().
m_protoType
ProtoConstants cluon::FromProtoVisitor::m_protoType {ProtoConstants::VARINT} [private]
m_stringValue
std::vector<char> cluon::FromProtoVisitor::m_stringValue [private]
m_value
uint64_t cluon::FromProtoVisitor::m_value {0} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp