opendlv::logic::perception::GroundSurfaceArea Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSurfaceArea ()=default
GroundSurfaceArea (const GroundSurfaceArea &)=default
GroundSurfaceArea & operator= (const GroundSurfaceArea &)=default
GroundSurfaceArea (GroundSurfaceArea &&)=default
GroundSurfaceArea & operator= (GroundSurfaceArea &&)=default
~GroundSurfaceArea ()=default
GroundSurfaceArea & surfaceId (const uint32_t &v) noexcept
uint32_t surfaceId () const noexcept
GroundSurfaceArea & x1 (const float &v) noexcept
float x1 () const noexcept
GroundSurfaceArea & y1 (const float &v) noexcept
float y1 () const noexcept
GroundSurfaceArea & x2 (const float &v) noexcept
float x2 () const noexcept
GroundSurfaceArea & y2 (const float &v) noexcept
float y2 () const noexcept
GroundSurfaceArea & x3 (const float &v) noexcept
float x3 () const noexcept
GroundSurfaceArea & y3 (const float &v) noexcept
float y3 () const noexcept
GroundSurfaceArea & x4 (const float &v) noexcept
float x4 () const noexcept
GroundSurfaceArea & y4 (const float &v) noexcept
float y4 () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_surfaceId { 0 }
float m_x1 { 0.0f }
float m_y1 { 0.0f }
float m_x2 { 0.0f }
float m_y2 { 0.0f }
float m_x3 { 0.0f }
float m_y3 { 0.0f }
float m_x4 { 0.0f }
float m_y4 { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSurfaceArea`
static constexpr const char * TheLongName = `opendlv.logic.perception.GroundSurfaceArea`
Constructor & Destructor Documentation
GroundSurfaceArea() [1/3]
opendlv::logic::perception::GroundSurfaceArea::GroundSurfaceArea () [default]
GroundSurfaceArea() [2/3]
opendlv::logic::perception::GroundSurfaceArea::GroundSurfaceArea (const GroundSurfaceArea &) [default]
GroundSurfaceArea() [3/3]
opendlv::logic::perception::GroundSurfaceArea::GroundSurfaceArea (GroundSurfaceArea &&) [default]
 GroundSurfaceArea()
opendlv::logic::perception::GroundSurfaceArea::~GroundSurfaceArea () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::GroundSurfaceArea::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("x1"s), m_x1, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("y1"s), m_y1, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("x2"s), m_x2, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("float"s), std::move("y2"s), m_y2, preVisit, visit, postVisit);
            doTripletForwardVisit(6, std::move("float"s), std::move("x3"s), m_x3, preVisit, visit, postVisit);
            doTripletForwardVisit(7, std::move("float"s), std::move("y3"s), m_y3, preVisit, visit, postVisit);
            doTripletForwardVisit(8, std::move("float"s), std::move("x4"s), m_x4, preVisit, visit, postVisit);
            doTripletForwardVisit(9, std::move("float"s), std::move("y4"s), m_y4, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceArea::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("x1"s), m_x1, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("y1"s), m_y1, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("x2"s), m_x2, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("float"s), std::move("y2"s), m_y2, visitor);
                return;
            }
            if (6 == fieldId) {
                doVisit(6, std::move("float"s), std::move("x3"s), m_x3, visitor);
                return;
            }
            if (7 == fieldId) {
                doVisit(7, std::move("float"s), std::move("y3"s), m_y3, visitor);
                return;
            }
            if (8 == fieldId) {
                doVisit(8, std::move("float"s), std::move("x4"s), m_x4, visitor);
                return;
            }
            if (9 == fieldId) {
                doVisit(9, std::move("float"s), std::move("y4"s), m_y4, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceArea::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
            doVisit(2, std::move("float"s), std::move("x1"s), m_x1, visitor);
            doVisit(3, std::move("float"s), std::move("y1"s), m_y1, visitor);
            doVisit(4, std::move("float"s), std::move("x2"s), m_x2, visitor);
            doVisit(5, std::move("float"s), std::move("y2"s), m_y2, visitor);
            doVisit(6, std::move("float"s), std::move("x3"s), m_x3, visitor);
            doVisit(7, std::move("float"s), std::move("y3"s), m_y3, visitor);
            doVisit(8, std::move("float"s), std::move("x4"s), m_x4, visitor);
            doVisit(9, std::move("float"s), std::move("y4"s), m_y4, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::GroundSurfaceArea::ID () [inline], [static]
                                   {
            return 1143;
        }
LongName()
static const std::string opendlv::logic::perception::GroundSurfaceArea::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::operator= (const GroundSurfaceArea &) [default]
operator=() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::operator= (GroundSurfaceArea &&) [default]
ShortName()
static const std::string opendlv::logic::perception::GroundSurfaceArea::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
surfaceId() [1/2]
uint32_t opendlv::logic::perception::GroundSurfaceArea::surfaceId () const [inline], [noexcept]
                                                   {
            return m_surfaceId;
        }
surfaceId() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::surfaceId (const uint32_t & v) [inline], [noexcept]
                                                                        {
            m_surfaceId = v;
            return *this;
        }
x1() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::x1 () const [inline], [noexcept]
                                         {
            return m_x1;
        }
x1() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::x1 (const float & v) [inline], [noexcept]
                                                              {
            m_x1 = v;
            return *this;
        }
x2() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::x2 () const [inline], [noexcept]
                                         {
            return m_x2;
        }
x2() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::x2 (const float & v) [inline], [noexcept]
                                                              {
            m_x2 = v;
            return *this;
        }
x3() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::x3 () const [inline], [noexcept]
                                         {
            return m_x3;
        }
x3() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::x3 (const float & v) [inline], [noexcept]
                                                              {
            m_x3 = v;
            return *this;
        }
x4() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::x4 () const [inline], [noexcept]
                                         {
            return m_x4;
        }
x4() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::x4 (const float & v) [inline], [noexcept]
                                                              {
            m_x4 = v;
            return *this;
        }
y1() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::y1 () const [inline], [noexcept]
                                         {
            return m_y1;
        }
y1() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::y1 (const float & v) [inline], [noexcept]
                                                              {
            m_y1 = v;
            return *this;
        }
y2() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::y2 () const [inline], [noexcept]
                                         {
            return m_y2;
        }
y2() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::y2 (const float & v) [inline], [noexcept]
                                                              {
            m_y2 = v;
            return *this;
        }
y3() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::y3 () const [inline], [noexcept]
                                         {
            return m_y3;
        }
y3() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::y3 (const float & v) [inline], [noexcept]
                                                              {
            m_y3 = v;
            return *this;
        }
y4() [1/2]
float opendlv::logic::perception::GroundSurfaceArea::y4 () const [inline], [noexcept]
                                         {
            return m_y4;
        }
y4() [2/2]
GroundSurfaceArea & opendlv::logic::perception::GroundSurfaceArea::y4 (const float & v) [inline], [noexcept]
                                                              {
            m_y4 = v;
            return *this;
        }
Member Data Documentation
m_surfaceId
uint32_t opendlv::logic::perception::GroundSurfaceArea::m_surfaceId { 0 } [private]
m_x1
float opendlv::logic::perception::GroundSurfaceArea::m_x1 { 0.0f } [private]
m_x2
float opendlv::logic::perception::GroundSurfaceArea::m_x2 { 0.0f } [private]
m_x3
float opendlv::logic::perception::GroundSurfaceArea::m_x3 { 0.0f } [private]
m_x4
float opendlv::logic::perception::GroundSurfaceArea::m_x4 { 0.0f } [private]
m_y1
float opendlv::logic::perception::GroundSurfaceArea::m_y1 { 0.0f } [private]
m_y2
float opendlv::logic::perception::GroundSurfaceArea::m_y2 { 0.0f } [private]
m_y3
float opendlv::logic::perception::GroundSurfaceArea::m_y3 { 0.0f } [private]
m_y4
float opendlv::logic::perception::GroundSurfaceArea::m_y4 { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::perception::GroundSurfaceArea::TheLongName = `opendlv.logic.perception.GroundSurfaceArea` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::GroundSurfaceArea::TheShortName = `GroundSurfaceArea` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp