cluon::FromLCMVisitor Class Reference
#include <cluon-complete.hpp>
Public Member Functions
FromLCMVisitor () noexcept
~FromLCMVisitor ()=default
void decodeFrom (std::istream &in) noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Private Member Functions
FromLCMVisitor (std::stringstream &in) noexcept
FromLCMVisitor (const FromLCMVisitor &)=delete
FromLCMVisitor (FromLCMVisitor &&)=delete
FromLCMVisitor & operator= (const FromLCMVisitor &)=delete
FromLCMVisitor & operator= (FromLCMVisitor &&)=delete
int64_t hash () const noexcept
void calculateHash (char c) noexcept
void calculateHash (const std::string &s) noexcept
Private Attributes
int64_t m_calculatedHash {0x12345678}
int64_t m_expectedHash {0}
std::stringstream m_internalBuffer {``}
std::stringstream & m_buffer
std::vector< int64_t > m_hashes {}
Detailed Description
This class decodes a given message from LCM format.
Constructor & Destructor Documentation
FromLCMVisitor() [1/4]
cluon::FromLCMVisitor::FromLCMVisitor (std::stringstream & in) [inline], [private], [noexcept]
    : m_expectedHash{0}
    , m_buffer(in) {}
FromLCMVisitor() [2/4]
cluon::FromLCMVisitor::FromLCMVisitor (const FromLCMVisitor &) [private], [delete]
FromLCMVisitor() [3/4]
cluon::FromLCMVisitor::FromLCMVisitor (FromLCMVisitor &&) [private], [delete]
FromLCMVisitor() [4/4]
cluon::FromLCMVisitor::FromLCMVisitor () [inline], [noexcept]
    : m_buffer(m_internalBuffer) {}
 FromLCMVisitor()
cluon::FromLCMVisitor::~FromLCMVisitor () [default]
Member Function Documentation
calculateHash() [1/2]
void cluon::FromLCMVisitor::calculateHash (char c) [inline], [private], [noexcept]
                                                         {
    m_calculatedHash = ((m_calculatedHash << 8) ^ (m_calculatedHash >> 55)) + c;
}
calculateHash() [2/2]
void cluon::FromLCMVisitor::calculateHash (const std::string & s) [inline], [private], [noexcept]
                                                                     {
    const std::string tmp{(s.length() > 255 ? s.substr(0, 255) : s)};
    const uint8_t length{static_cast<uint8_t>(tmp.length())};
    calculateHash(static_cast<char>(length));
    for (auto c : tmp) { calculateHash(c); }
}
decodeFrom()
void cluon::FromLCMVisitor::decodeFrom (std::istream & in) [inline], [noexcept]
This method decodes a given istream into LCM.
Parameters
in istream to decode.
                                                              {
    // Reset internal states as this deserializer could be reused.
    m_buffer.clear();
    m_buffer.str("");
    in.read(reinterpret_cast<char *>(&m_expectedHash), sizeof(int64_t));
    m_expectedHash = static_cast<int64_t>(be64toh(m_expectedHash));
    m_buffer << in.rdbuf();
}
Referenced by cluon::LCMToGenericMessage::getGenericMessage().
hash()
int64_t cluon::FromLCMVisitor::hash () const [inline], [private], [noexcept]
                                                   {
    // Apply ZigZag encoding for hash from this message's fields and depending
    // hashes for complex nested types.
    int64_t tmp{m_calculatedHash};
    for (int64_t v : m_hashes) { tmp += v; }
    const int64_t hash = (tmp << 1) + ((tmp >> 63) & 1);
    return hash;
}
References hash(), m_calculatedHash, and m_hashes.
Referenced by hash(), postVisit(), and visit().
operator=() [1/2]
FromLCMVisitor & cluon::FromLCMVisitor::operator= (const FromLCMVisitor &) [private], [delete]
operator=() [2/2]
FromLCMVisitor & cluon::FromLCMVisitor::operator= (FromLCMVisitor &&) [private], [delete]
postVisit()
void cluon::FromLCMVisitor::postVisit () [inline], [noexcept]
                                               {
    if ((0 != m_expectedHash) && (m_expectedHash != hash())) {
        std::cerr << "[cluon::FromLCMVisitor] Hash mismatch - decoding might have failed" << std::endl; // LCOV_EXCL_LINE
    }
}
References hash(), and m_expectedHash.
preVisit()
void cluon::FromLCMVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                               {
    (void)id;
    (void)shortName;
    (void)longName;
    // Reset m_buffer read pointer to beginning only if we are not dealing with
    // nested complex types as we are sharing our buffer with our parent message.
    if (0 != m_expectedHash) {
        m_buffer.clear();
        m_buffer.seekg(0);
        m_calculatedHash = 0x12345678;
        m_hashes.clear();
    }
}
visit() [1/14]
template<typename T >
void cluon::FromLCMVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                        {
        (void)id;
        (void)typeName;
        // No hash for the type but for name and dimension.
        calculateHash(name);
        calculateHash(0);
        cluon::FromLCMVisitor nestedLCMDecoder(m_buffer);
        value.accept(nestedLCMDecoder);
        m_hashes.push_back(nestedLCMDecoder.hash());
    }
References hash().
visit() [2/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                       {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("boolean");
    calculateHash(0);
    m_buffer.read(reinterpret_cast<char *>(&v), sizeof(bool));
}
visit() [3/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                       {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.read(reinterpret_cast<char *>(&v), sizeof(char));
}
visit() [4/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                         {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("double");
    calculateHash(0);
    int64_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int64_t));
    _v = static_cast<int64_t>(be64toh(_v));
    std::memmove(&v, &_v, sizeof(int64_t));
}
visit() [5/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                        {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("float");
    calculateHash(0);
    int32_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int32_t));
    _v = static_cast<int32_t>(be32toh(_v));
    std::memmove(&v, &_v, sizeof(int32_t));
}
visit() [6/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                          {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int16_t");
    calculateHash(0);
    int16_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int16_t));
    v = static_cast<int16_t>(be16toh(_v));
}
visit() [7/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                          {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int32_t");
    calculateHash(0);
    int32_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int32_t));
    v = static_cast<int32_t>(be32toh(_v));
}
visit() [8/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                          {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int64_t");
    calculateHash(0);
    int64_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int64_t));
    v = static_cast<int64_t>(be64toh(_v));
}
visit() [9/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                         {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.read(reinterpret_cast<char *>(&v), sizeof(int8_t));
}
visit() [10/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                            {
    (void)id;
    (void)typeName;
    (void)name;
    (void)v;
    calculateHash(name);
    calculateHash("string");
    calculateHash(0);
    int32_t length{0};
    m_buffer.read(reinterpret_cast<char *>(&length), sizeof(int32_t));
    length = static_cast<int32_t>(be32toh(length));
    v.clear();
    if (length > 0) {
        std::vector<char> buffer;
        buffer.reserve(static_cast<uint32_t>(length));
#ifdef WIN32
        for (uint32_t i = 0; i < static_cast<uint32_t>(length); i++) {
            char c;
            m_buffer.get(c);
            buffer.push_back(c);
        }
#else
        m_buffer.read(static_cast<char *>(&buffer[0]), static_cast<std::streamsize>(length));
#endif
        const std::string s(buffer.begin(), buffer.begin() + length - 1); // Skip trailing '\0'.
        v = s;
    }
}
visit() [11/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                           {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int16_t");
    calculateHash(0);
    int16_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int16_t));
    v = be16toh(_v);
}
visit() [12/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                           {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int32_t");
    calculateHash(0);
    int32_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int32_t));
    v = be32toh(_v);
}
visit() [13/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                           {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int64_t");
    calculateHash(0);
    int64_t _v{0};
    m_buffer.read(reinterpret_cast<char *>(&_v), sizeof(int64_t));
    v = be64toh(_v);
}
visit() [14/14]
void cluon::FromLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                          {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.read(reinterpret_cast<char *>(&v), sizeof(int8_t));
}
Member Data Documentation
m_buffer
std::stringstream& cluon::FromLCMVisitor::m_buffer [private]
m_calculatedHash
int64_t cluon::FromLCMVisitor::m_calculatedHash {0x12345678} [private]
Referenced by hash().
m_expectedHash
int64_t cluon::FromLCMVisitor::m_expectedHash {0} [private]
Referenced by postVisit().
m_hashes
std::vector<int64_t> cluon::FromLCMVisitor::m_hashes {} [private]
Referenced by hash().
m_internalBuffer
std::stringstream cluon::FromLCMVisitor::m_internalBuffer {``} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp