opendlv::proxy::WheelSpeedRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
WheelSpeedRequest ()=default
WheelSpeedRequest (const WheelSpeedRequest &)=default
WheelSpeedRequest & operator= (const WheelSpeedRequest &)=default
WheelSpeedRequest (WheelSpeedRequest &&)=default
WheelSpeedRequest & operator= (WheelSpeedRequest &&)=default
~WheelSpeedRequest ()=default
WheelSpeedRequest & wheelSpeed (const float &v) noexcept
float wheelSpeed () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_wheelSpeed { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `WheelSpeedRequest`
static constexpr const char * TheLongName = `opendlv.proxy.WheelSpeedRequest`
Constructor & Destructor Documentation
WheelSpeedRequest() [1/3]
opendlv::proxy::WheelSpeedRequest::WheelSpeedRequest () [default]
WheelSpeedRequest() [2/3]
opendlv::proxy::WheelSpeedRequest::WheelSpeedRequest (const WheelSpeedRequest &) [default]
WheelSpeedRequest() [3/3]
opendlv::proxy::WheelSpeedRequest::WheelSpeedRequest (WheelSpeedRequest &&) [default]
 WheelSpeedRequest()
opendlv::proxy::WheelSpeedRequest::~WheelSpeedRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::WheelSpeedRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::WheelSpeedRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::WheelSpeedRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("wheelSpeed"s), m_wheelSpeed, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::WheelSpeedRequest::ID () [inline], [static]
                                   {
            return 1094;
        }
LongName()
static const std::string opendlv::proxy::WheelSpeedRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
WheelSpeedRequest & opendlv::proxy::WheelSpeedRequest::operator= (const WheelSpeedRequest &) [default]
operator=() [2/2]
WheelSpeedRequest & opendlv::proxy::WheelSpeedRequest::operator= (WheelSpeedRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::WheelSpeedRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
wheelSpeed() [1/2]
float opendlv::proxy::WheelSpeedRequest::wheelSpeed () const [inline], [noexcept]
                                                 {
            return m_wheelSpeed;
        }
wheelSpeed() [2/2]
WheelSpeedRequest & opendlv::proxy::WheelSpeedRequest::wheelSpeed (const float & v) [inline], [noexcept]
                                                                      {
            m_wheelSpeed = v;
            return *this;
        }
Member Data Documentation
m_wheelSpeed
float opendlv::proxy::WheelSpeedRequest::m_wheelSpeed { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::WheelSpeedRequest::TheLongName = `opendlv.proxy.WheelSpeedRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::WheelSpeedRequest::TheShortName = `WheelSpeedRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp