peg::TokenBoundary Class Reference
#include <cluon-complete.hpp>
Public Member Functions
TokenBoundary (const std::shared_ptr< Ope > &ope)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::shared_ptr< Ope > ope_
Constructor & Destructor Documentation
TokenBoundary()
peg::TokenBoundary::TokenBoundary (const std::shared_ptr< Ope > & ope) [inline]
: ope_(ope) {}
Member Function Documentation
accept()
void peg::TokenBoundary::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::TokenBoundary::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                         {
    c.in_token = true;
    auto se = make_scope_exit([&]() { c.in_token = false; });
    const auto& rule = *ope_;
    auto len = rule.parse(s, n, sv, c, dt);
    if (success(len)) {
        sv.tokens.push_back(std::make_pair(s, len));
        if (c.whitespaceOpe) {
            auto l = c.whitespaceOpe->parse(s + len, n - len, sv, c, dt);
            if (fail(l)) {
                return static_cast<size_t>(-1);
            }
            len += l;
        }
    }
    return len;
}
References peg::fail(), peg::Context::in_token, peg::make_scope_exit(), peg::success(), peg::SemanticValues::tokens, and peg::Context::whitespaceOpe.
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::TokenBoundary::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp