opendlv::proxy::PointCloudReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PointCloudReading ()=default
PointCloudReading (const PointCloudReading &)=default
PointCloudReading & operator= (const PointCloudReading &)=default
PointCloudReading (PointCloudReading &&)=default
PointCloudReading & operator= (PointCloudReading &&)=default
~PointCloudReading ()=default
PointCloudReading & startAzimuth (const float &v) noexcept
float startAzimuth () const noexcept
PointCloudReading & endAzimuth (const float &v) noexcept
float endAzimuth () const noexcept
PointCloudReading & entriesPerAzimuth (const uint8_t &v) noexcept
uint8_t entriesPerAzimuth () const noexcept
PointCloudReading & distances (const std::string &v) noexcept
std::string distances () const noexcept
PointCloudReading & numberOfBitsForIntensity (const uint8_t &v) noexcept
uint8_t numberOfBitsForIntensity () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_startAzimuth { 0.0f }
float m_endAzimuth { 0.0f }
uint8_t m_entriesPerAzimuth { 0 }
std::string m_distances { ``s }
uint8_t m_numberOfBitsForIntensity { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `PointCloudReading`
static constexpr const char * TheLongName = `opendlv.proxy.PointCloudReading`
Constructor & Destructor Documentation
PointCloudReading() [1/3]
opendlv::proxy::PointCloudReading::PointCloudReading () [default]
PointCloudReading() [2/3]
opendlv::proxy::PointCloudReading::PointCloudReading (const PointCloudReading &) [default]
PointCloudReading() [3/3]
opendlv::proxy::PointCloudReading::PointCloudReading (PointCloudReading &&) [default]
 PointCloudReading()
opendlv::proxy::PointCloudReading::~PointCloudReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PointCloudReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("startAzimuth"s), m_startAzimuth, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("endAzimuth"s), m_endAzimuth, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("uint8_t"s), std::move("entriesPerAzimuth"s), m_entriesPerAzimuth, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("std::string"s), std::move("distances"s), m_distances, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("uint8_t"s), std::move("numberOfBitsForIntensity"s), m_numberOfBitsForIntensity, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PointCloudReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("startAzimuth"s), m_startAzimuth, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("endAzimuth"s), m_endAzimuth, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("uint8_t"s), std::move("entriesPerAzimuth"s), m_entriesPerAzimuth, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("std::string"s), std::move("distances"s), m_distances, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("uint8_t"s), std::move("numberOfBitsForIntensity"s), m_numberOfBitsForIntensity, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PointCloudReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("startAzimuth"s), m_startAzimuth, visitor);
            doVisit(2, std::move("float"s), std::move("endAzimuth"s), m_endAzimuth, visitor);
            doVisit(3, std::move("uint8_t"s), std::move("entriesPerAzimuth"s), m_entriesPerAzimuth, visitor);
            doVisit(4, std::move("std::string"s), std::move("distances"s), m_distances, visitor);
            doVisit(5, std::move("uint8_t"s), std::move("numberOfBitsForIntensity"s), m_numberOfBitsForIntensity, visitor);
            visitor.postVisit();
        }
References doVisit().
distances() [1/2]
std::string opendlv::proxy::PointCloudReading::distances () const [inline], [noexcept]
                                                    {
            return m_distances;
        }
distances() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::distances (const std::string & v) [inline], [noexcept]
                                                                         {
            m_distances = v;
            return *this;
        }
endAzimuth() [1/2]
float opendlv::proxy::PointCloudReading::endAzimuth () const [inline], [noexcept]
                                                 {
            return m_endAzimuth;
        }
endAzimuth() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::endAzimuth (const float & v) [inline], [noexcept]
                                                                      {
            m_endAzimuth = v;
            return *this;
        }
entriesPerAzimuth() [1/2]
uint8_t opendlv::proxy::PointCloudReading::entriesPerAzimuth () const [inline], [noexcept]
                                                          {
            return m_entriesPerAzimuth;
        }
entriesPerAzimuth() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::entriesPerAzimuth (const uint8_t & v) [inline], [noexcept]
                                                                               {
            m_entriesPerAzimuth = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::PointCloudReading::ID () [inline], [static]
                                   {
            return 49;
        }
LongName()
static const std::string opendlv::proxy::PointCloudReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
numberOfBitsForIntensity() [1/2]
uint8_t opendlv::proxy::PointCloudReading::numberOfBitsForIntensity () const [inline], [noexcept]
                                                                 {
            return m_numberOfBitsForIntensity;
        }
numberOfBitsForIntensity() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::numberOfBitsForIntensity (const uint8_t & v) [inline], [noexcept]
                                                                                      {
            m_numberOfBitsForIntensity = v;
            return *this;
        }
operator=() [1/2]
PointCloudReading & opendlv::proxy::PointCloudReading::operator= (const PointCloudReading &) [default]
operator=() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::operator= (PointCloudReading &&) [default]
ShortName()
static const std::string opendlv::proxy::PointCloudReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
startAzimuth() [1/2]
float opendlv::proxy::PointCloudReading::startAzimuth () const [inline], [noexcept]
                                                   {
            return m_startAzimuth;
        }
startAzimuth() [2/2]
PointCloudReading & opendlv::proxy::PointCloudReading::startAzimuth (const float & v) [inline], [noexcept]
                                                                        {
            m_startAzimuth = v;
            return *this;
        }
Member Data Documentation
m_distances
std::string opendlv::proxy::PointCloudReading::m_distances { ``s } [private]
m_endAzimuth
float opendlv::proxy::PointCloudReading::m_endAzimuth { 0.0f } [private]
m_entriesPerAzimuth
uint8_t opendlv::proxy::PointCloudReading::m_entriesPerAzimuth { 0 } [private]
m_numberOfBitsForIntensity
uint8_t opendlv::proxy::PointCloudReading::m_numberOfBitsForIntensity { 0 } [private]
m_startAzimuth
float opendlv::proxy::PointCloudReading::m_startAzimuth { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::PointCloudReading::TheLongName = `opendlv.proxy.PointCloudReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PointCloudReading::TheShortName = `PointCloudReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp