cluon::GenericMessage::GenericMessageVisitor Class Reference
Public Member Functions
GenericMessageVisitor ()=default
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
MetaMessage metaMessage () const noexcept
std::unordered_map< uint32_t, linb::any, UseUInt32ValueAsHashKey > intermediateDataRepresentation () const noexcept
Private Member Functions
GenericMessageVisitor (const GenericMessageVisitor &)=delete
GenericMessageVisitor (GenericMessageVisitor &&)=delete
GenericMessageVisitor & operator= (const GenericMessageVisitor &)=delete
GenericMessageVisitor & operator= (GenericMessageVisitor &&)=delete
Private Attributes
MetaMessage m_metaMessage {}
std::unordered_map< uint32_t, linb::any, UseUInt32ValueAsHashKey > m_intermediateDataRepresentation
Constructor & Destructor Documentation
GenericMessageVisitor() [1/3]
cluon::GenericMessage::GenericMessageVisitor::GenericMessageVisitor (const GenericMessageVisitor &) [private], [delete]
GenericMessageVisitor() [2/3]
cluon::GenericMessage::GenericMessageVisitor::GenericMessageVisitor (GenericMessageVisitor &&) [private], [delete]
GenericMessageVisitor() [3/3]
cluon::GenericMessage::GenericMessageVisitor::GenericMessageVisitor () [default]
Member Function Documentation
intermediateDataRepresentation()
std::unordered_map< uint32_t, linb::any, UseUInt32ValueAsHashKey > cluon::GenericMessage::GenericMessageVisitor::intermediateDataRepresentation () const [inline], [noexcept]
Returns
Intermediate data representation for this GenericMessage.
                                                                                                                                                       {
    return m_intermediateDataRepresentation;
}
References cluon::GenericMessage::m_intermediateDataRepresentation.
Referenced by cluon::GenericMessage::createFrom().
metaMessage()
MetaMessage cluon::GenericMessage::GenericMessageVisitor::metaMessage () const [inline], [noexcept]
Returns
MetaMessage for this GenericMessage.
                                                                                   {
    return m_metaMessage;
}
References cluon::GenericMessage::m_metaMessage.
Referenced by cluon::GenericMessage::createFrom().
operator=() [1/2]
GenericMessageVisitor & cluon::GenericMessage::GenericMessageVisitor::operator= (const GenericMessageVisitor &) [private], [delete]
operator=() [2/2]
GenericMessageVisitor & cluon::GenericMessage::GenericMessageVisitor::operator= (GenericMessageVisitor &&) [private], [delete]
postVisit()
void cluon::GenericMessage::GenericMessageVisitor::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::GenericMessage::GenericMessageVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                                                    {
    (void)longName;
    m_metaMessage.messageIdentifier(id).messageName(shortName);
    if (!longName.empty()) {
        const auto pos = longName.rfind(shortName);
        if (std::string::npos != pos) {
            m_metaMessage.packageName(longName.substr(0, pos - 1));
        }
    }
}
visit() [1/14]
template<typename T >
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                            {
            cluon::MetaMessage::MetaField mf;
            mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::MESSAGE_T).fieldDataTypeName(typeName).fieldName(name);
            GenericMessage gm;
            gm.createFrom<T>(value);
            m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{gm};
            m_metaMessage.add(std::move(mf));
        }
References cluon::GenericMessage::createFrom(), cluon::MetaMessage::MetaField::MESSAGE_T, and mf.
visit() [2/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                                            {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::BOOL_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::BOOL_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [3/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                                            {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::CHAR_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::CHAR_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [4/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                                              {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::DOUBLE_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::DOUBLE_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [5/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                                             {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::FLOAT_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::FLOAT_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [6/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                                               {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::INT16_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::INT16_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [7/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                                               {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::INT32_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::INT32_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [8/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                                               {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::INT64_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::INT64_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [9/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                                              {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::INT8_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::MetaMessage::MetaField::INT8_T, cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, and mf.
visit() [10/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                                                 {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::STRING_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, mf, and cluon::MetaMessage::MetaField::STRING_T.
visit() [11/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                                                {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::UINT16_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, mf, and cluon::MetaMessage::MetaField::UINT16_T.
visit() [12/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                                                {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::UINT32_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, mf, and cluon::MetaMessage::MetaField::UINT32_T.
visit() [13/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                                                {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::UINT64_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, mf, and cluon::MetaMessage::MetaField::UINT64_T.
visit() [14/14]
void cluon::GenericMessage::GenericMessageVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                                               {
    cluon::MetaMessage::MetaField mf;
    mf.fieldIdentifier(id).fieldDataType(cluon::MetaMessage::MetaField::UINT8_T).fieldDataTypeName(typeName).fieldName(name);
    m_intermediateDataRepresentation[mf.fieldIdentifier()] = linb::any{v};
    m_metaMessage.add(std::move(mf));
}
References cluon::MetaMessage::add(), cluon::GenericMessage::m_intermediateDataRepresentation, cluon::GenericMessage::m_metaMessage, mf, and cluon::MetaMessage::MetaField::UINT8_T.
Member Data Documentation
m_intermediateDataRepresentation
std::unordered_map<uint32_t, linb::any, UseUInt32ValueAsHashKey> cluon::GenericMessage::GenericMessageVisitor::m_intermediateDataRepresentation [private]
m_metaMessage
MetaMessage cluon::GenericMessage::GenericMessageVisitor::m_metaMessage {} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp