peg::NotPredicate Class Reference
#include <cluon-complete.hpp>
Public Member Functions
NotPredicate (const std::shared_ptr< Ope > &ope)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::shared_ptr< Ope > ope_
Constructor & Destructor Documentation
NotPredicate()
peg::NotPredicate::NotPredicate (const std::shared_ptr< Ope > & ope) [inline]
: ope_(ope) {}
Member Function Documentation
accept()
void peg::NotPredicate::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::NotPredicate::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("NotPredicate", s, n, sv, dt);
        auto save_error_pos = c.error_pos;
        c.nest_level++;
        auto& chldsv = c.push();
        c.push_capture_scope();
        auto se = make_scope_exit([&]() {
            c.nest_level--;
            c.pop();
            c.pop_capture_scope();
        });
        const auto& rule = *ope_;
        auto len = rule.parse(s, n, chldsv, c, dt);
        if (success(len)) {
            c.set_error_pos(s);
            return static_cast<size_t>(-1);
        } else {
            c.error_pos = save_error_pos;
            return 0;
        }
    }
References peg::Context::error_pos, peg::make_scope_exit(), peg::Context::nest_level, peg::Context::pop(), peg::Context::pop_capture_scope(), peg::Context::push(), peg::Context::push_capture_scope(), peg::Context::set_error_pos(), peg::success(), and peg::Context::trace().
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::NotPredicate::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp