peg::Ope Class Reference
#include <cluon-complete.hpp>
Classes
struct Visitor
Public Member Functions
virtual ~Ope ()
virtual size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const =0
virtual void accept (Visitor &v)=0
Constructor & Destructor Documentation
 Ope()
virtual peg::Ope::~Ope () [inline], [virtual]
{}
Member Function Documentation
accept()
virtual void peg::Ope::accept (Visitor & v) [pure virtual]
Implemented in peg::Sequence, peg::PrioritizedChoice, peg::ZeroOrMore, peg::OneOrMore, peg::Option, peg::AndPredicate, peg::NotPredicate, peg::LiteralString, peg::CharacterClass, peg::Character, peg::AnyCharacter, peg::CaptureScope, peg::Capture, peg::TokenBoundary, peg::Ignore, peg::User, peg::WeakHolder, peg::Holder, peg::Reference, peg::Whitespace, and peg::BackReference.
Referenced by peg::IsLiteralToken::check(), peg::IsPrioritizedChoice::check(), and peg::TokenChecker::is_token().
parse()
virtual size_t peg::Ope::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [pure virtual]
Implemented in peg::Ignore, peg::Sequence, peg::PrioritizedChoice, peg::ZeroOrMore, peg::OneOrMore, peg::Option, peg::AndPredicate, peg::NotPredicate, peg::LiteralString, peg::CharacterClass, peg::Character, peg::AnyCharacter, peg::CaptureScope, peg::Capture, peg::TokenBoundary, peg::User, peg::WeakHolder, peg::Holder, peg::Reference, peg::Whitespace, and peg::BackReference.
The documentation for this class was generated from the following file:
src/cluon-complete.hpp