opendlv::logic::perception::ObjectDirection Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ObjectDirection ()=default
ObjectDirection (const ObjectDirection &)=default
ObjectDirection & operator= (const ObjectDirection &)=default
ObjectDirection (ObjectDirection &&)=default
ObjectDirection & operator= (ObjectDirection &&)=default
~ObjectDirection ()=default
ObjectDirection & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
ObjectDirection & azimuthAngle (const float &v) noexcept
float azimuthAngle () const noexcept
ObjectDirection & zenithAngle (const float &v) noexcept
float zenithAngle () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
float m_azimuthAngle { 0.0f }
float m_zenithAngle { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `ObjectDirection`
static constexpr const char * TheLongName = `opendlv.logic.perception.ObjectDirection`
Constructor & Destructor Documentation
ObjectDirection() [1/3]
opendlv::logic::perception::ObjectDirection::ObjectDirection () [default]
ObjectDirection() [2/3]
opendlv::logic::perception::ObjectDirection::ObjectDirection (const ObjectDirection &) [default]
ObjectDirection() [3/3]
opendlv::logic::perception::ObjectDirection::ObjectDirection (ObjectDirection &&) [default]
 ObjectDirection()
opendlv::logic::perception::ObjectDirection::~ObjectDirection () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::ObjectDirection::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::ObjectDirection::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::ObjectDirection::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            doVisit(2, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
            doVisit(3, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
            visitor.postVisit();
        }
References doVisit().
azimuthAngle() [1/2]
float opendlv::logic::perception::ObjectDirection::azimuthAngle () const [inline], [noexcept]
                                                   {
            return m_azimuthAngle;
        }
azimuthAngle() [2/2]
ObjectDirection & opendlv::logic::perception::ObjectDirection::azimuthAngle (const float & v) [inline], [noexcept]
                                                                      {
            m_azimuthAngle = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::perception::ObjectDirection::ID () [inline], [static]
                                   {
            return 1133;
        }
LongName()
static const std::string opendlv::logic::perception::ObjectDirection::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::ObjectDirection::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
ObjectDirection & opendlv::logic::perception::ObjectDirection::objectId (const uint32_t & v) [inline], [noexcept]
                                                                     {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
ObjectDirection & opendlv::logic::perception::ObjectDirection::operator= (const ObjectDirection &) [default]
operator=() [2/2]
ObjectDirection & opendlv::logic::perception::ObjectDirection::operator= (ObjectDirection &&) [default]
ShortName()
static const std::string opendlv::logic::perception::ObjectDirection::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
zenithAngle() [1/2]
float opendlv::logic::perception::ObjectDirection::zenithAngle () const [inline], [noexcept]
                                                  {
            return m_zenithAngle;
        }
zenithAngle() [2/2]
ObjectDirection & opendlv::logic::perception::ObjectDirection::zenithAngle (const float & v) [inline], [noexcept]
                                                                     {
            m_zenithAngle = v;
            return *this;
        }
Member Data Documentation
m_azimuthAngle
float opendlv::logic::perception::ObjectDirection::m_azimuthAngle { 0.0f } [private]
m_objectId
uint32_t opendlv::logic::perception::ObjectDirection::m_objectId { 0 } [private]
m_zenithAngle
float opendlv::logic::perception::ObjectDirection::m_zenithAngle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::perception::ObjectDirection::TheLongName = `opendlv.logic.perception.ObjectDirection` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::ObjectDirection::TheShortName = `ObjectDirection` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp