opendlv::logic::sensation::Equilibrioception Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
Equilibrioception ()=default
Equilibrioception (const Equilibrioception &)=default
Equilibrioception & operator= (const Equilibrioception &)=default
Equilibrioception (Equilibrioception &&)=default
Equilibrioception & operator= (Equilibrioception &&)=default
~Equilibrioception ()=default
Equilibrioception & vx (const float &v) noexcept
float vx () const noexcept
Equilibrioception & vy (const float &v) noexcept
float vy () const noexcept
Equilibrioception & vz (const float &v) noexcept
float vz () const noexcept
Equilibrioception & rollRate (const float &v) noexcept
float rollRate () const noexcept
Equilibrioception & pitchRate (const float &v) noexcept
float pitchRate () const noexcept
Equilibrioception & yawRate (const float &v) noexcept
float yawRate () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_vx { 0.0f }
float m_vy { 0.0f }
float m_vz { 0.0f }
float m_rollRate { 0.0f }
float m_pitchRate { 0.0f }
float m_yawRate { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `Equilibrioception`
static constexpr const char * TheLongName = `opendlv.logic.sensation.Equilibrioception`
Constructor & Destructor Documentation
Equilibrioception() [1/3]
opendlv::logic::sensation::Equilibrioception::Equilibrioception () [default]
Equilibrioception() [2/3]
opendlv::logic::sensation::Equilibrioception::Equilibrioception (const Equilibrioception &) [default]
Equilibrioception() [3/3]
opendlv::logic::sensation::Equilibrioception::Equilibrioception (Equilibrioception &&) [default]
 Equilibrioception()
opendlv::logic::sensation::Equilibrioception::~Equilibrioception () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::sensation::Equilibrioception::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("vx"s), m_vx, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("vy"s), m_vy, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("vz"s), m_vz, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("rollRate"s), m_rollRate, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("float"s), std::move("pitchRate"s), m_pitchRate, preVisit, visit, postVisit);
            doTripletForwardVisit(6, std::move("float"s), std::move("yawRate"s), m_yawRate, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::sensation::Equilibrioception::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("vx"s), m_vx, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("vy"s), m_vy, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("vz"s), m_vz, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("rollRate"s), m_rollRate, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("float"s), std::move("pitchRate"s), m_pitchRate, visitor);
                return;
            }
            if (6 == fieldId) {
                doVisit(6, std::move("float"s), std::move("yawRate"s), m_yawRate, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::sensation::Equilibrioception::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("vx"s), m_vx, visitor);
            doVisit(2, std::move("float"s), std::move("vy"s), m_vy, visitor);
            doVisit(3, std::move("float"s), std::move("vz"s), m_vz, visitor);
            doVisit(4, std::move("float"s), std::move("rollRate"s), m_rollRate, visitor);
            doVisit(5, std::move("float"s), std::move("pitchRate"s), m_pitchRate, visitor);
            doVisit(6, std::move("float"s), std::move("yawRate"s), m_yawRate, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::sensation::Equilibrioception::ID () [inline], [static]
                                   {
            return 1017;
        }
LongName()
static const std::string opendlv::logic::sensation::Equilibrioception::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::operator= (const Equilibrioception &) [default]
operator=() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::operator= (Equilibrioception &&) [default]
pitchRate() [1/2]
float opendlv::logic::sensation::Equilibrioception::pitchRate () const [inline], [noexcept]
                                                {
            return m_pitchRate;
        }
pitchRate() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::pitchRate (const float & v) [inline], [noexcept]
                                                                     {
            m_pitchRate = v;
            return *this;
        }
rollRate() [1/2]
float opendlv::logic::sensation::Equilibrioception::rollRate () const [inline], [noexcept]
                                               {
            return m_rollRate;
        }
rollRate() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::rollRate (const float & v) [inline], [noexcept]
                                                                    {
            m_rollRate = v;
            return *this;
        }
ShortName()
static const std::string opendlv::logic::sensation::Equilibrioception::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
vx() [1/2]
float opendlv::logic::sensation::Equilibrioception::vx () const [inline], [noexcept]
                                         {
            return m_vx;
        }
vx() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::vx (const float & v) [inline], [noexcept]
                                                              {
            m_vx = v;
            return *this;
        }
vy() [1/2]
float opendlv::logic::sensation::Equilibrioception::vy () const [inline], [noexcept]
                                         {
            return m_vy;
        }
vy() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::vy (const float & v) [inline], [noexcept]
                                                              {
            m_vy = v;
            return *this;
        }
vz() [1/2]
float opendlv::logic::sensation::Equilibrioception::vz () const [inline], [noexcept]
                                         {
            return m_vz;
        }
vz() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::vz (const float & v) [inline], [noexcept]
                                                              {
            m_vz = v;
            return *this;
        }
yawRate() [1/2]
float opendlv::logic::sensation::Equilibrioception::yawRate () const [inline], [noexcept]
                                              {
            return m_yawRate;
        }
yawRate() [2/2]
Equilibrioception & opendlv::logic::sensation::Equilibrioception::yawRate (const float & v) [inline], [noexcept]
                                                                   {
            m_yawRate = v;
            return *this;
        }
Member Data Documentation
m_pitchRate
float opendlv::logic::sensation::Equilibrioception::m_pitchRate { 0.0f } [private]
m_rollRate
float opendlv::logic::sensation::Equilibrioception::m_rollRate { 0.0f } [private]
m_vx
float opendlv::logic::sensation::Equilibrioception::m_vx { 0.0f } [private]
m_vy
float opendlv::logic::sensation::Equilibrioception::m_vy { 0.0f } [private]
m_vz
float opendlv::logic::sensation::Equilibrioception::m_vz { 0.0f } [private]
m_yawRate
float opendlv::logic::sensation::Equilibrioception::m_yawRate { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::sensation::Equilibrioception::TheLongName = `opendlv.logic.sensation.Equilibrioception` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::sensation::Equilibrioception::TheShortName = `Equilibrioception` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp