opendlv::logic::cognition::GroundSpeedLimit Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSpeedLimit ()=default
GroundSpeedLimit (const GroundSpeedLimit &)=default
GroundSpeedLimit & operator= (const GroundSpeedLimit &)=default
GroundSpeedLimit (GroundSpeedLimit &&)=default
GroundSpeedLimit & operator= (GroundSpeedLimit &&)=default
~GroundSpeedLimit ()=default
GroundSpeedLimit & speedLimit (const float &v) noexcept
float speedLimit () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_speedLimit { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSpeedLimit`
static constexpr const char * TheLongName = `opendlv.logic.cognition.GroundSpeedLimit`
Constructor & Destructor Documentation
GroundSpeedLimit() [1/3]
opendlv::logic::cognition::GroundSpeedLimit::GroundSpeedLimit () [default]
GroundSpeedLimit() [2/3]
opendlv::logic::cognition::GroundSpeedLimit::GroundSpeedLimit (const GroundSpeedLimit &) [default]
GroundSpeedLimit() [3/3]
opendlv::logic::cognition::GroundSpeedLimit::GroundSpeedLimit (GroundSpeedLimit &&) [default]
 GroundSpeedLimit()
opendlv::logic::cognition::GroundSpeedLimit::~GroundSpeedLimit () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::cognition::GroundSpeedLimit::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("speedLimit"s), m_speedLimit, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::cognition::GroundSpeedLimit::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("speedLimit"s), m_speedLimit, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::cognition::GroundSpeedLimit::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("speedLimit"s), m_speedLimit, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::cognition::GroundSpeedLimit::ID () [inline], [static]
                                   {
            return 1192;
        }
LongName()
static const std::string opendlv::logic::cognition::GroundSpeedLimit::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSpeedLimit & opendlv::logic::cognition::GroundSpeedLimit::operator= (const GroundSpeedLimit &) [default]
operator=() [2/2]
GroundSpeedLimit & opendlv::logic::cognition::GroundSpeedLimit::operator= (GroundSpeedLimit &&) [default]
ShortName()
static const std::string opendlv::logic::cognition::GroundSpeedLimit::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
speedLimit() [1/2]
float opendlv::logic::cognition::GroundSpeedLimit::speedLimit () const [inline], [noexcept]
                                                 {
            return m_speedLimit;
        }
speedLimit() [2/2]
GroundSpeedLimit & opendlv::logic::cognition::GroundSpeedLimit::speedLimit (const float & v) [inline], [noexcept]
                                                                     {
            m_speedLimit = v;
            return *this;
        }
Member Data Documentation
m_speedLimit
float opendlv::logic::cognition::GroundSpeedLimit::m_speedLimit { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::cognition::GroundSpeedLimit::TheLongName = `opendlv.logic.cognition.GroundSpeedLimit` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::cognition::GroundSpeedLimit::TheShortName = `GroundSpeedLimit` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp