opendlv::body::ActuatorInfo Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ActuatorInfo ()=default
ActuatorInfo (const ActuatorInfo &)=default
ActuatorInfo & operator= (const ActuatorInfo &)=default
ActuatorInfo (ActuatorInfo &&)=default
ActuatorInfo & operator= (ActuatorInfo &&)=default
~ActuatorInfo ()=default
ActuatorInfo & description (const std::string &v) noexcept
std::string description () const noexcept
ActuatorInfo & x (const float &v) noexcept
float x () const noexcept
ActuatorInfo & y (const float &v) noexcept
float y () const noexcept
ActuatorInfo & z (const float &v) noexcept
float z () const noexcept
ActuatorInfo & signalId (const uint32_t &v) noexcept
uint32_t signalId () const noexcept
ActuatorInfo & minValue (const float &v) noexcept
float minValue () const noexcept
ActuatorInfo & maxValue (const float &v) noexcept
float maxValue () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_description { ``s }
float m_x { 0.0f }
float m_y { 0.0f }
float m_z { 0.0f }
uint32_t m_signalId { 0 }
float m_minValue { 0.0f }
float m_maxValue { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `ActuatorInfo`
static constexpr const char * TheLongName = `opendlv.body.ActuatorInfo`
Constructor & Destructor Documentation
ActuatorInfo() [1/3]
opendlv::body::ActuatorInfo::ActuatorInfo () [default]
ActuatorInfo() [2/3]
opendlv::body::ActuatorInfo::ActuatorInfo (const ActuatorInfo &) [default]
ActuatorInfo() [3/3]
opendlv::body::ActuatorInfo::ActuatorInfo (ActuatorInfo &&) [default]
 ActuatorInfo()
opendlv::body::ActuatorInfo::~ActuatorInfo () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::body::ActuatorInfo::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("x"s), m_x, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("y"s), m_y, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("z"s), m_z, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, preVisit, visit, postVisit);
            doTripletForwardVisit(6, std::move("float"s), std::move("minValue"s), m_minValue, preVisit, visit, postVisit);
            doTripletForwardVisit(7, std::move("float"s), std::move("maxValue"s), m_maxValue, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::body::ActuatorInfo::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
                return;
            }
            if (6 == fieldId) {
                doVisit(6, std::move("float"s), std::move("minValue"s), m_minValue, visitor);
                return;
            }
            if (7 == fieldId) {
                doVisit(7, std::move("float"s), std::move("maxValue"s), m_maxValue, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::body::ActuatorInfo::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
            doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
            doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
            doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
            doVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
            doVisit(6, std::move("float"s), std::move("minValue"s), m_minValue, visitor);
            doVisit(7, std::move("float"s), std::move("maxValue"s), m_maxValue, visitor);
            visitor.postVisit();
        }
References doVisit().
description() [1/2]
std::string opendlv::body::ActuatorInfo::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::description (const std::string & v) [inline], [noexcept]
                                                                      {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::body::ActuatorInfo::ID () [inline], [static]
                                   {
            return 1022;
        }
LongName()
static const std::string opendlv::body::ActuatorInfo::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
maxValue() [1/2]
float opendlv::body::ActuatorInfo::maxValue () const [inline], [noexcept]
                                               {
            return m_maxValue;
        }
maxValue() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::maxValue (const float & v) [inline], [noexcept]
                                                               {
            m_maxValue = v;
            return *this;
        }
minValue() [1/2]
float opendlv::body::ActuatorInfo::minValue () const [inline], [noexcept]
                                               {
            return m_minValue;
        }
minValue() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::minValue (const float & v) [inline], [noexcept]
                                                               {
            m_minValue = v;
            return *this;
        }
operator=() [1/2]
ActuatorInfo & opendlv::body::ActuatorInfo::operator= (ActuatorInfo &&) [default]
operator=() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::operator= (const ActuatorInfo &) [default]
ShortName()
static const std::string opendlv::body::ActuatorInfo::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
signalId() [1/2]
uint32_t opendlv::body::ActuatorInfo::signalId () const [inline], [noexcept]
                                                  {
            return m_signalId;
        }
signalId() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::signalId (const uint32_t & v) [inline], [noexcept]
                                                                  {
            m_signalId = v;
            return *this;
        }
x() [1/2]
float opendlv::body::ActuatorInfo::x () const [inline], [noexcept]
                                        {
            return m_x;
        }
x() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::x (const float & v) [inline], [noexcept]
                                                        {
            m_x = v;
            return *this;
        }
y() [1/2]
float opendlv::body::ActuatorInfo::y () const [inline], [noexcept]
                                        {
            return m_y;
        }
y() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::y (const float & v) [inline], [noexcept]
                                                        {
            m_y = v;
            return *this;
        }
z() [1/2]
float opendlv::body::ActuatorInfo::z () const [inline], [noexcept]
                                        {
            return m_z;
        }
z() [2/2]
ActuatorInfo & opendlv::body::ActuatorInfo::z (const float & v) [inline], [noexcept]
                                                        {
            m_z = v;
            return *this;
        }
Member Data Documentation
m_description
std::string opendlv::body::ActuatorInfo::m_description { ``s } [private]
m_maxValue
float opendlv::body::ActuatorInfo::m_maxValue { 0.0f } [private]
m_minValue
float opendlv::body::ActuatorInfo::m_minValue { 0.0f } [private]
m_signalId
uint32_t opendlv::body::ActuatorInfo::m_signalId { 0 } [private]
m_x
float opendlv::body::ActuatorInfo::m_x { 0.0f } [private]
m_y
float opendlv::body::ActuatorInfo::m_y { 0.0f } [private]
m_z
float opendlv::body::ActuatorInfo::m_z { 0.0f } [private]
TheLongName
constexpr const char* opendlv::body::ActuatorInfo::TheLongName = `opendlv.body.ActuatorInfo` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::body::ActuatorInfo::TheShortName = `ActuatorInfo` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp