opendlv::logic::sensation::Geolocation Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
Geolocation ()=default
Geolocation (const Geolocation &)=default
Geolocation & operator= (const Geolocation &)=default
Geolocation (Geolocation &&)=default
Geolocation & operator= (Geolocation &&)=default
~Geolocation ()=default
Geolocation & latitude (const double &v) noexcept
double latitude () const noexcept
Geolocation & longitude (const double &v) noexcept
double longitude () const noexcept
Geolocation & altitude (const float &v) noexcept
float altitude () const noexcept
Geolocation & heading (const float &v) noexcept
float heading () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
double m_latitude { 0.0 }
double m_longitude { 0.0 }
float m_altitude { 0.0f }
float m_heading { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `Geolocation`
static constexpr const char * TheLongName = `opendlv.logic.sensation.Geolocation`
Constructor & Destructor Documentation
Geolocation() [1/3]
opendlv::logic::sensation::Geolocation::Geolocation () [default]
Geolocation() [2/3]
opendlv::logic::sensation::Geolocation::Geolocation (const Geolocation &) [default]
Geolocation() [3/3]
opendlv::logic::sensation::Geolocation::Geolocation (Geolocation &&) [default]
 Geolocation()
opendlv::logic::sensation::Geolocation::~Geolocation () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::sensation::Geolocation::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("double"s), std::move("longitude"s), m_longitude, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("altitude"s), m_altitude, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("heading"s), m_heading, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::sensation::Geolocation::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("double"s), std::move("longitude"s), m_longitude, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("altitude"s), m_altitude, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("heading"s), m_heading, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::sensation::Geolocation::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, visitor);
            doVisit(2, std::move("double"s), std::move("longitude"s), m_longitude, visitor);
            doVisit(3, std::move("float"s), std::move("altitude"s), m_altitude, visitor);
            doVisit(4, std::move("float"s), std::move("heading"s), m_heading, visitor);
            visitor.postVisit();
        }
References doVisit().
altitude() [1/2]
float opendlv::logic::sensation::Geolocation::altitude () const [inline], [noexcept]
                                               {
            return m_altitude;
        }
altitude() [2/2]
Geolocation & opendlv::logic::sensation::Geolocation::altitude (const float & v) [inline], [noexcept]
                                                              {
            m_altitude = v;
            return *this;
        }
heading() [1/2]
float opendlv::logic::sensation::Geolocation::heading () const [inline], [noexcept]
                                              {
            return m_heading;
        }
heading() [2/2]
Geolocation & opendlv::logic::sensation::Geolocation::heading (const float & v) [inline], [noexcept]
                                                             {
            m_heading = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::sensation::Geolocation::ID () [inline], [static]
                                   {
            return 1116;
        }
latitude() [1/2]
double opendlv::logic::sensation::Geolocation::latitude () const [inline], [noexcept]
                                                {
            return m_latitude;
        }
latitude() [2/2]
Geolocation & opendlv::logic::sensation::Geolocation::latitude (const double & v) [inline], [noexcept]
                                                               {
            m_latitude = v;
            return *this;
        }
longitude() [1/2]
double opendlv::logic::sensation::Geolocation::longitude () const [inline], [noexcept]
                                                 {
            return m_longitude;
        }
longitude() [2/2]
Geolocation & opendlv::logic::sensation::Geolocation::longitude (const double & v) [inline], [noexcept]
                                                                {
            m_longitude = v;
            return *this;
        }
LongName()
static const std::string opendlv::logic::sensation::Geolocation::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
Geolocation & opendlv::logic::sensation::Geolocation::operator= (const Geolocation &) [default]
operator=() [2/2]
Geolocation & opendlv::logic::sensation::Geolocation::operator= (Geolocation &&) [default]
ShortName()
static const std::string opendlv::logic::sensation::Geolocation::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_altitude
float opendlv::logic::sensation::Geolocation::m_altitude { 0.0f } [private]
m_heading
float opendlv::logic::sensation::Geolocation::m_heading { 0.0f } [private]
m_latitude
double opendlv::logic::sensation::Geolocation::m_latitude { 0.0 } [private]
m_longitude
double opendlv::logic::sensation::Geolocation::m_longitude { 0.0 } [private]
TheLongName
constexpr const char* opendlv::logic::sensation::Geolocation::TheLongName = `opendlv.logic.sensation.Geolocation` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::sensation::Geolocation::TheShortName = `Geolocation` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp