opendlv::logic::perception::ObjectProperty Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ObjectProperty ()=default
ObjectProperty (const ObjectProperty &)=default
ObjectProperty & operator= (const ObjectProperty &)=default
ObjectProperty (ObjectProperty &&)=default
ObjectProperty & operator= (ObjectProperty &&)=default
~ObjectProperty ()=default
ObjectProperty & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
ObjectProperty & property (const std::string &v) noexcept
std::string property () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
std::string m_property { ``s }
Static Private Attributes
static constexpr const char * TheShortName = `ObjectProperty`
static constexpr const char * TheLongName = `opendlv.logic.perception.ObjectProperty`
Constructor & Destructor Documentation
ObjectProperty() [1/3]
opendlv::logic::perception::ObjectProperty::ObjectProperty () [default]
ObjectProperty() [2/3]
opendlv::logic::perception::ObjectProperty::ObjectProperty (const ObjectProperty &) [default]
ObjectProperty() [3/3]
opendlv::logic::perception::ObjectProperty::ObjectProperty (ObjectProperty &&) [default]
 ObjectProperty()
opendlv::logic::perception::ObjectProperty::~ObjectProperty () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::ObjectProperty::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("std::string"s), std::move("property"s), m_property, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::ObjectProperty::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("std::string"s), std::move("property"s), m_property, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::ObjectProperty::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            doVisit(2, std::move("std::string"s), std::move("property"s), m_property, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::ObjectProperty::ID () [inline], [static]
                                   {
            return 1132;
        }
LongName()
static const std::string opendlv::logic::perception::ObjectProperty::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::ObjectProperty::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
ObjectProperty & opendlv::logic::perception::ObjectProperty::objectId (const uint32_t & v) [inline], [noexcept]
                                                                    {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
ObjectProperty & opendlv::logic::perception::ObjectProperty::operator= (const ObjectProperty &) [default]
operator=() [2/2]
ObjectProperty & opendlv::logic::perception::ObjectProperty::operator= (ObjectProperty &&) [default]
property() [1/2]
std::string opendlv::logic::perception::ObjectProperty::property () const [inline], [noexcept]
                                                   {
            return m_property;
        }
property() [2/2]
ObjectProperty & opendlv::logic::perception::ObjectProperty::property (const std::string & v) [inline], [noexcept]
                                                                     {
            m_property = v;
            return *this;
        }
ShortName()
static const std::string opendlv::logic::perception::ObjectProperty::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_objectId
uint32_t opendlv::logic::perception::ObjectProperty::m_objectId { 0 } [private]
m_property
std::string opendlv::logic::perception::ObjectProperty::m_property { ``s } [private]
TheLongName
constexpr const char* opendlv::logic::perception::ObjectProperty::TheLongName = `opendlv.logic.perception.ObjectProperty` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::ObjectProperty::TheShortName = `ObjectProperty` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp