opendlv::proxy::DistanceReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
DistanceReading ()=default
DistanceReading (const DistanceReading &)=default
DistanceReading & operator= (const DistanceReading &)=default
DistanceReading (DistanceReading &&)=default
DistanceReading & operator= (DistanceReading &&)=default
~DistanceReading ()=default
DistanceReading & distance (const float &v) noexcept
float distance () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_distance { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `DistanceReading`
static constexpr const char * TheLongName = `opendlv.proxy.DistanceReading`
Constructor & Destructor Documentation
DistanceReading() [1/3]
opendlv::proxy::DistanceReading::DistanceReading () [default]
DistanceReading() [2/3]
opendlv::proxy::DistanceReading::DistanceReading (const DistanceReading &) [default]
DistanceReading() [3/3]
opendlv::proxy::DistanceReading::DistanceReading (DistanceReading &&) [default]
 DistanceReading()
opendlv::proxy::DistanceReading::~DistanceReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::DistanceReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("distance"s), m_distance, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::DistanceReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("distance"s), m_distance, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::DistanceReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("distance"s), m_distance, visitor);
            visitor.postVisit();
        }
References doVisit().
distance() [1/2]
float opendlv::proxy::DistanceReading::distance () const [inline], [noexcept]
                                               {
            return m_distance;
        }
distance() [2/2]
DistanceReading & opendlv::proxy::DistanceReading::distance (const float & v) [inline], [noexcept]
                                                                  {
            m_distance = v;
            return *this;
        }
Referenced by main().
ID()
static int32_t opendlv::proxy::DistanceReading::ID () [inline], [static]
                                   {
            return 1039;
        }
Referenced by main().
LongName()
static const std::string opendlv::proxy::DistanceReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
DistanceReading & opendlv::proxy::DistanceReading::operator= (const DistanceReading &) [default]
operator=() [2/2]
DistanceReading & opendlv::proxy::DistanceReading::operator= (DistanceReading &&) [default]
ShortName()
static const std::string opendlv::proxy::DistanceReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_distance
float opendlv::proxy::DistanceReading::m_distance { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::DistanceReading::TheLongName = `opendlv.proxy.DistanceReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::DistanceReading::TheShortName = `DistanceReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp