peg::Ignore Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Ignore (const std::shared_ptr< Ope > &ope)
size_t parse (const char *s, size_t n, SemanticValues &, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::shared_ptr< Ope > ope_
Constructor & Destructor Documentation
Ignore()
peg::Ignore::Ignore (const std::shared_ptr< Ope > & ope) [inline]
: ope_(ope) {}
Member Function Documentation
accept()
void peg::Ignore::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::Ignore::parse (const char * s, size_t n, SemanticValues & , Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                 {
        const auto& rule = *ope_;
        auto& chldsv = c.push();
        auto se = make_scope_exit([&]() {
            c.pop();
        });
        return rule.parse(s, n, chldsv, c, dt);
    }
References peg::make_scope_exit(), peg::Context::pop(), and peg::Context::push().
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::Ignore::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::TokenChecker::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp