opendlv::proxy::GroundDecelerationRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundDecelerationRequest ()=default
GroundDecelerationRequest (const GroundDecelerationRequest &)=default
GroundDecelerationRequest & operator= (const GroundDecelerationRequest &)=default
GroundDecelerationRequest (GroundDecelerationRequest &&)=default
GroundDecelerationRequest & operator= (GroundDecelerationRequest &&)=default
~GroundDecelerationRequest ()=default
GroundDecelerationRequest & groundDeceleration (const float &v) noexcept
float groundDeceleration () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundDeceleration { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundDecelerationRequest`
static constexpr const char * TheLongName = `opendlv.proxy.GroundDecelerationRequest`
Constructor & Destructor Documentation
GroundDecelerationRequest() [1/3]
opendlv::proxy::GroundDecelerationRequest::GroundDecelerationRequest () [default]
GroundDecelerationRequest() [2/3]
opendlv::proxy::GroundDecelerationRequest::GroundDecelerationRequest (const GroundDecelerationRequest &) [default]
GroundDecelerationRequest() [3/3]
opendlv::proxy::GroundDecelerationRequest::GroundDecelerationRequest (GroundDecelerationRequest &&) [default]
 GroundDecelerationRequest()
opendlv::proxy::GroundDecelerationRequest::~GroundDecelerationRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundDecelerationRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundDeceleration"s), m_groundDeceleration, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundDecelerationRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundDeceleration"s), m_groundDeceleration, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundDecelerationRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundDeceleration"s), m_groundDeceleration, visitor);
            visitor.postVisit();
        }
References doVisit().
groundDeceleration() [1/2]
float opendlv::proxy::GroundDecelerationRequest::groundDeceleration () const [inline], [noexcept]
                                                         {
            return m_groundDeceleration;
        }
groundDeceleration() [2/2]
GroundDecelerationRequest & opendlv::proxy::GroundDecelerationRequest::groundDeceleration (const float & v) [inline], [noexcept]
                                                                                      {
            m_groundDeceleration = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::GroundDecelerationRequest::ID () [inline], [static]
                                   {
            return 1093;
        }
LongName()
static const std::string opendlv::proxy::GroundDecelerationRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundDecelerationRequest & opendlv::proxy::GroundDecelerationRequest::operator= (const GroundDecelerationRequest &) [default]
operator=() [2/2]
GroundDecelerationRequest & opendlv::proxy::GroundDecelerationRequest::operator= (GroundDecelerationRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundDecelerationRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundDeceleration
float opendlv::proxy::GroundDecelerationRequest::m_groundDeceleration { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundDecelerationRequest::TheLongName = `opendlv.proxy.GroundDecelerationRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundDecelerationRequest::TheShortName = `GroundDecelerationRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp