peg::Context Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Context (const char *a_path, const char *a_s, size_t a_l, size_t a_def_count, std::shared_ptr< Ope > a_whitespaceOpe, std::shared_ptr< Ope > a_wordOpe, bool a_enablePackratParsing, Tracer a_tracer)
template<typename T >
void packrat (const char *a_s, size_t def_id, size_t &len, any &val, T fn)
SemanticValues & push ()
void pop ()
void push_args (const std::vector< std::shared_ptr< Ope > > &args)
void pop_args ()
const std::vector< std::shared_ptr< Ope > > & top_args () const
void push_capture_scope ()
void pop_capture_scope ()
void shift_capture_values ()
void set_error_pos (const char *a_s)
void trace (const char *name, const char *a_s, size_t n, SemanticValues &sv, any &dt) const
Public Attributes
const char * path
const char * s
const size_t l
const char * error_pos
const char * message_pos
std::string message
std::vector< std::shared_ptr< SemanticValues > > value_stack
size_t value_stack_size
std::vector< std::vector< std::shared_ptr< Ope > > > args_stack
size_t nest_level
bool in_token
std::shared_ptr< Ope > whitespaceOpe
bool in_whitespace
std::shared_ptr< Ope > wordOpe
std::vector< std::unordered_map< std::string, std::string > > capture_scope_stack
const size_t def_count
const bool enablePackratParsing
std::vector< bool > cache_registered
std::vector< bool > cache_success
std::map< std::pair< size_t, size_t >, std::tuple< size_t, any > > cache_values
std::function< void(const char *, const char *, size_t, const SemanticValues &, const Context &, const any &)> tracer
Constructor & Destructor Documentation
Context()
peg::Context::Context (const char * a_path, const char * a_s, size_t a_l, size_t a_def_count, std::shared_ptr< Ope > a_whitespaceOpe, std::shared_ptr< Ope > a_wordOpe, bool a_enablePackratParsing, Tracer a_tracer) [inline]
        : path(a_path)
        , s(a_s)
        , l(a_l)
        , error_pos(nullptr)
        , message_pos(nullptr)
        , value_stack_size(0)
        , nest_level(0)
        , in_token(false)
        , whitespaceOpe(a_whitespaceOpe)
        , in_whitespace(false)
        , wordOpe(a_wordOpe)
        , def_count(a_def_count)
        , enablePackratParsing(a_enablePackratParsing)
        , cache_registered(enablePackratParsing ? def_count * (l + 1) : 0)
        , cache_success(enablePackratParsing ? def_count * (l + 1) : 0)
        , tracer(a_tracer)
    {
        args_stack.resize(1);
        capture_scope_stack.resize(1);
    }
Member Function Documentation
packrat()
template<typename T >
void peg::Context::packrat (const char * a_s, size_t def_id, size_t & len, any & val, T fn) [inline]
                                                                              {
        if (!enablePackratParsing) {
            fn(val);
            return;
        }
        auto col = a_s - s;
        auto idx = def_count * static_cast<size_t>(col) + def_id;
        if (cache_registered[idx]) {
            if (cache_success[idx]) {
                auto key = std::make_pair(col, def_id);
                std::tie(len, val) = cache_values[key];
                return;
            } else {
                len = static_cast<size_t>(-1);
                return;
            }
        } else {
            fn(val);
            cache_registered[idx] = true;
            cache_success[idx] = success(len);
            if (success(len)) {
                auto key = std::make_pair(col, def_id);
                cache_values[key] = std::make_pair(len, val);
            }
            return;
        }
    }
References peg::success().
Referenced by peg::Holder::parse().
pop()
void peg::Context::pop () [inline]
               {
        value_stack_size--;
    }
Referenced by peg::Ignore::parse(), peg::PrioritizedChoice::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), and peg::Holder::parse().
pop_args()
void peg::Context::pop_args () [inline]
                    {
        args_stack.pop_back();
    }
Referenced by peg::Reference::parse().
pop_capture_scope()
void peg::Context::pop_capture_scope () [inline]
                             {
        capture_scope_stack.pop_back();
    }
Referenced by peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), and peg::CaptureScope::parse().
push()
SemanticValues & peg::Context::push () [inline]
                           {
        assert(value_stack_size <= value_stack.size());
        if (value_stack_size == value_stack.size()) {
            value_stack.emplace_back(std::make_shared<SemanticValues>());
        }
        auto& sv = *value_stack[value_stack_size++];
        if (!sv.empty()) {
            sv.clear();
            sv.tags.clear();
        }
        sv.reset();
        sv.path = path;
        sv.ss = s;
        return sv;
    }
Referenced by peg::Ignore::parse(), peg::Sequence::parse(), peg::PrioritizedChoice::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), and peg::Holder::parse().
push_args()
void peg::Context::push_args (const std::vector< std::shared_ptr< Ope > > & args) [inline]
                                                              {
        args_stack.push_back(args);
    }
Referenced by peg::Reference::parse().
push_capture_scope()
void peg::Context::push_capture_scope () [inline]
                              {
        capture_scope_stack.resize(capture_scope_stack.size() + 1);
    }
Referenced by peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), and peg::CaptureScope::parse().
set_error_pos()
void peg::Context::set_error_pos (const char * a_s) [inline]
                                        {
        if (error_pos < a_s) error_pos = a_s;
    }
Referenced by peg::NotPredicate::parse(), peg::CharacterClass::parse(), peg::Character::parse(), peg::AnyCharacter::parse(), and peg::parse_literal().
shift_capture_values()
void peg::Context::shift_capture_values () [inline]
                                {
        assert(capture_scope_stack.size() >= 2);
        auto it = capture_scope_stack.rbegin();
        auto it_prev = it + 1;
        for (const auto& kv: *it) {
            (*it_prev)[kv.first] = kv.second;
        }
    }
Referenced by peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), and peg::Option::parse().
top_args()
const std::vector< std::shared_ptr< Ope > > & peg::Context::top_args () const [inline]
                                                          {
        return args_stack[args_stack.size() - 1];
    }
Referenced by peg::Reference::parse().
trace()
void peg::Context::trace (const char * name, const char * a_s, size_t n, SemanticValues & sv, any & dt) const [inline]
                                                                                               {
        if (tracer) tracer(name, a_s, n, sv, *this, dt);
    }
Referenced by peg::Sequence::parse(), peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), peg::LiteralString::parse(), peg::CharacterClass::parse(), peg::Character::parse(), peg::AnyCharacter::parse(), peg::User::parse(), peg::Holder::parse(), and peg::BackReference::parse().
Member Data Documentation
args_stack
std::vector<std::vector<std::shared_ptr<Ope> > > peg::Context::args_stack
cache_registered
std::vector<bool> peg::Context::cache_registered
cache_success
std::vector<bool> peg::Context::cache_success
cache_values
std::map<std::pair<size_t, size_t>, std::tuple<size_t, any> > peg::Context::cache_values
capture_scope_stack
std::vector<std::unordered_map<std::string, std::string> > peg::Context::capture_scope_stack
Referenced by peg::BackReference::parse(), and peg::ParserGenerator::setup_actions().
def_count
const size_t peg::Context::def_count
enablePackratParsing
const bool peg::Context::enablePackratParsing
error_pos
const char* peg::Context::error_pos
Referenced by peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::NotPredicate::parse(), and peg::Definition::parse_core().
in_token
bool peg::Context::in_token
Referenced by peg::TokenBoundary::parse(), and peg::parse_literal().
in_whitespace
bool peg::Context::in_whitespace
Referenced by peg::Whitespace::parse().
l
const size_t peg::Context::l
Referenced by peg::parse_literal().
message
std::string peg::Context::message
Referenced by peg::Holder::parse(), and peg::Definition::parse_core().
message_pos
const char* peg::Context::message_pos
Referenced by peg::Holder::parse(), and peg::Definition::parse_core().
nest_level
size_t peg::Context::nest_level
Referenced by peg::Sequence::parse(), peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), and peg::Holder::parse().
path
const char* peg::Context::path
s
const char* peg::Context::s
Referenced by peg::parse_literal().
tracer
std::function<void (const char*, const char*, size_t, const SemanticValues&, const Context&, const any&)> peg::Context::tracer
value_stack
std::vector<std::shared_ptr<SemanticValues> > peg::Context::value_stack
value_stack_size
size_t peg::Context::value_stack_size
whitespaceOpe
std::shared_ptr<Ope> peg::Context::whitespaceOpe
Referenced by peg::TokenBoundary::parse(), and peg::parse_literal().
wordOpe
std::shared_ptr<Ope> peg::Context::wordOpe
Referenced by peg::parse_literal().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp