peg::AnyCharacter Class Reference
#include <cluon-complete.hpp>
Public Member Functions
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Member Function Documentation
accept()
void peg::AnyCharacter::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::AnyCharacter::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("AnyCharacter", s, n, sv, dt);
        auto len = codepoint_length(s, n);
        if (len < 1) {
            c.set_error_pos(s);
            return static_cast<size_t>(-1);
        }
        return len;
    }
References peg::codepoint_length(), peg::Context::set_error_pos(), and peg::Context::trace().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp