peg::PrioritizedChoice Class Reference
#include <cluon-complete.hpp>
Public Member Functions
template<typename... Args>
PrioritizedChoice (const Args &...args)
PrioritizedChoice (const std::vector< std::shared_ptr< Ope > > &opes)
PrioritizedChoice (std::vector< std::shared_ptr< Ope > > &&opes)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
size_t size () const
Public Attributes
std::vector< std::shared_ptr< Ope > > opes_
Constructor & Destructor Documentation
PrioritizedChoice() [1/3]
template<typename... Args>
peg::PrioritizedChoice::PrioritizedChoice (const Args &... args) [inline]
: opes_{ static_cast<std::shared_ptr<Ope>>(args)... } {}
PrioritizedChoice() [2/3]
peg::PrioritizedChoice::PrioritizedChoice (const std::vector< std::shared_ptr< Ope > > & opes) [inline]
: opes_(opes) {}
PrioritizedChoice() [3/3]
peg::PrioritizedChoice::PrioritizedChoice (std::vector< std::shared_ptr< Ope > > && opes) [inline]
: opes_(opes) {}
Member Function Documentation
accept()
void peg::PrioritizedChoice::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::PrioritizedChoice::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("PrioritizedChoice", s, n, sv, dt);
        size_t id = 0;
        for (const auto& ope : opes_) {
            c.nest_level++;
            auto& chldsv = c.push();
            c.push_capture_scope();
            auto se = make_scope_exit([&]() {
                c.nest_level--;
                c.pop();
                c.pop_capture_scope();
            });
            const auto& rule = *ope;
            auto len = rule.parse(s, n, chldsv, c, dt);
            if (success(len)) {
                sv.insert(sv.end(), chldsv.begin(), chldsv.end());
                sv.tags.insert(sv.tags.end(), chldsv.tags.begin(), chldsv.tags.end());
                sv.s_ = chldsv.c_str();
                sv.n_ = chldsv.length();
                sv.choice_count_ = opes_.size();
                sv.choice_ = id;
                sv.tokens.insert(sv.tokens.end(), chldsv.tokens.begin(), chldsv.tokens.end());
                c.shift_capture_values();
                return len;
            }
            id++;
        }
        return static_cast<size_t>(-1);
    }
References peg::SemanticValues::choice_, peg::SemanticValues::choice_count_, peg::make_scope_exit(), peg::SemanticValues::n_, peg::Context::nest_level, peg::Context::pop(), peg::Context::pop_capture_scope(), peg::Context::push(), peg::Context::push_capture_scope(), peg::SemanticValues::s_, peg::Context::shift_capture_values(), peg::success(), peg::SemanticValues::tags, peg::SemanticValues::tokens, and peg::Context::trace().
size()
size_t peg::PrioritizedChoice::size () const [inline]
{ return opes_.size(); }
Member Data Documentation
opes_
std::vector<std::shared_ptr<Ope> > peg::PrioritizedChoice::opes_
Referenced by peg::AssignIDToDefinition::visit(), peg::IsLiteralToken::visit(), peg::TokenChecker::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp