argh::parser Class Reference
#include <cluon-complete.hpp>
Public Types
enum Mode { PREFER_FLAG_FOR_UNREG_OPTION = 1 << 0
, PREFER_PARAM_FOR_UNREG_OPTION = 1 << 1
, NO_SPLIT_ON_EQUALSIGN = 1 << 2
, SINGLE_DASH_IS_MULTIFLAG = 1 << 3
 }
Public Member Functions
parser ()=default
parser (std::initializer_list< char const *const > pre_reg_names)
parser (const char *const argv[], int mode=PREFER_FLAG_FOR_UNREG_OPTION)
parser (int argc, const char *const argv[], int mode=PREFER_FLAG_FOR_UNREG_OPTION)
void add_param (std::string const &name)
void add_params (std::initializer_list< char const *const > init_list)
void parse (const char *const argv[], int mode=PREFER_FLAG_FOR_UNREG_OPTION)
void parse (int argc, const char *const argv[], int mode=PREFER_FLAG_FOR_UNREG_OPTION)
std::multiset< std::string > const & flags () const
std::map< std::string, std::string > const & params () const
std::vector< std::string > const & pos_args () const
std::vector< std::string >::const_iterator begin () const
std::vector< std::string >::const_iterator end () const
size_t size () const
bool operator[] (std::string const &name) const
bool operator[] (std::initializer_list< char const *const > init_list) const
std::string const & operator[] (size_t ind) const
string_stream operator() (size_t ind) const
template<typename T >
string_stream operator() (size_t ind, T &&def_val) const
string_stream operator() (std::string const &name) const
string_stream operator() (std::initializer_list< char const *const > init_list) const
template<typename T >
string_stream operator() (std::string const &name, T &&def_val) const
template<typename T >
string_stream operator() (std::initializer_list< char const *const > init_list, T &&def_val) const
Private Member Functions
string_stream bad_stream () const
std::string trim_leading_dashes (std::string const &name) const
bool is_number (std::string const &arg) const
bool is_option (std::string const &arg) const
bool got_flag (std::string const &name) const
bool is_param (std::string const &name) const
Private Attributes
std::vector< std::string > args_
std::map< std::string, std::string > params_
std::vector< std::string > pos_args_
std::multiset< std::string > flags_
std::set< std::string > registeredParams_
std::string empty_
Member Enumeration Documentation
Mode
enum argh::parser::Mode
Enumerator
PREFER_FLAG_FOR_UNREG_OPTION
PREFER_PARAM_FOR_UNREG_OPTION
NO_SPLIT_ON_EQUALSIGN
SINGLE_DASH_IS_MULTIFLAG
                { PREFER_FLAG_FOR_UNREG_OPTION = 1 << 0,
                  PREFER_PARAM_FOR_UNREG_OPTION = 1 << 1,
                  NO_SPLIT_ON_EQUALSIGN = 1 << 2,
                  SINGLE_DASH_IS_MULTIFLAG = 1 << 3,
                };
Constructor & Destructor Documentation
parser() [1/4]
argh::parser::parser () [default]
parser() [2/4]
argh::parser::parser (std::initializer_list< char const *const > pre_reg_names) [inline]
      { add_params(pre_reg_names); }
References add_params().
parser() [3/4]
argh::parser::parser (const char *const argv[], int mode = PREFER_FLAG_FOR_UNREG_OPTION) [inline]
      { parse(argv, mode); }
References parse().
parser() [4/4]
argh::parser::parser (int argc, const char *const argv[], int mode = PREFER_FLAG_FOR_UNREG_OPTION) [inline]
      { parse(argc, argv, mode); }
References parse().
Member Function Documentation
add_param()
void argh::parser::add_param (std::string const & name) [inline]
   {
      registeredParams_.insert(trim_leading_dashes(name));
   }
References registeredParams_, and trim_leading_dashes().
add_params()
void argh::parser::add_params (std::initializer_list< char const *const > init_list) [inline]
   {
      for (auto& name : init_list)
         registeredParams_.insert(trim_leading_dashes(name));
   }
References registeredParams_, and trim_leading_dashes().
Referenced by parser().
bad_stream()
string_stream argh::parser::bad_stream () const [inline], [private]
   {
      string_stream bad;
      bad.setstate(std::ios_base::failbit);
      return bad;
   }
Referenced by operator()().
begin()
std::vector< std::string >::const_iterator argh::parser::begin () const [inline]
{ return pos_args_.cbegin(); }
References pos_args_.
end()
std::vector< std::string >::const_iterator argh::parser::end () const [inline]
{ return pos_args_.cend(); }
References pos_args_.
flags()
std::multiset< std::string > const & argh::parser::flags () const [inline]
{ return flags_; }
References flags_.
got_flag()
bool argh::parser::got_flag (std::string const & name) const [inline], [private]
   {
      return flags_.end() != flags_.find(trim_leading_dashes(name));
   }
Referenced by operator[]().
is_number()
bool argh::parser::is_number (std::string const & arg) const [inline], [private]
   {
      // inefficient but simple way to determine if a string is a number (which can start with a '-')
      std::istringstream istr(arg);
      double number;
      istr >> number;
      return !(istr.fail() || istr.bad());
   }
Referenced by is_option().
is_option()
bool argh::parser::is_option (std::string const & arg) const [inline], [private]
   {
      assert(0 != arg.size());
      if (is_number(arg))
         return false;
      return '-' == arg[0];
   }
References is_number().
Referenced by parse().
is_param()
bool argh::parser::is_param (std::string const & name) const [inline], [private]
   {
      return registeredParams_.count(name);
   }
Referenced by parse().
operator()() [1/6]
string_stream argh::parser::operator() (size_t ind) const [inline]
   {
      if (pos_args_.size() <= ind)
         return bad_stream();
      return string_stream(pos_args_[ind]);
   }
References bad_stream(), and pos_args_.
operator()() [2/6]
template<typename T >
string_stream argh::parser::operator() (size_t ind, T && def_val) const
   {
      if (pos_args_.size() <= ind)
      {
         std::ostringstream ostr;
         ostr << def_val;
         return string_stream(ostr.str());
      }
      return string_stream(pos_args_[ind]);
   }
References pos_args_.
operator()() [3/6]
string_stream argh::parser::operator() (std::initializer_list< char const *const > init_list) const [inline]
   {
      for (auto& name : init_list)
      {
         auto optIt = params_.find(trim_leading_dashes(name));
         if (params_.end() != optIt)
            return string_stream(optIt->second);
      }
      return bad_stream();
   }
References bad_stream(), params_, and trim_leading_dashes().
operator()() [4/6]
template<typename T >
string_stream argh::parser::operator() (std::initializer_list< char const *const > init_list, T && def_val) const
   {
      for (auto& name : init_list)
      {
         auto optIt = params_.find(trim_leading_dashes(name));
         if (params_.end() != optIt)
            return string_stream(optIt->second);
      }
      std::ostringstream ostr;
      ostr << def_val;
      return string_stream(ostr.str()); // use default
   }
References params_, and trim_leading_dashes().
operator()() [5/6]
string_stream argh::parser::operator() (std::string const & name) const [inline]
   {
      auto optIt = params_.find(trim_leading_dashes(name));
      if (params_.end() != optIt)
         return string_stream(optIt->second);
      return bad_stream();
   }
References bad_stream(), params_, and trim_leading_dashes().
operator()() [6/6]
template<typename T >
string_stream argh::parser::operator() (std::string const & name, T && def_val) const
   {
      auto optIt = params_.find(trim_leading_dashes(name));
      if (params_.end() != optIt)
         return string_stream(optIt->second);
      std::ostringstream ostr;
      ostr << def_val;
      return string_stream(ostr.str()); // use default
   }
References params_, and trim_leading_dashes().
operator[]() [1/3]
std::string const & argh::parser::operator[] (size_t ind) const [inline]
   {
      if (ind < pos_args_.size())
         return pos_args_[ind];
      return empty_;
   }
References empty_, and pos_args_.
operator[]() [2/3]
bool argh::parser::operator[] (std::initializer_list< char const *const > init_list) const [inline]
   {
      return std::any_of(init_list.begin(), init_list.end(), [&](char const* const name) { return got_flag(name); });
   }
operator[]() [3/3]
bool argh::parser::operator[] (std::string const & name) const [inline]
   {
      return got_flag(name);
   }
References got_flag().
params()
std::map< std::string, std::string > const & argh::parser::params () const [inline]
{ return params_; }
References params_.
parse() [1/2]
void argh::parser::parse (const char *const argv[], int mode = PREFER_FLAG_FOR_UNREG_OPTION) [inline]
   {
      int argc = 0;
      for (auto argvp = argv; *argvp; ++argc, ++argvp);
      parse(argc, argv, mode);
   }
References parse().
Referenced by parse(), and parser().
parse() [2/2]
void argh::parser::parse (int argc, const char *const argv[], int mode = PREFER_FLAG_FOR_UNREG_OPTION) [inline]
   {
      // convert to strings
      args_.resize(argc);
      std::transform(argv, argv + argc, args_.begin(), [](const char* const arg) { return arg; });
      // parse line
      for (auto i = 0u; i < args_.size(); ++i)
      {
         if (!is_option(args_[i]))
         {
            pos_args_.emplace_back(args_[i]);
            continue;
         }
         auto name = trim_leading_dashes(args_[i]);
         if (!(mode & NO_SPLIT_ON_EQUALSIGN))
         {
            auto equalPos = name.find('=');
            if (equalPos != std::string::npos)
            {
               params_.insert({ name.substr(0, equalPos), name.substr(equalPos + 1) });
               continue;
            }
         }
         // if the option is unregistered and should be a multi-flag
         if (1 == (args_[i].size() - name.size()) && // single dash
            argh::parser::SINGLE_DASH_IS_MULTIFLAG & mode && // multi-flag mode
            !is_param(name)) // unregistered
         {
            std::string keep_param;
            
            if (!name.empty() && is_param(std::string(1ul, name.back()))) // last char is param
            {
               keep_param += name.back();
               name.resize(name.size() - 1);
            }
            for (auto const& c : name)
            {
               flags_.emplace(std::string{ c });
            }
            if (!keep_param.empty())
            {
               name = keep_param;
            }
            else
            {
               continue; // do not consider other options for this arg
            }
         }
         // any potential option will get as its value the next arg, unless that arg is an option too
         // in that case it will be determined a flag.
         if (i == args_.size() - 1 || is_option(args_[i + 1]))
         {
            flags_.emplace(name);
            continue;
         }
         // if 'name' is a pre-registered option, then the next arg cannot be a free parameter to it is skipped
         // otherwise we have 2 modes:
         // PREFER_FLAG_FOR_UNREG_OPTION: a non-registered 'name' is determined a flag.
         // The following value (the next arg) will be a free parameter.
         //
         // PREFER_PARAM_FOR_UNREG_OPTION: a non-registered 'name' is determined a parameter, the next arg
         // will be the value of that option.
         assert(!(mode & argh::parser::PREFER_FLAG_FOR_UNREG_OPTION)
             || !(mode & argh::parser::PREFER_PARAM_FOR_UNREG_OPTION));
         bool preferParam = mode & argh::parser::PREFER_PARAM_FOR_UNREG_OPTION;
         if (is_param(name) || preferParam)
         {
            params_.insert({ name, args_[i + 1] });
            ++i; // skip next value, it is not a free parameter
            continue;
         }
         else
         {
            flags_.emplace(name);
         }
      };
   }
References args_, flags_, is_option(), is_param(), NO_SPLIT_ON_EQUALSIGN, params_, pos_args_, PREFER_FLAG_FOR_UNREG_OPTION, PREFER_PARAM_FOR_UNREG_OPTION, SINGLE_DASH_IS_MULTIFLAG, size(), and trim_leading_dashes().
pos_args()
std::vector< std::string > const & argh::parser::pos_args () const [inline]
{ return pos_args_; }
References pos_args_.
size()
size_t argh::parser::size () const [inline]
{ return pos_args_.size(); }
References pos_args_.
Referenced by parse().
trim_leading_dashes()
std::string argh::parser::trim_leading_dashes (std::string const & name) const [inline], [private]
   {
      auto pos = name.find_first_not_of('-');
      return std::string::npos != pos ? name.substr(pos) : name;
   }
Referenced by add_param(), add_params(), operator()(), and parse().
Member Data Documentation
args_
std::vector<std::string> argh::parser::args_ [private]
Referenced by parse().
empty_
std::string argh::parser::empty_ [private]
Referenced by operator[]().
flags_
std::multiset<std::string> argh::parser::flags_ [private]
Referenced by flags(), and parse().
params_
std::map<std::string, std::string> argh::parser::params_ [private]
Referenced by operator()(), params(), and parse().
pos_args_
std::vector<std::string> argh::parser::pos_args_ [private]
Referenced by begin(), end(), operator()(), operator[](), parse(), pos_args(), and size().
registeredParams_
std::set<std::string> argh::parser::registeredParams_ [private]
Referenced by add_param(), and add_params().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp