opendlv::proxy::MagneticFieldReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
MagneticFieldReading ()=default
MagneticFieldReading (const MagneticFieldReading &)=default
MagneticFieldReading & operator= (const MagneticFieldReading &)=default
MagneticFieldReading (MagneticFieldReading &&)=default
MagneticFieldReading & operator= (MagneticFieldReading &&)=default
~MagneticFieldReading ()=default
MagneticFieldReading & magneticFieldX (const float &v) noexcept
float magneticFieldX () const noexcept
MagneticFieldReading & magneticFieldY (const float &v) noexcept
float magneticFieldY () const noexcept
MagneticFieldReading & magneticFieldZ (const float &v) noexcept
float magneticFieldZ () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_magneticFieldX { 0.0f }
float m_magneticFieldY { 0.0f }
float m_magneticFieldZ { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `MagneticFieldReading`
static constexpr const char * TheLongName = `opendlv.proxy.MagneticFieldReading`
Constructor & Destructor Documentation
MagneticFieldReading() [1/3]
opendlv::proxy::MagneticFieldReading::MagneticFieldReading () [default]
MagneticFieldReading() [2/3]
opendlv::proxy::MagneticFieldReading::MagneticFieldReading (const MagneticFieldReading &) [default]
MagneticFieldReading() [3/3]
opendlv::proxy::MagneticFieldReading::MagneticFieldReading (MagneticFieldReading &&) [default]
 MagneticFieldReading()
opendlv::proxy::MagneticFieldReading::~MagneticFieldReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::MagneticFieldReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("magneticFieldX"s), m_magneticFieldX, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("magneticFieldY"s), m_magneticFieldY, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("magneticFieldZ"s), m_magneticFieldZ, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::MagneticFieldReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("magneticFieldX"s), m_magneticFieldX, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("magneticFieldY"s), m_magneticFieldY, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("magneticFieldZ"s), m_magneticFieldZ, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::MagneticFieldReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("magneticFieldX"s), m_magneticFieldX, visitor);
            doVisit(2, std::move("float"s), std::move("magneticFieldY"s), m_magneticFieldY, visitor);
            doVisit(3, std::move("float"s), std::move("magneticFieldZ"s), m_magneticFieldZ, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::MagneticFieldReading::ID () [inline], [static]
                                   {
            return 1032;
        }
Referenced by main().
LongName()
static const std::string opendlv::proxy::MagneticFieldReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
magneticFieldX() [1/2]
float opendlv::proxy::MagneticFieldReading::magneticFieldX () const [inline], [noexcept]
                                                     {
            return m_magneticFieldX;
        }
magneticFieldX() [2/2]
MagneticFieldReading & opendlv::proxy::MagneticFieldReading::magneticFieldX (const float & v) [inline], [noexcept]
                                                                             {
            m_magneticFieldX = v;
            return *this;
        }
Referenced by main().
magneticFieldY() [1/2]
float opendlv::proxy::MagneticFieldReading::magneticFieldY () const [inline], [noexcept]
                                                     {
            return m_magneticFieldY;
        }
magneticFieldY() [2/2]
MagneticFieldReading & opendlv::proxy::MagneticFieldReading::magneticFieldY (const float & v) [inline], [noexcept]
                                                                             {
            m_magneticFieldY = v;
            return *this;
        }
Referenced by main().
magneticFieldZ() [1/2]
float opendlv::proxy::MagneticFieldReading::magneticFieldZ () const [inline], [noexcept]
                                                     {
            return m_magneticFieldZ;
        }
magneticFieldZ() [2/2]
MagneticFieldReading & opendlv::proxy::MagneticFieldReading::magneticFieldZ (const float & v) [inline], [noexcept]
                                                                             {
            m_magneticFieldZ = v;
            return *this;
        }
Referenced by main().
operator=() [1/2]
MagneticFieldReading & opendlv::proxy::MagneticFieldReading::operator= (const MagneticFieldReading &) [default]
operator=() [2/2]
MagneticFieldReading & opendlv::proxy::MagneticFieldReading::operator= (MagneticFieldReading &&) [default]
ShortName()
static const std::string opendlv::proxy::MagneticFieldReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_magneticFieldX
float opendlv::proxy::MagneticFieldReading::m_magneticFieldX { 0.0f } [private]
m_magneticFieldY
float opendlv::proxy::MagneticFieldReading::m_magneticFieldY { 0.0f } [private]
m_magneticFieldZ
float opendlv::proxy::MagneticFieldReading::m_magneticFieldZ { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::MagneticFieldReading::TheLongName = `opendlv.proxy.MagneticFieldReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::MagneticFieldReading::TheShortName = `MagneticFieldReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp