opendlv::proxy::GroundSteeringReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSteeringReading ()=default
GroundSteeringReading (const GroundSteeringReading &)=default
GroundSteeringReading & operator= (const GroundSteeringReading &)=default
GroundSteeringReading (GroundSteeringReading &&)=default
GroundSteeringReading & operator= (GroundSteeringReading &&)=default
~GroundSteeringReading ()=default
GroundSteeringReading & groundSteering (const float &v) noexcept
float groundSteering () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundSteering { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSteeringReading`
static constexpr const char * TheLongName = `opendlv.proxy.GroundSteeringReading`
Constructor & Destructor Documentation
GroundSteeringReading() [1/3]
opendlv::proxy::GroundSteeringReading::GroundSteeringReading () [default]
GroundSteeringReading() [2/3]
opendlv::proxy::GroundSteeringReading::GroundSteeringReading (const GroundSteeringReading &) [default]
GroundSteeringReading() [3/3]
opendlv::proxy::GroundSteeringReading::GroundSteeringReading (GroundSteeringReading &&) [default]
 GroundSteeringReading()
opendlv::proxy::GroundSteeringReading::~GroundSteeringReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundSteeringReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundSteeringReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundSteeringReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundSteering"s), m_groundSteering, visitor);
            visitor.postVisit();
        }
References doVisit().
groundSteering() [1/2]
float opendlv::proxy::GroundSteeringReading::groundSteering () const [inline], [noexcept]
                                                     {
            return m_groundSteering;
        }
groundSteering() [2/2]
GroundSteeringReading & opendlv::proxy::GroundSteeringReading::groundSteering (const float & v) [inline], [noexcept]
                                                                              {
            m_groundSteering = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::GroundSteeringReading::ID () [inline], [static]
                                   {
            return 1045;
        }
LongName()
static const std::string opendlv::proxy::GroundSteeringReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSteeringReading & opendlv::proxy::GroundSteeringReading::operator= (const GroundSteeringReading &) [default]
operator=() [2/2]
GroundSteeringReading & opendlv::proxy::GroundSteeringReading::operator= (GroundSteeringReading &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundSteeringReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundSteering
float opendlv::proxy::GroundSteeringReading::m_groundSteering { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundSteeringReading::TheLongName = `opendlv.proxy.GroundSteeringReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundSteeringReading::TheShortName = `GroundSteeringReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp