opendlv::proxy::GroundAccelerationRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundAccelerationRequest ()=default
GroundAccelerationRequest (const GroundAccelerationRequest &)=default
GroundAccelerationRequest & operator= (const GroundAccelerationRequest &)=default
GroundAccelerationRequest (GroundAccelerationRequest &&)=default
GroundAccelerationRequest & operator= (GroundAccelerationRequest &&)=default
~GroundAccelerationRequest ()=default
GroundAccelerationRequest & groundAcceleration (const float &v) noexcept
float groundAcceleration () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundAcceleration { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundAccelerationRequest`
static constexpr const char * TheLongName = `opendlv.proxy.GroundAccelerationRequest`
Constructor & Destructor Documentation
GroundAccelerationRequest() [1/3]
opendlv::proxy::GroundAccelerationRequest::GroundAccelerationRequest () [default]
GroundAccelerationRequest() [2/3]
opendlv::proxy::GroundAccelerationRequest::GroundAccelerationRequest (const GroundAccelerationRequest &) [default]
GroundAccelerationRequest() [3/3]
opendlv::proxy::GroundAccelerationRequest::GroundAccelerationRequest (GroundAccelerationRequest &&) [default]
 GroundAccelerationRequest()
opendlv::proxy::GroundAccelerationRequest::~GroundAccelerationRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundAccelerationRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundAcceleration"s), m_groundAcceleration, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundAccelerationRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundAcceleration"s), m_groundAcceleration, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundAccelerationRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundAcceleration"s), m_groundAcceleration, visitor);
            visitor.postVisit();
        }
References doVisit().
groundAcceleration() [1/2]
float opendlv::proxy::GroundAccelerationRequest::groundAcceleration () const [inline], [noexcept]
                                                         {
            return m_groundAcceleration;
        }
groundAcceleration() [2/2]
GroundAccelerationRequest & opendlv::proxy::GroundAccelerationRequest::groundAcceleration (const float & v) [inline], [noexcept]
                                                                                      {
            m_groundAcceleration = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::GroundAccelerationRequest::ID () [inline], [static]
                                   {
            return 1092;
        }
LongName()
static const std::string opendlv::proxy::GroundAccelerationRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundAccelerationRequest & opendlv::proxy::GroundAccelerationRequest::operator= (const GroundAccelerationRequest &) [default]
operator=() [2/2]
GroundAccelerationRequest & opendlv::proxy::GroundAccelerationRequest::operator= (GroundAccelerationRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundAccelerationRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundAcceleration
float opendlv::proxy::GroundAccelerationRequest::m_groundAcceleration { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundAccelerationRequest::TheLongName = `opendlv.proxy.GroundAccelerationRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundAccelerationRequest::TheShortName = `GroundAccelerationRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp