cluon::data::Envelope Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Envelope ()=default
Envelope (const Envelope &)=default
Envelope & operator= (const Envelope &)=default
Envelope (Envelope &&)=default
Envelope & operator= (Envelope &&)=default
~Envelope ()=default
Envelope & dataType (const int32_t &v) noexcept
int32_t dataType () const noexcept
Envelope & serializedData (const std::string &v) noexcept
std::string serializedData () const noexcept
Envelope & sent (const cluon::data::TimeStamp &v) noexcept
cluon::data::TimeStamp sent () const noexcept
Envelope & received (const cluon::data::TimeStamp &v) noexcept
cluon::data::TimeStamp received () const noexcept
Envelope & sampleTimeStamp (const cluon::data::TimeStamp &v) noexcept
cluon::data::TimeStamp sampleTimeStamp () const noexcept
Envelope & senderStamp (const uint32_t &v) noexcept
uint32_t senderStamp () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
int32_t m_dataType { 0 }
std::string m_serializedData { ``s }
cluon::data::TimeStamp m_sent { }
cluon::data::TimeStamp m_received { }
cluon::data::TimeStamp m_sampleTimeStamp { }
uint32_t m_senderStamp { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `Envelope`
static constexpr const char * TheLongName = `cluon.data.Envelope`
Constructor & Destructor Documentation
Envelope() [1/3]
cluon::data::Envelope::Envelope () [default]
Envelope() [2/3]
cluon::data::Envelope::Envelope (const Envelope &) [default]
Envelope() [3/3]
cluon::data::Envelope::Envelope (Envelope &&) [default]
 Envelope()
cluon::data::Envelope::~Envelope () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::data::Envelope::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("int32_t"s), std::move("dataType"s), m_dataType, preVisit, visit, postVisit);
            
            doTripletForwardVisit(2, std::move("std::string"s), std::move("serializedData"s), m_serializedData, preVisit, visit, postVisit);
            
            doTripletForwardVisit(3, std::move("cluon::data::TimeStamp"s), std::move("sent"s), m_sent, preVisit, visit, postVisit);
            
            doTripletForwardVisit(4, std::move("cluon::data::TimeStamp"s), std::move("received"s), m_received, preVisit, visit, postVisit);
            
            doTripletForwardVisit(5, std::move("cluon::data::TimeStamp"s), std::move("sampleTimeStamp"s), m_sampleTimeStamp, preVisit, visit, postVisit);
            
            doTripletForwardVisit(6, std::move("uint32_t"s), std::move("senderStamp"s), m_senderStamp, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void cluon::data::Envelope::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("int32_t"s), std::move("dataType"s), m_dataType, visitor);
                return;
            }
            
            if (2 == fieldId) {
                doVisit(2, std::move("std::string"s), std::move("serializedData"s), m_serializedData, visitor);
                return;
            }
            
            if (3 == fieldId) {
                doVisit(3, std::move("cluon::data::TimeStamp"s), std::move("sent"s), m_sent, visitor);
                return;
            }
            
            if (4 == fieldId) {
                doVisit(4, std::move("cluon::data::TimeStamp"s), std::move("received"s), m_received, visitor);
                return;
            }
            
            if (5 == fieldId) {
                doVisit(5, std::move("cluon::data::TimeStamp"s), std::move("sampleTimeStamp"s), m_sampleTimeStamp, visitor);
                return;
            }
            
            if (6 == fieldId) {
                doVisit(6, std::move("uint32_t"s), std::move("senderStamp"s), m_senderStamp, visitor);
                return;
            }
            
// visitor.postVisit();
        }
References doVisit().
Referenced by cluon::OD4Session::send().
accept() [3/3]
template<class Visitor >
void cluon::data::Envelope::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("int32_t"s), std::move("dataType"s), m_dataType, visitor);
            
            doVisit(2, std::move("std::string"s), std::move("serializedData"s), m_serializedData, visitor);
            
            doVisit(3, std::move("cluon::data::TimeStamp"s), std::move("sent"s), m_sent, visitor);
            
            doVisit(4, std::move("cluon::data::TimeStamp"s), std::move("received"s), m_received, visitor);
            
            doVisit(5, std::move("cluon::data::TimeStamp"s), std::move("sampleTimeStamp"s), m_sampleTimeStamp, visitor);
            
            doVisit(6, std::move("uint32_t"s), std::move("senderStamp"s), m_senderStamp, visitor);
            
            visitor.postVisit();
        }
References doVisit().
dataType() [1/2]
int32_t cluon::data::Envelope::dataType () const [inline], [noexcept]
                                                 {
            return m_dataType;
        }
dataType() [2/2]
Envelope & cluon::data::Envelope::dataType (const int32_t & v) [inline], [noexcept]
                                                             {
            m_dataType = v;
            return *this;
        }
Referenced by cluon::EnvelopeConverter::getJSONFromProtoEncodedEnvelope(), cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::OD4Session::send().
ID()
static int32_t cluon::data::Envelope::ID () [inline], [static]
                                   {
            return 1;
        }
LongName()
static const std::string cluon::data::Envelope::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
Envelope & cluon::data::Envelope::operator= (const Envelope &) [default]
operator=() [2/2]
Envelope & cluon::data::Envelope::operator= (Envelope &&) [default]
received() [1/2]
cluon::data::TimeStamp cluon::data::Envelope::received () const [inline], [noexcept]
                                                            {
            return m_received;
        }
received() [2/2]
Envelope & cluon::data::Envelope::received (const cluon::data::TimeStamp & v) [inline], [noexcept]
                                                                        {
            m_received = v;
            return *this;
        }
sampleTimeStamp() [1/2]
cluon::data::TimeStamp cluon::data::Envelope::sampleTimeStamp () const [inline], [noexcept]
                                                                   {
            return m_sampleTimeStamp;
        }
sampleTimeStamp() [2/2]
Envelope & cluon::data::Envelope::sampleTimeStamp (const cluon::data::TimeStamp & v) [inline], [noexcept]
                                                                               {
            m_sampleTimeStamp = v;
            return *this;
        }
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::OD4Session::send().
senderStamp() [1/2]
uint32_t cluon::data::Envelope::senderStamp () const [inline], [noexcept]
                                                     {
            return m_senderStamp;
        }
senderStamp() [2/2]
Envelope & cluon::data::Envelope::senderStamp (const uint32_t & v) [inline], [noexcept]
                                                                 {
            m_senderStamp = v;
            return *this;
        }
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::OD4Session::send().
sent() [1/2]
cluon::data::TimeStamp cluon::data::Envelope::sent () const [inline], [noexcept]
                                                        {
            return m_sent;
        }
sent() [2/2]
Envelope & cluon::data::Envelope::sent (const cluon::data::TimeStamp & v) [inline], [noexcept]
                                                                    {
            m_sent = v;
            return *this;
        }
Referenced by cluon::OD4Session::send().
serializedData() [1/2]
std::string cluon::data::Envelope::serializedData () const [inline], [noexcept]
                                                         {
            return m_serializedData;
        }
serializedData() [2/2]
Envelope & cluon::data::Envelope::serializedData (const std::string & v) [inline], [noexcept]
                                                                     {
            m_serializedData = v;
            return *this;
        }
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::OD4Session::send().
ShortName()
static const std::string cluon::data::Envelope::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_dataType
int32_t cluon::data::Envelope::m_dataType { 0 } [private]
m_received
cluon::data::TimeStamp cluon::data::Envelope::m_received { } [private]
m_sampleTimeStamp
cluon::data::TimeStamp cluon::data::Envelope::m_sampleTimeStamp { } [private]
m_senderStamp
uint32_t cluon::data::Envelope::m_senderStamp { 0 } [private]
m_sent
cluon::data::TimeStamp cluon::data::Envelope::m_sent { } [private]
m_serializedData
std::string cluon::data::Envelope::m_serializedData { ``s } [private]
TheLongName
constexpr const char* cluon::data::Envelope::TheLongName = `cluon.data.Envelope` [static], [constexpr], [private]
TheShortName
constexpr const char* cluon::data::Envelope::TheShortName = `Envelope` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp