opendlv::proxy::SwitchStateReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
SwitchStateReading ()=default
SwitchStateReading (const SwitchStateReading &)=default
SwitchStateReading & operator= (const SwitchStateReading &)=default
SwitchStateReading (SwitchStateReading &&)=default
SwitchStateReading & operator= (SwitchStateReading &&)=default
~SwitchStateReading ()=default
SwitchStateReading & state (const int16_t &v) noexcept
int16_t state () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
int16_t m_state { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `SwitchStateReading`
static constexpr const char * TheLongName = `opendlv.proxy.SwitchStateReading`
Constructor & Destructor Documentation
SwitchStateReading() [1/3]
opendlv::proxy::SwitchStateReading::SwitchStateReading () [default]
SwitchStateReading() [2/3]
opendlv::proxy::SwitchStateReading::SwitchStateReading (const SwitchStateReading &) [default]
SwitchStateReading() [3/3]
opendlv::proxy::SwitchStateReading::SwitchStateReading (SwitchStateReading &&) [default]
 SwitchStateReading()
opendlv::proxy::SwitchStateReading::~SwitchStateReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::SwitchStateReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("int16_t"s), std::move("state"s), m_state, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::SwitchStateReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("int16_t"s), std::move("state"s), m_state, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::SwitchStateReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("int16_t"s), std::move("state"s), m_state, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::SwitchStateReading::ID () [inline], [static]
                                   {
            return 1040;
        }
LongName()
static const std::string opendlv::proxy::SwitchStateReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
SwitchStateReading & opendlv::proxy::SwitchStateReading::operator= (const SwitchStateReading &) [default]
operator=() [2/2]
SwitchStateReading & opendlv::proxy::SwitchStateReading::operator= (SwitchStateReading &&) [default]
ShortName()
static const std::string opendlv::proxy::SwitchStateReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
state() [1/2]
int16_t opendlv::proxy::SwitchStateReading::state () const [inline], [noexcept]
                                              {
            return m_state;
        }
state() [2/2]
SwitchStateReading & opendlv::proxy::SwitchStateReading::state (const int16_t & v) [inline], [noexcept]
                                                                    {
            m_state = v;
            return *this;
        }
Member Data Documentation
m_state
int16_t opendlv::proxy::SwitchStateReading::m_state { 0 } [private]
TheLongName
constexpr const char* opendlv::proxy::SwitchStateReading::TheLongName = `opendlv.proxy.SwitchStateReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::SwitchStateReading::TheShortName = `SwitchStateReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp