opendlv::logic::action::AimPoint Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AimPoint ()=default
AimPoint (const AimPoint &)=default
AimPoint & operator= (const AimPoint &)=default
AimPoint (AimPoint &&)=default
AimPoint & operator= (AimPoint &&)=default
~AimPoint ()=default
AimPoint & azimuthAngle (const float &v) noexcept
float azimuthAngle () const noexcept
AimPoint & zenithAngle (const float &v) noexcept
float zenithAngle () const noexcept
AimPoint & distance (const float &v) noexcept
float distance () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_azimuthAngle { 0.0f }
float m_zenithAngle { 0.0f }
float m_distance { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AimPoint`
static constexpr const char * TheLongName = `opendlv.logic.action.AimPoint`
Constructor & Destructor Documentation
AimPoint() [1/3]
opendlv::logic::action::AimPoint::AimPoint () [default]
AimPoint() [2/3]
opendlv::logic::action::AimPoint::AimPoint (const AimPoint &) [default]
AimPoint() [3/3]
opendlv::logic::action::AimPoint::AimPoint (AimPoint &&) [default]
 AimPoint()
opendlv::logic::action::AimPoint::~AimPoint () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::action::AimPoint::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("distance"s), m_distance, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::action::AimPoint::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("distance"s), m_distance, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::action::AimPoint::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
            doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
            doVisit(3, std::move("float"s), std::move("distance"s), m_distance, visitor);
            visitor.postVisit();
        }
References doVisit().
azimuthAngle() [1/2]
float opendlv::logic::action::AimPoint::azimuthAngle () const [inline], [noexcept]
                                                   {
            return m_azimuthAngle;
        }
azimuthAngle() [2/2]
AimPoint & opendlv::logic::action::AimPoint::azimuthAngle (const float & v) [inline], [noexcept]
                                                               {
            m_azimuthAngle = v;
            return *this;
        }
distance() [1/2]
float opendlv::logic::action::AimPoint::distance () const [inline], [noexcept]
                                               {
            return m_distance;
        }
distance() [2/2]
AimPoint & opendlv::logic::action::AimPoint::distance (const float & v) [inline], [noexcept]
                                                           {
            m_distance = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::action::AimPoint::ID () [inline], [static]
                                   {
            return 1172;
        }
LongName()
static const std::string opendlv::logic::action::AimPoint::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AimPoint & opendlv::logic::action::AimPoint::operator= (AimPoint &&) [default]
operator=() [2/2]
AimPoint & opendlv::logic::action::AimPoint::operator= (const AimPoint &) [default]
ShortName()
static const std::string opendlv::logic::action::AimPoint::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
zenithAngle() [1/2]
float opendlv::logic::action::AimPoint::zenithAngle () const [inline], [noexcept]
                                                  {
            return m_zenithAngle;
        }
zenithAngle() [2/2]
AimPoint & opendlv::logic::action::AimPoint::zenithAngle (const float & v) [inline], [noexcept]
                                                              {
            m_zenithAngle = v;
            return *this;
        }
Member Data Documentation
m_azimuthAngle
float opendlv::logic::action::AimPoint::m_azimuthAngle { 0.0f } [private]
m_distance
float opendlv::logic::action::AimPoint::m_distance { 0.0f } [private]
m_zenithAngle
float opendlv::logic::action::AimPoint::m_zenithAngle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::action::AimPoint::TheLongName = `opendlv.logic.action.AimPoint` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::action::AimPoint::TheShortName = `AimPoint` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp