opendlv::proxy::PulseWidthModulationRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PulseWidthModulationRequest ()=default
PulseWidthModulationRequest (const PulseWidthModulationRequest &)=default
PulseWidthModulationRequest & operator= (const PulseWidthModulationRequest &)=default
PulseWidthModulationRequest (PulseWidthModulationRequest &&)=default
PulseWidthModulationRequest & operator= (PulseWidthModulationRequest &&)=default
~PulseWidthModulationRequest ()=default
PulseWidthModulationRequest & dutyCycleNs (const uint32_t &v) noexcept
uint32_t dutyCycleNs () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_dutyCycleNs { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `PulseWidthModulationRequest`
static constexpr const char * TheLongName = `opendlv.proxy.PulseWidthModulationRequest`
Constructor & Destructor Documentation
PulseWidthModulationRequest() [1/3]
opendlv::proxy::PulseWidthModulationRequest::PulseWidthModulationRequest () [default]
PulseWidthModulationRequest() [2/3]
opendlv::proxy::PulseWidthModulationRequest::PulseWidthModulationRequest (const PulseWidthModulationRequest &) [default]
PulseWidthModulationRequest() [3/3]
opendlv::proxy::PulseWidthModulationRequest::PulseWidthModulationRequest (PulseWidthModulationRequest &&) [default]
 PulseWidthModulationRequest()
opendlv::proxy::PulseWidthModulationRequest::~PulseWidthModulationRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PulseWidthModulationRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("dutyCycleNs"s), m_dutyCycleNs, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PulseWidthModulationRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("dutyCycleNs"s), m_dutyCycleNs, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PulseWidthModulationRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("dutyCycleNs"s), m_dutyCycleNs, visitor);
            visitor.postVisit();
        }
References doVisit().
dutyCycleNs() [1/2]
uint32_t opendlv::proxy::PulseWidthModulationRequest::dutyCycleNs () const [inline], [noexcept]
                                                     {
            return m_dutyCycleNs;
        }
dutyCycleNs() [2/2]
PulseWidthModulationRequest & opendlv::proxy::PulseWidthModulationRequest::dutyCycleNs (const uint32_t & v) [inline], [noexcept]
                                                                                    {
            m_dutyCycleNs = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::PulseWidthModulationRequest::ID () [inline], [static]
                                   {
            return 1087;
        }
LongName()
static const std::string opendlv::proxy::PulseWidthModulationRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PulseWidthModulationRequest & opendlv::proxy::PulseWidthModulationRequest::operator= (const PulseWidthModulationRequest &) [default]
operator=() [2/2]
PulseWidthModulationRequest & opendlv::proxy::PulseWidthModulationRequest::operator= (PulseWidthModulationRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::PulseWidthModulationRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_dutyCycleNs
uint32_t opendlv::proxy::PulseWidthModulationRequest::m_dutyCycleNs { 0 } [private]
TheLongName
constexpr const char* opendlv::proxy::PulseWidthModulationRequest::TheLongName = `opendlv.proxy.PulseWidthModulationRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PulseWidthModulationRequest::TheShortName = `PulseWidthModulationRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp