opendlv::logic::perception::GroundSurfaceType Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSurfaceType ()=default
GroundSurfaceType (const GroundSurfaceType &)=default
GroundSurfaceType & operator= (const GroundSurfaceType &)=default
GroundSurfaceType (GroundSurfaceType &&)=default
GroundSurfaceType & operator= (GroundSurfaceType &&)=default
~GroundSurfaceType ()=default
GroundSurfaceType & surfaceId (const uint32_t &v) noexcept
uint32_t surfaceId () const noexcept
GroundSurfaceType & type (const uint32_t &v) noexcept
uint32_t type () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_surfaceId { 0 }
uint32_t m_type { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSurfaceType`
static constexpr const char * TheLongName = `opendlv.logic.perception.GroundSurfaceType`
Constructor & Destructor Documentation
GroundSurfaceType() [1/3]
opendlv::logic::perception::GroundSurfaceType::GroundSurfaceType () [default]
GroundSurfaceType() [2/3]
opendlv::logic::perception::GroundSurfaceType::GroundSurfaceType (const GroundSurfaceType &) [default]
GroundSurfaceType() [3/3]
opendlv::logic::perception::GroundSurfaceType::GroundSurfaceType (GroundSurfaceType &&) [default]
 GroundSurfaceType()
opendlv::logic::perception::GroundSurfaceType::~GroundSurfaceType () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::GroundSurfaceType::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceType::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurfaceType::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::GroundSurfaceType::ID () [inline], [static]
                                   {
            return 1141;
        }
LongName()
static const std::string opendlv::logic::perception::GroundSurfaceType::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSurfaceType & opendlv::logic::perception::GroundSurfaceType::operator= (const GroundSurfaceType &) [default]
operator=() [2/2]
GroundSurfaceType & opendlv::logic::perception::GroundSurfaceType::operator= (GroundSurfaceType &&) [default]
ShortName()
static const std::string opendlv::logic::perception::GroundSurfaceType::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
surfaceId() [1/2]
uint32_t opendlv::logic::perception::GroundSurfaceType::surfaceId () const [inline], [noexcept]
                                                   {
            return m_surfaceId;
        }
surfaceId() [2/2]
GroundSurfaceType & opendlv::logic::perception::GroundSurfaceType::surfaceId (const uint32_t & v) [inline], [noexcept]
                                                                        {
            m_surfaceId = v;
            return *this;
        }
type() [1/2]
uint32_t opendlv::logic::perception::GroundSurfaceType::type () const [inline], [noexcept]
                                              {
            return m_type;
        }
type() [2/2]
GroundSurfaceType & opendlv::logic::perception::GroundSurfaceType::type (const uint32_t & v) [inline], [noexcept]
                                                                   {
            m_type = v;
            return *this;
        }
Member Data Documentation
m_surfaceId
uint32_t opendlv::logic::perception::GroundSurfaceType::m_surfaceId { 0 } [private]
m_type
uint32_t opendlv::logic::perception::GroundSurfaceType::m_type { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::GroundSurfaceType::TheLongName = `opendlv.logic.perception.GroundSurfaceType` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::GroundSurfaceType::TheShortName = `GroundSurfaceType` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp