peg::ParserGenerator Class Reference
#include <cluon-complete.hpp>
Classes
struct Data
Static Public Member Functions
static std::shared_ptr< Grammar > parse (const char *s, size_t n, const Rules &rules, std::string &start, Log log)
static std::shared_ptr< Grammar > parse (const char *s, size_t n, std::string &start, Log log)
static Grammar & grammar ()
Private Member Functions
ParserGenerator ()
void make_grammar ()
void setup_actions ()
std::shared_ptr< Grammar > perform_core (const char *s, size_t n, const Rules &rules, std::string &start, Log log)
Static Private Member Functions
static ParserGenerator & get_instance ()
Private Attributes
Grammar g
Constructor & Destructor Documentation
ParserGenerator()
peg::ParserGenerator::ParserGenerator () [inline], [private]
                      {
        make_grammar();
        setup_actions();
    }
Member Function Documentation
get_instance()
static ParserGenerator & peg::ParserGenerator::get_instance () [inline], [static], [private]
                                           {
        static ParserGenerator instance;
        return instance;
    }
grammar()
static Grammar & peg::ParserGenerator::grammar () [inline], [static]
                              {
        return get_instance().g;
    }
make_grammar()
void peg::ParserGenerator::make_grammar () [inline], [private]
                        {
        // Setup PEG syntax parser
        g["Grammar"] <= seq(g["Spacing"], oom(g["Definition"]), g["EndOfFile"]);
        g["Definition"] <= cho(seq(g["Ignore"], g["IdentCont"], g["Parameters"], g["LEFTARROW"], g["Expression"]),
                               seq(g["Ignore"], g["Identifier"], g["LEFTARROW"], g["Expression"]));
        g["Expression"] <= seq(g["Sequence"], zom(seq(g["SLASH"], g["Sequence"])));
        g["Sequence"] <= zom(g["Prefix"]);
        g["Prefix"] <= seq(opt(cho(g["AND"], g["NOT"])), g["Suffix"]);
        g["Suffix"] <= seq(g["Primary"], opt(cho(g["QUESTION"], g["STAR"], g["PLUS"])));
        g["Primary"] <= cho(seq(g["Ignore"], g["IdentCont"], g["Arguments"], npd(g["LEFTARROW"])),
                               seq(g["Ignore"], g["Identifier"], npd(seq(opt(g["Parameters"]), g["LEFTARROW"]))),
                               seq(g["OPEN"], g["Expression"], g["CLOSE"]),
                               seq(g["BeginTok"], g["Expression"], g["EndTok"]),
                               seq(g["BeginCapScope"], g["Expression"], g["EndCapScope"]),
                               seq(g["BeginCap"], g["Expression"], g["EndCap"]),
                               g["BackRef"], g["LiteralI"], g["Literal"], g["Class"], g["DOT"]);
        g["Identifier"] <= seq(g["IdentCont"], g["Spacing"]);
        g["IdentCont"] <= seq(g["IdentStart"], zom(g["IdentRest"]));
        const static std::vector<std::pair<char32_t, char32_t>> range = {{ 0x0080, 0xFFFF }};
        g["IdentStart"] <= cho(cls("a-zA-Z_%"), cls(range));
        g["IdentRest"] <= cho(g["IdentStart"], cls("0-9"));
        g["LiteralI"] <= cho(seq(cls("'"), tok(zom(seq(npd(cls("'")), g["Char"]))), lit("'i"), g["Spacing"]),
                               seq(cls("\""), tok(zom(seq(npd(cls("\"")), g["Char"]))), lit("\"i"), g["Spacing"]));
        g["Literal"] <= cho(seq(cls("'"), tok(zom(seq(npd(cls("'")), g["Char"]))), cls("'"), g["Spacing"]),
                               seq(cls("\""), tok(zom(seq(npd(cls("\"")), g["Char"]))), cls("\""), g["Spacing"]));
        g["Class"] <= seq(chr('['), tok(zom(seq(npd(chr(']')), g["Range"]))), chr(']'), g["Spacing"]);
        g["Range"] <= cho(seq(g["Char"], chr('-'), g["Char"]), g["Char"]);
        g["Char"] <= cho(seq(chr('\\'), cls("nrt'\"[]\\")),
                               seq(chr('\\'), cls("0-3"), cls("0-7"), cls("0-7")),
                               seq(chr('\\'), cls("0-7"), opt(cls("0-7"))),
                               seq(lit("\\x"), cls("0-9a-fA-F"), opt(cls("0-9a-fA-F"))),
                               seq(lit("\\u"), cls("0-9a-fA-F"), cls("0-9a-fA-F"), cls("0-9a-fA-F"), cls("0-9a-fA-F")),
                               seq(npd(chr('\\')), dot()));
#if defined(PEGLIB_NO_UNICODE_CHARS)
        g["LEFTARROW"] <= seq(lit("<-"), g["Spacing"]);
#else
        g["LEFTARROW"] <= seq(cho(lit("<-"), lit(u8"â†")), g["Spacing"]);
#endif
        ~g["SLASH"] <= seq(chr('/'), g["Spacing"]);
        g["AND"] <= seq(chr('&'), g["Spacing"]);
        g["NOT"] <= seq(chr('!'), g["Spacing"]);
        g["QUESTION"] <= seq(chr('?'), g["Spacing"]);
        g["STAR"] <= seq(chr('*'), g["Spacing"]);
        g["PLUS"] <= seq(chr('+'), g["Spacing"]);
        ~g["OPEN"] <= seq(chr('('), g["Spacing"]);
        ~g["CLOSE"] <= seq(chr(')'), g["Spacing"]);
        g["DOT"] <= seq(chr('.'), g["Spacing"]);
        ~g["Spacing"] <= zom(cho(g["Space"], g["Comment"]));
        g["Comment"] <= seq(chr('#'), zom(seq(npd(g["EndOfLine"]), dot())), g["EndOfLine"]);
        g["Space"] <= cho(chr(' '), chr('\t'), g["EndOfLine"]);
        g["EndOfLine"] <= cho(lit("\r\n"), chr('\n'), chr('\r'));
        g["EndOfFile"] <= npd(dot());
        ~g["BeginTok"] <= seq(chr('<'), g["Spacing"]);
        ~g["EndTok"] <= seq(chr('>'), g["Spacing"]);
        ~g["BeginCapScope"] <= seq(chr('$'), chr('('), g["Spacing"]);
        ~g["EndCapScope"] <= seq(chr(')'), g["Spacing"]);
        g["BeginCap"] <= seq(chr('$'), tok(g["IdentCont"]), chr('<'), g["Spacing"]);
        ~g["EndCap"] <= seq(chr('>'), g["Spacing"]);
        g["BackRef"] <= seq(chr('$'), tok(g["IdentCont"]), g["Spacing"]);
        g["IGNORE"] <= chr('~');
        g["Ignore"] <= opt(g["IGNORE"]);
        g["Parameters"] <= seq(g["OPEN"], g["Identifier"], zom(seq(g["COMMA"], g["Identifier"])), g["CLOSE"]);
        g["Arguments"] <= seq(g["OPEN"], g["Expression"], zom(seq(g["COMMA"], g["Expression"])), g["CLOSE"]);
        ~g["COMMA"] <= seq(chr(','), g["Spacing"]);
        // Set definition names
        for (auto& x: g) {
            x.second.name = x.first;
        }
    }
References peg::cho(), peg::chr(), peg::cls(), peg::dot(), peg::lit(), peg::npd(), peg::oom(), peg::opt(), peg::seq(), peg::tok(), and peg::zom().
parse() [1/2]
static std::shared_ptr< Grammar > peg::ParserGenerator::parse (const char * s, size_t n, const Rules & rules, std::string & start, Log log) [inline], [static]
    {
        return get_instance().perform_core(s, n, rules, start, log);
    }
References log.
parse() [2/2]
static std::shared_ptr< Grammar > peg::ParserGenerator::parse (const char * s, size_t n, std::string & start, Log log) [inline], [static]
    {
        Rules dummy;
        return parse(s, n, dummy, start, log);
    }
References log.
perform_core()
std::shared_ptr< Grammar > peg::ParserGenerator::perform_core (const char * s, size_t n, const Rules & rules, std::string & start, Log log) [inline], [private]
    {
        Data data;
        any dt = &data;
        auto r = g["Grammar"].parse(s, n, dt);
        if (!r.ret) {
            if (log) {
                if (r.message_pos) {
                    auto line = line_info(s, r.message_pos);
                    log(line.first, line.second, r.message);
                } else {
                    auto line = line_info(s, r.error_pos);
                    log(line.first, line.second, "syntax error");
                }
            }
            return nullptr;
        }
        auto& grammar = *data.grammar;
        // User provided rules
        for (const auto& x: rules) {
            auto name = x.first;
            bool ignore = false;
            if (!name.empty() && name[0] == '~') {
                ignore = true;
                name.erase(0, 1);
            }
            if (!name.empty()) {
                auto& rule = grammar[name];
                rule <= x.second;
                rule.name = name;
                rule.ignoreSemanticValue = ignore;
            }
        }
        // Check duplicated definitions
        bool ret = data.duplicates.empty();
        for (const auto& x: data.duplicates) {
            if (log) {
                const auto& name = x.first;
                auto ptr = x.second;
                auto line = line_info(s, ptr);
                log(line.first, line.second, "'" + name + "' is already defined.");
            }
        }
        // Check missing definitions
        for (auto& x: grammar) {
            auto& rule = x.second;
            ReferenceChecker vis(*data.grammar, rule.params);
            rule.accept(vis);
            for (const auto& y: vis.error_s) {
                const auto& name = y.first;
                const auto ptr = y.second;
                if (log) {
                    auto line = line_info(s, ptr);
                    log(line.first, line.second, vis.error_message[name]);
                }
                ret = false;
            }
        }
        if (!ret) {
            return nullptr;
        }
        // Link references
        for (auto& x: grammar) {
            auto& rule = x.second;
            LinkReferences vis(*data.grammar, rule.params);
            rule.accept(vis);
        }
        // Check left recursion
        ret = true;
        for (auto& x: grammar) {
            const auto& name = x.first;
            auto& rule = x.second;
            DetectLeftRecursion vis(name);
            rule.accept(vis);
            if (vis.error_s) {
                if (log) {
                    auto line = line_info(s, vis.error_s);
                    log(line.first, line.second, "'" + name + "' is left recursive.");
                }
                ret = false;;
            }
        }
        if (!ret) {
            return nullptr;
        }
        // Set root definition
        start = data.start;
        // Automatic whitespace skipping
        if (grammar.count(WHITESPACE_DEFINITION_NAME)) {
            for (auto& x: grammar) {
                auto& rule = x.second;
                auto ope = rule.get_core_operator();
                if (IsLiteralToken::check(*ope)) {
                    rule <= tok(ope);
                }
            }
            auto& rule = (*data.grammar)[start];
            rule.whitespaceOpe = wsp((*data.grammar)[WHITESPACE_DEFINITION_NAME].get_core_operator());
        }
        // Word expression
        if (grammar.count(WORD_DEFINITION_NAME)) {
            auto& rule = (*data.grammar)[start];
            rule.wordOpe = (*data.grammar)[WORD_DEFINITION_NAME].get_core_operator();
        }
        return data.grammar;
    }
References peg::ParserGenerator::Data::duplicates, peg::ReferenceChecker::error_message, peg::DetectLeftRecursion::error_s, peg::ReferenceChecker::error_s, peg::ParserGenerator::Data::grammar, peg::line_info(), log, peg::ParserGenerator::Data::start, peg::tok(), peg::WHITESPACE_DEFINITION_NAME, peg::WORD_DEFINITION_NAME, and peg::wsp().
setup_actions()
void peg::ParserGenerator::setup_actions () [inline], [private]
                         {
        g["Definition"] = [&](const SemanticValues& sv, any& dt) {
            auto is_macro = sv.choice() == 0;
            auto ignore = sv[0].get<bool>();
            auto name = sv[1].get<std::string>();
            std::vector<std::string> params;
            std::shared_ptr<Ope> ope;
            if (is_macro) {
                params = sv[2].get<std::vector<std::string>>();
                ope = sv[4].get<std::shared_ptr<Ope>>();
            } else {
                ope = sv[3].get<std::shared_ptr<Ope>>();
            }
            Data& data = *dt.get<Data*>();
            auto& grammar = *data.grammar;
            if (!grammar.count(name)) {
                auto& rule = grammar[name];
                rule <= ope;
                rule.name = name;
                rule.ignoreSemanticValue = ignore;
                rule.is_macro = is_macro;
                rule.params = params;
                if (data.start.empty()) {
                    data.start = name;
                }
            } else {
                data.duplicates.emplace_back(name, sv.c_str());
            }
        };
        g["Expression"] = [&](const SemanticValues& sv) {
            if (sv.size() == 1) {
                return sv[0].get<std::shared_ptr<Ope>>();
            } else {
                std::vector<std::shared_ptr<Ope>> opes;
                for (auto i = 0u; i < sv.size(); i++) {
                    opes.emplace_back(sv[i].get<std::shared_ptr<Ope>>());
                }
                const std::shared_ptr<Ope> ope = std::make_shared<PrioritizedChoice>(opes);
                return ope;
            }
        };
        g["Sequence"] = [&](const SemanticValues& sv) {
            if (sv.size() == 1) {
                return sv[0].get<std::shared_ptr<Ope>>();
            } else {
                std::vector<std::shared_ptr<Ope>> opes;
                for (const auto& x: sv) {
                    opes.emplace_back(x.get<std::shared_ptr<Ope>>());
                }
                const std::shared_ptr<Ope> ope = std::make_shared<Sequence>(opes);
                return ope;
            }
        };
        g["Prefix"] = [&](const SemanticValues& sv) {
            std::shared_ptr<Ope> ope;
            if (sv.size() == 1) {
                ope = sv[0].get<std::shared_ptr<Ope>>();
            } else {
                assert(sv.size() == 2);
                auto tok = sv[0].get<char>();
                ope = sv[1].get<std::shared_ptr<Ope>>();
                if (tok == '&') {
                    ope = apd(ope);
                } else { // '!'
                    ope = npd(ope);
                }
            }
            return ope;
        };
        g["Suffix"] = [&](const SemanticValues& sv) {
            auto ope = sv[0].get<std::shared_ptr<Ope>>();
            if (sv.size() == 1) {
                return ope;
            } else {
                assert(sv.size() == 2);
                auto tok = sv[1].get<char>();
                if (tok == '?') {
                    return opt(ope);
                } else if (tok == '*') {
                    return zom(ope);
                } else { // '+'
                    return oom(ope);
                }
            }
        };
        g["Primary"] = [&](const SemanticValues& sv, any& dt) -> std::shared_ptr<Ope> {
            Data& data = *dt.get<Data*>();
            switch (sv.choice()) {
                case 0: // Macro Reference
                case 1: { // Reference
                    auto is_macro = sv.choice() == 0;
                    auto ignore = sv[0].get<bool>();
                    const auto& ident = sv[1].get<std::string>();
                    std::vector<std::shared_ptr<Ope>> args;
                    if (is_macro) {
                        args = sv[2].get<std::vector<std::shared_ptr<Ope>>>();
                    }
                    if (ignore) {
                        return ign(ref(*data.grammar, ident, sv.c_str(), is_macro, args));
                    } else {
                        return ref(*data.grammar, ident, sv.c_str(), is_macro, args);
                    }
                }
                case 2: { // (Expression)
                    return sv[0].get<std::shared_ptr<Ope>>();
                }
                case 3: { // TokenBoundary
                    return tok(sv[0].get<std::shared_ptr<Ope>>());
                }
                case 4: { // CaptureScope
                    return csc(sv[0].get<std::shared_ptr<Ope>>());
                }
                case 5: { // Capture
                    const auto& name = sv[0].get<std::string>();
                    auto ope = sv[1].get<std::shared_ptr<Ope>>();
                    return cap(ope, [name](const char* a_s, size_t a_n, Context& c) {
                        c.capture_scope_stack.back()[name] = std::string(a_s, a_n);
                    });
                }
                default: {
                    return sv[0].get<std::shared_ptr<Ope>>();
                }
            }
        };
        g["IdentCont"] = [](const SemanticValues& sv) {
            return std::string(sv.c_str(), sv.length());
        };
        g["IdentStart"] = [](const SemanticValues& /*sv*/) {
            return std::string();
        };
        g["IdentRest"] = [](const SemanticValues& /*sv*/) {
            return std::string();
        };
        g["LiteralI"] = [](const SemanticValues& sv) {
            const auto& tok = sv.tokens.front();
            return liti(resolve_escape_sequence(tok.first, tok.second));
        };
        g["Literal"] = [](const SemanticValues& sv) {
            const auto& tok = sv.tokens.front();
            return lit(resolve_escape_sequence(tok.first, tok.second));
        };
        g["Class"] = [](const SemanticValues& sv) {
            auto ranges = sv.transform<std::pair<char32_t, char32_t>>();
            return cls(ranges);
        };
        g["Range"] = [](const SemanticValues& sv) {
            switch (sv.choice()) {
                case 0: {
                    auto s1 = sv[0].get<std::string>();
                    auto s2 = sv[1].get<std::string>();
                    auto cp1 = decode_codepoint(s1.c_str(), s1.length());
                    auto cp2 = decode_codepoint(s2.c_str(), s2.length());
                    return std::make_pair(cp1, cp2);
                }
                case 1: {
                    auto s = sv[0].get<std::string>();
                    auto cp = decode_codepoint(s.c_str(), s.length());
                    return std::make_pair(cp, cp);
                }
            }
            return std::make_pair<char32_t, char32_t>(0, 0);
        };
        g["Char"] = [](const SemanticValues& sv) {
            return resolve_escape_sequence(sv.c_str(), sv.length());
        };
        g["AND"] = [](const SemanticValues& sv) { return *sv.c_str(); };
        g["NOT"] = [](const SemanticValues& sv) { return *sv.c_str(); };
        g["QUESTION"] = [](const SemanticValues& sv) { return *sv.c_str(); };
        g["STAR"] = [](const SemanticValues& sv) { return *sv.c_str(); };
        g["PLUS"] = [](const SemanticValues& sv) { return *sv.c_str(); };
        g["DOT"] = [](const SemanticValues& /*sv*/) { return dot(); };
        g["BeginCap"] = [](const SemanticValues& sv) { return sv.token(); };
        g["BackRef"] = [&](const SemanticValues& sv) {
            return bkr(sv.token());
        };
        g["Ignore"] = [](const SemanticValues& sv) { return sv.size() > 0; };
        g["Parameters"] = [](const SemanticValues& sv) {
            return sv.transform<std::string>();
        };
        g["Arguments"] = [](const SemanticValues& sv) {
            return sv.transform<std::shared_ptr<Ope>>();
        };
    }
References peg::apd(), peg::bkr(), peg::SemanticValues::c_str(), peg::cap(), peg::Context::capture_scope_stack, peg::SemanticValues::choice(), peg::cls(), peg::csc(), peg::decode_codepoint(), peg::dot(), peg::ParserGenerator::Data::duplicates, peg::ParserGenerator::Data::grammar, peg::ign(), peg::SemanticValues::length(), peg::lit(), peg::liti(), peg::npd(), peg::oom(), peg::opt(), peg::ref(), peg::resolve_escape_sequence(), peg::ParserGenerator::Data::start, peg::tok(), peg::SemanticValues::token(), peg::SemanticValues::tokens, peg::SemanticValues::transform(), and peg::zom().
Member Data Documentation
g
Grammar peg::ParserGenerator::g [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp