opendlv::proxy::GroundSpeedRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSpeedRequest ()=default
GroundSpeedRequest (const GroundSpeedRequest &)=default
GroundSpeedRequest & operator= (const GroundSpeedRequest &)=default
GroundSpeedRequest (GroundSpeedRequest &&)=default
GroundSpeedRequest & operator= (GroundSpeedRequest &&)=default
~GroundSpeedRequest ()=default
GroundSpeedRequest & groundSpeed (const float &v) noexcept
float groundSpeed () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundSpeed { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSpeedRequest`
static constexpr const char * TheLongName = `opendlv.proxy.GroundSpeedRequest`
Constructor & Destructor Documentation
GroundSpeedRequest() [1/3]
opendlv::proxy::GroundSpeedRequest::GroundSpeedRequest () [default]
GroundSpeedRequest() [2/3]
opendlv::proxy::GroundSpeedRequest::GroundSpeedRequest (const GroundSpeedRequest &) [default]
GroundSpeedRequest() [3/3]
opendlv::proxy::GroundSpeedRequest::GroundSpeedRequest (GroundSpeedRequest &&) [default]
 GroundSpeedRequest()
opendlv::proxy::GroundSpeedRequest::~GroundSpeedRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundSpeedRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundSpeedRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundSpeedRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, visitor);
            visitor.postVisit();
        }
References doVisit().
groundSpeed() [1/2]
float opendlv::proxy::GroundSpeedRequest::groundSpeed () const [inline], [noexcept]
                                                  {
            return m_groundSpeed;
        }
groundSpeed() [2/2]
GroundSpeedRequest & opendlv::proxy::GroundSpeedRequest::groundSpeed (const float & v) [inline], [noexcept]
                                                                        {
            m_groundSpeed = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::GroundSpeedRequest::ID () [inline], [static]
                                   {
            return 1091;
        }
LongName()
static const std::string opendlv::proxy::GroundSpeedRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSpeedRequest & opendlv::proxy::GroundSpeedRequest::operator= (const GroundSpeedRequest &) [default]
operator=() [2/2]
GroundSpeedRequest & opendlv::proxy::GroundSpeedRequest::operator= (GroundSpeedRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundSpeedRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundSpeed
float opendlv::proxy::GroundSpeedRequest::m_groundSpeed { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundSpeedRequest::TheLongName = `opendlv.proxy.GroundSpeedRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundSpeedRequest::TheShortName = `GroundSpeedRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp