opendlv::proxy::AltitudeReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AltitudeReading ()=default
AltitudeReading (const AltitudeReading &)=default
AltitudeReading & operator= (const AltitudeReading &)=default
AltitudeReading (AltitudeReading &&)=default
AltitudeReading & operator= (AltitudeReading &&)=default
~AltitudeReading ()=default
AltitudeReading & altitude (const float &v) noexcept
float altitude () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_altitude { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AltitudeReading`
static constexpr const char * TheLongName = `opendlv.proxy.AltitudeReading`
Constructor & Destructor Documentation
AltitudeReading() [1/3]
opendlv::proxy::AltitudeReading::AltitudeReading () [default]
AltitudeReading() [2/3]
opendlv::proxy::AltitudeReading::AltitudeReading (const AltitudeReading &) [default]
AltitudeReading() [3/3]
opendlv::proxy::AltitudeReading::AltitudeReading (AltitudeReading &&) [default]
 AltitudeReading()
opendlv::proxy::AltitudeReading::~AltitudeReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::AltitudeReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("altitude"s), m_altitude, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::AltitudeReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("altitude"s), m_altitude, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::AltitudeReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("altitude"s), m_altitude, visitor);
            visitor.postVisit();
        }
References doVisit().
altitude() [1/2]
float opendlv::proxy::AltitudeReading::altitude () const [inline], [noexcept]
                                               {
            return m_altitude;
        }
altitude() [2/2]
AltitudeReading & opendlv::proxy::AltitudeReading::altitude (const float & v) [inline], [noexcept]
                                                                  {
            m_altitude = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::AltitudeReading::ID () [inline], [static]
                                   {
            return 1033;
        }
LongName()
static const std::string opendlv::proxy::AltitudeReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AltitudeReading & opendlv::proxy::AltitudeReading::operator= (AltitudeReading &&) [default]
operator=() [2/2]
AltitudeReading & opendlv::proxy::AltitudeReading::operator= (const AltitudeReading &) [default]
ShortName()
static const std::string opendlv::proxy::AltitudeReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_altitude
float opendlv::proxy::AltitudeReading::m_altitude { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::AltitudeReading::TheLongName = `opendlv.proxy.AltitudeReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::AltitudeReading::TheShortName = `AltitudeReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp