cluon::data::RecorderCommand Class Reference
#include <cluon-complete.hpp>
Public Member Functions
RecorderCommand ()=default
RecorderCommand (const RecorderCommand &)=default
RecorderCommand & operator= (const RecorderCommand &)=default
RecorderCommand (RecorderCommand &&)=default
RecorderCommand & operator= (RecorderCommand &&)=default
~RecorderCommand ()=default
RecorderCommand & command (const uint8_t &v) noexcept
uint8_t command () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint8_t m_command { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `RecorderCommand`
static constexpr const char * TheLongName = `cluon.data.RecorderCommand`
Constructor & Destructor Documentation
RecorderCommand() [1/3]
cluon::data::RecorderCommand::RecorderCommand () [default]
RecorderCommand() [2/3]
cluon::data::RecorderCommand::RecorderCommand (const RecorderCommand &) [default]
RecorderCommand() [3/3]
cluon::data::RecorderCommand::RecorderCommand (RecorderCommand &&) [default]
 RecorderCommand()
cluon::data::RecorderCommand::~RecorderCommand () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::data::RecorderCommand::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void cluon::data::RecorderCommand::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, visitor);
                return;
            }
            
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void cluon::data::RecorderCommand::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, visitor);
            
            visitor.postVisit();
        }
References doVisit().
command() [1/2]
uint8_t cluon::data::RecorderCommand::command () const [inline], [noexcept]
                                                {
            return m_command;
        }
command() [2/2]
RecorderCommand & cluon::data::RecorderCommand::command (const uint8_t & v) [inline], [noexcept]
                                                                   {
            m_command = v;
            return *this;
        }
ID()
static int32_t cluon::data::RecorderCommand::ID () [inline], [static]
                                   {
            return 11;
        }
LongName()
static const std::string cluon::data::RecorderCommand::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
RecorderCommand & cluon::data::RecorderCommand::operator= (const RecorderCommand &) [default]
operator=() [2/2]
RecorderCommand & cluon::data::RecorderCommand::operator= (RecorderCommand &&) [default]
ShortName()
static const std::string cluon::data::RecorderCommand::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_command
uint8_t cluon::data::RecorderCommand::m_command { 0 } [private]
TheLongName
constexpr const char* cluon::data::RecorderCommand::TheLongName = `cluon.data.RecorderCommand` [static], [constexpr], [private]
TheShortName
constexpr const char* cluon::data::RecorderCommand::TheShortName = `RecorderCommand` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp