peg::Holder Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Holder (Definition *outer)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
any reduce (SemanticValues &sv, any &dt) const
Public Attributes
std::shared_ptr< Ope > ope_
Definition * outer_
Friends
class Definition
Constructor & Destructor Documentation
Holder()
peg::Holder::Holder (Definition * outer) [inline]
       : outer_(outer) {}
Member Function Documentation
accept()
void peg::Holder::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::Holder::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
    if (!ope_) {
        throw std::logic_error("Uninitialized definition ope was used...");
    }
    c.trace(outer_->name.c_str(), s, n, sv, dt);
    c.nest_level++;
    auto se = make_scope_exit([&]() {
        c.nest_level--;
    });
    // Macro reference
    // TODO: need packrat support
    if (outer_->is_macro) {
        return ope_->parse(s, n, sv, c, dt);
    }
    size_t len;
    any val;
    c.packrat(s, outer_->id, len, val, [&](any& a_val) {
        if (outer_->enter) {
            outer_->enter(s, n, dt);
        }
        auto se2 = make_scope_exit([&]() {
            c.pop();
            if (outer_->leave) {
                outer_->leave(s, n, len, a_val, dt);
            }
        });
        auto& chldsv = c.push();
        len = ope_->parse(s, n, chldsv, c, dt);
        // Invoke action
        if (success(len)) {
            chldsv.s_ = s;
            chldsv.n_ = len;
            chldsv.name_ = outer_->name;
            if (!IsPrioritizedChoice::check(*ope_)) {
                chldsv.choice_count_ = 0;
                chldsv.choice_ = 0;
            }
            try {
                a_val = reduce(chldsv, dt);
            } catch (const parse_error& e) {
                if (e.what()) {
                    if (c.message_pos < s) {
                        c.message_pos = s;
                        c.message = e.what();
                    }
                }
                len = static_cast<size_t>(-1);
            }
        }
    });
    if (success(len)) {
        if (!outer_->ignoreSemanticValue) {
            sv.emplace_back(val);
            sv.tags.emplace_back(str2tag(outer_->name.c_str()));
        }
    } else {
        if (outer_->error_message) {
            if (c.message_pos < s) {
                c.message_pos = s;
                c.message = outer_->error_message();
            }
        }
    }
    return len;
}
References peg::make_scope_exit(), peg::Context::message, peg::Context::message_pos, peg::Context::nest_level, peg::Context::packrat(), peg::Context::pop(), peg::Context::push(), peg::SemanticValues::s_, peg::success(), peg::Context::trace(), and peg::parse_error::what().
reduce()
any peg::Holder::reduce (SemanticValues & sv, any & dt) const [inline]
                                                           {
    if (outer_->action) {
        return outer_->action(sv, dt);
    } else if (sv.empty()) {
        return any();
    } else {
        return std::move(sv.front());
    }
}
Friends And Related Function Documentation
Definition
friend class Definition [friend]
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::Holder::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
outer_
Definition* peg::Holder::outer_
Referenced by peg::AssignIDToDefinition::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp