opendlv::body::SensorInfo Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
SensorInfo ()=default
SensorInfo (const SensorInfo &)=default
SensorInfo & operator= (const SensorInfo &)=default
SensorInfo (SensorInfo &&)=default
SensorInfo & operator= (SensorInfo &&)=default
~SensorInfo ()=default
SensorInfo & description (const std::string &v) noexcept
std::string description () const noexcept
SensorInfo & x (const float &v) noexcept
float x () const noexcept
SensorInfo & y (const float &v) noexcept
float y () const noexcept
SensorInfo & z (const float &v) noexcept
float z () const noexcept
SensorInfo & signalId (const uint32_t &v) noexcept
uint32_t signalId () const noexcept
SensorInfo & accuracyStd (const float &v) noexcept
float accuracyStd () const noexcept
SensorInfo & minFrequency (const uint16_t &v) noexcept
uint16_t minFrequency () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_description { ``s }
float m_x { 0.0f }
float m_y { 0.0f }
float m_z { 0.0f }
uint32_t m_signalId { 0 }
float m_accuracyStd { 0.0f }
uint16_t m_minFrequency { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `SensorInfo`
static constexpr const char * TheLongName = `opendlv.body.SensorInfo`
Constructor & Destructor Documentation
SensorInfo() [1/3]
opendlv::body::SensorInfo::SensorInfo () [default]
SensorInfo() [2/3]
opendlv::body::SensorInfo::SensorInfo (const SensorInfo &) [default]
SensorInfo() [3/3]
opendlv::body::SensorInfo::SensorInfo (SensorInfo &&) [default]
 SensorInfo()
opendlv::body::SensorInfo::~SensorInfo () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::body::SensorInfo::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("x"s), m_x, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("y"s), m_y, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("z"s), m_z, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, preVisit, visit, postVisit);
            doTripletForwardVisit(6, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, preVisit, visit, postVisit);
            doTripletForwardVisit(7, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::body::SensorInfo::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
                return;
            }
            if (6 == fieldId) {
                doVisit(6, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, visitor);
                return;
            }
            if (7 == fieldId) {
                doVisit(7, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::body::SensorInfo::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
            doVisit(2, std::move("float"s), std::move("x"s), m_x, visitor);
            doVisit(3, std::move("float"s), std::move("y"s), m_y, visitor);
            doVisit(4, std::move("float"s), std::move("z"s), m_z, visitor);
            doVisit(5, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
            doVisit(6, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, visitor);
            doVisit(7, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, visitor);
            visitor.postVisit();
        }
References doVisit().
accuracyStd() [1/2]
float opendlv::body::SensorInfo::accuracyStd () const [inline], [noexcept]
                                                  {
            return m_accuracyStd;
        }
accuracyStd() [2/2]
SensorInfo & opendlv::body::SensorInfo::accuracyStd (const float & v) [inline], [noexcept]
                                                                {
            m_accuracyStd = v;
            return *this;
        }
description() [1/2]
std::string opendlv::body::SensorInfo::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
SensorInfo & opendlv::body::SensorInfo::description (const std::string & v) [inline], [noexcept]
                                                                    {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::body::SensorInfo::ID () [inline], [static]
                                   {
            return 1023;
        }
LongName()
static const std::string opendlv::body::SensorInfo::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
minFrequency() [1/2]
uint16_t opendlv::body::SensorInfo::minFrequency () const [inline], [noexcept]
                                                      {
            return m_minFrequency;
        }
minFrequency() [2/2]
SensorInfo & opendlv::body::SensorInfo::minFrequency (const uint16_t & v) [inline], [noexcept]
                                                                    {
            m_minFrequency = v;
            return *this;
        }
operator=() [1/2]
SensorInfo & opendlv::body::SensorInfo::operator= (const SensorInfo &) [default]
operator=() [2/2]
SensorInfo & opendlv::body::SensorInfo::operator= (SensorInfo &&) [default]
ShortName()
static const std::string opendlv::body::SensorInfo::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
signalId() [1/2]
uint32_t opendlv::body::SensorInfo::signalId () const [inline], [noexcept]
                                                  {
            return m_signalId;
        }
signalId() [2/2]
SensorInfo & opendlv::body::SensorInfo::signalId (const uint32_t & v) [inline], [noexcept]
                                                                {
            m_signalId = v;
            return *this;
        }
x() [1/2]
float opendlv::body::SensorInfo::x () const [inline], [noexcept]
                                        {
            return m_x;
        }
x() [2/2]
SensorInfo & opendlv::body::SensorInfo::x (const float & v) [inline], [noexcept]
                                                      {
            m_x = v;
            return *this;
        }
y() [1/2]
float opendlv::body::SensorInfo::y () const [inline], [noexcept]
                                        {
            return m_y;
        }
y() [2/2]
SensorInfo & opendlv::body::SensorInfo::y (const float & v) [inline], [noexcept]
                                                      {
            m_y = v;
            return *this;
        }
z() [1/2]
float opendlv::body::SensorInfo::z () const [inline], [noexcept]
                                        {
            return m_z;
        }
z() [2/2]
SensorInfo & opendlv::body::SensorInfo::z (const float & v) [inline], [noexcept]
                                                      {
            m_z = v;
            return *this;
        }
Member Data Documentation
m_accuracyStd
float opendlv::body::SensorInfo::m_accuracyStd { 0.0f } [private]
m_description
std::string opendlv::body::SensorInfo::m_description { ``s } [private]
m_minFrequency
uint16_t opendlv::body::SensorInfo::m_minFrequency { 0 } [private]
m_signalId
uint32_t opendlv::body::SensorInfo::m_signalId { 0 } [private]
m_x
float opendlv::body::SensorInfo::m_x { 0.0f } [private]
m_y
float opendlv::body::SensorInfo::m_y { 0.0f } [private]
m_z
float opendlv::body::SensorInfo::m_z { 0.0f } [private]
TheLongName
constexpr const char* opendlv::body::SensorInfo::TheLongName = `opendlv.body.SensorInfo` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::body::SensorInfo::TheShortName = `SensorInfo` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp