peg::Definition Class Reference
#include <cluon-complete.hpp>
Classes
struct Result
Public Member Functions
Definition ()
Definition (const Definition &rhs)
Definition (Definition &&rhs)
Definition (const std::shared_ptr< Ope > &ope)
operator std::shared_ptr< Ope > ()
Definition & operator<= (const std::shared_ptr< Ope > &ope)
Result parse (const char *s, size_t n, const char *path=nullptr) const
Result parse (const char *s, const char *path=nullptr) const
Result parse (const char *s, size_t n, any &dt, const char *path=nullptr) const
Result parse (const char *s, any &dt, const char *path=nullptr) const
template<typename T >
Result parse_and_get_value (const char *s, size_t n, T &val, const char *path=nullptr) const
template<typename T >
Result parse_and_get_value (const char *s, T &val, const char *path=nullptr) const
template<typename T >
Result parse_and_get_value (const char *s, size_t n, any &dt, T &val, const char *path=nullptr) const
template<typename T >
Result parse_and_get_value (const char *s, any &dt, T &val, const char *path=nullptr) const
Action operator= (Action a)
template<typename T >
Definition & operator, (T fn)
Definition & operator~ ()
void accept (Ope::Visitor &v)
std::shared_ptr< Ope > get_core_operator () const
bool is_token () const
Public Attributes
std::string name
size_t id
Action action
std::function< void(const char *s, size_t n, any &dt)> enter
std::function< void(const char *s, size_t n, size_t matchlen, any &value, any &dt)> leave
std::function< std::string()> error_message
bool ignoreSemanticValue
std::shared_ptr< Ope > whitespaceOpe
std::shared_ptr< Ope > wordOpe
bool enablePackratParsing
bool is_macro
std::vector< std::string > params
Tracer tracer
Private Member Functions
Definition & operator= (const Definition &rhs)
Definition & operator= (Definition &&rhs)
Result parse_core (const char *s, size_t n, SemanticValues &sv, any &dt, const char *path) const
Private Attributes
std::shared_ptr< Holder > holder_
std::once_flag is_token_init_
bool is_token_
Friends
class Reference
Constructor & Destructor Documentation
Definition() [1/4]
peg::Definition::Definition () [inline]
        : ignoreSemanticValue(false)
        , enablePackratParsing(false)
        , is_macro(false)
        , holder_(std::make_shared<Holder>(this))
        , is_token_(false) {}
Definition() [2/4]
peg::Definition::Definition (const Definition & rhs) [inline]
        : name(rhs.name)
        , ignoreSemanticValue(false)
        , enablePackratParsing(false)
        , is_macro(false)
        , holder_(rhs.holder_)
        , is_token_(false)
    {
        holder_->outer_ = this;
    }
Definition() [3/4]
peg::Definition::Definition (Definition && rhs) [inline]
        : name(std::move(rhs.name))
        , ignoreSemanticValue(rhs.ignoreSemanticValue)
        , whitespaceOpe(rhs.whitespaceOpe)
        , wordOpe(rhs.wordOpe)
        , enablePackratParsing(rhs.enablePackratParsing)
        , is_macro(rhs.is_macro)
        , holder_(std::move(rhs.holder_))
        , is_token_(rhs.is_token_)
    {
        holder_->outer_ = this;
    }
Definition() [4/4]
peg::Definition::Definition (const std::shared_ptr< Ope > & ope) [inline]
        : ignoreSemanticValue(false)
        , enablePackratParsing(false)
        , is_macro(false)
        , holder_(std::make_shared<Holder>(this))
        , is_token_(false)
    {
        *this <= ope;
    }
Member Function Documentation
accept()
void peg::Definition::accept (Ope::Visitor & v) [inline]
                               {
        holder_->accept(v);
    }
Referenced by peg::AssignIDToDefinition::visit(), peg::TokenChecker::visit(), and peg::DetectLeftRecursion::visit().
get_core_operator()
std::shared_ptr< Ope > peg::Definition::get_core_operator () const [inline]
                                                 {
        return holder_->ope_;
    }
is_token()
bool peg::Definition::is_token () const [inline]
                          {
        std::call_once(is_token_init_, [this]() {
            is_token_ = TokenChecker::is_token(*get_core_operator());
        });
        return is_token_;
    }
operator std::shared_ptr< Ope >()
peg::Definition::operator std::shared_ptr< Ope > () [inline]
                                  {
        return std::make_shared<WeakHolder>(holder_);
    }
operator,()
template<typename T >
Definition & peg::Definition::operator, (T fn) [inline]
                                {
        operator=(fn);
        return *this;
    }
operator<=()
Definition & peg::Definition::operator<= (const std::shared_ptr< Ope > & ope) [inline]
                                                          {
        holder_->ope_ = ope;
        return *this;
    }
operator=() [1/3]
Action peg::Definition::operator= (Action a) [inline]
                               {
        action = a;
        return a;
    }
operator=() [2/3]
Definition & peg::Definition::operator= (const Definition & rhs) [private]
operator=() [3/3]
Definition & peg::Definition::operator= (Definition && rhs) [private]
operator ()
Definition & peg::Definition::operator~ () [inline]
                            {
        ignoreSemanticValue = true;
        return *this;
    }
parse() [1/4]
Result peg::Definition::parse (const char * s, any & dt, const char * path = nullptr) const [inline]
                                                                           {
        auto n = strlen(s);
        return parse(s, n, dt, path);
    }
parse() [2/4]
Result peg::Definition::parse (const char * s, const char * path = nullptr) const [inline]
                                                                  {
        auto n = strlen(s);
        return parse(s, n, path);
    }
parse() [3/4]
Result peg::Definition::parse (const char * s, size_t n, any & dt, const char * path = nullptr) const [inline]
                                                                                     {
        SemanticValues sv;
        return parse_core(s, n, sv, dt, path);
    }
parse() [4/4]
Result peg::Definition::parse (const char * s, size_t n, const char * path = nullptr) const [inline]
                                                                            {
        SemanticValues sv;
        any dt;
        return parse_core(s, n, sv, dt, path);
    }
parse_and_get_value() [1/4]
template<typename T >
Result peg::Definition::parse_and_get_value (const char * s, any & dt, T & val, const char * path = nullptr) const [inline]
                                                                                                 {
        auto n = strlen(s);
        return parse_and_get_value(s, n, dt, val, path);
    }
parse_and_get_value() [2/4]
template<typename T >
Result peg::Definition::parse_and_get_value (const char * s, size_t n, any & dt, T & val, const char * path = nullptr) const [inline]
                                                                                                           {
        SemanticValues sv;
        auto r = parse_core(s, n, sv, dt, path);
        if (r.ret && !sv.empty() && !sv.front().is_undefined()) {
            val = sv[0].get<T>();
        }
        return r;
    }
parse_and_get_value() [3/4]
template<typename T >
Result peg::Definition::parse_and_get_value (const char * s, size_t n, T & val, const char * path = nullptr) const [inline]
                                                                                                  {
        SemanticValues sv;
        any dt;
        auto r = parse_core(s, n, sv, dt, path);
        if (r.ret && !sv.empty() && !sv.front().is_undefined()) {
            val = sv[0].get<T>();
        }
        return r;
    }
parse_and_get_value() [4/4]
template<typename T >
Result peg::Definition::parse_and_get_value (const char * s, T & val, const char * path = nullptr) const [inline]
                                                                                        {
        auto n = strlen(s);
        return parse_and_get_value(s, n, val, path);
    }
parse_core()
Result peg::Definition::parse_core (const char * s, size_t n, SemanticValues & sv, any & dt, const char * path) const [inline], [private]
                                                                                                    {
        std::shared_ptr<Ope> ope = holder_;
        AssignIDToDefinition vis;
        holder_->accept(vis);
        if (whitespaceOpe) {
            ope = std::make_shared<Sequence>(whitespaceOpe, ope);
            whitespaceOpe->accept(vis);
        }
        if (wordOpe) {
            wordOpe->accept(vis);
        }
        Context cxt(path, s, n, vis.ids.size(), whitespaceOpe, wordOpe, enablePackratParsing, tracer);
        auto len = ope->parse(s, n, sv, cxt, dt);
        return Result{ success(len), len, cxt.error_pos, cxt.message_pos, cxt.message };
    }
References peg::Context::error_pos, peg::AssignIDToDefinition::ids, peg::Context::message, peg::Context::message_pos, and peg::success().
Friends And Related Function Documentation
Reference
friend class Reference [friend]
Member Data Documentation
action
Action peg::Definition::action
enablePackratParsing
bool peg::Definition::enablePackratParsing
enter
std::function<void (const char* s, size_t n, any& dt)> peg::Definition::enter
error_message
std::function<std::string ()> peg::Definition::error_message
holder_
std::shared_ptr<Holder> peg::Definition::holder_ [private]
id
size_t peg::Definition::id
Referenced by peg::AssignIDToDefinition::visit().
ignoreSemanticValue
bool peg::Definition::ignoreSemanticValue
is_macro
bool peg::Definition::is_macro
is_token_
bool peg::Definition::is_token_ [mutable], [private]
is_token_init_
std::once_flag peg::Definition::is_token_init_ [mutable], [private]
leave
std::function<void (const char* s, size_t n, size_t matchlen, any& value, any& dt)> peg::Definition::leave
name
std::string peg::Definition::name
params
std::vector<std::string> peg::Definition::params
tracer
Tracer peg::Definition::tracer
whitespaceOpe
std::shared_ptr<Ope> peg::Definition::whitespaceOpe
wordOpe
std::shared_ptr<Ope> peg::Definition::wordOpe
The documentation for this class was generated from the following file:
src/cluon-complete.hpp