opendlv::sim::Frame Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
Frame ()=default
Frame (const Frame &)=default
Frame & operator= (const Frame &)=default
Frame (Frame &&)=default
Frame & operator= (Frame &&)=default
~Frame ()=default
Frame & x (const float &v) noexcept
float x () const noexcept
Frame & y (const float &v) noexcept
float y () const noexcept
Frame & z (const float &v) noexcept
float z () const noexcept
Frame & roll (const float &v) noexcept
float roll () const noexcept
Frame & pitch (const float &v) noexcept
float pitch () const noexcept
Frame & yaw (const float &v) noexcept
float yaw () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_x { 0.0f }
float m_y { 0.0f }
float m_z { 0.0f }
float m_roll { 0.0f }
float m_pitch { 0.0f }
float m_yaw { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `Frame`
static constexpr const char * TheLongName = `opendlv.sim.Frame`
Constructor & Destructor Documentation
Frame() [1/3]
opendlv::sim::Frame::Frame () [default]
Frame() [2/3]
opendlv::sim::Frame::Frame (const Frame &) [default]
Frame() [3/3]
opendlv::sim::Frame::Frame (Frame &&) [default]
 Frame()
opendlv::sim::Frame::~Frame () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::sim::Frame::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("x"s), m_x, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("y"s), m_y, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("z"s), m_z, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("float"s), std::move("roll"s), m_roll, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("float"s), std::move("pitch"s), m_pitch, preVisit, visit, postVisit);
            doTripletForwardVisit(6, std::move("float"s), std::move("yaw"s), m_yaw, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::sim::Frame::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("x"s), m_x, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("y"s), m_y, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("z"s), m_z, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("float"s), std::move("roll"s), m_roll, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("float"s), std::move("pitch"s), m_pitch, visitor);
                return;
            }
            if (6 == fieldId) {
                doVisit(6, std::move("float"s), std::move("yaw"s), m_yaw, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::sim::Frame::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("x"s), m_x, visitor);
            doVisit(2, std::move("float"s), std::move("y"s), m_y, visitor);
            doVisit(3, std::move("float"s), std::move("z"s), m_z, visitor);
            doVisit(4, std::move("float"s), std::move("roll"s), m_roll, visitor);
            doVisit(5, std::move("float"s), std::move("pitch"s), m_pitch, visitor);
            doVisit(6, std::move("float"s), std::move("yaw"s), m_yaw, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::sim::Frame::ID () [inline], [static]
                                   {
            return 1001;
        }
LongName()
static const std::string opendlv::sim::Frame::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
Frame & opendlv::sim::Frame::operator= (const Frame &) [default]
operator=() [2/2]
Frame & opendlv::sim::Frame::operator= (Frame &&) [default]
pitch() [1/2]
float opendlv::sim::Frame::pitch () const [inline], [noexcept]
                                            {
            return m_pitch;
        }
pitch() [2/2]
Frame & opendlv::sim::Frame::pitch (const float & v) [inline], [noexcept]
                                                     {
            m_pitch = v;
            return *this;
        }
roll() [1/2]
float opendlv::sim::Frame::roll () const [inline], [noexcept]
                                           {
            return m_roll;
        }
roll() [2/2]
Frame & opendlv::sim::Frame::roll (const float & v) [inline], [noexcept]
                                                    {
            m_roll = v;
            return *this;
        }
ShortName()
static const std::string opendlv::sim::Frame::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
x() [1/2]
float opendlv::sim::Frame::x () const [inline], [noexcept]
                                        {
            return m_x;
        }
x() [2/2]
Frame & opendlv::sim::Frame::x (const float & v) [inline], [noexcept]
                                                 {
            m_x = v;
            return *this;
        }
y() [1/2]
float opendlv::sim::Frame::y () const [inline], [noexcept]
                                        {
            return m_y;
        }
y() [2/2]
Frame & opendlv::sim::Frame::y (const float & v) [inline], [noexcept]
                                                 {
            m_y = v;
            return *this;
        }
yaw() [1/2]
float opendlv::sim::Frame::yaw () const [inline], [noexcept]
                                          {
            return m_yaw;
        }
yaw() [2/2]
Frame & opendlv::sim::Frame::yaw (const float & v) [inline], [noexcept]
                                                   {
            m_yaw = v;
            return *this;
        }
z() [1/2]
float opendlv::sim::Frame::z () const [inline], [noexcept]
                                        {
            return m_z;
        }
z() [2/2]
Frame & opendlv::sim::Frame::z (const float & v) [inline], [noexcept]
                                                 {
            m_z = v;
            return *this;
        }
Member Data Documentation
m_pitch
float opendlv::sim::Frame::m_pitch { 0.0f } [private]
m_roll
float opendlv::sim::Frame::m_roll { 0.0f } [private]
m_x
float opendlv::sim::Frame::m_x { 0.0f } [private]
m_y
float opendlv::sim::Frame::m_y { 0.0f } [private]
m_yaw
float opendlv::sim::Frame::m_yaw { 0.0f } [private]
m_z
float opendlv::sim::Frame::m_z { 0.0f } [private]
TheLongName
constexpr const char* opendlv::sim::Frame::TheLongName = `opendlv.sim.Frame` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::sim::Frame::TheShortName = `Frame` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp