opendlv::logic::perception::Object Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
Object ()=default
Object (const Object &)=default
Object & operator= (const Object &)=default
Object (Object &&)=default
Object & operator= (Object &&)=default
~Object ()=default
Object & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `Object`
static constexpr const char * TheLongName = `opendlv.logic.perception.Object`
Constructor & Destructor Documentation
Object() [1/3]
opendlv::logic::perception::Object::Object () [default]
Object() [2/3]
opendlv::logic::perception::Object::Object (const Object &) [default]
Object() [3/3]
opendlv::logic::perception::Object::Object (Object &&) [default]
 Object()
opendlv::logic::perception::Object::~Object () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::Object::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::Object::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::Object::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::Object::ID () [inline], [static]
                                   {
            return 1130;
        }
LongName()
static const std::string opendlv::logic::perception::Object::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::Object::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
Object & opendlv::logic::perception::Object::objectId (const uint32_t & v) [inline], [noexcept]
                                                            {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
Object & opendlv::logic::perception::Object::operator= (const Object &) [default]
operator=() [2/2]
Object & opendlv::logic::perception::Object::operator= (Object &&) [default]
ShortName()
static const std::string opendlv::logic::perception::Object::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_objectId
uint32_t opendlv::logic::perception::Object::m_objectId { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::Object::TheLongName = `opendlv.logic.perception.Object` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::Object::TheShortName = `Object` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp