cluon::OD4Session Class Reference
#include <cluon-complete.hpp>
Public Member Functions
OD4Session (uint16_t CID, std::function< void(cluon::data::Envelope &&envelope)> delegate=nullptr) noexcept
void send (cluon::data::Envelope &&envelope) noexcept
bool dataTrigger (int32_t messageIdentifier, std::function< void(cluon::data::Envelope &&envelope)> delegate) noexcept
void timeTrigger (float freq, std::function< bool()> delegate) noexcept
template<typename T >
void send (T &message, const cluon::data::TimeStamp &sampleTimeStamp=cluon::data::TimeStamp(), uint32_t senderStamp=0) noexcept
bool isRunning () noexcept
Private Member Functions
OD4Session (const OD4Session &)=delete
OD4Session (OD4Session &&)=delete
OD4Session & operator= (const OD4Session &)=delete
OD4Session & operator= (OD4Session &&)=delete
void callback (std::string &&data, std::string &&from, std::chrono::system_clock::time_point &&timepoint) noexcept
void sendInternal (std::string &&dataToSend) noexcept
Private Attributes
std::unique_ptr< cluon::UDPReceiver > m_receiver
cluon::UDPSender m_sender
std::mutex m_senderMutex {}
std::function< void(cluon::data::Envelope &&envelope)> m_delegate {nullptr}
std::mutex m_mapOfDataTriggeredDelegatesMutex {}
std::unordered_map< int32_t, std::function< void(cluon::data::Envelope &&envelope)>, UseUInt32ValueAsHashKey > m_mapOfDataTriggeredDelegates {}
Detailed Description
This class provides an interface to an OpenDaVINCI v4 session. An OpenDaVINCI v4 session allows the automatic exchange of time-stamped Envelopes carrying user-defined messages usually using UDP multicast. A running OD4Session will not receive the bytes that itself has sent to other microservices.
There are two ways to participate in an OpenDaVINCI session. Variant A is simply calling a user-supplied lambda whenever a new Envelope is received:
cluon::OD4Session od4{111, [](cluon::data::Envelope &&envelope){ std::cout << "Received cluon::Envelope" << std::endl;}
};
// Do something in parallel.
MyMessage msg;
od4.send(msg);
Variant B allows a more fine-grained setup where you specify the Envelopes of interest:
cluon::OD4Session od4{111};
od4.dataTrigger(cluon::data::TimeStamp::ID(), [](cluon::data::Envelope &&envelope){ std::cout << "Received cluon::data::TimeStamp" << std::endl;});
od4.dataTrigger(MyMessage::ID(), [](cluon::data::Envelope &&envelope){ std::cout << "Received MyMessage" << std::endl;});
// Do something in parallel.
MyMessage msg;
od4.send(msg);
Next to receive Envelopes, OD4Session can call a user-supplied lambda in a time-triggered way. The lambda is executed as long as it does not return false or throws an exception that is then caught in the method timeTrigger and the method is exited:
cluon::OD4Session od4{111};
const float FREQ{10}; // 10 Hz.
od4.timeTrigger(FREQ, [](){
  // Do something time-triggered.
  return false;
}); // This call blocks until the lambda returns false.
Constructor & Destructor Documentation
OD4Session() [1/3]
cluon::OD4Session::OD4Session (const OD4Session &) [private], [delete]
OD4Session() [2/3]
cluon::OD4Session::OD4Session (OD4Session &&) [private], [delete]
OD4Session() [3/3]
cluon::OD4Session::OD4Session (uint16_t CID, std::function< void(cluon::data::Envelope &&envelope)> delegate = nullptr) [inline], [noexcept]
Constructor.
Parameters
CID OpenDaVINCI v4 session identifier [1 .. 254]
delegate Function to call on newly arriving Envelopes (`catch-all`); if a nullptr is passed, the method dataTrigger can be used to set message specific delegates. Please note that it is NOT possible to have both: a delegate for `catch-all` and the data-triggered ones.
    : m_receiver{nullptr}
    , m_sender{"225.0.0." + std::to_string(CID), 12175}
    , m_delegate(std::move(delegate))
    , m_mapOfDataTriggeredDelegatesMutex{}
    , m_mapOfDataTriggeredDelegates{} {
    m_receiver = std::make_unique<cluon::UDPReceiver>(
        "225.0.0." + std::to_string(CID),
        12175,
        [this](std::string &&data, std::string &&from, std::chrono::system_clock::time_point &&timepoint) {
            this->callback(std::move(data), std::move(from), std::move(timepoint));
        },
        m_sender.getSendFromPort() /* passing our local send from port to the UDPReceiver to filter out our own bytes */);
}
Member Function Documentation
callback()
void cluon::OD4Session::callback (std::string && data, std::string && from, std::chrono::system_clock::time_point && timepoint) [inline], [private], [noexcept]
                                                                                                                       {
    size_t numberOfDataTriggeredDelegates{0};
    {
        try {
            std::lock_guard<std::mutex> lck{m_mapOfDataTriggeredDelegatesMutex};
            numberOfDataTriggeredDelegates = m_mapOfDataTriggeredDelegates.size();
        } catch (...) {} // LCOV_EXCL_LINE
    }
    // Only unpack the envelope when it needs to be post-processed.
    if ((nullptr != m_delegate) || (0 < numberOfDataTriggeredDelegates)) {
        std::stringstream sstr(data);
        auto retVal = extractEnvelope(sstr);
        if (retVal.first) {
            cluon::data::Envelope env{retVal.second};
            env.received(cluon::time::convert(timepoint));
            // "Catch all"-delegate.
            if (nullptr != m_delegate) {
                m_delegate(std::move(env));
            } else {
                try {
                    // Data triggered-delegates.
                    std::lock_guard<std::mutex> lck{m_mapOfDataTriggeredDelegatesMutex};
                    if (m_mapOfDataTriggeredDelegates.count(env.dataType()) > 0) {
                        m_mapOfDataTriggeredDelegates[env.dataType()](std::move(env));
                    }
                } catch (...) {} // LCOV_EXCL_LINE
            }
        }
    }
}
References cluon::time::convert(), cluon::extractEnvelope(), and retVal.
dataTrigger()
bool cluon::OD4Session::dataTrigger (int32_t messageIdentifier, std::function< void(cluon::data::Envelope &&envelope)> delegate) [inline], [noexcept]
This method sets a delegate to be called data-triggered on arrival of a new Envelope for a given message identifier.
Parameters
messageIdentifier Message identifier to assign a delegate.
delegate Function to call on newly arriving Envelopes; setting it to nullptr will erase it.
Returns
true if the given delegate could be successfully set or unset.
                                                                                                                                {
    bool retVal{false};
    if (nullptr == m_delegate) {
        try {
            std::lock_guard<std::mutex> lck{m_mapOfDataTriggeredDelegatesMutex};
            if ((nullptr == delegate) && (m_mapOfDataTriggeredDelegates.count(messageIdentifier) > 0)) {
                auto element = m_mapOfDataTriggeredDelegates.find(messageIdentifier);
                if (element != m_mapOfDataTriggeredDelegates.end()) {
                    m_mapOfDataTriggeredDelegates.erase(element);
                }
            } else {
                m_mapOfDataTriggeredDelegates[messageIdentifier] = delegate;
            }
            retVal = true;
        } catch (...) {} // LCOV_EXCL_LINE
    }
    return retVal;
}
References retVal.
isRunning()
bool cluon::OD4Session::isRunning () [inline], [noexcept]
                                           {
    return m_receiver->isRunning();
}
References m_receiver.
operator=() [1/2]
OD4Session & cluon::OD4Session::operator= (const OD4Session &) [private], [delete]
operator=() [2/2]
OD4Session & cluon::OD4Session::operator= (OD4Session &&) [private], [delete]
send() [1/2]
void cluon::OD4Session::send (cluon::data::Envelope && envelope) [inline], [noexcept]
This method will send a given Envelope to this OpenDaVINCI v4 session.
Parameters
envelope to be sent.
                                                                  {
    sendInternal(cluon::serializeEnvelope(std::move(envelope)));
}
References cluon::serializeEnvelope().
send() [2/2]
template<typename T >
void cluon::OD4Session::send (T & message, const cluon::data::TimeStamp & sampleTimeStamp = cluon::data::TimeStamp(), uint32_t senderStamp = 0) [inline], [noexcept]
This method will send a given message to this OpenDaVINCI v4 session.
Parameters
message Message to be sent.
sampleTimeStamp Time point when this sample to be sent was captured (default = sent time point).
senderStamp Optional sender stamp (default = 0).
                                                                                                                               {
        try {
            std::lock_guard<std::mutex> lck(m_senderMutex);
            cluon::ToProtoVisitor protoEncoder;
            cluon::data::Envelope envelope;
            {
                envelope.dataType(static_cast<int32_t>(message.ID()));
                message.accept(protoEncoder);
                envelope.serializedData(protoEncoder.encodedData());
                envelope.sent(cluon::time::now());
                envelope.sampleTimeStamp((0 == (sampleTimeStamp.seconds() + sampleTimeStamp.microseconds())) ? envelope.sent() : sampleTimeStamp);
                envelope.senderStamp(senderStamp);
            }
            send(std::move(envelope));
        } catch (...) {} // LCOV_EXCL_LINE
    }
References cluon::data::Envelope::accept(), cluon::data::Envelope::dataType(), cluon::ToProtoVisitor::encodedData(), cluon::time::now(), cluon::data::Envelope::sampleTimeStamp(), cluon::data::Envelope::senderStamp(), cluon::data::Envelope::sent(), and cluon::data::Envelope::serializedData().
sendInternal()
void cluon::OD4Session::sendInternal (std::string && dataToSend) [inline], [private], [noexcept]
                                                                    {
    m_sender.send(std::move(dataToSend));
}
timeTrigger()
void cluon::OD4Session::timeTrigger (float freq, std::function< bool()> delegate) [inline], [noexcept]
This method sets a delegate to be called time-triggered using the specified frequency until the delegate returns false. This method blocks until the delegate has returned false or threw an exception. Thus, this method is typically called as last statement in a main function of a program.
Parameters
freq Frequency in Hertz to run the given delegate.
delegate Function to call according to the given frequency.
                                                                                     {
    if (nullptr != delegate) {
        bool delegateIsRunning{true};
        const int64_t TIME_SLICE_IN_MILLISECONDS{static_cast<uint32_t>(1000 / ((freq > 0) ? freq : 1.0f))};
        do {
            cluon::data::TimeStamp before{cluon::time::now()};
            try {
                delegateIsRunning = delegate();
            } catch (...) {
                delegateIsRunning = false; // delegate threw exception.
            }
            cluon::data::TimeStamp after{cluon::time::now()};
            const int64_t beforeInMicroseconds{cluon::time::toMicroseconds(before)};
            const int64_t afterInMicroseconds{cluon::time::toMicroseconds(after)};
            const int64_t timeSpent{(afterInMicroseconds > beforeInMicroseconds) ? (afterInMicroseconds - beforeInMicroseconds) / 1000 : 0};
            const int64_t timeToSleepInMilliseconds{TIME_SLICE_IN_MILLISECONDS - timeSpent};
            // Sleep the remaining time.
            if ((timeToSleepInMilliseconds > 0) && (timeToSleepInMilliseconds <= TIME_SLICE_IN_MILLISECONDS)) {
                std::this_thread::sleep_for(std::chrono::duration<int64_t, std::milli>(timeToSleepInMilliseconds));
            } else {
                std::cerr << "[cluon::OD4Session]: time-triggered delegate violated allocated time slice." << std::endl;
            }
        } while (delegateIsRunning && !TerminateHandler::instance().isTerminated.load());
    }
}
References cluon::TerminateHandler::instance(), cluon::time::now(), and cluon::time::toMicroseconds().
Member Data Documentation
m_delegate
std::function<void(cluon::data::Envelope &&envelope)> cluon::OD4Session::m_delegate {nullptr} [private]
m_mapOfDataTriggeredDelegates
std::unordered_map<int32_t, std::function<void(cluon::data::Envelope &&envelope)>, UseUInt32ValueAsHashKey> cluon::OD4Session::m_mapOfDataTriggeredDelegates {} [private]
m_mapOfDataTriggeredDelegatesMutex
std::mutex cluon::OD4Session::m_mapOfDataTriggeredDelegatesMutex {} [private]
m_receiver
std::unique_ptr<cluon::UDPReceiver> cluon::OD4Session::m_receiver [private]
Referenced by isRunning().
m_sender
cluon::UDPSender cluon::OD4Session::m_sender [private]
m_senderMutex
std::mutex cluon::OD4Session::m_senderMutex {} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp