opendlv::logic::perception::ObjectType Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ObjectType ()=default
ObjectType (const ObjectType &)=default
ObjectType & operator= (const ObjectType &)=default
ObjectType (ObjectType &&)=default
ObjectType & operator= (ObjectType &&)=default
~ObjectType ()=default
ObjectType & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
ObjectType & type (const uint32_t &v) noexcept
uint32_t type () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
uint32_t m_type { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `ObjectType`
static constexpr const char * TheLongName = `opendlv.logic.perception.ObjectType`
Constructor & Destructor Documentation
ObjectType() [1/3]
opendlv::logic::perception::ObjectType::ObjectType () [default]
ObjectType() [2/3]
opendlv::logic::perception::ObjectType::ObjectType (const ObjectType &) [default]
ObjectType() [3/3]
opendlv::logic::perception::ObjectType::ObjectType (ObjectType &&) [default]
 ObjectType()
opendlv::logic::perception::ObjectType::~ObjectType () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::ObjectType::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::ObjectType::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::ObjectType::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("type"s), m_type, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::ObjectType::ID () [inline], [static]
                                   {
            return 1131;
        }
LongName()
static const std::string opendlv::logic::perception::ObjectType::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::ObjectType::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
ObjectType & opendlv::logic::perception::ObjectType::objectId (const uint32_t & v) [inline], [noexcept]
                                                                {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
ObjectType & opendlv::logic::perception::ObjectType::operator= (const ObjectType &) [default]
operator=() [2/2]
ObjectType & opendlv::logic::perception::ObjectType::operator= (ObjectType &&) [default]
ShortName()
static const std::string opendlv::logic::perception::ObjectType::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
type() [1/2]
uint32_t opendlv::logic::perception::ObjectType::type () const [inline], [noexcept]
                                              {
            return m_type;
        }
type() [2/2]
ObjectType & opendlv::logic::perception::ObjectType::type (const uint32_t & v) [inline], [noexcept]
                                                            {
            m_type = v;
            return *this;
        }
Member Data Documentation
m_objectId
uint32_t opendlv::logic::perception::ObjectType::m_objectId { 0 } [private]
m_type
uint32_t opendlv::logic::perception::ObjectType::m_type { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::ObjectType::TheLongName = `opendlv.logic.perception.ObjectType` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::ObjectType::TheShortName = `ObjectType` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp