opendlv::proxy::AngularVelocityReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AngularVelocityReading ()=default
AngularVelocityReading (const AngularVelocityReading &)=default
AngularVelocityReading & operator= (const AngularVelocityReading &)=default
AngularVelocityReading (AngularVelocityReading &&)=default
AngularVelocityReading & operator= (AngularVelocityReading &&)=default
~AngularVelocityReading ()=default
AngularVelocityReading & angularVelocityX (const float &v) noexcept
float angularVelocityX () const noexcept
AngularVelocityReading & angularVelocityY (const float &v) noexcept
float angularVelocityY () const noexcept
AngularVelocityReading & angularVelocityZ (const float &v) noexcept
float angularVelocityZ () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_angularVelocityX { 0.0f }
float m_angularVelocityY { 0.0f }
float m_angularVelocityZ { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AngularVelocityReading`
static constexpr const char * TheLongName = `opendlv.proxy.AngularVelocityReading`
Constructor & Destructor Documentation
AngularVelocityReading() [1/3]
opendlv::proxy::AngularVelocityReading::AngularVelocityReading () [default]
AngularVelocityReading() [2/3]
opendlv::proxy::AngularVelocityReading::AngularVelocityReading (const AngularVelocityReading &) [default]
AngularVelocityReading() [3/3]
opendlv::proxy::AngularVelocityReading::AngularVelocityReading (AngularVelocityReading &&) [default]
 AngularVelocityReading()
opendlv::proxy::AngularVelocityReading::~AngularVelocityReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::AngularVelocityReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("angularVelocityX"s), m_angularVelocityX, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("angularVelocityY"s), m_angularVelocityY, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("angularVelocityZ"s), m_angularVelocityZ, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::AngularVelocityReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("angularVelocityX"s), m_angularVelocityX, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("angularVelocityY"s), m_angularVelocityY, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("angularVelocityZ"s), m_angularVelocityZ, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::AngularVelocityReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("angularVelocityX"s), m_angularVelocityX, visitor);
            doVisit(2, std::move("float"s), std::move("angularVelocityY"s), m_angularVelocityY, visitor);
            doVisit(3, std::move("float"s), std::move("angularVelocityZ"s), m_angularVelocityZ, visitor);
            visitor.postVisit();
        }
References doVisit().
angularVelocityX() [1/2]
float opendlv::proxy::AngularVelocityReading::angularVelocityX () const [inline], [noexcept]
                                                       {
            return m_angularVelocityX;
        }
angularVelocityX() [2/2]
AngularVelocityReading & opendlv::proxy::AngularVelocityReading::angularVelocityX (const float & v) [inline], [noexcept]
                                                                                 {
            m_angularVelocityX = v;
            return *this;
        }
angularVelocityY() [1/2]
float opendlv::proxy::AngularVelocityReading::angularVelocityY () const [inline], [noexcept]
                                                       {
            return m_angularVelocityY;
        }
angularVelocityY() [2/2]
AngularVelocityReading & opendlv::proxy::AngularVelocityReading::angularVelocityY (const float & v) [inline], [noexcept]
                                                                                 {
            m_angularVelocityY = v;
            return *this;
        }
angularVelocityZ() [1/2]
float opendlv::proxy::AngularVelocityReading::angularVelocityZ () const [inline], [noexcept]
                                                       {
            return m_angularVelocityZ;
        }
angularVelocityZ() [2/2]
AngularVelocityReading & opendlv::proxy::AngularVelocityReading::angularVelocityZ (const float & v) [inline], [noexcept]
                                                                                 {
            m_angularVelocityZ = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::AngularVelocityReading::ID () [inline], [static]
                                   {
            return 1031;
        }
LongName()
static const std::string opendlv::proxy::AngularVelocityReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AngularVelocityReading & opendlv::proxy::AngularVelocityReading::operator= (AngularVelocityReading &&) [default]
operator=() [2/2]
AngularVelocityReading & opendlv::proxy::AngularVelocityReading::operator= (const AngularVelocityReading &) [default]
ShortName()
static const std::string opendlv::proxy::AngularVelocityReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_angularVelocityX
float opendlv::proxy::AngularVelocityReading::m_angularVelocityX { 0.0f } [private]
m_angularVelocityY
float opendlv::proxy::AngularVelocityReading::m_angularVelocityY { 0.0f } [private]
m_angularVelocityZ
float opendlv::proxy::AngularVelocityReading::m_angularVelocityZ { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::AngularVelocityReading::TheLongName = `opendlv.proxy.AngularVelocityReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::AngularVelocityReading::TheShortName = `AngularVelocityReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp