opendlv::proxy::VoltageRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
VoltageRequest ()=default
VoltageRequest (const VoltageRequest &)=default
VoltageRequest & operator= (const VoltageRequest &)=default
VoltageRequest (VoltageRequest &&)=default
VoltageRequest & operator= (VoltageRequest &&)=default
~VoltageRequest ()=default
VoltageRequest & voltage (const float &v) noexcept
float voltage () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_voltage { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `VoltageRequest`
static constexpr const char * TheLongName = `opendlv.proxy.VoltageRequest`
Constructor & Destructor Documentation
VoltageRequest() [1/3]
opendlv::proxy::VoltageRequest::VoltageRequest () [default]
VoltageRequest() [2/3]
opendlv::proxy::VoltageRequest::VoltageRequest (const VoltageRequest &) [default]
VoltageRequest() [3/3]
opendlv::proxy::VoltageRequest::VoltageRequest (VoltageRequest &&) [default]
 VoltageRequest()
opendlv::proxy::VoltageRequest::~VoltageRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::VoltageRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::VoltageRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::VoltageRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::VoltageRequest::ID () [inline], [static]
                                   {
            return 1083;
        }
LongName()
static const std::string opendlv::proxy::VoltageRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
VoltageRequest & opendlv::proxy::VoltageRequest::operator= (const VoltageRequest &) [default]
operator=() [2/2]
VoltageRequest & opendlv::proxy::VoltageRequest::operator= (VoltageRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::VoltageRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
voltage() [1/2]
float opendlv::proxy::VoltageRequest::voltage () const [inline], [noexcept]
                                              {
            return m_voltage;
        }
voltage() [2/2]
VoltageRequest & opendlv::proxy::VoltageRequest::voltage (const float & v) [inline], [noexcept]
                                                                {
            m_voltage = v;
            return *this;
        }
Member Data Documentation
m_voltage
float opendlv::proxy::VoltageRequest::m_voltage { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::VoltageRequest::TheLongName = `opendlv.proxy.VoltageRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::VoltageRequest::TheShortName = `VoltageRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp