cluon::LCMToGenericMessage Class Reference
#include <cluon-complete.hpp>
Public Member Functions
LCMToGenericMessage ()=default
int32_t setMessageSpecification (const std::string &ms) noexcept
cluon::GenericMessage getGenericMessage (const std::string &data) noexcept
Private Member Functions
LCMToGenericMessage (const LCMToGenericMessage &)=delete
LCMToGenericMessage (LCMToGenericMessage &&)=delete
LCMToGenericMessage & operator= (const LCMToGenericMessage &)=delete
LCMToGenericMessage & operator= (LCMToGenericMessage &&)=delete
Private Attributes
std::vector< cluon::MetaMessage > m_listOfMetaMessages {}
std::map< std::string, cluon::MetaMessage > m_scopeOfMetaMessages {}
Detailed Description
This class transforms a given LCM message into a GenericMessage.
Constructor & Destructor Documentation
LCMToGenericMessage() [1/3]
cluon::LCMToGenericMessage::LCMToGenericMessage (const LCMToGenericMessage &) [private], [delete]
LCMToGenericMessage() [2/3]
cluon::LCMToGenericMessage::LCMToGenericMessage (LCMToGenericMessage &&) [private], [delete]
LCMToGenericMessage() [3/3]
cluon::LCMToGenericMessage::LCMToGenericMessage () [default]
Member Function Documentation
getGenericMessage()
cluon::GenericMessage cluon::LCMToGenericMessage::getGenericMessage (const std::string & data) [inline], [noexcept]
This method transforms the given LCM payload into a GenericMessage.
Parameters
data LCM Payload.
Returns
GenericMessage representation using the given message specification.
                                                                                                {
    cluon::GenericMessage gm;
    if (!m_listOfMetaMessages.empty()) {
        constexpr uint8_t LCM_HEADER_SIZE{4 /*magic number*/ + 4 /*sequence number*/ + 1 /*'\0' after channel name*/};
        if (LCM_HEADER_SIZE < data.size()) {
            // First, read magic number.
            constexpr uint32_t MAGIC_NUMBER_LCM2{0x4c433032};
            uint32_t offset{0};
            uint32_t magicNumber{0};
            {
                std::stringstream sstr{std::string(&data[offset], 4)};
                // clang-format off
                sstr.read(reinterpret_cast<char *>(&magicNumber), sizeof(uint32_t)); /* Flawfinder: ignore */ // NOLINT
                // clang-format on
                magicNumber = be32toh(magicNumber);
            }
            if (MAGIC_NUMBER_LCM2 == magicNumber) {
                offset += 4;
                // Next, read sequence number in case of fragmented data.
                uint32_t sequenceNumber{0};
                {
                    std::stringstream sstr{std::string(&data[offset], 4)};
                    // clang-format off
                    sstr.read(reinterpret_cast<char *>(&sequenceNumber), sizeof(uint32_t)); /* Flawfinder: ignore */ // NOLINT
                    // clang-format on
                    sequenceNumber = be32toh(sequenceNumber);
                }
                // Only support for non-fragmented messages.
                if (0 == sequenceNumber) {
                    offset += 4;
                    const std::string::size_type START_POSITION = offset;
                    std::string::size_type pos = data.find('\0', START_POSITION); // Extract channel name.
                    if (std::string::npos != pos) {
                        const std::string CHANNEL_NAME(data.substr(START_POSITION, (pos - START_POSITION)));
                        // Next, find the MetaMessage corresponding to the channel name
                        // and create a Message therefrom based on the decoded LCM data.
                        if ((0 < m_scopeOfMetaMessages.count(CHANNEL_NAME)) && (std::string::npos != (pos + 1))) {
                            // data[offset+i] marks now the beginning of the payload to be decoded.
                            std::stringstream sstr{data.substr(pos + 1)};
                            cluon::FromLCMVisitor fromLCM;
                            fromLCM.decodeFrom(sstr);
                            gm.createFrom(m_scopeOfMetaMessages[CHANNEL_NAME], m_listOfMetaMessages);
                            gm.accept(fromLCM);
                        }
                    }
                }
            }
        }
    }
    return gm;
}
References cluon::GenericMessage::accept(), cluon::GenericMessage::createFrom(), and cluon::FromLCMVisitor::decodeFrom().
operator=() [1/2]
LCMToGenericMessage & cluon::LCMToGenericMessage::operator= (const LCMToGenericMessage &) [private], [delete]
operator=() [2/2]
LCMToGenericMessage & cluon::LCMToGenericMessage::operator= (LCMToGenericMessage &&) [private], [delete]
setMessageSpecification()
int32_t cluon::LCMToGenericMessage::setMessageSpecification (const std::string & ms) [inline], [noexcept]
This method sets the message specification to be used for interpreting a given LCM-encoded message.
Parameters
ms Message specification following the ODVD format.
Returns
-1 in case of invalid message specification; otherwise, number of successfully parsed messages from given message specification.
                                                                                        {
    int32_t retVal{-1};
    m_listOfMetaMessages.clear();
    m_scopeOfMetaMessages.clear();
    cluon::MessageParser mp;
    auto parsingResult = mp.parse(ms);
    if (cluon::MessageParser::MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR == parsingResult.second) {
        m_listOfMetaMessages = parsingResult.first;
        for (const auto &mm : m_listOfMetaMessages) { m_scopeOfMetaMessages[mm.messageName()] = mm; }
        retVal = static_cast<int32_t>(m_listOfMetaMessages.size());
    }
    return retVal;
}
References mm, cluon::MessageParser::parse(), and retVal.
Member Data Documentation
m_listOfMetaMessages
std::vector<cluon::MetaMessage> cluon::LCMToGenericMessage::m_listOfMetaMessages {} [private]
m_scopeOfMetaMessages
std::map<std::string, cluon::MetaMessage> cluon::LCMToGenericMessage::m_scopeOfMetaMessages {} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp