peg::Sequence Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Sequence (const Sequence &rhs)
template<typename... Args>
Sequence (const Args &...args)
Sequence (const std::vector< std::shared_ptr< Ope > > &opes)
Sequence (std::vector< std::shared_ptr< Ope > > &&opes)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::vector< std::shared_ptr< Ope > > opes_
Constructor & Destructor Documentation
Sequence() [1/4]
peg::Sequence::Sequence (const Sequence & rhs) [inline]
: opes_(rhs.opes_) {}
Sequence() [2/4]
template<typename... Args>
peg::Sequence::Sequence (const Args &... args) [inline]
: opes_{ static_cast<std::shared_ptr<Ope>>(args)... } {}
Sequence() [3/4]
peg::Sequence::Sequence (const std::vector< std::shared_ptr< Ope > > & opes) [inline]
: opes_(opes) {}
Sequence() [4/4]
peg::Sequence::Sequence (std::vector< std::shared_ptr< Ope > > && opes) [inline]
: opes_(opes) {}
Member Function Documentation
accept()
void peg::Sequence::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::Sequence::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("Sequence", s, n, sv, dt);
        auto& chldsv = c.push();
        size_t i = 0;
        for (const auto& ope : opes_) {
            c.nest_level++;
            auto se = make_scope_exit([&]() { c.nest_level--; });
            const auto& rule = *ope;
            auto len = rule.parse(s + i, n - i, chldsv, c, dt);
            if (fail(len)) {
                return static_cast<size_t>(-1);
            }
            i += len;
        }
        sv.insert(sv.end(), chldsv.begin(), chldsv.end());
        sv.tags.insert(sv.tags.end(), chldsv.tags.begin(), chldsv.tags.end());
        sv.s_ = chldsv.c_str();
        sv.n_ = chldsv.length();
        sv.tokens.insert(sv.tokens.end(), chldsv.tokens.begin(), chldsv.tokens.end());
        return i;
    }
References peg::fail(), peg::make_scope_exit(), peg::SemanticValues::n_, peg::Context::nest_level, peg::Context::push(), peg::SemanticValues::s_, peg::SemanticValues::tags, peg::SemanticValues::tokens, and peg::Context::trace().
Member Data Documentation
opes_
std::vector<std::shared_ptr<Ope> > peg::Sequence::opes_
Referenced by peg::AssignIDToDefinition::visit(), peg::TokenChecker::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp