cluon::TCPConnection Class Reference
#include <cluon-complete.hpp>
Classes
struct m_address
class PipelineEntry
Public Member Functions
TCPConnection (const std::string &address, uint16_t port, std::function< void(std::string &&, std::chrono::system_clock::time_point &&)> newDataDelegate=nullptr, std::function< void()> connectionLostDelegate=nullptr) noexcept
~TCPConnection () noexcept
void setOnNewData (std::function< void(std::string &&, std::chrono::system_clock::time_point &&)> newDataDelegate) noexcept
void setOnConnectionLost (std::function< void()> connectionLostDelegate) noexcept
bool isRunning () const noexcept
std::pair< ssize_t, int32_t > send (std::string &&data) const noexcept
Private Member Functions
TCPConnection (const int32_t &socket) noexcept
TCPConnection (const TCPConnection &)=delete
TCPConnection (TCPConnection &&)=delete
TCPConnection & operator= (const TCPConnection &)=delete
TCPConnection & operator= (TCPConnection &&)=delete
void closeSocket (int errorCode) noexcept
void startReadingFromSocket () noexcept
void readFromSocket () noexcept
Private Attributes
std::mutex m_socketMutex {}
int32_t m_socket {-1}
std::atomic< bool > m_readFromSocketThreadRunning {false}
std::thread m_readFromSocketThread {}
std::mutex m_newDataDelegateMutex {}
std::function< void(std::string &&, std::chrono::system_clock::time_point)> m_newDataDelegate {}
std::mutex m_connectionLostDelegateMutex {}
std::function< void()> m_connectionLostDelegate {}
std::shared_ptr< cluon::NotifyingPipeline< PipelineEntry > > m_pipeline {}
Friends
class TCPServer
Detailed Description
To exchange data via TCP, simply include the header #include <cluon/TCPConnection.hpp>.
Next, create an instance of class cluon::TCPConnection as follows: cluon::TCPConnection connection(`127.0.0.1`, 1234, newDataDelegate, connectionLostDelegate);. The first parameter is of type std::string expecting a numerical IPv4 address, the second parameter specifies the TCP port, from which data shall be received from, the third paraemter is of type std::function that is called whenever new bytes are available to be processed, and the last parameter is of type std::function that is called when the connection is lost.
The complete signature for the newDataDelegate function is std::function<void(std::string &&, std::string &&, std::chrono::system_clock::time_point &&) noexcept>: The first parameter contains the bytes that have been received, the second parameter containes the human-readable representation of the sender (X.Y.Z.W:ABCD), and the last parameter is the time stamp when the data has been received.
The complete signature for the connectionLostDelegate function is std::function<void() noexcept>.
To finally send data, simply call the method send supplying the data to be sent: connection.send(std::move(`Hello World!`). Please note that the data is supplied using the move-semantics. The method send returns a std::pair<ssize_t, int32_t> where the first element returns the size of the successfully sent bytes and the second element contains the error code in case the transmission of the data failed.
An example using a C++ lambda expression would look as follows:
cluon::TCPConnection connection("127.0.0.1", 1234,
    [](std::string &&data, std::string &&sender, std::chrono::system_clock::time_point &&ts) noexcept {
        const auto timestamp(std::chrono::system_clock::to_time_t(ts));
        std::cout << "Received " << data.size() << " bytes"
                  << " from " << sender
                  << " at " << std::put_time(std::localtime(&timestamp), "%Y-%m-%d %X")
                  << ", containing '" << data << "'." << std::endl;
    },
    [](){ std::cout << "Connection lost." << std::endl; });
std::pair<ssize_t, int32_t> retVal = connection.send(std::move("Hello World!"));
After creating an instance of class cluon::TCPConnection, it is immediately activated and concurrently waiting for data in a separate thread. To check whether the instance was created successfully and running, the method isRunning() should be called.
Constructor & Destructor Documentation
TCPConnection() [1/4]
cluon::TCPConnection::TCPConnection (const int32_t & socket) [inline], [private], [noexcept]
Constructor that is only accessible to TCPServer to manage incoming TCP connections.
Parameters
socket Socket to handle an existing TCP connection described by this socket.
    : m_socket(socket)
    , m_newDataDelegate(nullptr)
    , m_connectionLostDelegate(nullptr) {
    if (!(m_socket < 0)) {
        startReadingFromSocket();
    }
}
TCPConnection() [2/4]
cluon::TCPConnection::TCPConnection (const TCPConnection &) [private], [delete]
TCPConnection() [3/4]
cluon::TCPConnection::TCPConnection (TCPConnection &&) [private], [delete]
TCPConnection() [4/4]
cluon::TCPConnection::TCPConnection (const std::string & address, uint16_t port, std::function< void(std::string &&, std::chrono::system_clock::time_point &&)> newDataDelegate = nullptr, std::function< void()> connectionLostDelegate = nullptr) [inline], [noexcept]
Constructor to connect to a TCP server.
Parameters
address Numerical IPv4 address to receive UDP packets from.
port Port to receive UDP packets from.
newDataDelegate Functional (noexcept) to handle received bytes; parameters are received data, timestamp.
connectionLostDelegate Functional (noexcept) to handle a lost connection.
    : m_newDataDelegate(std::move(newDataDelegate))
    , m_connectionLostDelegate(std::move(connectionLostDelegate)) {
    // Decompose given address string to check validity with numerical IPv4 address.
    std::string resolvedHostname{cluon::getIPv4FromHostname(address)};
    std::string tmp{resolvedHostname};
    std::replace(tmp.begin(), tmp.end(), '.', ' ');
    std::istringstream sstr{tmp};
    std::vector<int> addressTokens{std::istream_iterator<int>(sstr), std::istream_iterator<int>()};
    if ((!addressTokens.empty()) && (4 == addressTokens.size())
        && !(std::end(addressTokens) != std::find_if(addressTokens.begin(), addressTokens.end(), [](int a) { return (a < 0) || (a > 255); })) && (0 < port)) {
        // Check for valid IP address.
        struct sockaddr_in tmpSocketAddress {};
        const bool isValid = (0 < ::inet_pton(AF_INET, resolvedHostname.c_str(), &(tmpSocketAddress.sin_addr)));
        if (isValid) {
            std::memset(&m_address, 0, sizeof(m_address));
            m_address.sin_addr.s_addr = ::inet_addr(resolvedHostname.c_str());
            m_address.sin_family = AF_INET;
            m_address.sin_port = htons(port);
#ifdef WIN32
            // Load Winsock 2.2 DLL.
            WSADATA wsaData;
            if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
                std::cerr << "[cluon::TCPConnection] Error while calling WSAStartUp: " << WSAGetLastError() << std::endl;
            }
#endif
            m_socket = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
#ifdef WIN32
            if (m_socket < 0) {
                std::cerr << "[cluon::TCPConnection] Error while creating socket: " << WSAGetLastError() << std::endl;
                WSACleanup();
            }
#endif
            if (!(m_socket < 0)) {
                auto retVal = ::connect(m_socket, reinterpret_cast<struct sockaddr *>(&m_address), sizeof(m_address));
                if (0 > retVal) {
#ifdef WIN32 // LCOV_EXCL_LINE
                    auto errorCode = WSAGetLastError();
#else
                    auto errorCode = errno; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
                    closeSocket(errorCode); // LCOV_EXCL_LINE
                } else {
                    startReadingFromSocket();
                }
            }
        }
    }
}
References cluon::getIPv4FromHostname(), and retVal.
 TCPConnection()
cluon::TCPConnection::~TCPConnection () [inline], [noexcept]
                                              {
    {
        m_readFromSocketThreadRunning.store(false);
        // Joining the thread could fail.
        try {
            if (m_readFromSocketThread.joinable()) {
                m_readFromSocketThread.join();
            }
        } catch (...) {} // LCOV_EXCL_LINE
    }
    m_pipeline.reset();
    closeSocket(0);
}
References closeSocket(), m_pipeline, m_readFromSocketThread, and m_readFromSocketThreadRunning.
Member Function Documentation
closeSocket()
void cluon::TCPConnection::closeSocket (int errorCode) [inline], [private], [noexcept]
This method closes the socket.
Parameters
errorCode Error code that caused this closing.
                                                             {
    if (0 != errorCode) {
        std::cerr << "[cluon::TCPConnection] Failed to perform socket operation: "; // LCOV_EXCL_LINE
#ifdef WIN32 // LCOV_EXCL_LINE
        std::cerr << errorCode << std::endl;
#else
        std::cerr << ::strerror(errorCode) << " (" << errorCode << ")" << std::endl; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
    }
    if (!(m_socket < 0)) {
#ifdef WIN32
        ::shutdown(m_socket, SD_BOTH);
        ::closesocket(m_socket);
        WSACleanup();
#else
        ::shutdown(m_socket, SHUT_RDWR); // Disallow further read/write operations.
        ::close(m_socket);
#endif
    }
    m_socket = -1;
}
Referenced by startReadingFromSocket(), and ~TCPConnection().
isRunning()
bool cluon::TCPConnection::isRunning () const [inline], [noexcept]
Returns
true if the TCPConnection could successfully be created and is able to receive data.
                                                    {
    return (m_readFromSocketThreadRunning.load() && !TerminateHandler::instance().isTerminated.load());
}
References cluon::TerminateHandler::instance(), cluon::TerminateHandler::isTerminated, and m_readFromSocketThreadRunning.
operator=() [1/2]
TCPConnection & cluon::TCPConnection::operator= (const TCPConnection &) [private], [delete]
operator=() [2/2]
TCPConnection & cluon::TCPConnection::operator= (TCPConnection &&) [private], [delete]
readFromSocket()
void cluon::TCPConnection::readFromSocket () [inline], [private], [noexcept]
                                                   {
    // Create buffer to store data from socket.
    constexpr uint16_t MAX_LENGTH{65535};
    std::array<char, MAX_LENGTH> buffer{};
    struct timeval timeout {};
    // Define file descriptor set to watch for read operations.
    fd_set setOfFiledescriptorsToReadFrom{};
    // Indicate to main thread that we are ready.
    m_readFromSocketThreadRunning.store(true);
    // This flag is used to not read data from the socket until this TCPConnection has a proper onNewDataHandler set.
    bool hasNewDataDelegate{false};
    while (m_readFromSocketThreadRunning.load()) {
        // Define timeout for select system call. The timeval struct must be
        // reinitialized for every select call as it might be modified containing
        // the actual time slept.
        timeout.tv_sec = 0;
        timeout.tv_usec = 20 * 1000; // Check for new data with 50Hz.
        FD_ZERO(&setOfFiledescriptorsToReadFrom);
        FD_SET(m_socket, &setOfFiledescriptorsToReadFrom);
        ::select(m_socket + 1, &setOfFiledescriptorsToReadFrom, nullptr, nullptr, &timeout);
        // Only read data when the newDataDelegate is set.
        if (!hasNewDataDelegate) {
            std::lock_guard<std::mutex> lck(m_newDataDelegateMutex);
            hasNewDataDelegate = (nullptr != m_newDataDelegate);
        }
        if (FD_ISSET(m_socket, &setOfFiledescriptorsToReadFrom) && hasNewDataDelegate) {
            ssize_t bytesRead = ::recv(m_socket, buffer.data(), buffer.max_size(), 0);
            if (0 >= bytesRead) {
                // 0 == bytesRead: peer shut down the connection; 0 > bytesRead: other error.
                m_readFromSocketThreadRunning.store(false);
                {
                    std::lock_guard<std::mutex> lck(m_connectionLostDelegateMutex);
                    if (nullptr != m_connectionLostDelegate) {
                        m_connectionLostDelegate();
                    }
                }
                break;
            }
            {
                std::lock_guard<std::mutex> lck(m_newDataDelegateMutex);
                if ((0 < bytesRead) && (nullptr != m_newDataDelegate)) {
                    // SIOCGSTAMP is not available for a stream-based socket,
                    // thus, falling back to regular chrono timestamping.
                    std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now();
                    {
                        PipelineEntry pe;
                        pe.m_data = std::string(buffer.data(), static_cast<size_t>(bytesRead));
                        pe.m_sampleTime = timestamp;
                        // Store entry in queue.
                        if (m_pipeline) {
                            m_pipeline->add(std::move(pe));
                        }
                    }
                    if (m_pipeline) {
                        m_pipeline->notifyAll();
                    }
                }
            }
        }
    }
}
References m_connectionLostDelegate, m_connectionLostDelegateMutex, cluon::TCPConnection::PipelineEntry::m_data, m_newDataDelegate, m_newDataDelegateMutex, m_pipeline, m_readFromSocketThreadRunning, cluon::TCPConnection::PipelineEntry::m_sampleTime, m_socket, and cluon::time::now().
Referenced by startReadingFromSocket().
send()
std::pair< ssize_t, int32_t > cluon::TCPConnection::send (std::string && data) const [inline], [noexcept]
Send a given string.
Parameters
data Data to send.
Returns
Pair: Number of bytes sent and errno.
                                                                                    {
    if (-1 == m_socket) {
        return {-1, EBADF};
    }
    if (data.empty()) {
        return {0, 0};
    }
    if (!m_readFromSocketThreadRunning.load()) {
        std::lock_guard<std::mutex> lck(m_connectionLostDelegateMutex); // LCOV_EXCL_LINE
        if (nullptr != m_connectionLostDelegate) { // LCOV_EXCL_LINE
            m_connectionLostDelegate(); // LCOV_EXCL_LINE
        }
        return {-1, ENOTCONN}; // LCOV_EXCL_LINE
    }
    constexpr uint16_t MAX_LENGTH{65535};
    if (MAX_LENGTH < data.size()) {
        return {-1, E2BIG};
    }
    std::lock_guard<std::mutex> lck(m_socketMutex);
    ssize_t bytesSent = ::send(m_socket, data.c_str(), data.length(), 0);
    return {bytesSent, (0 > bytesSent ? errno : 0)};
}
setOnConnectionLost()
void cluon::TCPConnection::setOnConnectionLost (std::function< void()> connectionLostDelegate) [inline], [noexcept]
                                                                                                  {
    std::lock_guard<std::mutex> lck(m_connectionLostDelegateMutex);
    m_connectionLostDelegate = connectionLostDelegate;
}
setOnNewData()
void cluon::TCPConnection::setOnNewData (std::function< void(std::string &&, std::chrono::system_clock::time_point &&)> newDataDelegate) [inline], [noexcept]
                                                                                                                                    {
    std::lock_guard<std::mutex> lck(m_newDataDelegateMutex);
    m_newDataDelegate = newDataDelegate;
}
startReadingFromSocket()
void cluon::TCPConnection::startReadingFromSocket () [inline], [private], [noexcept]
                                                           {
    // Constructing a thread could fail.
    try {
        m_readFromSocketThread = std::thread(&TCPConnection::readFromSocket, this);
        // Let the operating system spawn the thread.
        using namespace std::literals::chrono_literals;
        do { std::this_thread::sleep_for(1ms); } while (!m_readFromSocketThreadRunning.load());
    } catch (...) { // LCOV_EXCL_LINE
        closeSocket(ECHILD); // LCOV_EXCL_LINE
    }
    try {
        m_pipeline = std::make_shared<cluon::NotifyingPipeline<PipelineEntry>>(
            [this](PipelineEntry &&entry) { this->m_newDataDelegate(std::move(entry.m_data), std::move(entry.m_sampleTime)); });
        if (m_pipeline) {
            // Let the operating system spawn the thread.
            using namespace std::literals::chrono_literals; // NOLINT
            do { std::this_thread::sleep_for(1ms); } while (!m_pipeline->isRunning());
        }
    } catch (...) { closeSocket(ECHILD); } // LCOV_EXCL_LINE
}
References closeSocket(), m_newDataDelegate, m_pipeline, m_readFromSocketThread, m_readFromSocketThreadRunning, and readFromSocket().
Friends And Related Function Documentation
TCPServer
friend class TCPServer [friend]
Member Data Documentation
m_connectionLostDelegate
std::function<void()> cluon::TCPConnection::m_connectionLostDelegate {} [private]
Referenced by readFromSocket().
m_connectionLostDelegateMutex
std::mutex cluon::TCPConnection::m_connectionLostDelegateMutex {} [mutable], [private]
Referenced by readFromSocket().
m_newDataDelegate
std::function<void(std::string &&, std::chrono::system_clock::time_point)> cluon::TCPConnection::m_newDataDelegate {} [private]
Referenced by readFromSocket(), and startReadingFromSocket().
m_newDataDelegateMutex
std::mutex cluon::TCPConnection::m_newDataDelegateMutex {} [private]
Referenced by readFromSocket().
m_pipeline
std::shared_ptr<cluon::NotifyingPipeline<PipelineEntry> > cluon::TCPConnection::m_pipeline {} [private]
Referenced by readFromSocket(), startReadingFromSocket(), and ~TCPConnection().
m_readFromSocketThread
std::thread cluon::TCPConnection::m_readFromSocketThread {} [private]
Referenced by startReadingFromSocket(), and ~TCPConnection().
m_readFromSocketThreadRunning
std::atomic<bool> cluon::TCPConnection::m_readFromSocketThreadRunning {false} [private]
Referenced by isRunning(), readFromSocket(), startReadingFromSocket(), and ~TCPConnection().
m_socket
int32_t cluon::TCPConnection::m_socket {-1} [private]
Referenced by readFromSocket().
m_socketMutex
std::mutex cluon::TCPConnection::m_socketMutex {} [mutable], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp