peg::CharacterClass Class Reference
#include <cluon-complete.hpp>
Public Member Functions
CharacterClass (const std::string &s)
CharacterClass (const std::vector< std::pair< char32_t, char32_t > > &ranges)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::vector< std::pair< char32_t, char32_t > > ranges_
Constructor & Destructor Documentation
CharacterClass() [1/2]
peg::CharacterClass::CharacterClass (const std::string & s) [inline]
                                       {
        auto chars = decode(s.c_str(), s.length());
        auto i = 0u;
        while (i < chars.size()) {
            if (i + 2 < chars.size() && chars[i + 1] == '-') {
                auto cp1 = chars[i];
                auto cp2 = chars[i + 2];
                ranges_.emplace_back(std::make_pair(cp1, cp2));
                i += 3;
            } else {
                auto cp = chars[i];
                ranges_.emplace_back(std::make_pair(cp, cp));
                i += 1;
            }
        }
    }
References peg::decode().
CharacterClass() [2/2]
peg::CharacterClass::CharacterClass (const std::vector< std::pair< char32_t, char32_t > > & ranges) [inline]
: ranges_(ranges) {}
Member Function Documentation
accept()
void peg::CharacterClass::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::CharacterClass::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("CharacterClass", s, n, sv, dt);
        if (n < 1) {
            c.set_error_pos(s);
            return static_cast<size_t>(-1);
        }
        char32_t cp = '\0';
        auto len = decode_codepoint(s, n, cp);
        if (!ranges_.empty()) {
            for (const auto& range: ranges_) {
                if (range.first <= cp && cp <= range.second) {
                    return len;
                }
            }
        }
        c.set_error_pos(s);
        return static_cast<size_t>(-1);
    }
References peg::decode_codepoint(), peg::Context::set_error_pos(), and peg::Context::trace().
Member Data Documentation
ranges_
std::vector<std::pair<char32_t, char32_t> > peg::CharacterClass::ranges_
The documentation for this class was generated from the following file:
src/cluon-complete.hpp