peg::BackReference Class Reference
#include <cluon-complete.hpp>
Public Member Functions
BackReference (const std::string &name)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::string name_
Constructor & Destructor Documentation
BackReference()
peg::BackReference::BackReference (const std::string & name) [inline]
: name_(name) {}
Member Function Documentation
accept()
void peg::BackReference::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::BackReference::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                         {
    c.trace("BackReference", s, n, sv, dt);
    auto it = c.capture_scope_stack.rbegin();
    while (it != c.capture_scope_stack.rend()) {
        const auto& captures = *it;
        if (captures.find(name_) != captures.end()) {
            const auto& lit = captures.at(name_);
            auto init_is_word = false;
            auto is_word = false;
            return parse_literal(s, n, sv, c, dt, lit, init_is_word, is_word, false);
        }
        ++it;
    }
    throw std::runtime_error("Invalid back reference...");
}
References peg::Context::capture_scope_stack, peg::lit(), peg::parse_literal(), and peg::Context::trace().
Member Data Documentation
name_
std::string peg::BackReference::name_
The documentation for this class was generated from the following file:
src/cluon-complete.hpp