peg::Character Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Character (char ch)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
char ch_
Constructor & Destructor Documentation
Character()
peg::Character::Character (char ch) [inline]
: ch_(ch) {}
Member Function Documentation
accept()
void peg::Character::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::Character::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("Character", s, n, sv, dt);
        if (n < 1 || s[0] != ch_) {
            c.set_error_pos(s);
            return static_cast<size_t>(-1);
        }
        return 1;
    }
References peg::Context::set_error_pos(), and peg::Context::trace().
Member Data Documentation
ch_
char peg::Character::ch_
The documentation for this class was generated from the following file:
src/cluon-complete.hpp