opendlv::proxy::ImageReadingShared Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ImageReadingShared ()=default
ImageReadingShared (const ImageReadingShared &)=default
ImageReadingShared & operator= (const ImageReadingShared &)=default
ImageReadingShared (ImageReadingShared &&)=default
ImageReadingShared & operator= (ImageReadingShared &&)=default
~ImageReadingShared ()=default
ImageReadingShared & name (const std::string &v) noexcept
std::string name () const noexcept
ImageReadingShared & size (const uint32_t &v) noexcept
uint32_t size () const noexcept
ImageReadingShared & width (const uint32_t &v) noexcept
uint32_t width () const noexcept
ImageReadingShared & height (const uint32_t &v) noexcept
uint32_t height () const noexcept
ImageReadingShared & bytesPerPixel (const uint32_t &v) noexcept
uint32_t bytesPerPixel () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_name { ``s }
uint32_t m_size { 0 }
uint32_t m_width { 0 }
uint32_t m_height { 0 }
uint32_t m_bytesPerPixel { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `ImageReadingShared`
static constexpr const char * TheLongName = `opendlv.proxy.ImageReadingShared`
Constructor & Destructor Documentation
ImageReadingShared() [1/3]
opendlv::proxy::ImageReadingShared::ImageReadingShared () [default]
ImageReadingShared() [2/3]
opendlv::proxy::ImageReadingShared::ImageReadingShared (const ImageReadingShared &) [default]
ImageReadingShared() [3/3]
opendlv::proxy::ImageReadingShared::ImageReadingShared (ImageReadingShared &&) [default]
 ImageReadingShared()
opendlv::proxy::ImageReadingShared::~ImageReadingShared () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::ImageReadingShared::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("name"s), m_name, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("uint32_t"s), std::move("bytesPerPixel"s), m_bytesPerPixel, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::ImageReadingShared::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("name"s), m_name, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("uint32_t"s), std::move("bytesPerPixel"s), m_bytesPerPixel, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::ImageReadingShared::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("name"s), m_name, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, visitor);
            doVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
            doVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
            doVisit(5, std::move("uint32_t"s), std::move("bytesPerPixel"s), m_bytesPerPixel, visitor);
            visitor.postVisit();
        }
References doVisit().
bytesPerPixel() [1/2]
uint32_t opendlv::proxy::ImageReadingShared::bytesPerPixel () const [inline], [noexcept]
                                                       {
            return m_bytesPerPixel;
        }
bytesPerPixel() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::bytesPerPixel (const uint32_t & v) [inline], [noexcept]
                                                                             {
            m_bytesPerPixel = v;
            return *this;
        }
height() [1/2]
uint32_t opendlv::proxy::ImageReadingShared::height () const [inline], [noexcept]
                                                {
            return m_height;
        }
height() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::height (const uint32_t & v) [inline], [noexcept]
                                                                      {
            m_height = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::ImageReadingShared::ID () [inline], [static]
                                   {
            return 14;
        }
LongName()
static const std::string opendlv::proxy::ImageReadingShared::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
name() [1/2]
std::string opendlv::proxy::ImageReadingShared::name () const [inline], [noexcept]
                                               {
            return m_name;
        }
name() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::name (const std::string & v) [inline], [noexcept]
                                                                     {
            m_name = v;
            return *this;
        }
operator=() [1/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::operator= (const ImageReadingShared &) [default]
operator=() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::operator= (ImageReadingShared &&) [default]
ShortName()
static const std::string opendlv::proxy::ImageReadingShared::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
size() [1/2]
uint32_t opendlv::proxy::ImageReadingShared::size () const [inline], [noexcept]
                                              {
            return m_size;
        }
size() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::size (const uint32_t & v) [inline], [noexcept]
                                                                    {
            m_size = v;
            return *this;
        }
width() [1/2]
uint32_t opendlv::proxy::ImageReadingShared::width () const [inline], [noexcept]
                                               {
            return m_width;
        }
width() [2/2]
ImageReadingShared & opendlv::proxy::ImageReadingShared::width (const uint32_t & v) [inline], [noexcept]
                                                                     {
            m_width = v;
            return *this;
        }
Member Data Documentation
m_bytesPerPixel
uint32_t opendlv::proxy::ImageReadingShared::m_bytesPerPixel { 0 } [private]
m_height
uint32_t opendlv::proxy::ImageReadingShared::m_height { 0 } [private]
m_name
std::string opendlv::proxy::ImageReadingShared::m_name { ``s } [private]
m_size
uint32_t opendlv::proxy::ImageReadingShared::m_size { 0 } [private]
m_width
uint32_t opendlv::proxy::ImageReadingShared::m_width { 0 } [private]
TheLongName
constexpr const char* opendlv::proxy::ImageReadingShared::TheLongName = `opendlv.proxy.ImageReadingShared` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::ImageReadingShared::TheShortName = `ImageReadingShared` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp