cluon::data::PlayerCommand Class Reference
#include <cluon-complete.hpp>
Public Member Functions
PlayerCommand ()=default
PlayerCommand (const PlayerCommand &)=default
PlayerCommand & operator= (const PlayerCommand &)=default
PlayerCommand (PlayerCommand &&)=default
PlayerCommand & operator= (PlayerCommand &&)=default
~PlayerCommand ()=default
PlayerCommand & command (const uint8_t &v) noexcept
uint8_t command () const noexcept
PlayerCommand & seekTo (const float &v) noexcept
float seekTo () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint8_t m_command { 0 }
float m_seekTo { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PlayerCommand`
static constexpr const char * TheLongName = `cluon.data.PlayerCommand`
Constructor & Destructor Documentation
PlayerCommand() [1/3]
cluon::data::PlayerCommand::PlayerCommand () [default]
PlayerCommand() [2/3]
cluon::data::PlayerCommand::PlayerCommand (const PlayerCommand &) [default]
PlayerCommand() [3/3]
cluon::data::PlayerCommand::PlayerCommand (PlayerCommand &&) [default]
 PlayerCommand()
cluon::data::PlayerCommand::~PlayerCommand () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::data::PlayerCommand::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, preVisit, visit, postVisit);
            
            doTripletForwardVisit(2, std::move("float"s), std::move("seekTo"s), m_seekTo, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void cluon::data::PlayerCommand::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, visitor);
                return;
            }
            
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("seekTo"s), m_seekTo, visitor);
                return;
            }
            
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void cluon::data::PlayerCommand::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("uint8_t"s), std::move("command"s), m_command, visitor);
            
            doVisit(2, std::move("float"s), std::move("seekTo"s), m_seekTo, visitor);
            
            visitor.postVisit();
        }
References doVisit().
command() [1/2]
uint8_t cluon::data::PlayerCommand::command () const [inline], [noexcept]
                                                {
            return m_command;
        }
command() [2/2]
PlayerCommand & cluon::data::PlayerCommand::command (const uint8_t & v) [inline], [noexcept]
                                                                 {
            m_command = v;
            return *this;
        }
ID()
static int32_t cluon::data::PlayerCommand::ID () [inline], [static]
                                   {
            return 9;
        }
LongName()
static const std::string cluon::data::PlayerCommand::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PlayerCommand & cluon::data::PlayerCommand::operator= (const PlayerCommand &) [default]
operator=() [2/2]
PlayerCommand & cluon::data::PlayerCommand::operator= (PlayerCommand &&) [default]
seekTo() [1/2]
float cluon::data::PlayerCommand::seekTo () const [inline], [noexcept]
                                             {
            return m_seekTo;
        }
seekTo() [2/2]
PlayerCommand & cluon::data::PlayerCommand::seekTo (const float & v) [inline], [noexcept]
                                                              {
            m_seekTo = v;
            return *this;
        }
ShortName()
static const std::string cluon::data::PlayerCommand::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_command
uint8_t cluon::data::PlayerCommand::m_command { 0 } [private]
m_seekTo
float cluon::data::PlayerCommand::m_seekTo { 0.0f } [private]
TheLongName
constexpr const char* cluon::data::PlayerCommand::TheLongName = `cluon.data.PlayerCommand` [static], [constexpr], [private]
TheShortName
constexpr const char* cluon::data::PlayerCommand::TheShortName = `PlayerCommand` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp