opendlv::proxy::WeightReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
WeightReading ()=default
WeightReading (const WeightReading &)=default
WeightReading & operator= (const WeightReading &)=default
WeightReading (WeightReading &&)=default
WeightReading & operator= (WeightReading &&)=default
~WeightReading ()=default
WeightReading & weight (const float &v) noexcept
float weight () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_weight { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `WeightReading`
static constexpr const char * TheLongName = `opendlv.proxy.WeightReading`
Constructor & Destructor Documentation
WeightReading() [1/3]
opendlv::proxy::WeightReading::WeightReading () [default]
WeightReading() [2/3]
opendlv::proxy::WeightReading::WeightReading (const WeightReading &) [default]
WeightReading() [3/3]
opendlv::proxy::WeightReading::WeightReading (WeightReading &&) [default]
 WeightReading()
opendlv::proxy::WeightReading::~WeightReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::WeightReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("weight"s), m_weight, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::WeightReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("weight"s), m_weight, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::WeightReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("weight"s), m_weight, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::WeightReading::ID () [inline], [static]
                                   {
            return 1050;
        }
LongName()
static const std::string opendlv::proxy::WeightReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
WeightReading & opendlv::proxy::WeightReading::operator= (const WeightReading &) [default]
operator=() [2/2]
WeightReading & opendlv::proxy::WeightReading::operator= (WeightReading &&) [default]
ShortName()
static const std::string opendlv::proxy::WeightReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
weight() [1/2]
float opendlv::proxy::WeightReading::weight () const [inline], [noexcept]
                                             {
            return m_weight;
        }
weight() [2/2]
WeightReading & opendlv::proxy::WeightReading::weight (const float & v) [inline], [noexcept]
                                                              {
            m_weight = v;
            return *this;
        }
Member Data Documentation
m_weight
float opendlv::proxy::WeightReading::m_weight { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::WeightReading::TheLongName = `opendlv.proxy.WeightReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::WeightReading::TheShortName = `WeightReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp