peg::LiteralString Class Reference
#include <cluon-complete.hpp>
Public Member Functions
LiteralString (const std::string &s, bool ignore_case)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::string lit_
bool ignore_case_
bool init_is_word_
bool is_word_
Constructor & Destructor Documentation
LiteralString()
peg::LiteralString::LiteralString (const std::string & s, bool ignore_case) [inline]
        : lit_(s)
        , ignore_case_(ignore_case)
        , init_is_word_(false)
        , is_word_(false)
        {}
Member Function Documentation
accept()
void peg::LiteralString::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::LiteralString::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                         {
    c.trace("LiteralString", s, n, sv, dt);
    return parse_literal(s, n, sv, c, dt, lit_, init_is_word_, is_word_, ignore_case_);
}
References peg::parse_literal(), and peg::Context::trace().
Member Data Documentation
ignore_case_
bool peg::LiteralString::ignore_case_
init_is_word_
bool peg::LiteralString::init_is_word_ [mutable]
is_word_
bool peg::LiteralString::is_word_ [mutable]
lit_
std::string peg::LiteralString::lit_
Referenced by peg::DetectLeftRecursion::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp