cluon::ToProtoVisitor Class Reference
#include <cluon-complete.hpp>
Public Member Functions
ToProtoVisitor ()=default
~ToProtoVisitor ()=default
std::string encodedData () const noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Private Member Functions
ToProtoVisitor (const ToProtoVisitor &)=delete
ToProtoVisitor (ToProtoVisitor &&)=delete
ToProtoVisitor & operator= (const ToProtoVisitor &)=delete
ToProtoVisitor & operator= (ToProtoVisitor &&)=delete
std::size_t encode (std::ostream &o, bool &v) noexcept
std::size_t encode (std::ostream &o, int8_t &v) noexcept
std::size_t encode (std::ostream &o, uint8_t &v) noexcept
std::size_t encode (std::ostream &o, int16_t &v) noexcept
std::size_t encode (std::ostream &o, uint16_t &v) noexcept
std::size_t encode (std::ostream &o, int32_t &v) noexcept
std::size_t encode (std::ostream &o, uint32_t &v) noexcept
std::size_t encode (std::ostream &o, int64_t &v) noexcept
std::size_t encode (std::ostream &o, uint64_t &v) noexcept
std::size_t encode (std::ostream &o, float &v) noexcept
std::size_t encode (std::ostream &o, double &v) noexcept
std::size_t encode (std::ostream &o, const std::string &v) noexcept
uint8_t toZigZag8 (int8_t v) noexcept
uint16_t toZigZag16 (int16_t v) noexcept
uint32_t toZigZag32 (int32_t v) noexcept
uint64_t toZigZag64 (int64_t v) noexcept
std::size_t toVarInt (std::ostream &out, uint64_t v) noexcept
template<typename T >
std::size_t toKeyValue (uint32_t fieldIdentifier, T &v) noexcept
uint64_t encodeKey (uint32_t fieldIdentifier, uint8_t protoType) noexcept
Private Attributes
std::stringstream m_buffer {``}
Detailed Description
This class encodes a given message in Proto format.
Constructor & Destructor Documentation
ToProtoVisitor() [1/3]
cluon::ToProtoVisitor::ToProtoVisitor (const ToProtoVisitor &) [private], [delete]
ToProtoVisitor() [2/3]
cluon::ToProtoVisitor::ToProtoVisitor (ToProtoVisitor &&) [private], [delete]
ToProtoVisitor() [3/3]
cluon::ToProtoVisitor::ToProtoVisitor () [default]
 ToProtoVisitor()
cluon::ToProtoVisitor::~ToProtoVisitor () [default]
Member Function Documentation
encode() [1/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, bool & v) [inline], [private], [noexcept]
                                                                       {
    uint64_t _v{(v ? 1u : 0u)};
    return toVarInt(o, _v);
}
encode() [2/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, const std::string & v) [inline], [private], [noexcept]
                                                                                  {
    const std::size_t LENGTH = v.length();
    std::size_t size = toVarInt(o, LENGTH);
    o.write(v.c_str(), static_cast<std::streamsize>(LENGTH)); // LENGTH won't be negative.
    return size + LENGTH;
}
encode() [3/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, double & v) [inline], [private], [noexcept]
                                                                         {
    // Store 8 bytes as little endian encoding.
    uint64_t _v{0};
    std::memmove(&_v, &v, sizeof(double));
    _v = htole64(_v);
    o.write(reinterpret_cast<const char *>(&_v), sizeof(uint64_t)); // NOLINT
    return sizeof(uint64_t);
}
encode() [4/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, float & v) [inline], [private], [noexcept]
                                                                        {
    // Store 4 bytes as little endian encoding.
    uint32_t _v{0};
    std::memmove(&_v, &v, sizeof(float));
    _v = htole32(_v);
    o.write(reinterpret_cast<const char *>(&_v), sizeof(uint32_t)); // NOLINT
    return sizeof(uint32_t);
}
encode() [5/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, int16_t & v) [inline], [private], [noexcept]
                                                                          {
    uint64_t _v = toZigZag16(v);
    return toVarInt(o, _v);
}
encode() [6/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, int32_t & v) [inline], [private], [noexcept]
                                                                          {
    uint64_t _v = toZigZag32(v);
    return toVarInt(o, _v);
}
encode() [7/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, int64_t & v) [inline], [private], [noexcept]
                                                                          {
    uint64_t _v = toZigZag64(v);
    return toVarInt(o, _v);
}
encode() [8/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, int8_t & v) [inline], [private], [noexcept]
                                                                         {
    uint64_t _v = toZigZag8(v);
    return toVarInt(o, _v);
}
encode() [9/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, uint16_t & v) [inline], [private], [noexcept]
                                                                           {
    uint64_t _v = v;
    return toVarInt(o, _v);
}
encode() [10/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, uint32_t & v) [inline], [private], [noexcept]
                                                                           {
    uint64_t _v = v;
    return toVarInt(o, _v);
}
encode() [11/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, uint64_t & v) [inline], [private], [noexcept]
                                                                           {
    return toVarInt(o, v);
}
encode() [12/12]
std::size_t cluon::ToProtoVisitor::encode (std::ostream & o, uint8_t & v) [inline], [private], [noexcept]
                                                                          {
    uint64_t _v = v;
    return toVarInt(o, _v);
}
encodedData()
std::string cluon::ToProtoVisitor::encodedData () const [inline], [noexcept]
Returns
Encoded data in Proto format.
                                                            {
    std::string s{m_buffer.str()};
    return s;
}
References m_buffer.
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), cluon::OD4Session::send(), cluon::serializeEnvelope(), and visit().
encodeKey()
uint64_t cluon::ToProtoVisitor::encodeKey (uint32_t fieldIdentifier, uint8_t protoType) [inline], [private], [noexcept]
This method creates the key for the key/value pair in Protobuf format.
Parameters
fieldIdentifier Field identifier.
protoType Protobuf type identifier.
Returns
Protobuf fieldIdentifier/key pair.
                                                                                              {
    return (fieldIdentifier << 0x3) | protoType;
}
References fieldIdentifier().
operator=() [1/2]
ToProtoVisitor & cluon::ToProtoVisitor::operator= (const ToProtoVisitor &) [private], [delete]
operator=() [2/2]
ToProtoVisitor & cluon::ToProtoVisitor::operator= (ToProtoVisitor &&) [private], [delete]
postVisit()
void cluon::ToProtoVisitor::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::ToProtoVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                               {
    (void)id;
    (void)shortName;
    (void)longName;
}
toKeyValue()
template<typename T >
std::size_t cluon::ToProtoVisitor::toKeyValue (uint32_t fieldIdentifier, T & v) [inline], [private], [noexcept]
This method creates a key/value pair encoded in Proto format.
Parameters
fieldIdentifier Field identifier.
v Value to encode.
Returns
Bytes written.
                                                                  {
        std::size_t size{0};
        uint64_t key = encodeKey(fieldIdentifier, static_cast<uint8_t>(ProtoConstants::VARINT));
        size += toVarInt(m_buffer, key);
        size += encode(m_buffer, v);
        return size;
    }
References fieldIdentifier(), and cluon::VARINT.
toVarInt()
std::size_t cluon::ToProtoVisitor::toVarInt (std::ostream & out, uint64_t v) [inline], [private], [noexcept]
This method encodes a given value in VarInt.
Parameters
out std::ostream to encode to.
v Value to encode.
Returns
Bytes written.
                                                                              {
    // Minimum size is of the encoded data.
    std::size_t size{1};
    uint8_t b{0};
    while (0x7f < v) {
        // Use the MSB to indicate value overflow for more bytes to come.
        b = (static_cast<uint8_t>(v & 0x7f)) | 0x80;
        out.put(static_cast<char>(b));
        v >>= 7;
        size++;
    }
    // Write final byte.
    b = (static_cast<uint8_t>(v)) & 0x7f;
    out.put(static_cast<char>(b));
    return size;
}
toZigZag16()
uint16_t cluon::ToProtoVisitor::toZigZag16 (int16_t v) [inline], [private], [noexcept]
                                                             {
    return static_cast<uint16_t>((v << 1) ^ (v >> ((sizeof(v) * 8) - 1)));
}
toZigZag32()
uint32_t cluon::ToProtoVisitor::toZigZag32 (int32_t v) [inline], [private], [noexcept]
                                                             {
    return static_cast<uint32_t>((v << 1) ^ (v >> ((sizeof(v) * 8) - 1)));
}
toZigZag64()
uint64_t cluon::ToProtoVisitor::toZigZag64 (int64_t v) [inline], [private], [noexcept]
                                                             {
    return static_cast<uint64_t>((v << 1) ^ (v >> ((sizeof(v) * 8) - 1)));
}
toZigZag8()
uint8_t cluon::ToProtoVisitor::toZigZag8 (int8_t v) [inline], [private], [noexcept]
                                                          {
    return static_cast<uint8_t>((v << 1) ^ (v >> ((sizeof(v) * 8) - 1)));
}
visit() [1/14]
template<typename T >
void cluon::ToProtoVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                        {
        (void)typeName;
        (void)name;
        toVarInt(m_buffer, std::move(encodeKey(id, static_cast<uint8_t>(ProtoConstants::LENGTH_DELIMITED))));
        cluon::ToProtoVisitor nestedProtoEncoder;
        value.accept(nestedProtoEncoder);
        encode(m_buffer, std::move(nestedProtoEncoder.encodedData()));
    }
References encodedData(), and cluon::LENGTH_DELIMITED.
visit() [2/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                       {
    (void)typeName;
    (void)name;
    toKeyValue<bool>(id, v);
}
visit() [3/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                       {
    (void)typeName;
    (void)name;
    uint8_t _v = static_cast<uint8_t>(v); // NOLINT
    toKeyValue<uint8_t>(id, _v);
}
visit() [4/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    uint64_t key = encodeKey(id, static_cast<uint8_t>(ProtoConstants::EIGHT_BYTES));
    toVarInt(m_buffer, key);
    encode(m_buffer, v);
}
References cluon::EIGHT_BYTES.
visit() [5/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                        {
    (void)typeName;
    (void)name;
    uint64_t key = encodeKey(id, static_cast<uint8_t>(ProtoConstants::FOUR_BYTES));
    toVarInt(m_buffer, key);
    encode(m_buffer, v);
}
References cluon::FOUR_BYTES.
visit() [6/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    toKeyValue<int16_t>(id, v);
}
visit() [7/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    toKeyValue<int32_t>(id, v);
}
visit() [8/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    toKeyValue<int64_t>(id, v);
}
visit() [9/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    (void)name;
    toKeyValue<int8_t>(id, v);
}
visit() [10/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                            {
    (void)typeName;
    (void)name;
    uint64_t key = encodeKey(id, static_cast<uint8_t>(ProtoConstants::LENGTH_DELIMITED));
    toVarInt(m_buffer, key);
    encode(m_buffer, v);
}
References cluon::LENGTH_DELIMITED.
visit() [11/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    toKeyValue<uint16_t>(id, v);
}
visit() [12/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    toKeyValue<uint32_t>(id, v);
}
visit() [13/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    (void)name;
    toKeyValue<uint64_t>(id, v);
}
visit() [14/14]
void cluon::ToProtoVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    (void)name;
    toKeyValue<uint8_t>(id, v);
}
Member Data Documentation
m_buffer
std::stringstream cluon::ToProtoVisitor::m_buffer {``} [private]
Referenced by encodedData().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp