cluon::ToLCMVisitor Class Reference
#include <cluon-complete.hpp>
Public Member Functions
ToLCMVisitor ()=default
~ToLCMVisitor ()=default
std::string encodedData (bool withHash=true) const noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Private Member Functions
ToLCMVisitor (const ToLCMVisitor &)=delete
ToLCMVisitor (ToLCMVisitor &&)=delete
ToLCMVisitor & operator= (const ToLCMVisitor &)=delete
ToLCMVisitor & operator= (ToLCMVisitor &&)=delete
int64_t hash () const noexcept
void calculateHash (char c) noexcept
void calculateHash (const std::string &s) noexcept
Private Attributes
int64_t m_hash {0x12345678}
std::stringstream m_buffer {``}
std::vector< int64_t > m_hashes {}
Detailed Description
This class encodes a given message in LCM format.
Constructor & Destructor Documentation
ToLCMVisitor() [1/3]
cluon::ToLCMVisitor::ToLCMVisitor (const ToLCMVisitor &) [private], [delete]
ToLCMVisitor() [2/3]
cluon::ToLCMVisitor::ToLCMVisitor (ToLCMVisitor &&) [private], [delete]
ToLCMVisitor() [3/3]
cluon::ToLCMVisitor::ToLCMVisitor () [default]
 ToLCMVisitor()
cluon::ToLCMVisitor::~ToLCMVisitor () [default]
Member Function Documentation
calculateHash() [1/2]
void cluon::ToLCMVisitor::calculateHash (char c) [inline], [private], [noexcept]
                                                       {
    m_hash = ((m_hash << 8) ^ (m_hash >> 55)) + c;
}
calculateHash() [2/2]
void cluon::ToLCMVisitor::calculateHash (const std::string & s) [inline], [private], [noexcept]
                                                                   {
    const std::string tmp{(s.length() > 255 ? s.substr(0, 255) : s)};
    const uint8_t length{static_cast<uint8_t>(tmp.length())};
    calculateHash(static_cast<char>(length));
    for (auto c : s) { calculateHash(c); }
}
encodedData()
std::string cluon::ToLCMVisitor::encodedData (bool withHash = true) const [inline], [noexcept]
Parameters
withHash True if the hash value from the fields shall be included.
Returns
Encoded data in LCM format.
                                                                       {
    int64_t _hash = hash();
    _hash = static_cast<int64_t>(htobe64(_hash));
    std::stringstream hashBuffer;
    hashBuffer.write(reinterpret_cast<const char *>(&_hash), sizeof(int64_t));
    const std::string s{(withHash ? hashBuffer.str() : "") + m_buffer.str()};
    return s;
}
Referenced by visit().
hash()
int64_t cluon::ToLCMVisitor::hash () const [inline], [private], [noexcept]
                                                 {
    // Apply ZigZag encoding for hash from this message's fields and depending
    // hashes for complex nested types.
    int64_t tmp{m_hash};
    for (int64_t v : m_hashes) { tmp += v; }
    const int64_t hash = (tmp << 1) + ((tmp >> 63) & 1);
    return hash;
}
References hash(), m_hash, and m_hashes.
Referenced by hash(), and visit().
operator=() [1/2]
ToLCMVisitor & cluon::ToLCMVisitor::operator= (const ToLCMVisitor &) [private], [delete]
operator=() [2/2]
ToLCMVisitor & cluon::ToLCMVisitor::operator= (ToLCMVisitor &&) [private], [delete]
postVisit()
void cluon::ToLCMVisitor::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::ToLCMVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                             {
    (void)id;
    (void)shortName;
    (void)longName;
}
visit() [1/14]
template<typename T >
void cluon::ToLCMVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                        {
        (void)id;
        (void)typeName;
        calculateHash(name);
        calculateHash(0);
        // No hash for the type but for name and dimension.
        cluon::ToLCMVisitor nestedLCMEncoder;
        value.accept(nestedLCMEncoder);
        constexpr bool WITH_HASH{false};
        const std::string s = nestedLCMEncoder.encodedData(WITH_HASH);
        m_buffer.write(s.c_str(), static_cast<std::streamsize>(s.size()));
        // Save this complex field's hash for later to compute final hash.
        m_hashes.push_back(nestedLCMEncoder.hash());
    }
References encodedData(), and hash().
visit() [2/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                     {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("boolean");
    calculateHash(0);
    m_buffer.write(reinterpret_cast<char *>(&v), sizeof(bool));
}
visit() [3/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                     {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.write(reinterpret_cast<char *>(&v), sizeof(char));
}
visit() [4/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                       {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("double");
    calculateHash(0);
    int64_t _v{0};
    std::memmove(&_v, &v, sizeof(int64_t));
    _v = static_cast<int64_t>(htobe64(_v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int64_t));
}
visit() [5/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                      {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("float");
    calculateHash(0);
    int32_t _v{0};
    std::memmove(&_v, &v, sizeof(int32_t));
    _v = static_cast<int32_t>(htobe32(_v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int32_t));
}
visit() [6/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                        {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int16_t");
    calculateHash(0);
    int16_t _v = static_cast<int16_t>(htobe16(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int16_t));
}
visit() [7/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                        {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int32_t");
    calculateHash(0);
    int32_t _v = static_cast<int32_t>(htobe32(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int32_t));
}
visit() [8/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                        {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int64_t");
    calculateHash(0);
    int64_t _v = static_cast<int64_t>(htobe64(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int64_t));
}
visit() [9/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                       {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.write(reinterpret_cast<char *>(&v), sizeof(int8_t));
}
visit() [10/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                          {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("string");
    calculateHash(0);
    const std::size_t LENGTH = v.length();
    int32_t _v = static_cast<int32_t>(htobe32(static_cast<uint32_t>(LENGTH + 1)));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int32_t));
    m_buffer.write(v.c_str(), static_cast<std::streamsize>(LENGTH)); // LENGTH won't be negative.
    m_buffer << '\0';
}
visit() [11/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                         {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int16_t");
    calculateHash(0);
    int16_t _v = static_cast<int16_t>(htobe16(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int16_t));
}
visit() [12/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                         {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int32_t");
    calculateHash(0);
    int32_t _v = static_cast<int32_t>(htobe32(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int32_t));
}
visit() [13/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                         {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int64_t");
    calculateHash(0);
    int64_t _v = static_cast<int64_t>(htobe64(v));
    m_buffer.write(reinterpret_cast<char *>(&_v), sizeof(int64_t));
}
visit() [14/14]
void cluon::ToLCMVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                        {
    (void)id;
    (void)typeName;
    calculateHash(name);
    calculateHash("int8_t");
    calculateHash(0);
    m_buffer.write(reinterpret_cast<char *>(&v), sizeof(uint8_t));
}
Member Data Documentation
m_buffer
std::stringstream cluon::ToLCMVisitor::m_buffer {``} [private]
m_hash
int64_t cluon::ToLCMVisitor::m_hash {0x12345678} [private]
Referenced by hash().
m_hashes
std::vector<int64_t> cluon::ToLCMVisitor::m_hashes {} [private]
Referenced by hash().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp