opendlv::logic::perception::GroundSurface Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSurface ()=default
GroundSurface (const GroundSurface &)=default
GroundSurface & operator= (const GroundSurface &)=default
GroundSurface (GroundSurface &&)=default
GroundSurface & operator= (GroundSurface &&)=default
~GroundSurface ()=default
GroundSurface & surfaceId (const uint32_t &v) noexcept
uint32_t surfaceId () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_surfaceId { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSurface`
static constexpr const char * TheLongName = `opendlv.logic.perception.GroundSurface`
Constructor & Destructor Documentation
GroundSurface() [1/3]
opendlv::logic::perception::GroundSurface::GroundSurface () [default]
GroundSurface() [2/3]
opendlv::logic::perception::GroundSurface::GroundSurface (const GroundSurface &) [default]
GroundSurface() [3/3]
opendlv::logic::perception::GroundSurface::GroundSurface (GroundSurface &&) [default]
 GroundSurface()
opendlv::logic::perception::GroundSurface::~GroundSurface () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::GroundSurface::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurface::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::GroundSurface::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("surfaceId"s), m_surfaceId, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::perception::GroundSurface::ID () [inline], [static]
                                   {
            return 1140;
        }
LongName()
static const std::string opendlv::logic::perception::GroundSurface::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSurface & opendlv::logic::perception::GroundSurface::operator= (const GroundSurface &) [default]
operator=() [2/2]
GroundSurface & opendlv::logic::perception::GroundSurface::operator= (GroundSurface &&) [default]
ShortName()
static const std::string opendlv::logic::perception::GroundSurface::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
surfaceId() [1/2]
uint32_t opendlv::logic::perception::GroundSurface::surfaceId () const [inline], [noexcept]
                                                   {
            return m_surfaceId;
        }
surfaceId() [2/2]
GroundSurface & opendlv::logic::perception::GroundSurface::surfaceId (const uint32_t & v) [inline], [noexcept]
                                                                    {
            m_surfaceId = v;
            return *this;
        }
Member Data Documentation
m_surfaceId
uint32_t opendlv::logic::perception::GroundSurface::m_surfaceId { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::GroundSurface::TheLongName = `opendlv.logic.perception.GroundSurface` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::GroundSurface::TheShortName = `GroundSurface` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp