opendlv::proxy::TemperatureReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
TemperatureReading ()=default
TemperatureReading (const TemperatureReading &)=default
TemperatureReading & operator= (const TemperatureReading &)=default
TemperatureReading (TemperatureReading &&)=default
TemperatureReading & operator= (TemperatureReading &&)=default
~TemperatureReading ()=default
TemperatureReading & temperature (const float &v) noexcept
float temperature () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_temperature { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `TemperatureReading`
static constexpr const char * TheLongName = `opendlv.proxy.TemperatureReading`
Constructor & Destructor Documentation
TemperatureReading() [1/3]
opendlv::proxy::TemperatureReading::TemperatureReading () [default]
TemperatureReading() [2/3]
opendlv::proxy::TemperatureReading::TemperatureReading (const TemperatureReading &) [default]
TemperatureReading() [3/3]
opendlv::proxy::TemperatureReading::TemperatureReading (TemperatureReading &&) [default]
 TemperatureReading()
opendlv::proxy::TemperatureReading::~TemperatureReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::TemperatureReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::TemperatureReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::TemperatureReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::TemperatureReading::ID () [inline], [static]
                                   {
            return 1035;
        }
LongName()
static const std::string opendlv::proxy::TemperatureReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
TemperatureReading & opendlv::proxy::TemperatureReading::operator= (const TemperatureReading &) [default]
operator=() [2/2]
TemperatureReading & opendlv::proxy::TemperatureReading::operator= (TemperatureReading &&) [default]
ShortName()
static const std::string opendlv::proxy::TemperatureReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
temperature() [1/2]
float opendlv::proxy::TemperatureReading::temperature () const [inline], [noexcept]
                                                  {
            return m_temperature;
        }
temperature() [2/2]
TemperatureReading & opendlv::proxy::TemperatureReading::temperature (const float & v) [inline], [noexcept]
                                                                        {
            m_temperature = v;
            return *this;
        }
Member Data Documentation
m_temperature
float opendlv::proxy::TemperatureReading::m_temperature { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::TemperatureReading::TheLongName = `opendlv.proxy.TemperatureReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::TemperatureReading::TheShortName = `TemperatureReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp