peg::any Class Reference
#include <cluon-complete.hpp>
Classes
struct holder
struct placeholder
Public Member Functions
any ()
any (const any &rhs)
any (any &&rhs)
template<typename T >
any (const T &value)
any & operator= (const any &rhs)
any & operator= (any &&rhs)
~any ()
bool is_undefined () const
template<typename T , typename std::enable_if<!std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
T & get ()
template<typename T , typename std::enable_if< std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
T & get ()
template<typename T , typename std::enable_if<!std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
const T & get () const
template<typename T , typename std::enable_if< std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
const any & get () const
Private Member Functions
placeholder * clone () const
Private Attributes
placeholder * content_
Constructor & Destructor Documentation
any() [1/4]
peg::any::any () [inline]
: content_(nullptr) {}
any() [2/4]
peg::any::any (const any & rhs) [inline]
: content_(rhs.clone()) {}
any() [3/4]
peg::any::any (any && rhs) [inline]
                   : content_(rhs.content_) {
        rhs.content_ = nullptr;
    }
any() [4/4]
template<typename T >
peg::any::any (const T & value) [inline]
: content_(new holder<T>(value)) {}
 any()
peg::any::~any () [inline]
           {
        delete content_;
    }
Member Function Documentation
clone()
placeholder * peg::any::clone () const [inline], [private]
                               {
        return content_ ? content_->clone() : nullptr;
    }
References peg::any::placeholder::clone().
Referenced by operator=().
get() [1/4]
template<typename T , typename std::enable_if<!std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
T & peg::any::get () [inline]
             {
        if (!content_) {
            throw std::bad_cast();
        }
        auto p = dynamic_cast<holder<T>*>(content_);
        assert(p);
        if (!p) {
            throw std::bad_cast();
        }
        return p->value_;
    }
References p.
Referenced by peg::SemanticValues::transform().
get() [2/4]
template<typename T , typename std::enable_if< std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
T & peg::any::get () [inline]
             {
        return *this;
    }
get() [3/4]
template<typename T , typename std::enable_if<!std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
const T & peg::any::get () const [inline]
                         {
        assert(content_);
        auto p = dynamic_cast<holder<T>*>(content_);
        assert(p);
        if (!p) {
            throw std::bad_cast();
        }
        return p->value_;
    }
References p.
get() [4/4]
template<typename T , typename std::enable_if< std::is_same< T, any >::value, std::nullptr_t >::type = nullptr>
const any & peg::any::get () const [inline]
                           {
        return *this;
    }
is_undefined()
bool peg::any::is_undefined () const [inline]
                              {
        return content_ == nullptr;
    }
operator=() [1/2]
any & peg::any::operator= (any && rhs) [inline]
                              {
        if (this != &rhs) {
            if (content_) {
                delete content_;
            }
            content_ = rhs.content_;
            rhs.content_ = nullptr;
        }
        return *this;
    }
References content_.
operator=() [2/2]
any & peg::any::operator= (const any & rhs) [inline]
                                   {
        if (this != &rhs) {
            if (content_) {
                delete content_;
            }
            content_ = rhs.clone();
        }
        return *this;
    }
References clone().
Member Data Documentation
content_
placeholder* peg::any::content_ [private]
Referenced by operator=().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp