cluon::MetaMessage Class Reference
#include <cluon-complete.hpp>
Classes
class MetaField
Public Member Functions
MetaMessage () noexcept
MetaMessage (const MetaMessage &)=default
MetaMessage (MetaMessage &&)=default
MetaMessage & operator= (const MetaMessage &)=default
MetaMessage & operator= (MetaMessage &&)=default
MetaMessage & add (MetaField &&mf) noexcept
const std::vector< MetaField > & listOfMetaFields () const noexcept
void accept (const std::function< void(const MetaMessage &)> &visit)
std::string packageName () const noexcept
MetaMessage & packageName (const std::string &v) noexcept
std::string messageName () const noexcept
MetaMessage & messageName (const std::string &v) noexcept
int32_t messageIdentifier () const noexcept
MetaMessage & messageIdentifier (int32_t v) noexcept
Private Attributes
std::string m_packageName {``}
std::string m_messageName {``}
int32_t m_messageIdentifier {0}
std::vector< MetaField > m_listOfMetaFields {}
Detailed Description
This class provides a generic description for a message. It is internally used during the processing of message specifications to generate targets like C++ or .proto files.
Constructor & Destructor Documentation
MetaMessage() [1/3]
cluon::MetaMessage::MetaMessage () [inline], [noexcept]
{}
MetaMessage() [2/3]
cluon::MetaMessage::MetaMessage (const MetaMessage &) [default]
MetaMessage() [3/3]
cluon::MetaMessage::MetaMessage (MetaMessage &&) [default]
Member Function Documentation
accept()
void cluon::MetaMessage::accept (const std::function< void(const MetaMessage &)> & visit) [inline]
This method can be used to visit this instance and propagate information details about the contained fields.
Parameters
visit std::function object to be called to visit this MetaMessage.
                                                                                   {
    visit(*this);
}
add()
MetaMessage & cluon::MetaMessage::add (MetaMessage::MetaField && mf) [inline], [noexcept]
This method adds a metafield to this meta message.
Parameters
mf Meta field to be added.
Returns
Reference to this instance.
                                                                       {
    m_listOfMetaFields.emplace_back(std::move(mf));
    return *this;
}
References m_listOfMetaFields, and mf.
Referenced by cluon::GenericMessage::GenericMessageVisitor::visit().
listOfMetaFields()
const std::vector< MetaMessage::MetaField > & cluon::MetaMessage::listOfMetaFields () const [inline], [noexcept]
This method returns a vector of current meta fields.
Returns
Meta fields from this meta message.
                                                                                           {
    return m_listOfMetaFields;
}
References m_listOfMetaFields.
Referenced by cluon::GenericMessage::createFrom().
messageIdentifier() [1/2]
int32_t cluon::MetaMessage::messageIdentifier () const [inline], [noexcept]
Returns
Message identifier.
                                                             {
    return m_messageIdentifier;
}
References m_messageIdentifier.
Referenced by cluon::GenericMessage::ID().
messageIdentifier() [2/2]
MetaMessage & cluon::MetaMessage::messageIdentifier (int32_t v) [inline], [noexcept]
This method sets the message identifier.
Parameters
v Message identifier for this message.
Returns
Reference to this instance.
                                                                     {
    m_messageIdentifier = v;
    return *this;
}
References m_messageIdentifier.
messageName() [1/2]
std::string cluon::MetaMessage::messageName () const [inline], [noexcept]
Returns
Message name.
                                                         {
    return m_messageName;
}
References m_messageName.
Referenced by cluon::GenericMessage::createFrom(), and cluon::GenericMessage::LongName().
messageName() [2/2]
MetaMessage & cluon::MetaMessage::messageName (const std::string & v) [inline], [noexcept]
This method sets the message name.
Parameters
v Message name for this message.
Returns
Reference to this instance.
                                                                        {
    m_messageName = v;
    return *this;
}
References m_messageName.
operator=() [1/2]
MetaMessage & cluon::MetaMessage::operator= (const MetaMessage &) [default]
operator=() [2/2]
MetaMessage & cluon::MetaMessage::operator= (MetaMessage &&) [default]
packageName() [1/2]
std::string cluon::MetaMessage::packageName () const [inline], [noexcept]
Returns
Package name.
                                                         {
    return m_packageName;
}
References m_packageName.
Referenced by cluon::GenericMessage::LongName().
packageName() [2/2]
MetaMessage & cluon::MetaMessage::packageName (const std::string & v) [inline], [noexcept]
This method sets the package name.
Parameters
v Package name for this message.
Returns
Reference to this instance.
                                                                        {
    m_packageName = v;
    return *this;
}
References m_packageName.
Member Data Documentation
m_listOfMetaFields
std::vector<MetaField> cluon::MetaMessage::m_listOfMetaFields {} [private]
Referenced by add(), and listOfMetaFields().
m_messageIdentifier
int32_t cluon::MetaMessage::m_messageIdentifier {0} [private]
Referenced by messageIdentifier().
m_messageName
std::string cluon::MetaMessage::m_messageName {``} [private]
Referenced by messageName().
m_packageName
std::string cluon::MetaMessage::m_packageName {``} [private]
Referenced by packageName().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp