opendlv::proxy::PedalPositionReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PedalPositionReading ()=default
PedalPositionReading (const PedalPositionReading &)=default
PedalPositionReading & operator= (const PedalPositionReading &)=default
PedalPositionReading (PedalPositionReading &&)=default
PedalPositionReading & operator= (PedalPositionReading &&)=default
~PedalPositionReading ()=default
PedalPositionReading & position (const float &v) noexcept
float position () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_position { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PedalPositionReading`
static constexpr const char * TheLongName = `opendlv.proxy.PedalPositionReading`
Constructor & Destructor Documentation
PedalPositionReading() [1/3]
opendlv::proxy::PedalPositionReading::PedalPositionReading () [default]
PedalPositionReading() [2/3]
opendlv::proxy::PedalPositionReading::PedalPositionReading (const PedalPositionReading &) [default]
PedalPositionReading() [3/3]
opendlv::proxy::PedalPositionReading::PedalPositionReading (PedalPositionReading &&) [default]
 PedalPositionReading()
opendlv::proxy::PedalPositionReading::~PedalPositionReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PedalPositionReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("position"s), m_position, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PedalPositionReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("position"s), m_position, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PedalPositionReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("position"s), m_position, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::PedalPositionReading::ID () [inline], [static]
                                   {
            return 1041;
        }
LongName()
static const std::string opendlv::proxy::PedalPositionReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PedalPositionReading & opendlv::proxy::PedalPositionReading::operator= (const PedalPositionReading &) [default]
operator=() [2/2]
PedalPositionReading & opendlv::proxy::PedalPositionReading::operator= (PedalPositionReading &&) [default]
position() [1/2]
float opendlv::proxy::PedalPositionReading::position () const [inline], [noexcept]
                                               {
            return m_position;
        }
position() [2/2]
PedalPositionReading & opendlv::proxy::PedalPositionReading::position (const float & v) [inline], [noexcept]
                                                                       {
            m_position = v;
            return *this;
        }
ShortName()
static const std::string opendlv::proxy::PedalPositionReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_position
float opendlv::proxy::PedalPositionReading::m_position { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::PedalPositionReading::TheLongName = `opendlv.proxy.PedalPositionReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PedalPositionReading::TheShortName = `PedalPositionReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp