opendlv::logic::perception::ObjectAngularBlob Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ObjectAngularBlob ()=default
ObjectAngularBlob (const ObjectAngularBlob &)=default
ObjectAngularBlob & operator= (const ObjectAngularBlob &)=default
ObjectAngularBlob (ObjectAngularBlob &&)=default
ObjectAngularBlob & operator= (ObjectAngularBlob &&)=default
~ObjectAngularBlob ()=default
ObjectAngularBlob & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
ObjectAngularBlob & width (const float &v) noexcept
float width () const noexcept
ObjectAngularBlob & height (const float &v) noexcept
float height () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
float m_width { 0.0f }
float m_height { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `ObjectAngularBlob`
static constexpr const char * TheLongName = `opendlv.logic.perception.ObjectAngularBlob`
Constructor & Destructor Documentation
ObjectAngularBlob() [1/3]
opendlv::logic::perception::ObjectAngularBlob::ObjectAngularBlob () [default]
ObjectAngularBlob() [2/3]
opendlv::logic::perception::ObjectAngularBlob::ObjectAngularBlob (const ObjectAngularBlob &) [default]
ObjectAngularBlob() [3/3]
opendlv::logic::perception::ObjectAngularBlob::ObjectAngularBlob (ObjectAngularBlob &&) [default]
 ObjectAngularBlob()
opendlv::logic::perception::ObjectAngularBlob::~ObjectAngularBlob () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::ObjectAngularBlob::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("width"s), m_width, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("height"s), m_height, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::ObjectAngularBlob::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("width"s), m_width, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("height"s), m_height, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::ObjectAngularBlob::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            doVisit(2, std::move("float"s), std::move("width"s), m_width, visitor);
            doVisit(3, std::move("float"s), std::move("height"s), m_height, visitor);
            visitor.postVisit();
        }
References doVisit().
height() [1/2]
float opendlv::logic::perception::ObjectAngularBlob::height () const [inline], [noexcept]
                                             {
            return m_height;
        }
height() [2/2]
ObjectAngularBlob & opendlv::logic::perception::ObjectAngularBlob::height (const float & v) [inline], [noexcept]
                                                                  {
            m_height = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::perception::ObjectAngularBlob::ID () [inline], [static]
                                   {
            return 1135;
        }
LongName()
static const std::string opendlv::logic::perception::ObjectAngularBlob::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::ObjectAngularBlob::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
ObjectAngularBlob & opendlv::logic::perception::ObjectAngularBlob::objectId (const uint32_t & v) [inline], [noexcept]
                                                                       {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
ObjectAngularBlob & opendlv::logic::perception::ObjectAngularBlob::operator= (const ObjectAngularBlob &) [default]
operator=() [2/2]
ObjectAngularBlob & opendlv::logic::perception::ObjectAngularBlob::operator= (ObjectAngularBlob &&) [default]
ShortName()
static const std::string opendlv::logic::perception::ObjectAngularBlob::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
width() [1/2]
float opendlv::logic::perception::ObjectAngularBlob::width () const [inline], [noexcept]
                                            {
            return m_width;
        }
width() [2/2]
ObjectAngularBlob & opendlv::logic::perception::ObjectAngularBlob::width (const float & v) [inline], [noexcept]
                                                                 {
            m_width = v;
            return *this;
        }
Member Data Documentation
m_height
float opendlv::logic::perception::ObjectAngularBlob::m_height { 0.0f } [private]
m_objectId
uint32_t opendlv::logic::perception::ObjectAngularBlob::m_objectId { 0 } [private]
m_width
float opendlv::logic::perception::ObjectAngularBlob::m_width { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::perception::ObjectAngularBlob::TheLongName = `opendlv.logic.perception.ObjectAngularBlob` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::ObjectAngularBlob::TheShortName = `ObjectAngularBlob` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp