linb::any Class Reference
#include <cluon-complete.hpp>
Classes
struct requires_allocation
Whether the type T must be dynamically allocated or can be stored on the stack.
union storage_union
struct vtable_dynamic
VTable for dynamically allocated storage.
struct vtable_stack
VTable for stack allocated storage.
struct vtable_type
Base VTable specification.
Public Member Functions
any ()
Constructs an object of type any with an empty state.
any (const any &rhs)
Constructs an object of type any with an equivalent state as other.
any (any &&rhs) noexcept
~any ()
Same effect as this->clear().
template<typename ValueType , typename = typename std::enable_if<!std::is_same<typename std::decay<ValueType>::type, any>::value>::type>
any (ValueType &&value)
any & operator= (const any &rhs)
Has the same effect as any(rhs).swap(*this). No effects if an exception is thrown.
any & operator= (any &&rhs) noexcept
template<typename ValueType , typename = typename std::enable_if<!std::is_same<typename std::decay<ValueType>::type, any>::value>::type>
any & operator= (ValueType &&value)
void clear () noexcept
If not empty, destroys the contained object.
bool empty () const noexcept
Returns true if *this has no contained object, otherwise false.
const std::type_info & type () const noexcept
If *this has a contained object of type T, typeid(T); otherwise typeid(void).
void swap (any &rhs) noexcept
Exchange the states of *this and rhs.
Protected Member Functions
template<typename T >
const T * cast () const noexcept
Casts (with no type_info checks) the storage pointer as const T*.
template<typename T >
T * cast () noexcept
Casts (with no type_info checks) the storage pointer as T*.
Private Member Functions
template<typename ValueType , typename T >
std::enable_if< requires_allocation< T >::value >::type do_construct (ValueType &&value)
template<typename ValueType , typename T >
std::enable_if<!requires_allocation< T >::value >::type do_construct (ValueType &&value)
template<typename ValueType >
void construct (ValueType &&value)
Static Private Member Functions
template<typename T >
static vtable_type * vtable_for_type ()
Returns the pointer to the vtable of the type T.
Private Attributes
storage_union storage
vtable_type * vtable
Friends
template<typename T >
const T * any_cast (const any *operand) noexcept
template<typename T >
T * any_cast (any *operand) noexcept
Constructor & Destructor Documentation
any() [1/4]
linb::any::any () [inline]
Constructs an object of type any with an empty state.
          :
        vtable(nullptr)
    {
    }
Referenced by operator=().
any() [2/4]
linb::any::any (const any & rhs) [inline]
Constructs an object of type any with an equivalent state as other.
                        :
        vtable(rhs.vtable)
    {
        if(!rhs.empty())
        {
            rhs.vtable->copy(rhs.storage, this->storage);
        }
    }
References linb::any::vtable_type::copy, empty(), storage, and vtable.
any() [3/4]
linb::any::any (any && rhs) [inline], [noexcept]
Constructs an object of type any with a state equivalent to the original state of other. rhs is left in a valid but otherwise unspecified state.
                            :
        vtable(rhs.vtable)
    {
        if(!rhs.empty())
        {
            rhs.vtable->move(rhs.storage, this->storage);
            rhs.vtable = nullptr;
        }
    }
References linb::any::vtable_type::move.
 any()
linb::any::~any () [inline]
Same effect as this->clear().
    {
        this->clear();
    }
References clear().
any() [4/4]
template<typename ValueType , typename = typename std::enable_if<!std::is_same<typename std::decay<ValueType>::type, any>::value>::type>
linb::any::any (ValueType && value) [inline]
Constructs an object of type any that contains an object of type T direct-initialized with std::forward<ValueType>(value).
T shall satisfy the CopyConstructible requirements, otherwise the program is ill-formed. This is because an any may be copy constructed into another any at any time, so a copy should always be allowed.
    {
        static_assert(std::is_copy_constructible<typename std::decay<ValueType>::type>::value,
            "T shall satisfy the CopyConstructible requirements.");
        this->construct(std::forward<ValueType>(value));
    }
References construct().
Member Function Documentation
cast() [1/2]
template<typename T >
const T * linb::any::cast () const [inline], [protected], [noexcept]
Casts (with no type_info checks) the storage pointer as const T*.
    {
        return requires_allocation<typename std::decay<T>::type>::value?
            reinterpret_cast<const T*>(storage.dynamic) :
            reinterpret_cast<const T*>(&storage.stack);
    }
cast() [2/2]
template<typename T >
T * linb::any::cast () [inline], [protected], [noexcept]
Casts (with no type_info checks) the storage pointer as T*.
    {
        return requires_allocation<typename std::decay<T>::type>::value?
            reinterpret_cast<T*>(storage.dynamic) :
            reinterpret_cast<T*>(&storage.stack);
    }
clear()
void linb::any::clear () [inline], [noexcept]
If not empty, destroys the contained object.
    {
        if(!empty())
        {
            this->vtable->destroy(storage);
            this->vtable = nullptr;
        }
    }
References linb::any::vtable_type::destroy, empty(), storage, and vtable.
Referenced by ~any().
construct()
template<typename ValueType >
void linb::any::construct (ValueType && value) [inline], [private]
Chooses between stack and dynamic allocation for the type decay_t<ValueType>, assigns the correct vtable, and constructs the object on our storage.
    {
        using T = typename std::decay<ValueType>::type;
        this->vtable = vtable_for_type<T>();
        do_construct<ValueType,T>(std::forward<ValueType>(value));
    }
Referenced by any().
do_construct() [1/2]
template<typename ValueType , typename T >
std::enable_if< requires_allocation< T >::value >::type linb::any::do_construct (ValueType && value) [inline], [private]
    {
        storage.dynamic = new T(std::forward<ValueType>(value));
    }
do_construct() [2/2]
template<typename ValueType , typename T >
std::enable_if<!requires_allocation< T >::value >::type linb::any::do_construct (ValueType && value) [inline], [private]
    {
        new (&storage.stack) T(std::forward<ValueType>(value));
    }
empty()
bool linb::any::empty () const [inline], [noexcept]
Returns true if *this has no contained object, otherwise false.
    {
        return this->vtable == nullptr;
    }
References vtable.
Referenced by any(), clear(), and type().
operator=() [1/3]
any & linb::any::operator= (any && rhs) [inline], [noexcept]
Has the same effect as any(std::move(rhs)).swap(*this).
The state of *this is equivalent to the original state of rhs and rhs is left in a valid but otherwise unspecified state.
    {
        any(std::move(rhs)).swap(*this);
        return *this;
    }
References any().
operator=() [2/3]
any & linb::any::operator= (const any & rhs) [inline]
Has the same effect as any(rhs).swap(*this). No effects if an exception is thrown.
    {
        any(rhs).swap(*this);
        return *this;
    }
References any().
operator=() [3/3]
template<typename ValueType , typename = typename std::enable_if<!std::is_same<typename std::decay<ValueType>::type, any>::value>::type>
any & linb::any::operator= (ValueType && value) [inline]
Has the same effect as any(std::forward<ValueType>(value)).swap(*this). No effect if a exception is thrown.
T shall satisfy the CopyConstructible requirements, otherwise the program is ill-formed. This is because an any may be copy constructed into another any at any time, so a copy should always be allowed.
    {
        static_assert(std::is_copy_constructible<typename std::decay<ValueType>::type>::value,
            "T shall satisfy the CopyConstructible requirements.");
        any(std::forward<ValueType>(value)).swap(*this);
        return *this;
    }
References any().
swap()
void linb::any::swap (any & rhs) [inline], [noexcept]
Exchange the states of *this and rhs.
    {
        if(this->vtable != rhs.vtable)
        {
            any tmp(std::move(rhs));
            // move from *this to rhs.
            rhs.vtable = this->vtable;
            if(this->vtable != nullptr)
            {
                this->vtable->move(this->storage, rhs.storage);
                //this->vtable = nullptr; -- unneeded, see below
            }
            // move from tmp (previously rhs) to *this.
            this->vtable = tmp.vtable;
            if(tmp.vtable != nullptr)
            {
                tmp.vtable->move(tmp.storage, this->storage);
                tmp.vtable = nullptr;
            }
        }
        else // same types
        {
            if(this->vtable != nullptr)
                this->vtable->swap(this->storage, rhs.storage);
        }
    }
References linb::any::vtable_type::move, storage, linb::any::vtable_type::swap, and vtable.
type()
const std::type_info & linb::any::type () const [inline], [noexcept]
If *this has a contained object of type T, typeid(T); otherwise typeid(void).
    {
        return empty()? typeid(void) : this->vtable->type();
    }
References empty(), linb::any::vtable_type::type, and vtable.
vtable_for_type()
template<typename T >
static vtable_type * linb::any::vtable_for_type () [inline], [static], [private]
Returns the pointer to the vtable of the type T.
    {
        using VTableType = typename std::conditional<requires_allocation<T>::value, vtable_dynamic<T>, vtable_stack<T>>::type;
        static vtable_type table = {
#ifndef ANY_IMPL_NO_RTTI
            VTableType::type,
#endif
            VTableType::destroy,
            VTableType::copy, VTableType::move,
            VTableType::swap,
        };
        return &table;
    }
Friends And Related Function Documentation
any_cast [1/2]
template<typename T >
T * any_cast (any * operand) [friend]
If operand != nullptr && operand->type() == typeid(ValueType), a pointer to the object contained by operand, otherwise nullptr.
{
    using T = typename std::decay<ValueType>::type;
    if (operand && operand->vtable == any::vtable_for_type<T>())
        return operand->cast<ValueType>();
    else
        return nullptr;
}
any_cast [2/2]
template<typename T >
const T * any_cast (const any * operand) [friend]
If operand != nullptr && operand->type() == typeid(ValueType), a pointer to the object contained by operand, otherwise nullptr.
{
    using T = typename std::decay<ValueType>::type;
    if (operand && operand->vtable == any::vtable_for_type<T>())
        return operand->cast<ValueType>();
    else
        return nullptr;
}
Member Data Documentation
storage
storage_union linb::any::storage [private]
Referenced by any(), clear(), linb::any::vtable_dynamic< T >::destroy(), linb::any::vtable_stack< T >::destroy(), and swap().
vtable
vtable_type* linb::any::vtable [private]
Referenced by any(), clear(), empty(), swap(), and type().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp