SensorReading Class Reference
#include <SensorReading.hpp>
Public Member Functions
int Addition (int x, int y)
int Multiply (int x, int y)
Member Function Documentation
Addition()
int SensorReading::Addition (int x, int y)
{
   return (x + y);
}
Referenced by main(), and TEST_CASE().
Multiply()
int SensorReading::Multiply (int x, int y)
{
   return (x * y);
}
Referenced by main(), and TEST_CASE().
The documentation for this class was generated from the following files:
src/SensorReading.hpp
src/SensorReading.cpp