peg::CaptureScope Class Reference
#include <cluon-complete.hpp>
Public Member Functions
CaptureScope (const std::shared_ptr< Ope > &ope)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::shared_ptr< Ope > ope_
Constructor & Destructor Documentation
CaptureScope()
peg::CaptureScope::CaptureScope (const std::shared_ptr< Ope > & ope) [inline]
        : ope_(ope) {}
Member Function Documentation
accept()
void peg::CaptureScope::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::CaptureScope::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.push_capture_scope();
        auto se = make_scope_exit([&]() {
            c.pop_capture_scope();
        });
        const auto& rule = *ope_;
        auto len = rule.parse(s, n, sv, c, dt);
        return len;
    }
References peg::make_scope_exit(), peg::Context::pop_capture_scope(), and peg::Context::push_capture_scope().
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::CaptureScope::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::TokenChecker::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp