opendlv::proxy::AngleRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AngleRequest ()=default
AngleRequest (const AngleRequest &)=default
AngleRequest & operator= (const AngleRequest &)=default
AngleRequest (AngleRequest &&)=default
AngleRequest & operator= (AngleRequest &&)=default
~AngleRequest ()=default
AngleRequest & angle (const float &v) noexcept
float angle () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_angle { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AngleRequest`
static constexpr const char * TheLongName = `opendlv.proxy.AngleRequest`
Constructor & Destructor Documentation
AngleRequest() [1/3]
opendlv::proxy::AngleRequest::AngleRequest () [default]
AngleRequest() [2/3]
opendlv::proxy::AngleRequest::AngleRequest (const AngleRequest &) [default]
AngleRequest() [3/3]
opendlv::proxy::AngleRequest::AngleRequest (AngleRequest &&) [default]
 AngleRequest()
opendlv::proxy::AngleRequest::~AngleRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::AngleRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("angle"s), m_angle, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::AngleRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("angle"s), m_angle, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::AngleRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("angle"s), m_angle, visitor);
            visitor.postVisit();
        }
References doVisit().
angle() [1/2]
float opendlv::proxy::AngleRequest::angle () const [inline], [noexcept]
                                            {
            return m_angle;
        }
angle() [2/2]
AngleRequest & opendlv::proxy::AngleRequest::angle (const float & v) [inline], [noexcept]
                                                            {
            m_angle = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::AngleRequest::ID () [inline], [static]
                                   {
            return 1084;
        }
LongName()
static const std::string opendlv::proxy::AngleRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AngleRequest & opendlv::proxy::AngleRequest::operator= (AngleRequest &&) [default]
operator=() [2/2]
AngleRequest & opendlv::proxy::AngleRequest::operator= (const AngleRequest &) [default]
ShortName()
static const std::string opendlv::proxy::AngleRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_angle
float opendlv::proxy::AngleRequest::m_angle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::AngleRequest::TheLongName = `opendlv.proxy.AngleRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::AngleRequest::TheShortName = `AngleRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp