opendlv::proxy::VoltageReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
VoltageReading ()=default
VoltageReading (const VoltageReading &)=default
VoltageReading & operator= (const VoltageReading &)=default
VoltageReading (VoltageReading &&)=default
VoltageReading & operator= (VoltageReading &&)=default
~VoltageReading ()=default
VoltageReading & voltage (const float &v) noexcept
float voltage () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_voltage { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `VoltageReading`
static constexpr const char * TheLongName = `opendlv.proxy.VoltageReading`
Constructor & Destructor Documentation
VoltageReading() [1/3]
opendlv::proxy::VoltageReading::VoltageReading () [default]
VoltageReading() [2/3]
opendlv::proxy::VoltageReading::VoltageReading (const VoltageReading &) [default]
VoltageReading() [3/3]
opendlv::proxy::VoltageReading::VoltageReading (VoltageReading &&) [default]
 VoltageReading()
opendlv::proxy::VoltageReading::~VoltageReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::VoltageReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::VoltageReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::VoltageReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("voltage"s), m_voltage, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::VoltageReading::ID () [inline], [static]
                                   {
            return 1037;
        }
LongName()
static const std::string opendlv::proxy::VoltageReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
VoltageReading & opendlv::proxy::VoltageReading::operator= (const VoltageReading &) [default]
operator=() [2/2]
VoltageReading & opendlv::proxy::VoltageReading::operator= (VoltageReading &&) [default]
ShortName()
static const std::string opendlv::proxy::VoltageReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
voltage() [1/2]
float opendlv::proxy::VoltageReading::voltage () const [inline], [noexcept]
                                              {
            return m_voltage;
        }
voltage() [2/2]
VoltageReading & opendlv::proxy::VoltageReading::voltage (const float & v) [inline], [noexcept]
                                                                {
            m_voltage = v;
            return *this;
        }
Member Data Documentation
m_voltage
float opendlv::proxy::VoltageReading::m_voltage { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::VoltageReading::TheLongName = `opendlv.proxy.VoltageReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::VoltageReading::TheShortName = `VoltageReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp