cluon::ToJSONVisitor Class Reference
#include <cluon-complete.hpp>
Public Member Functions
ToJSONVisitor (bool withOuterCurlyBraces=true, const std::map< uint32_t, bool > &mask={}) noexcept
std::string json () const noexcept
void preVisit (int32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Static Public Member Functions
static std::string encodeBase64 (const std::string &input) noexcept
Private Member Functions
ToJSONVisitor (const ToJSONVisitor &)=delete
ToJSONVisitor (ToJSONVisitor &&)=delete
ToJSONVisitor & operator= (const ToJSONVisitor &)=delete
ToJSONVisitor & operator= (ToJSONVisitor &&)=delete
Private Attributes
bool m_withOuterCurlyBraces {true}
std::map< uint32_t, bool > m_mask
std::stringstream m_buffer {}
Detailed Description
This class provides a visitor to transform a message into JSON:
MyMessage msg;
// Set some values in msg.
cluon::ToJSONVisitor j;
msg.accept(j);
std::cout << j.json() << std::endl;
Constructor & Destructor Documentation
ToJSONVisitor() [1/3]
cluon::ToJSONVisitor::ToJSONVisitor (const ToJSONVisitor &) [private], [delete]
ToJSONVisitor() [2/3]
cluon::ToJSONVisitor::ToJSONVisitor (ToJSONVisitor &&) [private], [delete]
ToJSONVisitor() [3/3]
cluon::ToJSONVisitor::ToJSONVisitor (bool withOuterCurlyBraces = true, const std::map< uint32_t, bool > & mask = {}) [inline], [noexcept]
Constructor.
Parameters
withOuterCurlyBraces Include the outer curly braces.
mask Map describing which fields to render. If empty, all fields will be emitted; individual field identifiers can be masked setting them to false.
    : m_withOuterCurlyBraces(withOuterCurlyBraces)
    , m_mask(mask) {}
Member Function Documentation
encodeBase64()
std::string cluon::ToJSONVisitor::encodeBase64 (const std::string & input) [inline], [static], [noexcept]
This method returns the base64-encoded representation for the given input.
Parameters
input to encode as base64
Returns
base64 encoded input.
                                                                            {
    std::string retVal;
    const std::string ALPHABET{"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"};
    auto length{input.length()};
    uint32_t index{0};
    uint32_t value{0};
    while (length > 2) {
        value = static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++))) << 16;
        value |= static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++))) << 8;
        value |= static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++)));
        retVal += ALPHABET.at((value & 0xFC0000) >> 18);
        retVal += ALPHABET.at((value & 0x3F000) >> 12);
        retVal += ALPHABET.at((value & 0xFC0) >> 6);
        retVal += ALPHABET.at(value & 0x3F);
        length -= 3;
    }
    if (length == 2) {
        value = static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++))) << 16;
        value |= static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++))) << 8;
        retVal += ALPHABET.at((value & 0xFC0000) >> 18);
        retVal += ALPHABET.at((value & 0x3F000) >> 12);
        retVal += ALPHABET.at((value & 0xFC0) >> 6);
        retVal += "=";
    } else if (length == 1) {
        value = static_cast<uint32_t>(static_cast<unsigned char>(input.at(index++))) << 16;
        retVal += ALPHABET.at((value & 0xFC0000) >> 18);
        retVal += ALPHABET.at((value & 0x3F000) >> 12);
        retVal += "==";
    }
    return retVal;
}
References retVal.
Referenced by visit(), and cluon::ToCSVVisitor::visit().
json()
std::string cluon::ToJSONVisitor::json () const [inline], [noexcept]
Returns
JSON-encoded data.
                                                    {
    const std::string tmp{m_buffer.str()};
    std::string retVal{"{}"};
    if (2 < tmp.size()) {
        retVal = {(m_withOuterCurlyBraces ? "{" : "") + tmp.substr(0, tmp.size() - 2) + (m_withOuterCurlyBraces ? "}" : "")};
    }
    return retVal;
}
References m_buffer, m_withOuterCurlyBraces, and retVal.
Referenced by visit().
operator=() [1/2]
ToJSONVisitor & cluon::ToJSONVisitor::operator= (const ToJSONVisitor &) [private], [delete]
operator=() [2/2]
ToJSONVisitor & cluon::ToJSONVisitor::operator= (ToJSONVisitor &&) [private], [delete]
postVisit()
void cluon::ToJSONVisitor::postVisit () [inline], [noexcept]
{}
preVisit()
void cluon::ToJSONVisitor::preVisit (int32_t id, const std::string & shortName, const std::string & longName) [inline], [noexcept]
                                                                                                              {
    (void)id;
    (void)longName;
    (void)shortName;
}
visit() [1/14]
template<typename T >
void cluon::ToJSONVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) [inline], [noexcept]
                                                                                        {
        (void)typeName;
        if ((0 == m_mask.count(id)) || m_mask[id]) {
            try {
                ToJSONVisitor jsonVisitor;
                value.accept(jsonVisitor);
                m_buffer << '\"' << name << '\"' << ':' << jsonVisitor.json() << ',' << '\n';
            } catch (const linb::bad_any_cast &) { // LCOV_EXCL_LINE
            }
        }
    }
References json().
visit() [2/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) [inline], [noexcept]
                                                                                                      {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << v << ',' << '\n';
    }
}
visit() [3/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) [inline], [noexcept]
                                                                                                      {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << '\"' << v << '\"' << ',' << '\n';
    }
}
visit() [4/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) [inline], [noexcept]
                                                                                                        {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << std::setprecision(11) << v << std::setprecision(6) << ',' << '\n';
    }
}
visit() [5/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) [inline], [noexcept]
                                                                                                       {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << std::setprecision(7) << v << std::setprecision(6) << ',' << '\n';
    }
}
visit() [6/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << +v << ',' << '\n';
    }
}
visit() [7/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << v << ',' << '\n';
    }
}
visit() [8/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << v << ',' << '\n';
    }
}
visit() [9/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) [inline], [noexcept]
                                                                                                        {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << +v << ',' << '\n';
    }
}
visit() [10/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) [inline], [noexcept]
                                                                                                           {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << '\"' << ToJSONVisitor::encodeBase64(v) << '\"' << ',' << '\n';
    }
}
References encodeBase64().
visit() [11/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << +v << ',' << '\n';
    }
}
visit() [12/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << v << ',' << '\n';
    }
}
visit() [13/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) [inline], [noexcept]
                                                                                                          {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << v << ',' << '\n';
    }
}
visit() [14/14]
void cluon::ToJSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) [inline], [noexcept]
                                                                                                         {
    (void)typeName;
    if ((0 == m_mask.count(id)) || m_mask[id]) {
        m_buffer << '\"' << name << '\"' << ':' << +v << ',' << '\n';
    }
}
Member Data Documentation
m_buffer
std::stringstream cluon::ToJSONVisitor::m_buffer {} [private]
Referenced by json().
m_mask
std::map<uint32_t, bool> cluon::ToJSONVisitor::m_mask [private]
m_withOuterCurlyBraces
bool cluon::ToJSONVisitor::m_withOuterCurlyBraces {true} [private]
Referenced by json().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp