opendlv::proxy::PedalPositionRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PedalPositionRequest ()=default
PedalPositionRequest (const PedalPositionRequest &)=default
PedalPositionRequest & operator= (const PedalPositionRequest &)=default
PedalPositionRequest (PedalPositionRequest &&)=default
PedalPositionRequest & operator= (PedalPositionRequest &&)=default
~PedalPositionRequest ()=default
PedalPositionRequest & position (const float &v) noexcept
float position () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_position { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PedalPositionRequest`
static constexpr const char * TheLongName = `opendlv.proxy.PedalPositionRequest`
Constructor & Destructor Documentation
PedalPositionRequest() [1/3]
opendlv::proxy::PedalPositionRequest::PedalPositionRequest () [default]
PedalPositionRequest() [2/3]
opendlv::proxy::PedalPositionRequest::PedalPositionRequest (const PedalPositionRequest &) [default]
PedalPositionRequest() [3/3]
opendlv::proxy::PedalPositionRequest::PedalPositionRequest (PedalPositionRequest &&) [default]
 PedalPositionRequest()
opendlv::proxy::PedalPositionRequest::~PedalPositionRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PedalPositionRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("position"s), m_position, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PedalPositionRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("position"s), m_position, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PedalPositionRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("position"s), m_position, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::PedalPositionRequest::ID () [inline], [static]
                                   {
            return 1086;
        }
LongName()
static const std::string opendlv::proxy::PedalPositionRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PedalPositionRequest & opendlv::proxy::PedalPositionRequest::operator= (const PedalPositionRequest &) [default]
operator=() [2/2]
PedalPositionRequest & opendlv::proxy::PedalPositionRequest::operator= (PedalPositionRequest &&) [default]
position() [1/2]
float opendlv::proxy::PedalPositionRequest::position () const [inline], [noexcept]
                                               {
            return m_position;
        }
position() [2/2]
PedalPositionRequest & opendlv::proxy::PedalPositionRequest::position (const float & v) [inline], [noexcept]
                                                                       {
            m_position = v;
            return *this;
        }
ShortName()
static const std::string opendlv::proxy::PedalPositionRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_position
float opendlv::proxy::PedalPositionRequest::m_position { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::PedalPositionRequest::TheLongName = `opendlv.proxy.PedalPositionRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PedalPositionRequest::TheShortName = `PedalPositionRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp