opendlv::logic::action::PreviewPoint Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PreviewPoint ()=default
PreviewPoint (const PreviewPoint &)=default
PreviewPoint & operator= (const PreviewPoint &)=default
PreviewPoint (PreviewPoint &&)=default
PreviewPoint & operator= (PreviewPoint &&)=default
~PreviewPoint ()=default
PreviewPoint & azimuthAngle (const float &v) noexcept
float azimuthAngle () const noexcept
PreviewPoint & zenithAngle (const float &v) noexcept
float zenithAngle () const noexcept
PreviewPoint & distance (const float &v) noexcept
float distance () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_azimuthAngle { 0.0f }
float m_zenithAngle { 0.0f }
float m_distance { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PreviewPoint`
static constexpr const char * TheLongName = `opendlv.logic.action.PreviewPoint`
Constructor & Destructor Documentation
PreviewPoint() [1/3]
opendlv::logic::action::PreviewPoint::PreviewPoint () [default]
PreviewPoint() [2/3]
opendlv::logic::action::PreviewPoint::PreviewPoint (const PreviewPoint &) [default]
PreviewPoint() [3/3]
opendlv::logic::action::PreviewPoint::PreviewPoint (PreviewPoint &&) [default]
 PreviewPoint()
opendlv::logic::action::PreviewPoint::~PreviewPoint () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::action::PreviewPoint::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("distance"s), m_distance, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::action::PreviewPoint::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("distance"s), m_distance, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::action::PreviewPoint::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
            doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
            doVisit(3, std::move("float"s), std::move("distance"s), m_distance, visitor);
            visitor.postVisit();
        }
References doVisit().
azimuthAngle() [1/2]
float opendlv::logic::action::PreviewPoint::azimuthAngle () const [inline], [noexcept]
                                                   {
            return m_azimuthAngle;
        }
azimuthAngle() [2/2]
PreviewPoint & opendlv::logic::action::PreviewPoint::azimuthAngle (const float & v) [inline], [noexcept]
                                                                   {
            m_azimuthAngle = v;
            return *this;
        }
distance() [1/2]
float opendlv::logic::action::PreviewPoint::distance () const [inline], [noexcept]
                                               {
            return m_distance;
        }
distance() [2/2]
PreviewPoint & opendlv::logic::action::PreviewPoint::distance (const float & v) [inline], [noexcept]
                                                               {
            m_distance = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::action::PreviewPoint::ID () [inline], [static]
                                   {
            return 1173;
        }
LongName()
static const std::string opendlv::logic::action::PreviewPoint::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PreviewPoint & opendlv::logic::action::PreviewPoint::operator= (const PreviewPoint &) [default]
operator=() [2/2]
PreviewPoint & opendlv::logic::action::PreviewPoint::operator= (PreviewPoint &&) [default]
ShortName()
static const std::string opendlv::logic::action::PreviewPoint::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
zenithAngle() [1/2]
float opendlv::logic::action::PreviewPoint::zenithAngle () const [inline], [noexcept]
                                                  {
            return m_zenithAngle;
        }
zenithAngle() [2/2]
PreviewPoint & opendlv::logic::action::PreviewPoint::zenithAngle (const float & v) [inline], [noexcept]
                                                                  {
            m_zenithAngle = v;
            return *this;
        }
Member Data Documentation
m_azimuthAngle
float opendlv::logic::action::PreviewPoint::m_azimuthAngle { 0.0f } [private]
m_distance
float opendlv::logic::action::PreviewPoint::m_distance { 0.0f } [private]
m_zenithAngle
float opendlv::logic::action::PreviewPoint::m_zenithAngle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::action::PreviewPoint::TheLongName = `opendlv.logic.action.PreviewPoint` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::action::PreviewPoint::TheShortName = `PreviewPoint` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp