opendlv::proxy::TemperatureRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
TemperatureRequest ()=default
TemperatureRequest (const TemperatureRequest &)=default
TemperatureRequest & operator= (const TemperatureRequest &)=default
TemperatureRequest (TemperatureRequest &&)=default
TemperatureRequest & operator= (TemperatureRequest &&)=default
~TemperatureRequest ()=default
TemperatureRequest & temperature (const float &v) noexcept
float temperature () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_temperature { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `TemperatureRequest`
static constexpr const char * TheLongName = `opendlv.proxy.TemperatureRequest`
Constructor & Destructor Documentation
TemperatureRequest() [1/3]
opendlv::proxy::TemperatureRequest::TemperatureRequest () [default]
TemperatureRequest() [2/3]
opendlv::proxy::TemperatureRequest::TemperatureRequest (const TemperatureRequest &) [default]
TemperatureRequest() [3/3]
opendlv::proxy::TemperatureRequest::TemperatureRequest (TemperatureRequest &&) [default]
 TemperatureRequest()
opendlv::proxy::TemperatureRequest::~TemperatureRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::TemperatureRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::TemperatureRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::TemperatureRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("temperature"s), m_temperature, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::TemperatureRequest::ID () [inline], [static]
                                   {
            return 1081;
        }
LongName()
static const std::string opendlv::proxy::TemperatureRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
TemperatureRequest & opendlv::proxy::TemperatureRequest::operator= (const TemperatureRequest &) [default]
operator=() [2/2]
TemperatureRequest & opendlv::proxy::TemperatureRequest::operator= (TemperatureRequest &&) [default]
ShortName()
static const std::string opendlv::proxy::TemperatureRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
temperature() [1/2]
float opendlv::proxy::TemperatureRequest::temperature () const [inline], [noexcept]
                                                  {
            return m_temperature;
        }
temperature() [2/2]
TemperatureRequest & opendlv::proxy::TemperatureRequest::temperature (const float & v) [inline], [noexcept]
                                                                        {
            m_temperature = v;
            return *this;
        }
Member Data Documentation
m_temperature
float opendlv::proxy::TemperatureRequest::m_temperature { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::TemperatureRequest::TheLongName = `opendlv.proxy.TemperatureRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::TemperatureRequest::TheShortName = `TemperatureRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp