cluon::TCPServer Class Reference
#include <cluon-complete.hpp>
Public Member Functions
TCPServer (uint16_t port, std::function< void(std::string &&from, std::shared_ptr< cluon::TCPConnection > connection)> newConnectionDelegate) noexcept
~TCPServer () noexcept
bool isRunning () const noexcept
Private Member Functions
TCPServer (const TCPServer &)=delete
TCPServer (TCPServer &&)=delete
TCPServer & operator= (const TCPServer &)=delete
TCPServer & operator= (TCPServer &&)=delete
void closeSocket (int errorCode) noexcept
void readFromSocket () noexcept
Private Attributes
std::mutex m_socketMutex {}
int32_t m_socket {-1}
std::atomic< bool > m_readFromSocketThreadRunning {false}
std::thread m_readFromSocketThread {}
std::mutex m_newConnectionDelegateMutex {}
std::function< void(std::string &&from, std::shared_ptr< cluon::TCPConnection > connection)> m_newConnectionDelegate {}
Constructor & Destructor Documentation
TCPServer() [1/3]
cluon::TCPServer::TCPServer (const TCPServer &) [private], [delete]
TCPServer() [2/3]
cluon::TCPServer::TCPServer (TCPServer &&) [private], [delete]
TCPServer() [3/3]
cluon::TCPServer::TCPServer (uint16_t port, std::function< void(std::string &&from, std::shared_ptr< cluon::TCPConnection > connection)> newConnectionDelegate) [inline], [noexcept]
Constructor to create a TCP server.
Parameters
port Port to receive UDP packets from.
newConnectionDelegate Functional to handle incoming TCP connections.
    : m_newConnectionDelegate(newConnectionDelegate) {
    if (0 < port) {
#ifdef WIN32
        // Load Winsock 2.2 DLL.
        WSADATA wsaData;
        if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
            std::cerr << "[cluon::TCPServer] Error while calling WSAStartUp: " << WSAGetLastError() << std::endl;
        }
#endif
        m_socket = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
#ifdef WIN32
        if (m_socket < 0) {
            std::cerr << "[cluon::TCPServer] Error while creating socket: " << WSAGetLastError() << std::endl;
            WSACleanup();
        }
#endif
        if (!(m_socket < 0)) {
            // Allow reusing of ports by multiple calls with same address/port.
            uint32_t YES = 1;
            // clang-format off
            auto retVal = ::setsockopt(m_socket, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<char *>(&YES), sizeof(YES)); // NOLINT
            // clang-format on
            if (0 > retVal) {
#ifdef WIN32 // LCOV_EXCL_LINE
                auto errorCode = WSAGetLastError();
#else
                auto errorCode = errno; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
                closeSocket(errorCode); // LCOV_EXCL_LINE
            }
        }
        if (!(m_socket < 0)) {
            // Setup address and port.
            struct sockaddr_in address;
            ::memset(&address, 0, sizeof(address));
            address.sin_family = AF_INET;
            address.sin_addr.s_addr = htonl(INADDR_ANY);
            address.sin_port = htons(port);
            auto retVal = ::bind(m_socket, reinterpret_cast<struct sockaddr *>(&address), sizeof(address));
            if (-1 != retVal) {
                constexpr int32_t MAX_PENDING_CONNECTIONS{100};
                retVal = ::listen(m_socket, MAX_PENDING_CONNECTIONS);
                if (-1 != retVal) {
                    // Constructing a thread could fail.
                    try {
                        m_readFromSocketThread = std::thread(&TCPServer::readFromSocket, this);
                        // Let the operating system spawn the thread.
                        using namespace std::literals::chrono_literals;
                        do { std::this_thread::sleep_for(1ms); } while (!m_readFromSocketThreadRunning.load());
                    } catch (...) { // LCOV_EXCL_LINE
                        closeSocket(ECHILD); // LCOV_EXCL_LINE
                    }
                } else { // LCOV_EXCL_LINE
#ifdef WIN32 // LCOV_EXCL_LINE
                    auto errorCode = WSAGetLastError();
#else
                    auto errorCode = errno; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
                    closeSocket(errorCode); // LCOV_EXCL_LINE
                }
            } else { // LCOV_EXCL_LINE
#ifdef WIN32 // LCOV_EXCL_LINE
                auto errorCode = WSAGetLastError();
#else
                auto errorCode = errno; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
                closeSocket(errorCode); // LCOV_EXCL_LINE
            }
        }
    }
}
References readFromSocket(), and retVal.
 TCPServer()
cluon::TCPServer::~TCPServer () [inline], [noexcept]
                                      {
    m_readFromSocketThreadRunning.store(false);
    // Joining the thread could fail.
    try {
        if (m_readFromSocketThread.joinable()) {
            m_readFromSocketThread.join();
        }
    } catch (...) { // LCOV_EXCL_LINE
    }
    closeSocket(0);
}
References closeSocket(), m_readFromSocketThread, and m_readFromSocketThreadRunning.
Member Function Documentation
closeSocket()
void cluon::TCPServer::closeSocket (int errorCode) [inline], [private], [noexcept]
This method closes the socket.
Parameters
errorCode Error code that caused this closing.
                                                         {
    if (0 != errorCode) {
        std::cerr << "[cluon::TCPServer] Failed to perform socket operation: "; // LCOV_EXCL_LINE
#ifdef WIN32 // LCOV_EXCL_LINE
        std::cerr << errorCode << std::endl;
#else
        std::cerr << ::strerror(errorCode) << " (" << errorCode << ")" << std::endl; // LCOV_EXCL_LINE
#endif // LCOV_EXCL_LINE
    }
    if (!(m_socket < 0)) {
#ifdef WIN32
        ::shutdown(m_socket, SD_BOTH);
        ::closesocket(m_socket);
        WSACleanup();
#else
        ::shutdown(m_socket, SHUT_RDWR); // Disallow further read/write operations.
        ::close(m_socket);
#endif
    }
    m_socket = -1;
}
Referenced by ~TCPServer().
isRunning()
bool cluon::TCPServer::isRunning () const [inline], [noexcept]
Returns
true if the TCPServer could successfully be created and is able to receive data.
                                                {
    return (m_readFromSocketThreadRunning.load() && !TerminateHandler::instance().isTerminated.load());
}
References cluon::TerminateHandler::instance(), cluon::TerminateHandler::isTerminated, and m_readFromSocketThreadRunning.
operator=() [1/2]
TCPServer & cluon::TCPServer::operator= (const TCPServer &) [private], [delete]
operator=() [2/2]
TCPServer & cluon::TCPServer::operator= (TCPServer &&) [private], [delete]
readFromSocket()
void cluon::TCPServer::readFromSocket () [inline], [private], [noexcept]
                                               {
    struct timeval timeout {};
    // Define file descriptor set to watch for read operations.
    fd_set setOfFiledescriptorsToReadFrom{};
    // Indicate to main thread that we are ready.
    m_readFromSocketThreadRunning.store(true);
    constexpr uint16_t MAX_ADDR_SIZE{1024};
    std::array<char, MAX_ADDR_SIZE> remoteAddress{};
    while (m_readFromSocketThreadRunning.load()) {
        // Define timeout for select system call. The timeval struct must be
        // reinitialized for every select call as it might be modified containing
        // the actual time slept.
        timeout.tv_sec = 0;
        timeout.tv_usec = 20 * 1000; // Check for new data with 50Hz.
        FD_ZERO(&setOfFiledescriptorsToReadFrom);
        FD_SET(m_socket, &setOfFiledescriptorsToReadFrom);
        ::select(m_socket + 1, &setOfFiledescriptorsToReadFrom, nullptr, nullptr, &timeout);
        if (FD_ISSET(m_socket, &setOfFiledescriptorsToReadFrom)) {
            struct sockaddr_storage remote;
            socklen_t addrLength = sizeof(remote);
            int32_t connectingClient = ::accept(m_socket, reinterpret_cast<struct sockaddr *>(&remote), &addrLength);
            if ((0 <= connectingClient) && (nullptr != m_newConnectionDelegate)) {
                ::inet_ntop(remote.ss_family,
                            &((reinterpret_cast<struct sockaddr_in *>(&remote))->sin_addr), // NOLINT
                            remoteAddress.data(),
                            remoteAddress.max_size());
                const uint16_t RECVFROM_PORT{ntohs(reinterpret_cast<struct sockaddr_in *>(&remote)->sin_port)}; // NOLINT
                m_newConnectionDelegate(std::string(remoteAddress.data()) + ':' + std::to_string(RECVFROM_PORT),
                                        std::shared_ptr<cluon::TCPConnection>(new cluon::TCPConnection(connectingClient)));
            }
        }
    }
}
References m_newConnectionDelegate, m_readFromSocketThreadRunning, and m_socket.
Referenced by TCPServer().
Member Data Documentation
m_newConnectionDelegate
std::function<void(std::string &&from, std::shared_ptr<cluon::TCPConnection> connection)> cluon::TCPServer::m_newConnectionDelegate {} [private]
Referenced by readFromSocket().
m_newConnectionDelegateMutex
std::mutex cluon::TCPServer::m_newConnectionDelegateMutex {} [private]
m_readFromSocketThread
std::thread cluon::TCPServer::m_readFromSocketThread {} [private]
Referenced by ~TCPServer().
m_readFromSocketThreadRunning
std::atomic<bool> cluon::TCPServer::m_readFromSocketThreadRunning {false} [private]
Referenced by isRunning(), readFromSocket(), and ~TCPServer().
m_socket
int32_t cluon::TCPServer::m_socket {-1} [private]
Referenced by readFromSocket().
m_socketMutex
std::mutex cluon::TCPServer::m_socketMutex {} [mutable], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp