opendlv::proxy::PressureReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PressureReading ()=default
PressureReading (const PressureReading &)=default
PressureReading & operator= (const PressureReading &)=default
PressureReading (PressureReading &&)=default
PressureReading & operator= (PressureReading &&)=default
~PressureReading ()=default
PressureReading & pressure (const float &v) noexcept
float pressure () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_pressure { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PressureReading`
static constexpr const char * TheLongName = `opendlv.proxy.PressureReading`
Constructor & Destructor Documentation
PressureReading() [1/3]
opendlv::proxy::PressureReading::PressureReading () [default]
PressureReading() [2/3]
opendlv::proxy::PressureReading::PressureReading (const PressureReading &) [default]
PressureReading() [3/3]
opendlv::proxy::PressureReading::PressureReading (PressureReading &&) [default]
 PressureReading()
opendlv::proxy::PressureReading::~PressureReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PressureReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PressureReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PressureReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::PressureReading::ID () [inline], [static]
                                   {
            return 1034;
        }
LongName()
static const std::string opendlv::proxy::PressureReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PressureReading & opendlv::proxy::PressureReading::operator= (const PressureReading &) [default]
operator=() [2/2]
PressureReading & opendlv::proxy::PressureReading::operator= (PressureReading &&) [default]
pressure() [1/2]
float opendlv::proxy::PressureReading::pressure () const [inline], [noexcept]
                                               {
            return m_pressure;
        }
pressure() [2/2]
PressureReading & opendlv::proxy::PressureReading::pressure (const float & v) [inline], [noexcept]
                                                                  {
            m_pressure = v;
            return *this;
        }
ShortName()
static const std::string opendlv::proxy::PressureReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_pressure
float opendlv::proxy::PressureReading::m_pressure { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::PressureReading::TheLongName = `opendlv.proxy.PressureReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PressureReading::TheShortName = `PressureReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp