cluon::Player Class Reference
#include <cluon-complete.hpp>
Public Member Functions
Player (const std::string &file, const bool &autoRewind, const bool &threading) noexcept
~Player ()
std::pair< bool, cluon::data::Envelope > getNextEnvelopeToBeReplayed () noexcept
uint32_t delay () const noexcept
bool hasMoreData () const noexcept
void rewind () noexcept
void seekTo (float ratio) noexcept
uint32_t totalNumberOfEnvelopesInRecFile () const noexcept
void setPlayerListener (std::function< void(cluon::data::PlayerStatus playerStatus)> playerListener) noexcept
Private Types
enum {
ONE_MILLISECOND_IN_MICROSECONDS = 1000
, ONE_SECOND_IN_MICROSECONDS = 1000 * ONE_MILLISECOND_IN_MICROSECONDS
, MAX_DELAY_IN_MICROSECONDS = 1 * ONE_SECOND_IN_MICROSECONDS
, LOOK_AHEAD_IN_S = 30
,
MIN_ENTRIES_FOR_LOOK_AHEAD = 5000
 }
Private Member Functions
Player (const Player &)=delete
Player (Player &&)=delete
Player & operator= (Player &&)=delete
Player & operator= (const Player &other)=delete
bool hasMoreDataFromRecFile () const noexcept
void initializeIndex () noexcept
void computeInitialCacheLevelAndFillCache () noexcept
void resetCaches () noexcept
void resetIterators () noexcept
uint32_t fillEnvelopeCache (const uint32_t &maxNumberOfEntriesToReadFromFile) noexcept
void checkAvailabilityOfNextEnvelopeToBeReplayed () noexcept
void setEnvelopeCacheFillingRunning (const bool &running) noexcept
bool isEnvelopeCacheFillingRunning () const noexcept
void manageCache () noexcept
float checkRefillingCache (const uint32_t &numberOfEntries, float refillMultiplicator) noexcept
Private Attributes
bool m_threading
std::string m_file
std::fstream m_recFile
bool m_recFileValid
bool m_autoRewind
std::mutex m_indexMutex
std::multimap< int64_t, IndexEntry > m_index
std::multimap< int64_t, IndexEntry >::iterator m_previousPreviousEnvelopeAlreadyReplayed
std::multimap< int64_t, IndexEntry >::iterator m_previousEnvelopeAlreadyReplayed
std::multimap< int64_t, IndexEntry >::iterator m_currentEnvelopeToReplay
std::multimap< int64_t, IndexEntry >::iterator m_nextEntryToReadFromRecFile
uint32_t m_desiredInitialLevel
cluon::data::TimeStamp m_firstTimePointReturningAEnvelope
uint64_t m_numberOfReturnedEnvelopesInTotal
uint32_t m_delay
std::mutex m_envelopeCacheFillingThreadIsRunningMutex
bool m_envelopeCacheFillingThreadIsRunning
std::thread m_envelopeCacheFillingThread
std::map< uint64_t, cluon::data::Envelope > m_envelopeCache
std::mutex m_playerListenerMutex
std::function< void(cluon::data::PlayerStatus playerStatus)> m_playerListener {nullptr}
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
ONE_MILLISECOND_IN_MICROSECONDS
ONE_SECOND_IN_MICROSECONDS
MAX_DELAY_IN_MICROSECONDS
LOOK_AHEAD_IN_S
MIN_ENTRIES_FOR_LOOK_AHEAD
         {
        ONE_MILLISECOND_IN_MICROSECONDS = 1000,
        ONE_SECOND_IN_MICROSECONDS = 1000 * ONE_MILLISECOND_IN_MICROSECONDS,
        MAX_DELAY_IN_MICROSECONDS = 1 * ONE_SECOND_IN_MICROSECONDS,
        LOOK_AHEAD_IN_S = 30,
        MIN_ENTRIES_FOR_LOOK_AHEAD = 5000,
    };
Constructor & Destructor Documentation
Player() [1/3]
cluon::Player::Player (const Player &) [private], [delete]
Player() [2/3]
cluon::Player::Player (Player &&) [private], [delete]
Player() [3/3]
cluon::Player::Player (const std::string & file, const bool & autoRewind, const bool & threading) [inline], [noexcept]
Constructor.
Parameters
file File to play.
autoRewind True if the file should be rewind at EOF.
threading If set to true, player will load new envelopes from the files in background.
    : m_threading(threading)
    , m_file(file)
    , m_recFile()
    , m_recFileValid(false)
    , m_autoRewind(autoRewind)
    , m_indexMutex()
    , m_index()
    , m_previousPreviousEnvelopeAlreadyReplayed(m_index.end())
    , m_previousEnvelopeAlreadyReplayed(m_index.begin())
    , m_currentEnvelopeToReplay(m_index.begin())
    , m_nextEntryToReadFromRecFile(m_index.begin())
    , m_desiredInitialLevel(0)
    , m_firstTimePointReturningAEnvelope()
    , m_numberOfReturnedEnvelopesInTotal(0)
    , m_delay(0)
    , m_envelopeCacheFillingThreadIsRunningMutex()
    , m_envelopeCacheFillingThreadIsRunning(false)
    , m_envelopeCacheFillingThread()
    , m_envelopeCache()
    , m_playerListenerMutex()
    , m_playerListener(nullptr) {
    initializeIndex();
    computeInitialCacheLevelAndFillCache();
    if (m_threading) {
        // Start concurrent thread to manage cache.
        setEnvelopeCacheFillingRunning(true);
        m_envelopeCacheFillingThread = std::thread(&Player::manageCache, this);
    }
}
References manageCache().
 Player()
cluon::Player::~Player () [inline]
                       {
    if (m_threading) {
        // Stop concurrent thread to manage cache.
        setEnvelopeCacheFillingRunning(false);
        m_envelopeCacheFillingThread.join();
    }
    m_recFile.close();
}
References m_envelopeCacheFillingThread, m_recFile, m_threading, and setEnvelopeCacheFillingRunning().
Member Function Documentation
checkAvailabilityOfNextEnvelopeToBeReplayed()
void cluon::Player::checkAvailabilityOfNextEnvelopeToBeReplayed () [inline], [private], [noexcept]
This method checks the availability of the next cluon::data::Envelope to be replayed from the cache.
                                                                         {
    uint64_t numberOfEntries = 0;
    do {
        {
            try {
                std::lock_guard<std::mutex> lck(m_indexMutex);
                numberOfEntries = m_envelopeCache.size();
            } catch (...) {} // LCOV_EXCL_LINE
        }
        if (0 == numberOfEntries) {
            using namespace std::chrono_literals; // LCOV_EXCL_LINE
            std::this_thread::sleep_for(10ms); // LCOV_EXCL_LINE
        }
    } while (0 == numberOfEntries);
}
References m_envelopeCache, and m_indexMutex.
Referenced by getNextEnvelopeToBeReplayed().
checkRefillingCache()
float cluon::Player::checkRefillingCache (const uint32_t & numberOfEntries, float refillMultiplicator) [inline], [private], [noexcept]
This method checks whether the cache needs to be refilled.
Parameters
numberOfEntries Number of entries in cache.
refillMultiplicator Multiplicator to modify the amount of envelopes to be refilled.
Returns
Modified refillMultiplicator recommedned to be used next time
                                                                                                            {
    // If filling level is around 35%, pour in more from the recording.
    if (numberOfEntries < 0.35 * m_desiredInitialLevel) {
        const uint32_t entriesReadFromFile = fillEnvelopeCache(static_cast<uint32_t>(refillMultiplicator * static_cast<float>(m_desiredInitialLevel)));
        if (entriesReadFromFile > 0) {
            std::clog << "[cluon::Player]: Number of entries in cache: " << numberOfEntries << ". " << entriesReadFromFile << " added to cache. "
                      << m_envelopeCache.size() << " entries available." << std::endl;
            refillMultiplicator *= 1.25f;
        }
    }
    return refillMultiplicator;
}
Referenced by manageCache().
computeInitialCacheLevelAndFillCache()
void cluon::Player::computeInitialCacheLevelAndFillCache () [inline], [private], [noexcept]
This method computes the initially required amount of cluon::data::Envelope in the cache and fill the cache accordingly.
                                                                  {
    if (m_recFileValid && (m_index.size() > 0)) {
        int64_t smallestSampleTimePoint = (std::numeric_limits<int64_t>::max)();
        int64_t largestSampleTimePoint = (std::numeric_limits<int64_t>::min)();
        for (auto it = m_index.begin(); it != m_index.end(); it++) {
            smallestSampleTimePoint = (std::min)(smallestSampleTimePoint, it->first);
            largestSampleTimePoint = (std::max)(largestSampleTimePoint, it->first);
        }
        const uint32_t ENTRIES_TO_READ_PER_SECOND_FOR_REALTIME_REPLAY
            = static_cast<uint32_t>(std::ceil(static_cast<float>(m_index.size()) * (static_cast<float>(Player::ONE_SECOND_IN_MICROSECONDS))
                                              / static_cast<float>(largestSampleTimePoint - smallestSampleTimePoint)));
        m_desiredInitialLevel = (std::max<uint32_t>)(ENTRIES_TO_READ_PER_SECOND_FOR_REALTIME_REPLAY * Player::LOOK_AHEAD_IN_S, MIN_ENTRIES_FOR_LOOK_AHEAD);
        std::clog << "[cluon::Player]: Initializing cache with " << m_desiredInitialLevel << " entries." << std::endl;
        resetCaches();
        resetIterators();
        fillEnvelopeCache(m_desiredInitialLevel);
    }
}
References fillEnvelopeCache(), LOOK_AHEAD_IN_S, m_desiredInitialLevel, m_index, m_recFileValid, MIN_ENTRIES_FOR_LOOK_AHEAD, ONE_SECOND_IN_MICROSECONDS, resetCaches(), and resetIterators().
Referenced by rewind().
delay()
uint32_t cluon::Player::delay () const [inline], [noexcept]
Returns
real delay in microseconds to be waited before the next cluon::data::Envelope should be delivered.
                                             {
    std::lock_guard<std::mutex> lck(m_indexMutex);
    // Make sure that delay is not exceeding the specified maximum delay.
    return std::min<uint32_t>(m_delay, Player::MAX_DELAY_IN_MICROSECONDS);
}
References m_delay, m_indexMutex, and MAX_DELAY_IN_MICROSECONDS.
fillEnvelopeCache()
uint32_t cluon::Player::fillEnvelopeCache (const uint32_t & maxNumberOfEntriesToReadFromFile) [inline], [private], [noexcept]
This method fills the cache by trying to read up to maxNumberOfEntriesToReadFromFile from the rec file.
Parameters
maxNumberOfEntriesToReadFromFile Maximum number of entries to be read from file.
Returns
Number of entries read from file.
                                                                                                   {
    uint32_t entriesReadFromFile = 0;
    if (m_recFileValid && (maxNumberOfEntriesToReadFromFile > 0)) {
        // Reset any fstream's error states.
        m_recFile.clear();
        while ((m_nextEntryToReadFromRecFile != m_index.end()) && (entriesReadFromFile < maxNumberOfEntriesToReadFromFile)) {
            // Move to corresponding position in the .rec file.
            m_recFile.seekg(static_cast<std::streamoff>(m_nextEntryToReadFromRecFile->second.m_filePosition));
            // Read the corresponding cluon::data::Envelope.
            auto retVal = extractEnvelope(m_recFile);
            if (retVal.first) {
                // Store the envelope in the envelope cache.
                try {
                    std::lock_guard<std::mutex> lck(m_indexMutex);
                    m_nextEntryToReadFromRecFile->second.m_available
                        = m_envelopeCache.emplace(std::make_pair(m_nextEntryToReadFromRecFile->second.m_filePosition, retVal.second)).second;
                } catch (...) {} // LCOV_EXCL_LINE
                m_nextEntryToReadFromRecFile++;
                entriesReadFromFile++;
            }
        }
    }
    return entriesReadFromFile;
}
References cluon::extractEnvelope(), and retVal.
Referenced by computeInitialCacheLevelAndFillCache(), and getNextEnvelopeToBeReplayed().
getNextEnvelopeToBeReplayed()
std::pair< bool, cluon::data::Envelope > cluon::Player::getNextEnvelopeToBeReplayed () [inline], [noexcept]
Returns
Pair of bool and next cluon::data::Envelope to be replayed; if bool is false, no next Envelope is available.
                                                                                     {
    bool hasEnvelopeToReturn{false};
    cluon::data::Envelope envelopeToReturn;
    // If at "EOF", either throw exception or autorewind.
    if (m_currentEnvelopeToReplay == m_index.end()) {
        if (!m_autoRewind) {
            return std::make_pair(hasEnvelopeToReturn, envelopeToReturn);
        } else {
            rewind();
        }
    }
    if (m_currentEnvelopeToReplay != m_index.end()) {
        checkAvailabilityOfNextEnvelopeToBeReplayed();
        try {
            {
                std::lock_guard<std::mutex> lck(m_indexMutex);
                cluon::data::Envelope &nextEnvelope = m_envelopeCache[m_currentEnvelopeToReplay->second.m_filePosition];
                envelopeToReturn = nextEnvelope;
                m_delay = static_cast<uint32_t>(m_currentEnvelopeToReplay->first - m_previousEnvelopeAlreadyReplayed->first);
                // TODO: Delegate deleting into own thread.
                if (m_previousPreviousEnvelopeAlreadyReplayed != m_index.end()) {
                    auto it = m_envelopeCache.find(m_previousEnvelopeAlreadyReplayed->second.m_filePosition);
                    if (it != m_envelopeCache.end()) {
                        m_envelopeCache.erase(it);
                    }
                }
                m_previousPreviousEnvelopeAlreadyReplayed = m_previousEnvelopeAlreadyReplayed;
                m_previousEnvelopeAlreadyReplayed = m_currentEnvelopeToReplay++;
                m_numberOfReturnedEnvelopesInTotal++;
            }
            // TODO compensate for internal data processing.
            // If Player is non-threaded, read next entry sequentially.
            if (!m_threading) {
                fillEnvelopeCache(1);
            }
            // Store sample time stamp as int64 to avoid unnecessary copying of Envelopes.
            hasEnvelopeToReturn = true;
        } catch (...) {} // LCOV_EXCL_LINE
    }
    return std::make_pair(hasEnvelopeToReturn, envelopeToReturn);
}
References checkAvailabilityOfNextEnvelopeToBeReplayed(), fillEnvelopeCache(), m_autoRewind, m_currentEnvelopeToReplay, m_delay, m_envelopeCache, m_index, m_indexMutex, m_numberOfReturnedEnvelopesInTotal, m_previousEnvelopeAlreadyReplayed, m_previousPreviousEnvelopeAlreadyReplayed, m_threading, and rewind().
hasMoreData()
bool cluon::Player::hasMoreData () const [inline], [noexcept]
Returns
true if there is more data to replay.
                                               {
    std::lock_guard<std::mutex> lck(m_indexMutex);
    return hasMoreDataFromRecFile();
}
References hasMoreDataFromRecFile(), and m_indexMutex.
hasMoreDataFromRecFile()
bool cluon::Player::hasMoreDataFromRecFile () const [inline], [private], [noexcept]
                                                          {
    // File must be successfully opened AND
    // the Player must be configured as m_autoRewind OR
    // some entries are left to replay.
    return (m_recFileValid && (m_autoRewind || (m_currentEnvelopeToReplay != m_index.end())));
}
References m_autoRewind, m_currentEnvelopeToReplay, m_index, and m_recFileValid.
Referenced by hasMoreData().
initializeIndex()
void cluon::Player::initializeIndex () [inline], [private], [noexcept]
This method initializes the global index where the sample time stamps are sorted chronocally and mapped to the corresponding cluon::data::Envelope in the rec file.
                                             {
    m_recFile.open(m_file.c_str(), std::ios_base::in | std::ios_base::binary); /* Flawfinder: ignore */
    m_recFileValid = m_recFile.good();
    if (m_recFileValid) {
        // Determine file size to display progress.
        m_recFile.seekg(0, m_recFile.end);
        int64_t fileLength = m_recFile.tellg();
        m_recFile.seekg(0, m_recFile.beg);
        // Read complete file and store file positions to envelopes to create
        // index of available data. The actual reading of Envelopes is deferred.
        uint64_t totalBytesRead = 0;
        const cluon::data::TimeStamp BEFORE{cluon::time::now()};
        {
            int32_t oldPercentage = -1;
            while (m_recFile.good()) {
                const uint64_t POS_BEFORE = static_cast<uint64_t>(m_recFile.tellg());
                auto retVal = extractEnvelope(m_recFile);
                const uint64_t POS_AFTER = static_cast<uint64_t>(m_recFile.tellg());
                if (!m_recFile.eof() && retVal.first) {
                    totalBytesRead += (POS_AFTER - POS_BEFORE);
                    // Store mapping .rec file position --> index entry.
                    const int64_t microseconds = cluon::time::toMicroseconds(retVal.second.sampleTimeStamp());
                    m_index.emplace(std::make_pair(microseconds, IndexEntry(microseconds, POS_BEFORE)));
                    const int32_t percentage = static_cast<int32_t>((static_cast<float>(m_recFile.tellg()) * 100.0f) / static_cast<float>(fileLength));
                    if ((percentage % 5 == 0) && (percentage != oldPercentage)) {
                        std::clog << "[cluon::Player]: Indexed " << percentage << "% from " << m_file << "." << std::endl;
                        oldPercentage = percentage;
                    }
                }
            }
        }
        const cluon::data::TimeStamp AFTER{cluon::time::now()};
        std::clog << "[cluon::Player]: " << m_file << " contains " << m_index.size() << " entries; "
                  << "read " << totalBytesRead << " bytes "
                  << "in " << cluon::time::deltaInMicroseconds(AFTER, BEFORE) / static_cast<int64_t>(1000 * 1000) << "s." << std::endl;
    } else {
        std::clog << "[cluon::Player]: " << m_file << " could not be opened." << std::endl;
    }
}
References cluon::time::deltaInMicroseconds(), cluon::extractEnvelope(), m_file, m_index, m_recFile, m_recFileValid, cluon::time::now(), retVal, and cluon::time::toMicroseconds().
isEnvelopeCacheFillingRunning()
bool cluon::Player::isEnvelopeCacheFillingRunning () const [inline], [private], [noexcept]
                                                                 {
    std::lock_guard<std::mutex> lck(m_envelopeCacheFillingThreadIsRunningMutex);
    return m_envelopeCacheFillingThreadIsRunning;
}
References m_envelopeCacheFillingThreadIsRunning, and m_envelopeCacheFillingThreadIsRunningMutex.
Referenced by manageCache().
manageCache()
void cluon::Player::manageCache () [inline], [private], [noexcept]
This method manages the cache.
                                         {
    uint8_t statisticsCounter = 0;
    float refillMultiplicator = 1.1f;
    uint32_t numberOfEntries = 0;
    while (isEnvelopeCacheFillingRunning()) {
        try {
            std::lock_guard<std::mutex> lck(m_indexMutex);
            numberOfEntries = static_cast<uint32_t>(m_envelopeCache.size());
        } catch (...) {} // LCOV_EXCL_LINE
        // Check if refilling of the cache is needed.
        refillMultiplicator = checkRefillingCache(numberOfEntries, refillMultiplicator);
        (void)refillMultiplicator;
        // Manage cache at 10 Hz.
        using namespace std::chrono_literals;
        std::this_thread::sleep_for(100ms);
        // Publish some statistics at 1 Hz.
        if (0 == ((++statisticsCounter) % 10)) {
            uint64_t numberOfReturnedEnvelopesInTotal = 0;
            uint32_t totalNumberOfEnvelopes = 0;
            try {
                // m_numberOfReturnedEnvelopesInTotal is modified in a different thread.
                std::lock_guard<std::mutex> lck(m_indexMutex);
                numberOfReturnedEnvelopesInTotal = m_numberOfReturnedEnvelopesInTotal;
                totalNumberOfEnvelopes = static_cast<uint32_t>(m_index.size());
            } catch (...) {} // LCOV_EXCL_LINE
            try {
                std::lock_guard<std::mutex> lck(m_playerListenerMutex);
                if (nullptr != m_playerListener) {
                    cluon::data::PlayerStatus ps;
                    ps.state(2); // State: "playback"
                    ps.numberOfEntries(totalNumberOfEnvelopes);
                    ps.currentEntryForPlayback(static_cast<uint32_t>(numberOfReturnedEnvelopesInTotal));
                    m_playerListener(ps);
                }
            } catch (...) {} // LCOV_EXCL_LINE
            statisticsCounter = 0;
        }
    }
}
References checkRefillingCache(), cluon::data::PlayerStatus::currentEntryForPlayback(), isEnvelopeCacheFillingRunning(), m_envelopeCache, m_index, m_indexMutex, m_numberOfReturnedEnvelopesInTotal, m_playerListener, m_playerListenerMutex, cluon::data::PlayerStatus::numberOfEntries(), and cluon::data::PlayerStatus::state().
Referenced by Player(), rewind(), and seekTo().
operator=() [1/2]
Player & cluon::Player::operator= (const Player & other) [private], [delete]
operator=() [2/2]
Player & cluon::Player::operator= (Player &&) [private], [delete]
resetCaches()
void cluon::Player::resetCaches () [inline], [private], [noexcept]
This method clears all caches.
                                         {
    try {
        std::lock_guard<std::mutex> lck(m_indexMutex);
        m_delay = 0;
        m_numberOfReturnedEnvelopesInTotal = 0;
        m_envelopeCache.clear();
    } catch (...) {} // LCOV_EXCL_LINE
}
References m_delay, m_envelopeCache, m_indexMutex, and m_numberOfReturnedEnvelopesInTotal.
Referenced by computeInitialCacheLevelAndFillCache().
resetIterators()
void cluon::Player::resetIterators () [inline], [private], [noexcept]
This method resets the iterators.
                                            {
    try {
        std::lock_guard<std::mutex> lck(m_indexMutex);
        // Point to first entry in index.
        m_nextEntryToReadFromRecFile = m_previousEnvelopeAlreadyReplayed = m_currentEnvelopeToReplay = m_index.begin();
        // Invalidate iterator for erasing entries point.
        m_previousPreviousEnvelopeAlreadyReplayed = m_index.end();
    } catch (...) {} // LCOV_EXCL_LINE
}
References m_currentEnvelopeToReplay, m_index, m_indexMutex, m_nextEntryToReadFromRecFile, m_previousEnvelopeAlreadyReplayed, and m_previousPreviousEnvelopeAlreadyReplayed.
Referenced by computeInitialCacheLevelAndFillCache().
rewind()
void cluon::Player::rewind () [inline], [noexcept]
This method rewinds the iterators.
                                    {
    if (m_threading) {
        // Stop concurrent thread.
        setEnvelopeCacheFillingRunning(false);
        m_envelopeCacheFillingThread.join();
    }
    computeInitialCacheLevelAndFillCache();
    if (m_threading) {
        // Re-start concurrent thread.
        setEnvelopeCacheFillingRunning(true);
        m_envelopeCacheFillingThread = std::thread(&Player::manageCache, this);
    }
}
References computeInitialCacheLevelAndFillCache(), m_envelopeCacheFillingThread, m_threading, manageCache(), and setEnvelopeCacheFillingRunning().
Referenced by getNextEnvelopeToBeReplayed().
seekTo()
void cluon::Player::seekTo (float ratio) [inline], [noexcept]
                                               {
    if (!(ratio < 0) && !(ratio > 1)) {
        bool enableThreading = m_threading;
        if (m_threading) {
            // Stop concurrent thread.
            setEnvelopeCacheFillingRunning(false);
            m_envelopeCacheFillingThread.join();
        }
        // Read data sequentially.
        m_threading = false;
        resetCaches();
        resetIterators();
        uint32_t numberOfEntriesInIndex = 0;
        try {
            std::lock_guard<std::mutex> lck(m_indexMutex);
            numberOfEntriesInIndex = static_cast<uint32_t>(m_index.size());
        } catch (...) {} // LCOV_EXCL_LINE
        // Fast forward.
        m_numberOfReturnedEnvelopesInTotal = 0;
        std::clog << "[cluon::Player]: Seeking to " << static_cast<float>(numberOfEntriesInIndex) * ratio << "/" << numberOfEntriesInIndex << std::endl;
        if (0 < ratio) {
            for (m_numberOfReturnedEnvelopesInTotal = 0;
                 m_numberOfReturnedEnvelopesInTotal < static_cast<uint32_t>(static_cast<float>(numberOfEntriesInIndex) * ratio) - 1;
                 m_numberOfReturnedEnvelopesInTotal++) {
                m_currentEnvelopeToReplay++;
            }
        }
        try {
            std::lock_guard<std::mutex> lck(m_indexMutex);
            m_nextEntryToReadFromRecFile = m_previousEnvelopeAlreadyReplayed = m_currentEnvelopeToReplay;
        } catch (...) {} // LCOV_EXCL_LINE
        // Refill cache.
        m_envelopeCache.clear();
        fillEnvelopeCache(static_cast<uint32_t>(static_cast<float>(m_desiredInitialLevel) * .3f));
        // Correct iterators if not at the beginning.
        if ((0 < ratio) && (ratio < 1)) {
            getNextEnvelopeToBeReplayed();
        }
        std::clog << "[cluon::Player]: Seeking done." << std::endl;
        if (enableThreading) {
            m_threading = enableThreading;
            // Re-start concurrent thread.
            setEnvelopeCacheFillingRunning(true);
            m_envelopeCacheFillingThread = std::thread(&Player::manageCache, this);
        }
    }
}
References manageCache().
setEnvelopeCacheFillingRunning()
void cluon::Player::setEnvelopeCacheFillingRunning (const bool & running) [inline], [private], [noexcept]
This method sets the state of the envelopeCacheFilling thread.
Parameters
running False if the thread to fill the Envelope cache shall be joined.
                                                                               {
    std::lock_guard<std::mutex> lck(m_envelopeCacheFillingThreadIsRunningMutex);
    m_envelopeCacheFillingThreadIsRunning = running;
}
Referenced by rewind(), and ~Player().
setPlayerListener()
void cluon::Player::setPlayerListener (std::function< void(cluon::data::PlayerStatus playerStatus)> playerListener) [inline], [noexcept]
                                                                                                                   {
    std::lock_guard<std::mutex> lck(m_playerListenerMutex);
    m_playerListener = playerListener;
}
totalNumberOfEnvelopesInRecFile()
uint32_t cluon::Player::totalNumberOfEnvelopesInRecFile () const [inline], [noexcept]
Returns
total amount of cluon::data::Envelopes in the .rec file.
                                                                       {
    std::lock_guard<std::mutex> lck(m_indexMutex);
    return static_cast<uint32_t>(m_index.size());
}
References m_index, and m_indexMutex.
Member Data Documentation
m_autoRewind
bool cluon::Player::m_autoRewind [private]
Referenced by getNextEnvelopeToBeReplayed(), and hasMoreDataFromRecFile().
m_currentEnvelopeToReplay
std::multimap<int64_t,IndexEntry>::iterator cluon::Player::m_currentEnvelopeToReplay [private]
Referenced by getNextEnvelopeToBeReplayed(), hasMoreDataFromRecFile(), and resetIterators().
m_delay
uint32_t cluon::Player::m_delay [private]
Referenced by delay(), getNextEnvelopeToBeReplayed(), and resetCaches().
m_desiredInitialLevel
uint32_t cluon::Player::m_desiredInitialLevel [private]
Referenced by computeInitialCacheLevelAndFillCache().
m_envelopeCache
std::map<uint64_t, cluon::data::Envelope> cluon::Player::m_envelopeCache [private]
Referenced by checkAvailabilityOfNextEnvelopeToBeReplayed(), getNextEnvelopeToBeReplayed(), manageCache(), and resetCaches().
m_envelopeCacheFillingThread
std::thread cluon::Player::m_envelopeCacheFillingThread [private]
Referenced by rewind(), and ~Player().
m_envelopeCacheFillingThreadIsRunning
bool cluon::Player::m_envelopeCacheFillingThreadIsRunning [private]
Referenced by isEnvelopeCacheFillingRunning().
m_envelopeCacheFillingThreadIsRunningMutex
std::mutex cluon::Player::m_envelopeCacheFillingThreadIsRunningMutex [mutable], [private]
Referenced by isEnvelopeCacheFillingRunning().
m_file
std::string cluon::Player::m_file [private]
Referenced by initializeIndex().
m_firstTimePointReturningAEnvelope
cluon::data::TimeStamp cluon::Player::m_firstTimePointReturningAEnvelope [private]
m_index
std::multimap<int64_t, IndexEntry> cluon::Player::m_index [private]
Referenced by computeInitialCacheLevelAndFillCache(), getNextEnvelopeToBeReplayed(), hasMoreDataFromRecFile(), initializeIndex(), manageCache(), resetIterators(), and totalNumberOfEnvelopesInRecFile().
m_indexMutex
std::mutex cluon::Player::m_indexMutex [mutable], [private]
Referenced by checkAvailabilityOfNextEnvelopeToBeReplayed(), delay(), getNextEnvelopeToBeReplayed(), hasMoreData(), manageCache(), resetCaches(), resetIterators(), and totalNumberOfEnvelopesInRecFile().
m_nextEntryToReadFromRecFile
std::multimap<int64_t,IndexEntry>::iterator cluon::Player::m_nextEntryToReadFromRecFile [private]
Referenced by resetIterators().
m_numberOfReturnedEnvelopesInTotal
uint64_t cluon::Player::m_numberOfReturnedEnvelopesInTotal [private]
Referenced by getNextEnvelopeToBeReplayed(), manageCache(), and resetCaches().
m_playerListener
std::function<void(cluon::data::PlayerStatus playerStatus)> cluon::Player::m_playerListener {nullptr} [private]
Referenced by manageCache().
m_playerListenerMutex
std::mutex cluon::Player::m_playerListenerMutex [private]
Referenced by manageCache().
m_previousEnvelopeAlreadyReplayed
std::multimap<int64_t,IndexEntry>::iterator cluon::Player::m_previousEnvelopeAlreadyReplayed [private]
Referenced by getNextEnvelopeToBeReplayed(), and resetIterators().
m_previousPreviousEnvelopeAlreadyReplayed
std::multimap<int64_t,IndexEntry>::iterator cluon::Player::m_previousPreviousEnvelopeAlreadyReplayed [private]
Referenced by getNextEnvelopeToBeReplayed(), and resetIterators().
m_recFile
std::fstream cluon::Player::m_recFile [private]
Referenced by initializeIndex(), and ~Player().
m_recFileValid
bool cluon::Player::m_recFileValid [private]
Referenced by computeInitialCacheLevelAndFillCache(), hasMoreDataFromRecFile(), and initializeIndex().
m_threading
bool cluon::Player::m_threading [private]
Referenced by getNextEnvelopeToBeReplayed(), rewind(), and ~Player().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp