cluon::EnvelopeConverter Class Reference
#include <cluon-complete.hpp>
Public Member Functions
EnvelopeConverter ()=default
int32_t setMessageSpecification (const std::string &ms) noexcept
std::string getJSONFromProtoEncodedEnvelope (const std::string &protoEncodedEnvelope) noexcept
std::string getJSONFromEnvelope (cluon::data::Envelope &envelope) noexcept
std::string getProtoEncodedEnvelopeFromJSONWithoutTimeStamps (const std::string &json, int32_t messageIdentifier, uint32_t senderStamp) noexcept
std::string getProtoEncodedEnvelopeFromJSON (const std::string &json, int32_t messageIdentifier, uint32_t senderStamp) noexcept
Private Member Functions
EnvelopeConverter (const EnvelopeConverter &)=delete
EnvelopeConverter (EnvelopeConverter &&)=delete
EnvelopeConverter & operator= (const EnvelopeConverter &)=delete
EnvelopeConverter & operator= (EnvelopeConverter &&)=delete
std::string getProtoEncodedEnvelopeFromJSON (const std::string &json, int32_t messageIdentifier, uint32_t senderStamp, cluon::data::TimeStamp sampleTimeStamp) noexcept
Private Attributes
std::vector< cluon::MetaMessage > m_listOfMetaMessages {}
std::map< int32_t, cluon::MetaMessage > m_scopeOfMetaMessages {}
Detailed Description
This class provides various conversion functions to and from Envelope data structures.
Constructor & Destructor Documentation
EnvelopeConverter() [1/3]
cluon::EnvelopeConverter::EnvelopeConverter (const EnvelopeConverter &) [private], [delete]
EnvelopeConverter() [2/3]
cluon::EnvelopeConverter::EnvelopeConverter (EnvelopeConverter &&) [private], [delete]
EnvelopeConverter() [3/3]
cluon::EnvelopeConverter::EnvelopeConverter () [default]
Member Function Documentation
getJSONFromEnvelope()
std::string cluon::EnvelopeConverter::getJSONFromEnvelope (cluon::data::Envelope & envelope) [inline], [noexcept]
This method transforms the given Envelope to JSON.
Parameters
envelope Envelope.
Returns
JSON representation from given Envelope using the given message specification.
                                                                                            {
    std::string retVal{"{}"};
    if (!m_listOfMetaMessages.empty()) {
        if (0 < m_scopeOfMetaMessages.count(envelope.dataType())) {
            // First, create JSON from Envelope.
            constexpr bool OUTER_CURLY_BRACES{false};
            // Ignore field 2 (= serializedData) as it will be replaced below.
            const std::map<uint32_t, bool> mask{{2, false}};
            ToJSONVisitor envelopeToJSON{OUTER_CURLY_BRACES, mask};
            envelope.accept(envelopeToJSON);
            std::stringstream sstr{envelope.serializedData()};
            cluon::FromProtoVisitor protoDecoder;
            protoDecoder.decodeFrom(sstr);
            // Now, create JSON from payload.
            cluon::MetaMessage payload{m_scopeOfMetaMessages[envelope.dataType()]};
            cluon::GenericMessage gm;
            // Create "empty" GenericMessage from this MetaMessage.
            gm.createFrom(payload, m_listOfMetaMessages);
            // Set values in the newly created GenericMessage from ProtoDecoder.
            gm.accept(protoDecoder);
            ToJSONVisitor payloadToJSON{OUTER_CURLY_BRACES};
            try {
                // Catch possible linb::any exception.
                gm.accept(payloadToJSON);
            } catch (const linb::bad_any_cast &) {} // LCOV_EXCL_LINE
            std::string tmp{payload.messageName()};
            std::replace(tmp.begin(), tmp.end(), '.', '_');
            const std::string strPayloadJSON{payloadToJSON.json() != "{}" ? payloadToJSON.json() : ""};
            retVal = '{' + envelopeToJSON.json() + ',' + '\n' + '"' + tmp + '"' + ':' + '{' + strPayloadJSON + '}' + '}';
        }
    }
    return retVal;
}
References cluon::GenericMessage::accept(), cluon::GenericMessage::createFrom(), cluon::FromProtoVisitor::decodeFrom(), and retVal.
getJSONFromProtoEncodedEnvelope()
std::string cluon::EnvelopeConverter::getJSONFromProtoEncodedEnvelope (const std::string & protoEncodedEnvelope) [inline], [noexcept]
This method transforms the given Proto-encoded Envelope to JSON. The Proto-encoded envelope might be preceded with a 5-bytes OD4-header (optional).
Parameters
protoEncodedEnvelope Proto-encoded Envelope.
Returns
JSON representation from given Proto-encoded Envelope using the given message specification.
                                                                                                                  {
    std::string retVal{"{}"};
    if (!m_listOfMetaMessages.empty()) {
        cluon::data::Envelope envelope;
        std::stringstream sstr(protoEncodedEnvelope);
        constexpr uint8_t OD4_HEADER_SIZE{5};
        if (OD4_HEADER_SIZE < protoEncodedEnvelope.size()) {
            // Try decoding complete OD4-encoded Envelope including header.
            constexpr uint8_t byte0{0x0D};
            constexpr uint8_t byte1{0xA4};
            if ((static_cast<uint8_t>(protoEncodedEnvelope.at(0)) == byte0) && (static_cast<uint8_t>(protoEncodedEnvelope.at(1)) == byte1)) {
                uint32_t length = (*reinterpret_cast<const uint32_t *>(protoEncodedEnvelope.data() + 1));
                length = le32toh(length) >> 8;
                if ((OD4_HEADER_SIZE + length) == protoEncodedEnvelope.size()) {
                    auto result{extractEnvelope(sstr)};
                    if (result.first) {
                        envelope = result.second;
                    }
                }
            }
        }
        if (0 == envelope.dataType()) {
            // Directly decoding complete OD4 container failed, try decoding without header.
            cluon::FromProtoVisitor protoDecoder;
            protoDecoder.decodeFrom(sstr, envelope);
        }
        retVal = getJSONFromEnvelope(envelope);
    }
    return retVal;
}
References cluon::data::Envelope::dataType(), cluon::FromProtoVisitor::decodeFrom(), cluon::extractEnvelope(), and retVal.
getProtoEncodedEnvelopeFromJSON() [1/2]
std::string cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON (const std::string & json, int32_t messageIdentifier, uint32_t senderStamp) [inline], [noexcept]
This method transforms a given JSON representation into a Proto-encoded Envelope including the prepended OD4-header and setting cluon::time::now() as sampleTimeStamp.
Parameters
json representation according to the given message specification.
messageIdentifier The given JSON representation shall be interpreted as the specified message.
senderStamp to be used in the Envelope.
Returns
Proto-encoded Envelope including OD4-header or empty string.
                                                                                                                                                   {
    // clang-format on
    return getProtoEncodedEnvelopeFromJSON(json, messageIdentifier, senderStamp, cluon::time::now());
}
References cluon::time::now().
getProtoEncodedEnvelopeFromJSON() [2/2]
std::string cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON (const std::string & json, int32_t messageIdentifier, uint32_t senderStamp, cluon::data::TimeStamp sampleTimeStamp) [inline], [private], [noexcept]
                                                                                                                                                                                       {
    // clang-format on
    std::string retVal;
    if (0 < m_scopeOfMetaMessages.count(messageIdentifier)) {
        // Get specification for message to be created.
        cluon::MetaMessage message{m_scopeOfMetaMessages[messageIdentifier]};
        // Create "empty" instance for the required message as GenericMessage.
        cluon::GenericMessage gm;
        gm.createFrom(message, m_listOfMetaMessages);
        // Parse data from given JSON.
        std::stringstream sstr{json};
        cluon::FromJSONVisitor jsonDecoder;
        jsonDecoder.decodeFrom(sstr);
        // Set values in the newly created GenericMessage from JSONDecoder.
        gm.accept(jsonDecoder);
        // Finally, transform GenericMessage into Envelope.
        ToProtoVisitor protoEncoder;
        gm.accept(protoEncoder);
        cluon::data::Envelope env;
        env.dataType(messageIdentifier).serializedData(protoEncoder.encodedData()).senderStamp(senderStamp).sampleTimeStamp(sampleTimeStamp);
        retVal = cluon::serializeEnvelope(std::move(env));
    }
    return retVal;
}
References cluon::GenericMessage::accept(), cluon::GenericMessage::createFrom(), cluon::data::Envelope::dataType(), cluon::FromJSONVisitor::decodeFrom(), cluon::ToProtoVisitor::encodedData(), retVal, cluon::data::Envelope::sampleTimeStamp(), cluon::data::Envelope::senderStamp(), cluon::data::Envelope::serializedData(), and cluon::serializeEnvelope().
getProtoEncodedEnvelopeFromJSONWithoutTimeStamps()
std::string cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSONWithoutTimeStamps (const std::string & json, int32_t messageIdentifier, uint32_t senderStamp) [inline], [noexcept]
This method transforms a given JSON representation into a Proto-encoded Envelope including the prepended OD4-header.
Parameters
json representation according to the given message specification.
messageIdentifier The given JSON representation shall be interpreted as the specified message.
senderStamp to be used in the Envelope.
Returns
Proto-encoded Envelope including OD4-header or empty string.
                                                                                                                                                                    {
    // clang-format on
    return getProtoEncodedEnvelopeFromJSON(json, messageIdentifier, senderStamp, cluon::data::TimeStamp());
}
operator=() [1/2]
EnvelopeConverter & cluon::EnvelopeConverter::operator= (const EnvelopeConverter &) [private], [delete]
operator=() [2/2]
EnvelopeConverter & cluon::EnvelopeConverter::operator= (EnvelopeConverter &&) [private], [delete]
setMessageSpecification()
int32_t cluon::EnvelopeConverter::setMessageSpecification (const std::string & ms) [inline], [noexcept]
This method sets the message specification to be used for interpreting a given Proto-encoded Envelope.
Parameters
ms Message specification following the ODVD format.
Returns
-1 in case of invalid message specification; otherwise, number of successfully parsed messages from given message specification.
                                                                                      {
    int32_t retVal{-1};
    m_listOfMetaMessages.clear();
    m_scopeOfMetaMessages.clear();
    cluon::MessageParser mp;
    auto parsingResult = mp.parse(ms);
    if (cluon::MessageParser::MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR == parsingResult.second) {
        m_listOfMetaMessages = parsingResult.first;
        for (const auto &mm : m_listOfMetaMessages) { m_scopeOfMetaMessages[mm.messageIdentifier()] = mm; }
        retVal = static_cast<int32_t>(m_listOfMetaMessages.size());
    }
    return retVal;
}
References mm, cluon::MessageParser::parse(), and retVal.
Member Data Documentation
m_listOfMetaMessages
std::vector<cluon::MetaMessage> cluon::EnvelopeConverter::m_listOfMetaMessages {} [private]
m_scopeOfMetaMessages
std::map<int32_t, cluon::MetaMessage> cluon::EnvelopeConverter::m_scopeOfMetaMessages {} [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp