opendlv::proxy::AccelerationReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
AccelerationReading ()=default
AccelerationReading (const AccelerationReading &)=default
AccelerationReading & operator= (const AccelerationReading &)=default
AccelerationReading (AccelerationReading &&)=default
AccelerationReading & operator= (AccelerationReading &&)=default
~AccelerationReading ()=default
AccelerationReading & accelerationX (const float &v) noexcept
float accelerationX () const noexcept
AccelerationReading & accelerationY (const float &v) noexcept
float accelerationY () const noexcept
AccelerationReading & accelerationZ (const float &v) noexcept
float accelerationZ () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_accelerationX { 0.0f }
float m_accelerationY { 0.0f }
float m_accelerationZ { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `AccelerationReading`
static constexpr const char * TheLongName = `opendlv.proxy.AccelerationReading`
Constructor & Destructor Documentation
AccelerationReading() [1/3]
opendlv::proxy::AccelerationReading::AccelerationReading () [default]
AccelerationReading() [2/3]
opendlv::proxy::AccelerationReading::AccelerationReading (const AccelerationReading &) [default]
AccelerationReading() [3/3]
opendlv::proxy::AccelerationReading::AccelerationReading (AccelerationReading &&) [default]
 AccelerationReading()
opendlv::proxy::AccelerationReading::~AccelerationReading () [default]
Member Function Documentation
accelerationX() [1/2]
float opendlv::proxy::AccelerationReading::accelerationX () const [inline], [noexcept]
                                                    {
            return m_accelerationX;
        }
accelerationX() [2/2]
AccelerationReading & opendlv::proxy::AccelerationReading::accelerationX (const float & v) [inline], [noexcept]
                                                                           {
            m_accelerationX = v;
            return *this;
        }
accelerationY() [1/2]
float opendlv::proxy::AccelerationReading::accelerationY () const [inline], [noexcept]
                                                    {
            return m_accelerationY;
        }
accelerationY() [2/2]
AccelerationReading & opendlv::proxy::AccelerationReading::accelerationY (const float & v) [inline], [noexcept]
                                                                           {
            m_accelerationY = v;
            return *this;
        }
accelerationZ() [1/2]
float opendlv::proxy::AccelerationReading::accelerationZ () const [inline], [noexcept]
                                                    {
            return m_accelerationZ;
        }
accelerationZ() [2/2]
AccelerationReading & opendlv::proxy::AccelerationReading::accelerationZ (const float & v) [inline], [noexcept]
                                                                           {
            m_accelerationZ = v;
            return *this;
        }
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::AccelerationReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("accelerationX"s), m_accelerationX, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("accelerationY"s), m_accelerationY, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("accelerationZ"s), m_accelerationZ, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::AccelerationReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("accelerationX"s), m_accelerationX, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("accelerationY"s), m_accelerationY, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("accelerationZ"s), m_accelerationZ, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::AccelerationReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("accelerationX"s), m_accelerationX, visitor);
            doVisit(2, std::move("float"s), std::move("accelerationY"s), m_accelerationY, visitor);
            doVisit(3, std::move("float"s), std::move("accelerationZ"s), m_accelerationZ, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::AccelerationReading::ID () [inline], [static]
                                   {
            return 1030;
        }
LongName()
static const std::string opendlv::proxy::AccelerationReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
AccelerationReading & opendlv::proxy::AccelerationReading::operator= (AccelerationReading &&) [default]
operator=() [2/2]
AccelerationReading & opendlv::proxy::AccelerationReading::operator= (const AccelerationReading &) [default]
ShortName()
static const std::string opendlv::proxy::AccelerationReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_accelerationX
float opendlv::proxy::AccelerationReading::m_accelerationX { 0.0f } [private]
m_accelerationY
float opendlv::proxy::AccelerationReading::m_accelerationY { 0.0f } [private]
m_accelerationZ
float opendlv::proxy::AccelerationReading::m_accelerationZ { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::AccelerationReading::TheLongName = `opendlv.proxy.AccelerationReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::AccelerationReading::TheShortName = `AccelerationReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp