opendlv::proxy::GeodeticWgs84Reading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GeodeticWgs84Reading ()=default
GeodeticWgs84Reading (const GeodeticWgs84Reading &)=default
GeodeticWgs84Reading & operator= (const GeodeticWgs84Reading &)=default
GeodeticWgs84Reading (GeodeticWgs84Reading &&)=default
GeodeticWgs84Reading & operator= (GeodeticWgs84Reading &&)=default
~GeodeticWgs84Reading ()=default
GeodeticWgs84Reading & latitude (const double &v) noexcept
double latitude () const noexcept
GeodeticWgs84Reading & longitude (const double &v) noexcept
double longitude () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
double m_latitude { 0.0 }
double m_longitude { 0.0 }
Static Private Attributes
static constexpr const char * TheShortName = `GeodeticWgs84Reading`
static constexpr const char * TheLongName = `opendlv.proxy.GeodeticWgs84Reading`
Constructor & Destructor Documentation
GeodeticWgs84Reading() [1/3]
opendlv::proxy::GeodeticWgs84Reading::GeodeticWgs84Reading () [default]
GeodeticWgs84Reading() [2/3]
opendlv::proxy::GeodeticWgs84Reading::GeodeticWgs84Reading (const GeodeticWgs84Reading &) [default]
GeodeticWgs84Reading() [3/3]
opendlv::proxy::GeodeticWgs84Reading::GeodeticWgs84Reading (GeodeticWgs84Reading &&) [default]
 GeodeticWgs84Reading()
opendlv::proxy::GeodeticWgs84Reading::~GeodeticWgs84Reading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GeodeticWgs84Reading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("double"s), std::move("longitude"s), m_longitude, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GeodeticWgs84Reading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("double"s), std::move("longitude"s), m_longitude, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GeodeticWgs84Reading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("double"s), std::move("latitude"s), m_latitude, visitor);
            doVisit(3, std::move("double"s), std::move("longitude"s), m_longitude, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::GeodeticWgs84Reading::ID () [inline], [static]
                                   {
            return 19;
        }
latitude() [1/2]
double opendlv::proxy::GeodeticWgs84Reading::latitude () const [inline], [noexcept]
                                                {
            return m_latitude;
        }
latitude() [2/2]
GeodeticWgs84Reading & opendlv::proxy::GeodeticWgs84Reading::latitude (const double & v) [inline], [noexcept]
                                                                        {
            m_latitude = v;
            return *this;
        }
longitude() [1/2]
double opendlv::proxy::GeodeticWgs84Reading::longitude () const [inline], [noexcept]
                                                 {
            return m_longitude;
        }
longitude() [2/2]
GeodeticWgs84Reading & opendlv::proxy::GeodeticWgs84Reading::longitude (const double & v) [inline], [noexcept]
                                                                         {
            m_longitude = v;
            return *this;
        }
LongName()
static const std::string opendlv::proxy::GeodeticWgs84Reading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GeodeticWgs84Reading & opendlv::proxy::GeodeticWgs84Reading::operator= (const GeodeticWgs84Reading &) [default]
operator=() [2/2]
GeodeticWgs84Reading & opendlv::proxy::GeodeticWgs84Reading::operator= (GeodeticWgs84Reading &&) [default]
ShortName()
static const std::string opendlv::proxy::GeodeticWgs84Reading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_latitude
double opendlv::proxy::GeodeticWgs84Reading::m_latitude { 0.0 } [private]
m_longitude
double opendlv::proxy::GeodeticWgs84Reading::m_longitude { 0.0 } [private]
TheLongName
constexpr const char* opendlv::proxy::GeodeticWgs84Reading::TheLongName = `opendlv.proxy.GeodeticWgs84Reading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GeodeticWgs84Reading::TheShortName = `GeodeticWgs84Reading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp