opendlv::proxy::PointCloudReadingShared Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PointCloudReadingShared ()=default
PointCloudReadingShared (const PointCloudReadingShared &)=default
PointCloudReadingShared & operator= (const PointCloudReadingShared &)=default
PointCloudReadingShared (PointCloudReadingShared &&)=default
PointCloudReadingShared & operator= (PointCloudReadingShared &&)=default
~PointCloudReadingShared ()=default
PointCloudReadingShared & name (const std::string &v) noexcept
std::string name () const noexcept
PointCloudReadingShared & size (const uint32_t &v) noexcept
uint32_t size () const noexcept
PointCloudReadingShared & width (const uint32_t &v) noexcept
uint32_t width () const noexcept
PointCloudReadingShared & height (const uint32_t &v) noexcept
uint32_t height () const noexcept
PointCloudReadingShared & numberOfComponentsPerPoint (const uint8_t &v) noexcept
uint8_t numberOfComponentsPerPoint () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_name { ``s }
uint32_t m_size { 0 }
uint32_t m_width { 0 }
uint32_t m_height { 0 }
uint8_t m_numberOfComponentsPerPoint { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `PointCloudReadingShared`
static constexpr const char * TheLongName = `opendlv.proxy.PointCloudReadingShared`
Constructor & Destructor Documentation
PointCloudReadingShared() [1/3]
opendlv::proxy::PointCloudReadingShared::PointCloudReadingShared () [default]
PointCloudReadingShared() [2/3]
opendlv::proxy::PointCloudReadingShared::PointCloudReadingShared (const PointCloudReadingShared &) [default]
PointCloudReadingShared() [3/3]
opendlv::proxy::PointCloudReadingShared::PointCloudReadingShared (PointCloudReadingShared &&) [default]
 PointCloudReadingShared()
opendlv::proxy::PointCloudReadingShared::~PointCloudReadingShared () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PointCloudReadingShared::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("name"s), m_name, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, preVisit, visit, postVisit);
            doTripletForwardVisit(5, std::move("uint8_t"s), std::move("numberOfComponentsPerPoint"s), m_numberOfComponentsPerPoint, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PointCloudReadingShared::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("name"s), m_name, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
                return;
            }
            if (5 == fieldId) {
                doVisit(5, std::move("uint8_t"s), std::move("numberOfComponentsPerPoint"s), m_numberOfComponentsPerPoint, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PointCloudReadingShared::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("name"s), m_name, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("size"s), m_size, visitor);
            doVisit(3, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
            doVisit(4, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
            doVisit(5, std::move("uint8_t"s), std::move("numberOfComponentsPerPoint"s), m_numberOfComponentsPerPoint, visitor);
            visitor.postVisit();
        }
References doVisit().
height() [1/2]
uint32_t opendlv::proxy::PointCloudReadingShared::height () const [inline], [noexcept]
                                                {
            return m_height;
        }
height() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::height (const uint32_t & v) [inline], [noexcept]
                                                                           {
            m_height = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::PointCloudReadingShared::ID () [inline], [static]
                                   {
            return 28;
        }
LongName()
static const std::string opendlv::proxy::PointCloudReadingShared::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
name() [1/2]
std::string opendlv::proxy::PointCloudReadingShared::name () const [inline], [noexcept]
                                               {
            return m_name;
        }
name() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::name (const std::string & v) [inline], [noexcept]
                                                                          {
            m_name = v;
            return *this;
        }
numberOfComponentsPerPoint() [1/2]
uint8_t opendlv::proxy::PointCloudReadingShared::numberOfComponentsPerPoint () const [inline], [noexcept]
                                                                   {
            return m_numberOfComponentsPerPoint;
        }
numberOfComponentsPerPoint() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::numberOfComponentsPerPoint (const uint8_t & v) [inline], [noexcept]
                                                                                              {
            m_numberOfComponentsPerPoint = v;
            return *this;
        }
operator=() [1/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::operator= (const PointCloudReadingShared &) [default]
operator=() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::operator= (PointCloudReadingShared &&) [default]
ShortName()
static const std::string opendlv::proxy::PointCloudReadingShared::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
size() [1/2]
uint32_t opendlv::proxy::PointCloudReadingShared::size () const [inline], [noexcept]
                                              {
            return m_size;
        }
size() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::size (const uint32_t & v) [inline], [noexcept]
                                                                         {
            m_size = v;
            return *this;
        }
width() [1/2]
uint32_t opendlv::proxy::PointCloudReadingShared::width () const [inline], [noexcept]
                                               {
            return m_width;
        }
width() [2/2]
PointCloudReadingShared & opendlv::proxy::PointCloudReadingShared::width (const uint32_t & v) [inline], [noexcept]
                                                                          {
            m_width = v;
            return *this;
        }
Member Data Documentation
m_height
uint32_t opendlv::proxy::PointCloudReadingShared::m_height { 0 } [private]
m_name
std::string opendlv::proxy::PointCloudReadingShared::m_name { ``s } [private]
m_numberOfComponentsPerPoint
uint8_t opendlv::proxy::PointCloudReadingShared::m_numberOfComponentsPerPoint { 0 } [private]
m_size
uint32_t opendlv::proxy::PointCloudReadingShared::m_size { 0 } [private]
m_width
uint32_t opendlv::proxy::PointCloudReadingShared::m_width { 0 } [private]
TheLongName
constexpr const char* opendlv::proxy::PointCloudReadingShared::TheLongName = `opendlv.proxy.PointCloudReadingShared` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PointCloudReadingShared::TheShortName = `PointCloudReadingShared` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp