opendlv::body::SignalInfo Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
SignalInfo ()=default
SignalInfo (const SignalInfo &)=default
SignalInfo & operator= (const SignalInfo &)=default
SignalInfo (SignalInfo &&)=default
SignalInfo & operator= (SignalInfo &&)=default
~SignalInfo ()=default
SignalInfo & description (const std::string &v) noexcept
std::string description () const noexcept
SignalInfo & signalId (const uint32_t &v) noexcept
uint32_t signalId () const noexcept
SignalInfo & accuracyStd (const float &v) noexcept
float accuracyStd () const noexcept
SignalInfo & minFrequency (const uint16_t &v) noexcept
uint16_t minFrequency () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_description { ``s }
uint32_t m_signalId { 0 }
float m_accuracyStd { 0.0f }
uint16_t m_minFrequency { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `SignalInfo`
static constexpr const char * TheLongName = `opendlv.body.SignalInfo`
Constructor & Destructor Documentation
SignalInfo() [1/3]
opendlv::body::SignalInfo::SignalInfo () [default]
SignalInfo() [2/3]
opendlv::body::SignalInfo::SignalInfo (const SignalInfo &) [default]
SignalInfo() [3/3]
opendlv::body::SignalInfo::SignalInfo (SignalInfo &&) [default]
 SignalInfo()
opendlv::body::SignalInfo::~SignalInfo () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::body::SignalInfo::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("signalId"s), m_signalId, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::body::SignalInfo::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::body::SignalInfo::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("description"s), m_description, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("signalId"s), m_signalId, visitor);
            doVisit(3, std::move("float"s), std::move("accuracyStd"s), m_accuracyStd, visitor);
            doVisit(4, std::move("uint16_t"s), std::move("minFrequency"s), m_minFrequency, visitor);
            visitor.postVisit();
        }
References doVisit().
accuracyStd() [1/2]
float opendlv::body::SignalInfo::accuracyStd () const [inline], [noexcept]
                                                  {
            return m_accuracyStd;
        }
accuracyStd() [2/2]
SignalInfo & opendlv::body::SignalInfo::accuracyStd (const float & v) [inline], [noexcept]
                                                                {
            m_accuracyStd = v;
            return *this;
        }
description() [1/2]
std::string opendlv::body::SignalInfo::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
SignalInfo & opendlv::body::SignalInfo::description (const std::string & v) [inline], [noexcept]
                                                                    {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::body::SignalInfo::ID () [inline], [static]
                                   {
            return 1024;
        }
LongName()
static const std::string opendlv::body::SignalInfo::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
minFrequency() [1/2]
uint16_t opendlv::body::SignalInfo::minFrequency () const [inline], [noexcept]
                                                      {
            return m_minFrequency;
        }
minFrequency() [2/2]
SignalInfo & opendlv::body::SignalInfo::minFrequency (const uint16_t & v) [inline], [noexcept]
                                                                    {
            m_minFrequency = v;
            return *this;
        }
operator=() [1/2]
SignalInfo & opendlv::body::SignalInfo::operator= (const SignalInfo &) [default]
operator=() [2/2]
SignalInfo & opendlv::body::SignalInfo::operator= (SignalInfo &&) [default]
ShortName()
static const std::string opendlv::body::SignalInfo::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
signalId() [1/2]
uint32_t opendlv::body::SignalInfo::signalId () const [inline], [noexcept]
                                                  {
            return m_signalId;
        }
signalId() [2/2]
SignalInfo & opendlv::body::SignalInfo::signalId (const uint32_t & v) [inline], [noexcept]
                                                                {
            m_signalId = v;
            return *this;
        }
Member Data Documentation
m_accuracyStd
float opendlv::body::SignalInfo::m_accuracyStd { 0.0f } [private]
m_description
std::string opendlv::body::SignalInfo::m_description { ``s } [private]
m_minFrequency
uint16_t opendlv::body::SignalInfo::m_minFrequency { 0 } [private]
m_signalId
uint32_t opendlv::body::SignalInfo::m_signalId { 0 } [private]
TheLongName
constexpr const char* opendlv::body::SignalInfo::TheLongName = `opendlv.body.SignalInfo` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::body::SignalInfo::TheShortName = `SignalInfo` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp