opendlv::proxy::PressureRequest Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
PressureRequest ()=default
PressureRequest (const PressureRequest &)=default
PressureRequest & operator= (const PressureRequest &)=default
PressureRequest (PressureRequest &&)=default
PressureRequest & operator= (PressureRequest &&)=default
~PressureRequest ()=default
PressureRequest & pressure (const float &v) noexcept
float pressure () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_pressure { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `PressureRequest`
static constexpr const char * TheLongName = `opendlv.proxy.PressureRequest`
Constructor & Destructor Documentation
PressureRequest() [1/3]
opendlv::proxy::PressureRequest::PressureRequest () [default]
PressureRequest() [2/3]
opendlv::proxy::PressureRequest::PressureRequest (const PressureRequest &) [default]
PressureRequest() [3/3]
opendlv::proxy::PressureRequest::PressureRequest (PressureRequest &&) [default]
 PressureRequest()
opendlv::proxy::PressureRequest::~PressureRequest () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::PressureRequest::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::PressureRequest::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::PressureRequest::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("pressure"s), m_pressure, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::PressureRequest::ID () [inline], [static]
                                   {
            return 1080;
        }
LongName()
static const std::string opendlv::proxy::PressureRequest::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
PressureRequest & opendlv::proxy::PressureRequest::operator= (const PressureRequest &) [default]
operator=() [2/2]
PressureRequest & opendlv::proxy::PressureRequest::operator= (PressureRequest &&) [default]
pressure() [1/2]
float opendlv::proxy::PressureRequest::pressure () const [inline], [noexcept]
                                               {
            return m_pressure;
        }
pressure() [2/2]
PressureRequest & opendlv::proxy::PressureRequest::pressure (const float & v) [inline], [noexcept]
                                                                  {
            m_pressure = v;
            return *this;
        }
ShortName()
static const std::string opendlv::proxy::PressureRequest::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_pressure
float opendlv::proxy::PressureRequest::m_pressure { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::PressureRequest::TheLongName = `opendlv.proxy.PressureRequest` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::PressureRequest::TheShortName = `PressureRequest` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp