opendlv::system::NetworkStatusMessage Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
NetworkStatusMessage ()=default
NetworkStatusMessage (const NetworkStatusMessage &)=default
NetworkStatusMessage & operator= (const NetworkStatusMessage &)=default
NetworkStatusMessage (NetworkStatusMessage &&)=default
NetworkStatusMessage & operator= (NetworkStatusMessage &&)=default
~NetworkStatusMessage ()=default
NetworkStatusMessage & code (const int32_t &v) noexcept
int32_t code () const noexcept
NetworkStatusMessage & description (const std::string &v) noexcept
std::string description () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
int32_t m_code { 0 }
std::string m_description { ``s }
Static Private Attributes
static constexpr const char * TheShortName = `NetworkStatusMessage`
static constexpr const char * TheLongName = `opendlv.system.NetworkStatusMessage`
Constructor & Destructor Documentation
NetworkStatusMessage() [1/3]
opendlv::system::NetworkStatusMessage::NetworkStatusMessage () [default]
NetworkStatusMessage() [2/3]
opendlv::system::NetworkStatusMessage::NetworkStatusMessage (const NetworkStatusMessage &) [default]
NetworkStatusMessage() [3/3]
opendlv::system::NetworkStatusMessage::NetworkStatusMessage (NetworkStatusMessage &&) [default]
 NetworkStatusMessage()
opendlv::system::NetworkStatusMessage::~NetworkStatusMessage () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::system::NetworkStatusMessage::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("int32_t"s), std::move("code"s), m_code, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("std::string"s), std::move("description"s), m_description, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::system::NetworkStatusMessage::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("int32_t"s), std::move("code"s), m_code, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("std::string"s), std::move("description"s), m_description, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::system::NetworkStatusMessage::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("int32_t"s), std::move("code"s), m_code, visitor);
            doVisit(2, std::move("std::string"s), std::move("description"s), m_description, visitor);
            visitor.postVisit();
        }
References doVisit().
code() [1/2]
int32_t opendlv::system::NetworkStatusMessage::code () const [inline], [noexcept]
                                             {
            return m_code;
        }
code() [2/2]
NetworkStatusMessage & opendlv::system::NetworkStatusMessage::code (const int32_t & v) [inline], [noexcept]
                                                                     {
            m_code = v;
            return *this;
        }
description() [1/2]
std::string opendlv::system::NetworkStatusMessage::description () const [inline], [noexcept]
                                                      {
            return m_description;
        }
description() [2/2]
NetworkStatusMessage & opendlv::system::NetworkStatusMessage::description (const std::string & v) [inline], [noexcept]
                                                                              {
            m_description = v;
            return *this;
        }
ID()
static int32_t opendlv::system::NetworkStatusMessage::ID () [inline], [static]
                                   {
            return 1102;
        }
LongName()
static const std::string opendlv::system::NetworkStatusMessage::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
NetworkStatusMessage & opendlv::system::NetworkStatusMessage::operator= (const NetworkStatusMessage &) [default]
operator=() [2/2]
NetworkStatusMessage & opendlv::system::NetworkStatusMessage::operator= (NetworkStatusMessage &&) [default]
ShortName()
static const std::string opendlv::system::NetworkStatusMessage::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_code
int32_t opendlv::system::NetworkStatusMessage::m_code { 0 } [private]
m_description
std::string opendlv::system::NetworkStatusMessage::m_description { ``s } [private]
TheLongName
constexpr const char* opendlv::system::NetworkStatusMessage::TheLongName = `opendlv.system.NetworkStatusMessage` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::system::NetworkStatusMessage::TheShortName = `NetworkStatusMessage` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp