opendlv::proxy::ImageReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ImageReading ()=default
ImageReading (const ImageReading &)=default
ImageReading & operator= (const ImageReading &)=default
ImageReading (ImageReading &&)=default
ImageReading & operator= (ImageReading &&)=default
~ImageReading ()=default
ImageReading & fourcc (const std::string &v) noexcept
std::string fourcc () const noexcept
ImageReading & width (const uint32_t &v) noexcept
uint32_t width () const noexcept
ImageReading & height (const uint32_t &v) noexcept
uint32_t height () const noexcept
ImageReading & data (const std::string &v) noexcept
std::string data () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
std::string m_fourcc { ``s }
uint32_t m_width { 0 }
uint32_t m_height { 0 }
std::string m_data { ``s }
Static Private Attributes
static constexpr const char * TheShortName = `ImageReading`
static constexpr const char * TheLongName = `opendlv.proxy.ImageReading`
Constructor & Destructor Documentation
ImageReading() [1/3]
opendlv::proxy::ImageReading::ImageReading () [default]
ImageReading() [2/3]
opendlv::proxy::ImageReading::ImageReading (const ImageReading &) [default]
ImageReading() [3/3]
opendlv::proxy::ImageReading::ImageReading (ImageReading &&) [default]
 ImageReading()
opendlv::proxy::ImageReading::~ImageReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::ImageReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("std::string"s), std::move("fourcc"s), m_fourcc, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("uint32_t"s), std::move("width"s), m_width, preVisit, visit, postVisit);
            doTripletForwardVisit(3, std::move("uint32_t"s), std::move("height"s), m_height, preVisit, visit, postVisit);
            doTripletForwardVisit(4, std::move("std::string"s), std::move("data"s), m_data, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::ImageReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("std::string"s), std::move("fourcc"s), m_fourcc, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
                return;
            }
            if (3 == fieldId) {
                doVisit(3, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
                return;
            }
            if (4 == fieldId) {
                doVisit(4, std::move("std::string"s), std::move("data"s), m_data, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::ImageReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("std::string"s), std::move("fourcc"s), m_fourcc, visitor);
            doVisit(2, std::move("uint32_t"s), std::move("width"s), m_width, visitor);
            doVisit(3, std::move("uint32_t"s), std::move("height"s), m_height, visitor);
            doVisit(4, std::move("std::string"s), std::move("data"s), m_data, visitor);
            visitor.postVisit();
        }
References doVisit().
data() [1/2]
std::string opendlv::proxy::ImageReading::data () const [inline], [noexcept]
                                               {
            return m_data;
        }
data() [2/2]
ImageReading & opendlv::proxy::ImageReading::data (const std::string & v) [inline], [noexcept]
                                                               {
            m_data = v;
            return *this;
        }
fourcc() [1/2]
std::string opendlv::proxy::ImageReading::fourcc () const [inline], [noexcept]
                                                 {
            return m_fourcc;
        }
fourcc() [2/2]
ImageReading & opendlv::proxy::ImageReading::fourcc (const std::string & v) [inline], [noexcept]
                                                                 {
            m_fourcc = v;
            return *this;
        }
height() [1/2]
uint32_t opendlv::proxy::ImageReading::height () const [inline], [noexcept]
                                                {
            return m_height;
        }
height() [2/2]
ImageReading & opendlv::proxy::ImageReading::height (const uint32_t & v) [inline], [noexcept]
                                                                {
            m_height = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::ImageReading::ID () [inline], [static]
                                   {
            return 1055;
        }
LongName()
static const std::string opendlv::proxy::ImageReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
ImageReading & opendlv::proxy::ImageReading::operator= (const ImageReading &) [default]
operator=() [2/2]
ImageReading & opendlv::proxy::ImageReading::operator= (ImageReading &&) [default]
ShortName()
static const std::string opendlv::proxy::ImageReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
width() [1/2]
uint32_t opendlv::proxy::ImageReading::width () const [inline], [noexcept]
                                               {
            return m_width;
        }
width() [2/2]
ImageReading & opendlv::proxy::ImageReading::width (const uint32_t & v) [inline], [noexcept]
                                                               {
            m_width = v;
            return *this;
        }
Member Data Documentation
m_data
std::string opendlv::proxy::ImageReading::m_data { ``s } [private]
m_fourcc
std::string opendlv::proxy::ImageReading::m_fourcc { ``s } [private]
m_height
uint32_t opendlv::proxy::ImageReading::m_height { 0 } [private]
m_width
uint32_t opendlv::proxy::ImageReading::m_width { 0 } [private]
TheLongName
constexpr const char* opendlv::proxy::ImageReading::TheLongName = `opendlv.proxy.ImageReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::ImageReading::TheShortName = `ImageReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp