opendlv::logic::sensation::Direction Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
Direction ()=default
Direction (const Direction &)=default
Direction & operator= (const Direction &)=default
Direction (Direction &&)=default
Direction & operator= (Direction &&)=default
~Direction ()=default
Direction & azimuthAngle (const float &v) noexcept
float azimuthAngle () const noexcept
Direction & zenithAngle (const float &v) noexcept
float zenithAngle () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_azimuthAngle { 0.0f }
float m_zenithAngle { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `Direction`
static constexpr const char * TheLongName = `opendlv.logic.sensation.Direction`
Constructor & Destructor Documentation
Direction() [1/3]
opendlv::logic::sensation::Direction::Direction () [default]
Direction() [2/3]
opendlv::logic::sensation::Direction::Direction (const Direction &) [default]
Direction() [3/3]
opendlv::logic::sensation::Direction::Direction (Direction &&) [default]
 Direction()
opendlv::logic::sensation::Direction::~Direction () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::sensation::Direction::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::sensation::Direction::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::sensation::Direction::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("azimuthAngle"s), m_azimuthAngle, visitor);
            doVisit(2, std::move("float"s), std::move("zenithAngle"s), m_zenithAngle, visitor);
            visitor.postVisit();
        }
References doVisit().
azimuthAngle() [1/2]
float opendlv::logic::sensation::Direction::azimuthAngle () const [inline], [noexcept]
                                                   {
            return m_azimuthAngle;
        }
azimuthAngle() [2/2]
Direction & opendlv::logic::sensation::Direction::azimuthAngle (const float & v) [inline], [noexcept]
                                                                {
            m_azimuthAngle = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::sensation::Direction::ID () [inline], [static]
                                   {
            return 1110;
        }
LongName()
static const std::string opendlv::logic::sensation::Direction::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
Direction & opendlv::logic::sensation::Direction::operator= (const Direction &) [default]
operator=() [2/2]
Direction & opendlv::logic::sensation::Direction::operator= (Direction &&) [default]
ShortName()
static const std::string opendlv::logic::sensation::Direction::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
zenithAngle() [1/2]
float opendlv::logic::sensation::Direction::zenithAngle () const [inline], [noexcept]
                                                  {
            return m_zenithAngle;
        }
zenithAngle() [2/2]
Direction & opendlv::logic::sensation::Direction::zenithAngle (const float & v) [inline], [noexcept]
                                                               {
            m_zenithAngle = v;
            return *this;
        }
Member Data Documentation
m_azimuthAngle
float opendlv::logic::sensation::Direction::m_azimuthAngle { 0.0f } [private]
m_zenithAngle
float opendlv::logic::sensation::Direction::m_zenithAngle { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::sensation::Direction::TheLongName = `opendlv.logic.sensation.Direction` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::sensation::Direction::TheShortName = `Direction` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp