opendlv::proxy::TorqueReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
TorqueReading ()=default
TorqueReading (const TorqueReading &)=default
TorqueReading & operator= (const TorqueReading &)=default
TorqueReading (TorqueReading &&)=default
TorqueReading & operator= (TorqueReading &&)=default
~TorqueReading ()=default
TorqueReading & torque (const float &v) noexcept
float torque () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_torque { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `TorqueReading`
static constexpr const char * TheLongName = `opendlv.proxy.TorqueReading`
Constructor & Destructor Documentation
TorqueReading() [1/3]
opendlv::proxy::TorqueReading::TorqueReading () [default]
TorqueReading() [2/3]
opendlv::proxy::TorqueReading::TorqueReading (const TorqueReading &) [default]
TorqueReading() [3/3]
opendlv::proxy::TorqueReading::TorqueReading (TorqueReading &&) [default]
 TorqueReading()
opendlv::proxy::TorqueReading::~TorqueReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::TorqueReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("torque"s), m_torque, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::TorqueReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("torque"s), m_torque, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::TorqueReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("torque"s), m_torque, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::proxy::TorqueReading::ID () [inline], [static]
                                   {
            return 1036;
        }
LongName()
static const std::string opendlv::proxy::TorqueReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
TorqueReading & opendlv::proxy::TorqueReading::operator= (const TorqueReading &) [default]
operator=() [2/2]
TorqueReading & opendlv::proxy::TorqueReading::operator= (TorqueReading &&) [default]
ShortName()
static const std::string opendlv::proxy::TorqueReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
torque() [1/2]
float opendlv::proxy::TorqueReading::torque () const [inline], [noexcept]
                                             {
            return m_torque;
        }
torque() [2/2]
TorqueReading & opendlv::proxy::TorqueReading::torque (const float & v) [inline], [noexcept]
                                                              {
            m_torque = v;
            return *this;
        }
Member Data Documentation
m_torque
float opendlv::proxy::TorqueReading::m_torque { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::TorqueReading::TheLongName = `opendlv.proxy.TorqueReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::TorqueReading::TheShortName = `TorqueReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp