opendlv::logic::perception::ObjectDistance Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
ObjectDistance ()=default
ObjectDistance (const ObjectDistance &)=default
ObjectDistance & operator= (const ObjectDistance &)=default
ObjectDistance (ObjectDistance &&)=default
ObjectDistance & operator= (ObjectDistance &&)=default
~ObjectDistance ()=default
ObjectDistance & objectId (const uint32_t &v) noexcept
uint32_t objectId () const noexcept
ObjectDistance & distance (const float &v) noexcept
float distance () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
uint32_t m_objectId { 0 }
float m_distance { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `ObjectDistance`
static constexpr const char * TheLongName = `opendlv.logic.perception.ObjectDistance`
Constructor & Destructor Documentation
ObjectDistance() [1/3]
opendlv::logic::perception::ObjectDistance::ObjectDistance () [default]
ObjectDistance() [2/3]
opendlv::logic::perception::ObjectDistance::ObjectDistance (const ObjectDistance &) [default]
ObjectDistance() [3/3]
opendlv::logic::perception::ObjectDistance::ObjectDistance (ObjectDistance &&) [default]
 ObjectDistance()
opendlv::logic::perception::ObjectDistance::~ObjectDistance () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::perception::ObjectDistance::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, preVisit, visit, postVisit);
            doTripletForwardVisit(2, std::move("float"s), std::move("distance"s), m_distance, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::perception::ObjectDistance::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
                return;
            }
            if (2 == fieldId) {
                doVisit(2, std::move("float"s), std::move("distance"s), m_distance, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::perception::ObjectDistance::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("uint32_t"s), std::move("objectId"s), m_objectId, visitor);
            doVisit(2, std::move("float"s), std::move("distance"s), m_distance, visitor);
            visitor.postVisit();
        }
References doVisit().
distance() [1/2]
float opendlv::logic::perception::ObjectDistance::distance () const [inline], [noexcept]
                                               {
            return m_distance;
        }
distance() [2/2]
ObjectDistance & opendlv::logic::perception::ObjectDistance::distance (const float & v) [inline], [noexcept]
                                                                 {
            m_distance = v;
            return *this;
        }
ID()
static int32_t opendlv::logic::perception::ObjectDistance::ID () [inline], [static]
                                   {
            return 1134;
        }
LongName()
static const std::string opendlv::logic::perception::ObjectDistance::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
objectId() [1/2]
uint32_t opendlv::logic::perception::ObjectDistance::objectId () const [inline], [noexcept]
                                                  {
            return m_objectId;
        }
objectId() [2/2]
ObjectDistance & opendlv::logic::perception::ObjectDistance::objectId (const uint32_t & v) [inline], [noexcept]
                                                                    {
            m_objectId = v;
            return *this;
        }
operator=() [1/2]
ObjectDistance & opendlv::logic::perception::ObjectDistance::operator= (const ObjectDistance &) [default]
operator=() [2/2]
ObjectDistance & opendlv::logic::perception::ObjectDistance::operator= (ObjectDistance &&) [default]
ShortName()
static const std::string opendlv::logic::perception::ObjectDistance::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_distance
float opendlv::logic::perception::ObjectDistance::m_distance { 0.0f } [private]
m_objectId
uint32_t opendlv::logic::perception::ObjectDistance::m_objectId { 0 } [private]
TheLongName
constexpr const char* opendlv::logic::perception::ObjectDistance::TheLongName = `opendlv.logic.perception.ObjectDistance` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::perception::ObjectDistance::TheShortName = `ObjectDistance` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp