cluon::TerminateHandler Class Reference
#include <cluon-complete.hpp>
Classes
struct m_signalHandler
Public Member Functions
~TerminateHandler ()=default
Static Public Member Functions
static TerminateHandler & instance () noexcept
Public Attributes
std::atomic< bool > isTerminated {false}
Private Member Functions
TerminateHandler (const TerminateHandler &)=delete
TerminateHandler (TerminateHandler &&)=delete
TerminateHandler & operator= (const TerminateHandler &)=delete
TerminateHandler & operator= (TerminateHandler &&)=delete
TerminateHandler () noexcept
Constructor & Destructor Documentation
TerminateHandler() [1/3]
cluon::TerminateHandler::TerminateHandler (const TerminateHandler &) [private], [delete]
TerminateHandler() [2/3]
cluon::TerminateHandler::TerminateHandler (TerminateHandler &&) [private], [delete]
 TerminateHandler()
cluon::TerminateHandler::~TerminateHandler () [default]
TerminateHandler() [3/3]
cluon::TerminateHandler::TerminateHandler () [inline], [private], [noexcept]
                                                   {
    if (0 != std::atexit(cluon_handleExit)) {
        std::cerr << "[cluon::TerminateHandler] Failed to register cluon_exitHandler()." << std::endl; // LCOV_EXCL_LINE
    }
#ifdef WIN32
    if (SIG_ERR == ::signal(SIGINT, &cluon_handleSignal)) {
        std::cerr << "[cluon::TerminateHandler] Failed to register signal SIGINT." << std::endl;
    }
    if (SIG_ERR == ::signal(SIGTERM, &cluon_handleSignal)) {
        std::cerr << "[cluon::TerminateHandler] Failed to register signal SIGTERM." << std::endl;
    }
#else
    std::memset(&m_signalHandler, 0, sizeof(m_signalHandler));
    m_signalHandler.sa_handler = &cluon_handleSignal;
    if (::sigaction(SIGINT, &m_signalHandler, NULL) < 0) {
        std::cerr << "[cluon::TerminateHandler] Failed to register signal SIGINT." << std::endl; // LCOV_EXCL_LINE
    }
    if (::sigaction(SIGTERM, &m_signalHandler, NULL) < 0) {
        std::cerr << "[cluon::TerminateHandler] Failed to register signal SIGTERM." << std::endl; // LCOV_EXCL_LINE
    }
#endif
}
References cluon::cluon_handleExit(), and cluon::cluon_handleSignal().
Member Function Documentation
instance()
static TerminateHandler & cluon::TerminateHandler::instance () [inline], [static], [noexcept]
Define singleton behavior using static initializer (cf. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf, Sec. 6.7.4).
Returns
singleton for an instance of this class.
                                                 {
        static TerminateHandler instance;
        return instance;
    }
Referenced by cluon::cluon_handleExit(), cluon::cluon_handleSignal(), cluon::UDPReceiver::isRunning(), cluon::TCPConnection::isRunning(), cluon::TCPServer::isRunning(), and cluon::OD4Session::timeTrigger().
operator=() [1/2]
TerminateHandler & cluon::TerminateHandler::operator= (const TerminateHandler &) [private], [delete]
operator=() [2/2]
TerminateHandler & cluon::TerminateHandler::operator= (TerminateHandler &&) [private], [delete]
Member Data Documentation
isTerminated
std::atomic<bool> cluon::TerminateHandler::isTerminated {false}
Referenced by cluon::cluon_handleExit(), cluon::cluon_handleSignal(), cluon::UDPReceiver::isRunning(), cluon::TCPConnection::isRunning(), and cluon::TCPServer::isRunning().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp