peg::OneOrMore Class Reference
#include <cluon-complete.hpp>
Public Member Functions
OneOrMore (const std::shared_ptr< Ope > &ope)
size_t parse (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt) const override
void accept (Visitor &v) override
Public Attributes
std::shared_ptr< Ope > ope_
Constructor & Destructor Documentation
OneOrMore()
peg::OneOrMore::OneOrMore (const std::shared_ptr< Ope > & ope) [inline]
: ope_(ope) {}
Member Function Documentation
accept()
void peg::OneOrMore::accept (Visitor & v) [inline], [override], [virtual]
Implements peg::Ope.
{ v.visit(*this); }
References peg::Ope::Visitor::visit().
parse()
size_t peg::OneOrMore::parse (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt) const [inline], [override], [virtual]
Implements peg::Ope.
                                                                                                  {
        c.trace("OneOrMore", s, n, sv, dt);
        size_t len = 0;
        {
            c.nest_level++;
            c.push_capture_scope();
            auto se = make_scope_exit([&]() {
                c.nest_level--;
                c.pop_capture_scope();
            });
            const auto& rule = *ope_;
            len = rule.parse(s, n, sv, c, dt);
            if (success(len)) {
                c.shift_capture_values();
            } else {
                return static_cast<size_t>(-1);
            }
        }
        auto save_error_pos = c.error_pos;
        auto i = len;
        while (n - i > 0) {
            c.nest_level++;
            c.push_capture_scope();
            auto se = make_scope_exit([&]() {
                c.nest_level--;
                c.pop_capture_scope();
            });
            auto save_sv_size = sv.size();
            auto save_tok_size = sv.tokens.size();
            const auto& rule = *ope_;
            len = rule.parse(s + i, n - i, sv, c, dt);
            if (success(len)) {
                c.shift_capture_values();
            } else {
                if (sv.size() != save_sv_size) {
                    sv.erase(sv.begin() + static_cast<std::ptrdiff_t>(save_sv_size));
                    sv.tags.erase(sv.tags.begin() + static_cast<std::ptrdiff_t>(save_sv_size));
                }
                if (sv.tokens.size() != save_tok_size) {
                    sv.tokens.erase(sv.tokens.begin() + static_cast<std::ptrdiff_t>(save_tok_size));
                }
                c.error_pos = save_error_pos;
                break;
            }
            i += len;
        }
        return i;
    }
References peg::Context::error_pos, peg::make_scope_exit(), peg::Context::nest_level, peg::Context::pop_capture_scope(), peg::Context::push_capture_scope(), peg::Context::shift_capture_values(), peg::success(), peg::SemanticValues::tags, peg::SemanticValues::tokens, and peg::Context::trace().
Member Data Documentation
ope_
std::shared_ptr<Ope> peg::OneOrMore::ope_
Referenced by peg::AssignIDToDefinition::visit(), peg::TokenChecker::visit(), peg::DetectLeftRecursion::visit(), peg::ReferenceChecker::visit(), peg::LinkReferences::visit(), and peg::FindReference::visit().
The documentation for this class was generated from the following file:
src/cluon-complete.hpp