cluon::data::TimeStamp Class Reference
#include <cluon-complete.hpp>
Public Member Functions
TimeStamp ()=default
TimeStamp (const TimeStamp &)=default
TimeStamp & operator= (const TimeStamp &)=default
TimeStamp (TimeStamp &&)=default
TimeStamp & operator= (TimeStamp &&)=default
~TimeStamp ()=default
TimeStamp & seconds (const int32_t &v) noexcept
int32_t seconds () const noexcept
TimeStamp & microseconds (const int32_t &v) noexcept
int32_t microseconds () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
int32_t m_seconds { 0 }
int32_t m_microseconds { 0 }
Static Private Attributes
static constexpr const char * TheShortName = `TimeStamp`
static constexpr const char * TheLongName = `cluon.data.TimeStamp`
Constructor & Destructor Documentation
TimeStamp() [1/3]
cluon::data::TimeStamp::TimeStamp () [default]
TimeStamp() [2/3]
cluon::data::TimeStamp::TimeStamp (const TimeStamp &) [default]
TimeStamp() [3/3]
cluon::data::TimeStamp::TimeStamp (TimeStamp &&) [default]
 TimeStamp()
cluon::data::TimeStamp::~TimeStamp () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void cluon::data::TimeStamp::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("int32_t"s), std::move("seconds"s), m_seconds, preVisit, visit, postVisit);
            
            doTripletForwardVisit(2, std::move("int32_t"s), std::move("microseconds"s), m_microseconds, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void cluon::data::TimeStamp::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("int32_t"s), std::move("seconds"s), m_seconds, visitor);
                return;
            }
            
            if (2 == fieldId) {
                doVisit(2, std::move("int32_t"s), std::move("microseconds"s), m_microseconds, visitor);
                return;
            }
            
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void cluon::data::TimeStamp::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("int32_t"s), std::move("seconds"s), m_seconds, visitor);
            
            doVisit(2, std::move("int32_t"s), std::move("microseconds"s), m_microseconds, visitor);
            
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t cluon::data::TimeStamp::ID () [inline], [static]
                                   {
            return 12;
        }
LongName()
static const std::string cluon::data::TimeStamp::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
microseconds() [1/2]
int32_t cluon::data::TimeStamp::microseconds () const [inline], [noexcept]
                                                     {
            return m_microseconds;
        }
microseconds() [2/2]
TimeStamp & cluon::data::TimeStamp::microseconds (const int32_t & v) [inline], [noexcept]
                                                                  {
            m_microseconds = v;
            return *this;
        }
Referenced by cluon::time::convert(), cluon::time::fromMicroseconds(), and cluon::SharedMemory::getTimeStamp().
operator=() [1/2]
TimeStamp & cluon::data::TimeStamp::operator= (const TimeStamp &) [default]
operator=() [2/2]
TimeStamp & cluon::data::TimeStamp::operator= (TimeStamp &&) [default]
seconds() [1/2]
int32_t cluon::data::TimeStamp::seconds () const [inline], [noexcept]
                                                {
            return m_seconds;
        }
seconds() [2/2]
TimeStamp & cluon::data::TimeStamp::seconds (const int32_t & v) [inline], [noexcept]
                                                             {
            m_seconds = v;
            return *this;
        }
Referenced by cluon::time::convert(), cluon::time::fromMicroseconds(), cluon::SharedMemory::getTimeStamp(), and main().
ShortName()
static const std::string cluon::data::TimeStamp::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_microseconds
int32_t cluon::data::TimeStamp::m_microseconds { 0 } [private]
m_seconds
int32_t cluon::data::TimeStamp::m_seconds { 0 } [private]
TheLongName
constexpr const char* cluon::data::TimeStamp::TheLongName = `cluon.data.TimeStamp` [static], [constexpr], [private]
TheShortName
constexpr const char* cluon::data::TimeStamp::TheShortName = `TimeStamp` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/cluon-complete.hpp