opendlv::proxy::GroundSpeedReading Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSpeedReading ()=default
GroundSpeedReading (const GroundSpeedReading &)=default
GroundSpeedReading & operator= (const GroundSpeedReading &)=default
GroundSpeedReading (GroundSpeedReading &&)=default
GroundSpeedReading & operator= (GroundSpeedReading &&)=default
~GroundSpeedReading ()=default
GroundSpeedReading & groundSpeed (const float &v) noexcept
float groundSpeed () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_groundSpeed { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSpeedReading`
static constexpr const char * TheLongName = `opendlv.proxy.GroundSpeedReading`
Constructor & Destructor Documentation
GroundSpeedReading() [1/3]
opendlv::proxy::GroundSpeedReading::GroundSpeedReading () [default]
GroundSpeedReading() [2/3]
opendlv::proxy::GroundSpeedReading::GroundSpeedReading (const GroundSpeedReading &) [default]
GroundSpeedReading() [3/3]
opendlv::proxy::GroundSpeedReading::GroundSpeedReading (GroundSpeedReading &&) [default]
 GroundSpeedReading()
opendlv::proxy::GroundSpeedReading::~GroundSpeedReading () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::proxy::GroundSpeedReading::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::proxy::GroundSpeedReading::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::proxy::GroundSpeedReading::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("groundSpeed"s), m_groundSpeed, visitor);
            visitor.postVisit();
        }
References doVisit().
groundSpeed() [1/2]
float opendlv::proxy::GroundSpeedReading::groundSpeed () const [inline], [noexcept]
                                                  {
            return m_groundSpeed;
        }
groundSpeed() [2/2]
GroundSpeedReading & opendlv::proxy::GroundSpeedReading::groundSpeed (const float & v) [inline], [noexcept]
                                                                        {
            m_groundSpeed = v;
            return *this;
        }
ID()
static int32_t opendlv::proxy::GroundSpeedReading::ID () [inline], [static]
                                   {
            return 1046;
        }
LongName()
static const std::string opendlv::proxy::GroundSpeedReading::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSpeedReading & opendlv::proxy::GroundSpeedReading::operator= (const GroundSpeedReading &) [default]
operator=() [2/2]
GroundSpeedReading & opendlv::proxy::GroundSpeedReading::operator= (GroundSpeedReading &&) [default]
ShortName()
static const std::string opendlv::proxy::GroundSpeedReading::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
Member Data Documentation
m_groundSpeed
float opendlv::proxy::GroundSpeedReading::m_groundSpeed { 0.0f } [private]
TheLongName
constexpr const char* opendlv::proxy::GroundSpeedReading::TheLongName = `opendlv.proxy.GroundSpeedReading` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::proxy::GroundSpeedReading::TheShortName = `GroundSpeedReading` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp