opendlv::logic::cognition::GroundSteeringLimit Class Reference
#include <opendlv-standard-message-set.hpp>
Public Member Functions
GroundSteeringLimit ()=default
GroundSteeringLimit (const GroundSteeringLimit &)=default
GroundSteeringLimit & operator= (const GroundSteeringLimit &)=default
GroundSteeringLimit (GroundSteeringLimit &&)=default
GroundSteeringLimit & operator= (GroundSteeringLimit &&)=default
~GroundSteeringLimit ()=default
GroundSteeringLimit & steeringLimit (const float &v) noexcept
float steeringLimit () const noexcept
template<class Visitor >
void accept (uint32_t fieldId, Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
template<class PreVisitor , class Visitor , class PostVisitor >
void accept (PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Static Public Member Functions
static int32_t ID ()
static const std::string ShortName ()
static const std::string LongName ()
Private Attributes
float m_steeringLimit { 0.0f }
Static Private Attributes
static constexpr const char * TheShortName = `GroundSteeringLimit`
static constexpr const char * TheLongName = `opendlv.logic.cognition.GroundSteeringLimit`
Constructor & Destructor Documentation
GroundSteeringLimit() [1/3]
opendlv::logic::cognition::GroundSteeringLimit::GroundSteeringLimit () [default]
GroundSteeringLimit() [2/3]
opendlv::logic::cognition::GroundSteeringLimit::GroundSteeringLimit (const GroundSteeringLimit &) [default]
GroundSteeringLimit() [3/3]
opendlv::logic::cognition::GroundSteeringLimit::GroundSteeringLimit (GroundSteeringLimit &&) [default]
 GroundSteeringLimit()
opendlv::logic::cognition::GroundSteeringLimit::~GroundSteeringLimit () [default]
Member Function Documentation
accept() [1/3]
template<class PreVisitor , class Visitor , class PostVisitor >
void opendlv::logic::cognition::GroundSteeringLimit::accept (PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit) [inline]
                                                                                            {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            doTripletForwardVisit(1, std::move("float"s), std::move("steeringLimit"s), m_steeringLimit, preVisit, visit, postVisit);
            std::forward<PostVisitor>(postVisit)();
        }
References doTripletForwardVisit().
accept() [2/3]
template<class Visitor >
void opendlv::logic::cognition::GroundSteeringLimit::accept (uint32_t fieldId, Visitor & visitor) [inline]
                                                               {
            (void)fieldId;
            (void)visitor;
// visitor.preVisit(ID(), ShortName(), LongName());
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("steeringLimit"s), m_steeringLimit, visitor);
                return;
            }
// visitor.postVisit();
        }
References doVisit().
accept() [3/3]
template<class Visitor >
void opendlv::logic::cognition::GroundSteeringLimit::accept (Visitor & visitor) [inline]
                                             {
            visitor.preVisit(ID(), ShortName(), LongName());
            doVisit(1, std::move("float"s), std::move("steeringLimit"s), m_steeringLimit, visitor);
            visitor.postVisit();
        }
References doVisit().
ID()
static int32_t opendlv::logic::cognition::GroundSteeringLimit::ID () [inline], [static]
                                   {
            return 1191;
        }
LongName()
static const std::string opendlv::logic::cognition::GroundSteeringLimit::LongName () [inline], [static]
                                                 {
            return TheLongName;
        }
operator=() [1/2]
GroundSteeringLimit & opendlv::logic::cognition::GroundSteeringLimit::operator= (const GroundSteeringLimit &) [default]
operator=() [2/2]
GroundSteeringLimit & opendlv::logic::cognition::GroundSteeringLimit::operator= (GroundSteeringLimit &&) [default]
ShortName()
static const std::string opendlv::logic::cognition::GroundSteeringLimit::ShortName () [inline], [static]
                                                  {
            return TheShortName;
        }
steeringLimit() [1/2]
float opendlv::logic::cognition::GroundSteeringLimit::steeringLimit () const [inline], [noexcept]
                                                    {
            return m_steeringLimit;
        }
steeringLimit() [2/2]
GroundSteeringLimit & opendlv::logic::cognition::GroundSteeringLimit::steeringLimit (const float & v) [inline], [noexcept]
                                                                           {
            m_steeringLimit = v;
            return *this;
        }
Member Data Documentation
m_steeringLimit
float opendlv::logic::cognition::GroundSteeringLimit::m_steeringLimit { 0.0f } [private]
TheLongName
constexpr const char* opendlv::logic::cognition::GroundSteeringLimit::TheLongName = `opendlv.logic.cognition.GroundSteeringLimit` [static], [constexpr], [private]
TheShortName
constexpr const char* opendlv::logic::cognition::GroundSteeringLimit::TheShortName = `GroundSteeringLimit` [static], [constexpr], [private]
The documentation for this class was generated from the following file:
src/opendlv-standard-message-set.hpp