src/cluon-complete.hpp File Reference
#include <typeinfo>
#include <type_traits>
#include <stdexcept>
#include <algorithm>
#include <cctype>
#include <cassert>
#include <cstring>
#include <functional>
#include <initializer_list>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>
#include <sstream>
#include <cstdint>
#include <utility>
#include <chrono>
#include <atomic>
#include <csignal>
#include <condition_variable>
#include <deque>
#include <thread>
#include <netinet/in.h>
#include <cstddef>
#include <array>
#include <istream>
#include <regex>
#include <fstream>
#include <pthread.h>
#include <sys/ipc.h>
#include <cstdlib>
#include <arpa/inet.h>
#include <netdb.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
#include <cerrno>
#include <iterator>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <ifaddrs.h>
#include <iomanip>
#include <cmath>
#include <cstdio>
#include <sys/mman.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/stat.h>
#include <sys/time.h>
Classes
class linb::bad_any_cast
class linb::any
union linb::any::storage_union
struct linb::any::vtable_type
Base VTable specification.
struct linb::any::vtable_dynamic< T >
VTable for dynamically allocated storage.
struct linb::any::vtable_stack< T >
VTable for stack allocated storage.
struct linb::any::requires_allocation< T >
Whether the type T must be dynamically allocated or can be stored on the stack.
class peg::any
struct peg::any::placeholder
struct peg::any::holder< T >
struct peg::scope_exit< EF >
struct peg::SemanticValues
class peg::Action
struct peg::Action::TypeAdaptor_sv< R >
struct peg::Action::TypeAdaptor_csv< R >
struct peg::Action::TypeAdaptor_sv_dt< R >
struct peg::Action::TypeAdaptor_csv_dt< R >
struct peg::parse_error
class peg::Context
class peg::Ope
class peg::Sequence
class peg::PrioritizedChoice
class peg::ZeroOrMore
class peg::OneOrMore
class peg::Option
class peg::AndPredicate
class peg::NotPredicate
class peg::LiteralString
class peg::CharacterClass
class peg::Character
class peg::AnyCharacter
class peg::CaptureScope
class peg::Capture
class peg::TokenBoundary
class peg::Ignore
class peg::User
class peg::WeakHolder
class peg::Holder
class peg::Reference
class peg::Whitespace
class peg::BackReference
struct peg::Ope::Visitor
struct peg::AssignIDToDefinition
struct peg::IsLiteralToken
struct peg::TokenChecker
struct peg::DetectLeftRecursion
struct peg::ReferenceChecker
struct peg::LinkReferences
struct peg::FindReference
struct peg::IsPrioritizedChoice
class peg::Definition
struct peg::Definition::Result
class peg::ParserGenerator
struct peg::ParserGenerator::Data
struct peg::AstBase< Annotation >
struct peg::AstOptimizer
struct peg::EmptyType
class peg::parser
class argh::parser
struct visitorSelector< b >
struct visitorSelector< true >
struct isVisitable< T >
struct tripletForwardVisitorSelector< b >
struct tripletForwardVisitorSelector< true >
struct isTripletForwardVisitable< T >
class cluon::data::TimeStamp
struct isVisitable< cluon::data::TimeStamp >
struct isTripletForwardVisitable< cluon::data::TimeStamp >
class cluon::data::Envelope
struct isVisitable< cluon::data::Envelope >
struct isTripletForwardVisitable< cluon::data::Envelope >
class cluon::data::PlayerCommand
struct isVisitable< cluon::data::PlayerCommand >
struct isTripletForwardVisitable< cluon::data::PlayerCommand >
class cluon::data::PlayerStatus
struct isVisitable< cluon::data::PlayerStatus >
struct isTripletForwardVisitable< cluon::data::PlayerStatus >
class cluon::data::RecorderCommand
struct isVisitable< cluon::data::RecorderCommand >
struct isTripletForwardVisitable< cluon::data::RecorderCommand >
class cluon::UseUInt32ValueAsHashKey
class cluon::MetaMessage
class cluon::MetaMessage::MetaField
class cluon::MessageParser
class cluon::TerminateHandler
struct cluon::TerminateHandler::m_signalHandler
class cluon::NotifyingPipeline< T >
class cluon::UDPSender
struct cluon::UDPSender::m_sendToAddress
class cluon::UDPReceiver
struct cluon::UDPReceiver::m_receiveFromAddress
struct cluon::UDPReceiver::m_mreq
class cluon::UDPReceiver::PipelineEntry
class cluon::TCPConnection
struct cluon::TCPConnection::m_address
class cluon::TCPConnection::PipelineEntry
class cluon::TCPServer
class cluon::ToProtoVisitor
class cluon::FromProtoVisitor
union cluon::FromProtoVisitor::DoubleValue
union cluon::FromProtoVisitor::FloatValue
class cluon::FromLCMVisitor
class cluon::FromMsgPackVisitor
class cluon::FromMsgPackVisitor::MsgPackKeyValue
class cluon::FromJSONVisitor
class cluon::FromJSONVisitor::JSONKeyValue
class cluon::ToJSONVisitor
class cluon::ToCSVVisitor
class cluon::ToLCMVisitor
class cluon::ToODVDVisitor
class cluon::ToMsgPackVisitor
class cluon::EnvelopeConverter
class cluon::GenericMessage
class cluon::GenericMessage::GenericMessageVisitor
struct isVisitable< cluon::GenericMessage >
struct isTripletForwardVisitable< cluon::GenericMessage >
class cluon::LCMToGenericMessage
class cluon::OD4Session
class cluon::IndexEntry
class cluon::Player
class cluon::SharedMemory
struct cluon::SharedMemory::SharedMemoryHeader
union semun
Namespaces
namespace linb
namespace linb::detail
namespace std
STL namespace.
namespace peg
namespace peg::udl
namespace argh
namespace cluon
namespace cluon::data
namespace stringtoolbox
namespace cluon::time
Macros
#define CPPPEGLIB_PEGLIB_H
#define ARGH
#define VISITABLE_TYPE_TRAIT
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define CLUON_DATA_TIMESTAMP_HPP
#define LIB_API
#define CLUON_DATA_ENVELOPE_HPP
#define LIB_API
#define CLUON_DATA_PLAYERCOMMAND_HPP
#define LIB_API
#define CLUON_DATA_PLAYERSTATUS_HPP
#define LIB_API
#define CLUON_DATA_RECORDERCOMMAND_HPP
#define LIB_API
#define STRINGTOOLBOX_HPP
#define CLUON_TIME_HPP
#define CLUON_PORTABLEENDIAN_HPP
#define CLUON_CLUON_HPP
#define LIBCLUON_API
#define CLUON_METAMESSAGE_HPP
#define CLUON_MESSAGEPARSER_HPP
#define CLUON_TERMINATEHANDLER_HPP
#define CLUON_NOTIFYINGPIPELINE_HPP
#define CLUON_IPV4TOOLS_HPP
#define CLUON_UDPPACKETSIZECONSTRAINTS_H
#define CLUON_UDPSENDER_HPP
#define CLUON_UDPRECEIVER_HPP
#define CLUON_TCPCONNECTION_HPP
#define CLUON_TCPSERVER_HPP
#define CLUON_PROTOCONSTANTS_HPP
#define CLUON_TOPROTOVISITOR_HPP
#define CLUON_FROMPROTOVISITOR_HPP
#define CLUON_FROMLCMVISITOR_HPP
#define CLUON_MSGPACKCONSTANTS_HPP
#define CLUON_FROMMSGPACKVISITOR_HPP
#define CLUON_JSONCONSTANTS_HPP
#define CLUON_FROMJSONVISITOR_HPP
#define CLUON_TOJSONVISITOR_HPP
#define CLUON_TOCSVVISITOR_HPP
#define CLUON_TOLCMVISITOR_HPP
#define CLUON_TOODVDVISITOR_HPP
#define CLUON_TOMSGPACKVISITOR_HPP
#define CLUON_ENVELOPE_HPP
#define CLUON_ENVELOPECONVERTER_HPP
#define CLUON_GENERICMESSAGE_HPP
#define CLUON_LCMTOGENERICMESSAGE_HPP
#define CLUON_OD4SESSION_HPP
#define CLUON_PLAYER_HPP
#define CLUON_SHAREDMEMORY_HPP
#define BEGIN_HEADER_ONLY_IMPLEMENTATION
Typedefs
typedef std::function< void(const char *name, const char *s, size_t n, const SemanticValues &sv, const Context &c, const any &dt)> peg::Tracer
typedef std::function< size_t(const char *s, size_t n, SemanticValues &sv, any &dt)> peg::Parser
typedef std::unordered_map< std::string, Definition > peg::Grammar
typedef std::unordered_map< std::string, std::shared_ptr< Ope > > peg::Rules
typedef std::function< void(size_t, size_t, const std::string &)> peg::Log
typedef AstBase< EmptyType > peg::Ast
using argh::string_stream = std::istringstream
Enumerations
enum class cluon::UDPPacketSizeConstraints : uint16_t { cluon::SIZE_IPv4_HEADER = 20
, cluon::SIZE_UDP_HEADER = 8
, cluon::MAX_SIZE_UDP_PACKET = 0xFFFF
 }
enum class cluon::ProtoConstants : uint8_t { cluon::VARINT = 0
, cluon::EIGHT_BYTES = 1
, cluon::LENGTH_DELIMITED = 2
, cluon::FOUR_BYTES = 5
 }
enum class cluon::MsgPackConstants : uint16_t {
cluon::IS_FALSE = 0xC2
, cluon::IS_TRUE = 0xC3
, cluon::FLOAT = 0xCA
, cluon::DOUBLE = 0xCB
,
cluon::UINT8 = 0xCC
, cluon::UINT16 = 0xCD
, cluon::UINT32 = 0xCE
, cluon::UINT64 = 0xCF
,
cluon::NEGFIXINT = 0xE0
, cluon::INT8 = 0xD0
, cluon::INT16 = 0xD1
, cluon::INT32 = 0xD2
,
cluon::INT64 = 0xD3
, cluon::FIXSTR = 0xA0
, cluon::FIXSTR_END = 0xBF
, cluon::STR8 = 0xD9
,
cluon::STR16 = 0xDA
, cluon::STR32 = 0xDB
, cluon::FIXMAP = 0x80
, cluon::FIXMAP_END = 0x8F
,
cluon::MAP16 = 0xDE
, cluon::MAP32 = 0xDF
, cluon::UNKNOWN_FORMAT = 0xFF00
, cluon::BOOL_FORMAT = 0xFF01
,
cluon::UINT_FORMAT = 0xFF02
, cluon::INT_FORMAT = 0xFF03
, cluon::FLOAT_FORMAT = 0xFF04
, cluon::STR_FORMAT = 0xFF05
,
cluon::MAP_FORMAT = 0xFF06
 }
enum class cluon::JSONConstants : uint16_t {
cluon::IS_FALSE = 0
, cluon::IS_TRUE = 1
, cluon::NUMBER = 2
, cluon::STRING = 3
,
cluon::OBJECT = 4
, cluon::UNDEFINED = 99
 }
Functions
template<typename ValueType >
ValueType linb::detail::any_cast_move_if_true (typename std::remove_reference< ValueType >::type *p, std::true_type)
template<typename ValueType >
ValueType linb::detail::any_cast_move_if_true (typename std::remove_reference< ValueType >::type *p, std::false_type)
template<typename ValueType >
ValueType linb::any_cast (const any &operand)
Performs *any_cast<add_const_t<remove_reference_t<ValueType>>>(&operand), or throws bad_any_cast on failure.
template<typename ValueType >
ValueType linb::any_cast (any &operand)
Performs *any_cast<remove_reference_t<ValueType>>(&operand), or throws bad_any_cast on failure.
template<typename ValueType >
ValueType linb::any_cast (any &&operand)
template<typename ValueType >
const ValueType * linb::any_cast (const any *operand) noexcept
template<typename ValueType >
ValueType * linb::any_cast (any *operand) noexcept
void std::swap (linb::any &lhs, linb::any &rhs) noexcept
template<typename EF >
auto peg::make_scope_exit (EF &&exit_function) -> scope_exit< EF >
size_t peg::codepoint_length (const char *s8, size_t l)
size_t peg::encode_codepoint (char32_t cp, char *buff)
std::string peg::encode_codepoint (char32_t cp)
bool peg::decode_codepoint (const char *s8, size_t l, size_t &bytes, char32_t &cp)
size_t peg::decode_codepoint (const char *s8, size_t l, char32_t &out)
char32_t peg::decode_codepoint (const char *s8, size_t l)
std::u32string peg::decode (const char *s8, size_t l)
bool peg::is_hex (char c, int &v)
bool peg::is_digit (char c, int &v)
std::pair< int, size_t > peg::parse_hex_number (const char *s, size_t n, size_t i)
std::pair< int, size_t > peg::parse_octal_number (const char *s, size_t n, size_t i)
std::string peg::resolve_escape_sequence (const char *s, size_t n)
std::pair< size_t, size_t > peg::line_info (const char *start, const char *cur)
constexpr unsigned int peg::str2tag (const char *str, int h=0)
constexpr unsigned int peg::udl::operator``_ (const char *s, size_t)
template<typename R , typename F , typename std::enable_if< std::is_void< R >::value, std::nullptr_t >::type = nullptr, typename... Args>
any peg::call (F fn, Args &&... args)
bool peg::success (size_t len)
bool peg::fail (size_t len)
template<typename... Args>
std::shared_ptr< Ope > peg::seq (Args &&...args)
template<typename... Args>
std::shared_ptr< Ope > peg::cho (Args &&...args)
std::shared_ptr< Ope > peg::zom (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::oom (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::opt (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::apd (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::npd (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::lit (const std::string &s)
std::shared_ptr< Ope > peg::liti (const std::string &s)
std::shared_ptr< Ope > peg::cls (const std::string &s)
std::shared_ptr< Ope > peg::cls (const std::vector< std::pair< char32_t, char32_t > > &ranges)
std::shared_ptr< Ope > peg::chr (char dt)
std::shared_ptr< Ope > peg::dot ()
std::shared_ptr< Ope > peg::csc (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::cap (const std::shared_ptr< Ope > &ope, Capture::MatchAction ma)
std::shared_ptr< Ope > peg::tok (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::ign (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::usr (std::function< size_t(const char *s, size_t n, SemanticValues &sv, any &dt)> fn)
std::shared_ptr< Ope > peg::ref (const Grammar &grammar, const std::string &name, const char *s, bool is_macro, const std::vector< std::shared_ptr< Ope > > &args)
std::shared_ptr< Ope > peg::wsp (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > peg::bkr (const std::string &name)
size_t peg::parse_literal (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt, const std::string &lit, bool &init_is_word, bool &is_word, bool ignore_case)
template<typename T >
void peg::ast_to_s_core (const std::shared_ptr< T > &ptr, std::string &s, int level, std::function< std::string(const T &ast, int level)> fn)
template<typename T >
std::string peg::ast_to_s (const std::shared_ptr< T > &ptr, std::function< std::string(const T &ast, int level)> fn=nullptr)
template<typename T , class Visitor >
void doVisit (uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor)
template<typename T , class PreVisitor , class Visitor , class PostVisitor >
void doTripletForwardVisit (uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
std::string & stringtoolbox::rtrim (std::string &str) noexcept
std::string & stringtoolbox::ltrim (std::string &str) noexcept
std::string & stringtoolbox::trim (std::string &str) noexcept
std::string stringtoolbox::replaceAll (const std::string &str, const char &FROM, const char &TO) noexcept
std::vector< std::string > stringtoolbox::split (const std::string &str, const char &delimiter) noexcept
cluon::data::TimeStamp cluon::time::fromMicroseconds (int64_t tp) noexcept
int64_t cluon::time::toMicroseconds (const cluon::data::TimeStamp &tp) noexcept
int64_t cluon::time::deltaInMicroseconds (const cluon::data::TimeStamp &AFTER, const cluon::data::TimeStamp &BEFORE) noexcept
cluon::data::TimeStamp cluon::time::convert (const std::chrono::system_clock::time_point &tp) noexcept
cluon::data::TimeStamp cluon::time::now () noexcept
std::map< std::string, std::string > cluon::getCommandlineArguments (int32_t argc, char **argv) noexcept
std::string cluon::getIPv4FromHostname (const std::string &hostname) noexcept
std::string cluon::serializeEnvelope (cluon::data::Envelope &&envelope) noexcept
std::pair< bool, cluon::data::Envelope > cluon::extractEnvelope (std::istream &in) noexcept
template<typename T >
T cluon::extractMessage (cluon::data::Envelope &&envelope) noexcept
else cluon::if (`CHARACTER`==f->name)
if (0< STRING_TO_DATATYPE_MAP.count(_fieldDataType))
mf fieldDataTypeName (::stringtoolbox::trim(_fieldDataType))
mf fieldName (::stringtoolbox::trim(_fieldName))
mf fieldIdentifier ((!_fieldIdentifier.empty() ? static_cast< uint32_t >(std::stoi(::stringtoolbox::trim(_fieldIdentifier))) :fieldIdentifierCounter))
mf defaultInitializationValue (_fieldDefaultInitializerValue)
mm add (std::move(mf))
if (`MESSAGES_SPECIFICATION`==ast.name)
p enable_ast ()
catch (std::regex_error &)
catch (std::bad_cast &)
if (p.parse(inputWithoutComments.c_str(), ast))
void cluon::cluon_handleExit ()
void cluon::cluon_handleSignal (int32_t)
Variables
static const char * peg::WHITESPACE_DEFINITION_NAME = `%whitespace`
static const char * peg::WORD_DEFINITION_NAME = `%word`
cluon::else
std::map< std::string, MetaMessage::MetaField::MetaFieldDataTypes > STRING_TO_DATATYPE_MAP
MetaMessage::MetaField mf
else
return mm
peg::parser p (grammarMessageSpecificationLanguage)
p log
std::pair< std::vector< MetaMessage >, MessageParserErrorCodes > retVal {}
std::string inputWithoutComments {input}
try
std::shared_ptr< peg::Ast > ast {}
Macro Definition Documentation
ARGH
#define ARGH
BEGIN_HEADER_ONLY_IMPLEMENTATION
#define BEGIN_HEADER_ONLY_IMPLEMENTATION
CLUON_CLUON_HPP
#define CLUON_CLUON_HPP
CLUON_DATA_ENVELOPE_HPP
#define CLUON_DATA_ENVELOPE_HPP
CLUON_DATA_PLAYERCOMMAND_HPP
#define CLUON_DATA_PLAYERCOMMAND_HPP
CLUON_DATA_PLAYERSTATUS_HPP
#define CLUON_DATA_PLAYERSTATUS_HPP
CLUON_DATA_RECORDERCOMMAND_HPP
#define CLUON_DATA_RECORDERCOMMAND_HPP
CLUON_DATA_TIMESTAMP_HPP
#define CLUON_DATA_TIMESTAMP_HPP
CLUON_ENVELOPE_HPP
#define CLUON_ENVELOPE_HPP
CLUON_ENVELOPECONVERTER_HPP
#define CLUON_ENVELOPECONVERTER_HPP
CLUON_FROMJSONVISITOR_HPP
#define CLUON_FROMJSONVISITOR_HPP
CLUON_FROMLCMVISITOR_HPP
#define CLUON_FROMLCMVISITOR_HPP
CLUON_FROMMSGPACKVISITOR_HPP
#define CLUON_FROMMSGPACKVISITOR_HPP
CLUON_FROMPROTOVISITOR_HPP
#define CLUON_FROMPROTOVISITOR_HPP
CLUON_GENERICMESSAGE_HPP
#define CLUON_GENERICMESSAGE_HPP
CLUON_IPV4TOOLS_HPP
#define CLUON_IPV4TOOLS_HPP
CLUON_JSONCONSTANTS_HPP
#define CLUON_JSONCONSTANTS_HPP
CLUON_LCMTOGENERICMESSAGE_HPP
#define CLUON_LCMTOGENERICMESSAGE_HPP
CLUON_MESSAGEPARSER_HPP
#define CLUON_MESSAGEPARSER_HPP
CLUON_METAMESSAGE_HPP
#define CLUON_METAMESSAGE_HPP
CLUON_MSGPACKCONSTANTS_HPP
#define CLUON_MSGPACKCONSTANTS_HPP
CLUON_NOTIFYINGPIPELINE_HPP
#define CLUON_NOTIFYINGPIPELINE_HPP
CLUON_OD4SESSION_HPP
#define CLUON_OD4SESSION_HPP
CLUON_PLAYER_HPP
#define CLUON_PLAYER_HPP
CLUON_PORTABLEENDIAN_HPP
#define CLUON_PORTABLEENDIAN_HPP
CLUON_PROTOCONSTANTS_HPP
#define CLUON_PROTOCONSTANTS_HPP
CLUON_SHAREDMEMORY_HPP
#define CLUON_SHAREDMEMORY_HPP
CLUON_TCPCONNECTION_HPP
#define CLUON_TCPCONNECTION_HPP
CLUON_TCPSERVER_HPP
#define CLUON_TCPSERVER_HPP
CLUON_TERMINATEHANDLER_HPP
#define CLUON_TERMINATEHANDLER_HPP
CLUON_TIME_HPP
#define CLUON_TIME_HPP
CLUON_TOCSVVISITOR_HPP
#define CLUON_TOCSVVISITOR_HPP
CLUON_TOJSONVISITOR_HPP
#define CLUON_TOJSONVISITOR_HPP
CLUON_TOLCMVISITOR_HPP
#define CLUON_TOLCMVISITOR_HPP
CLUON_TOMSGPACKVISITOR_HPP
#define CLUON_TOMSGPACKVISITOR_HPP
CLUON_TOODVDVISITOR_HPP
#define CLUON_TOODVDVISITOR_HPP
CLUON_TOPROTOVISITOR_HPP
#define CLUON_TOPROTOVISITOR_HPP
CLUON_UDPPACKETSIZECONSTRAINTS_H
#define CLUON_UDPPACKETSIZECONSTRAINTS_H
CLUON_UDPRECEIVER_HPP
#define CLUON_UDPRECEIVER_HPP
CLUON_UDPSENDER_HPP
#define CLUON_UDPSENDER_HPP
CPPPEGLIB_PEGLIB_H
#define CPPPEGLIB_PEGLIB_H
LIB_API [1/5]
#define LIB_API
LIB_API [2/5]
#define LIB_API
LIB_API [3/5]
#define LIB_API
LIB_API [4/5]
#define LIB_API
LIB_API [5/5]
#define LIB_API
LIBCLUON_API
#define LIBCLUON_API
STRINGTOOLBOX_HPP
#define STRINGTOOLBOX_HPP
TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
VISITABLE_TYPE_TRAIT
#define VISITABLE_TYPE_TRAIT
Function Documentation
add()
mm add (std::move(mf))
catch() [1/2]
catch (std::bad_cast &)
                            { // LCOV_EXCL_LINE
    }
catch() [2/2]
catch (std::regex_error &)
                               { // LCOV_EXCL_LINE
    } catch (std::bad_cast &) { // LCOV_EXCL_LINE
defaultInitializationValue()
mf defaultInitializationValue (_fieldDefaultInitializerValue)
doTripletForwardVisit()
template<typename T , class PreVisitor , class Visitor , class PostVisitor >
void doTripletForwardVisit (uint32_t fieldIdentifier, std::string && typeName, std::string && name, T & value, PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit)
                                                                                                                                                                        {
    tripletForwardVisitorSelector<isTripletForwardVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, std::move(preVisit), std::move(visit), std::move(postVisit)); // NOLINT
}
References fieldIdentifier().
Referenced by cluon::GenericMessage::accept(), cluon::data::TimeStamp::accept(), cluon::data::Envelope::accept(), cluon::data::PlayerCommand::accept(), cluon::data::PlayerStatus::accept(), and cluon::data::RecorderCommand::accept().
doVisit()
template<typename T , class Visitor >
void doVisit (uint32_t fieldIdentifier, std::string && typeName, std::string && name, T & value, Visitor & visitor)
                                                                                                           {
    visitorSelector<isVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, visitor);
}
References fieldIdentifier().
Referenced by cluon::data::TimeStamp::accept(), cluon::data::Envelope::accept(), cluon::data::PlayerCommand::accept(), cluon::data::PlayerStatus::accept(), cluon::data::RecorderCommand::accept(), and cluon::GenericMessage::accept().
enable_ast()
p enable_ast ()
fieldDataTypeName()
mf fieldDataTypeName (::stringtoolbox::trim(_fieldDataType))
fieldIdentifier()
mf fieldIdentifier ((!_fieldIdentifier.empty() ? static_cast< uint32_t >(std::stoi(::stringtoolbox::trim(_fieldIdentifier))) :fieldIdentifierCounter))
Referenced by doTripletForwardVisit(), doVisit(), cluon::ToProtoVisitor::encodeKey(), tripletForwardVisitorSelector< b >::impl(), tripletForwardVisitorSelector< true >::impl(), visitorSelector< b >::impl(), visitorSelector< true >::impl(), cluon::MessageParser::parse(), and cluon::ToProtoVisitor::toKeyValue().
fieldName()
mf fieldName (::stringtoolbox::trim(_fieldName))
Referenced by cluon::MessageParser::parse().
if() [1/3]
if (`MESSAGES_SPECIFICATION` = = ast.name)
                                                        {
                  // Extract the value of entry "PACKAGE_IDENTIFIER".
                  auto nodeIdentifier = std::find_if(std::begin(ast.nodes), std::end(ast.nodes), [](auto a) { return (a->name == "PACKAGE_IDENTIFIER"); });
                  std::string packageName;
                  if (nodeIdentifier != std::end(ast.nodes)) {
                      packageName = (*nodeIdentifier)->token;
                  }
                  // Extract the value of entry "MESSAGE_DECLARATION".
                  for (const auto &node : ast.nodes) {
                      if (node->name == "MESSAGE_DECLARATION") {
                          listOfMetaMessages.emplace_back(createMetaMessage(*node, packageName));
                      }
                  }
              } else {
References ast.
if() [2/3]
if ()
                                                                                {
                              mf.fieldDataType(STRING_TO_DATATYPE_MAP[_fieldDataType]);
                          } else {
References mf, and STRING_TO_DATATYPE_MAP.
if() [3/3]
if (p. parseinputWithoutComments.c_str(), ast)
                                                        {
            ast = peg::AstOptimizer(true).optimize(ast);
            {
                std::string tmpPrefix;
                std::vector<std::string> tmpMessageNames{};
                std::vector<std::string> tmpFieldNames{};
                std::vector<int32_t> tmpNumericalMessageIdentifiers{};
                std::vector<int32_t> tmpNumericalFieldIdentifiers{};
                if (check4UniqueFieldNames(*ast, tmpPrefix, tmpMessageNames, tmpFieldNames, tmpNumericalMessageIdentifiers, tmpNumericalFieldIdentifiers)) {
                    transform2MetaMessages(*ast, listOfMetaMessages);
                    retVal = {listOfMetaMessages, MessageParserErrorCodes::NO_MESSAGEPARSER_ERROR};
                } else {
                    retVal = {listOfMetaMessages, MessageParserErrorCodes::DUPLICATE_IDENTIFIERS};
                }
            }
        } else {
References ast, peg::AstOptimizer::optimize(), and retVal.
Variable Documentation
ast
std::shared_ptr<peg::Ast> ast {}
Referenced by peg::ast_to_s_core(), peg::parser::enable_ast(), if(), peg::AstOptimizer::optimize(), and cluon::MessageParser::parse().
else
else
Initial value:
{
                              mf.fieldDataType(MetaMessage::MetaField::MESSAGE_T)
inputWithoutComments
inputWithoutComments {input}
log
p log
Initial value:
= [](size_t row, size_t col, const std::string &msg) {
        std::cerr << "[cluon::MessageParser] Parsing error:" << row << ":" << col << ": " << msg << '\n';
    }
Referenced by peg::parser::load_grammar(), peg::parser::output_log(), peg::ParserGenerator::parse(), and peg::ParserGenerator::perform_core().
mf
MetaMessage::MetaField mf
Referenced by cluon::MetaMessage::add(), if(), and cluon::GenericMessage::GenericMessageVisitor::visit().
mm
return mm
Referenced by cluon::GenericMessage::createFrom(), cluon::MessageParser::parse(), cluon::EnvelopeConverter::setMessageSpecification(), and cluon::LCMToGenericMessage::setMessageSpecification().
p
peg::parser p(grammarMessageSpecificationLanguage) (grammarMessageSpecificationLanguage)
Referenced by peg::any::get(), peg::line_info(), and peg::AssignIDToDefinition::visit().
retVal
return retVal {}
Referenced by cluon::OD4Session::callback(), cluon::UDPReceiver::closeSocket(), cluon::ToCSVVisitor::csv(), cluon::OD4Session::dataTrigger(), cluon::ToJSONVisitor::encodeBase64(), cluon::extractEnvelope(), cluon::Player::fillEnvelopeCache(), cluon::getCommandlineArguments(), cluon::EnvelopeConverter::getJSONFromEnvelope(), cluon::EnvelopeConverter::getJSONFromProtoEncodedEnvelope(), cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), cluon::SharedMemory::getTimeStamp(), if(), cluon::Player::initializeIndex(), cluon::SharedMemory::initPOSIX(), cluon::ToJSONVisitor::json(), cluon::SharedMemory::lockPOSIX(), cluon::ToODVDVisitor::messageSpecification(), cluon::MessageParser::parse(), cluon::FromMsgPackVisitor::readInt(), cluon::FromJSONVisitor::readKeyValues(), cluon::FromMsgPackVisitor::readString(), cluon::FromMsgPackVisitor::readUint(), stringtoolbox::replaceAll(), cluon::EnvelopeConverter::setMessageSpecification(), cluon::LCMToGenericMessage::setMessageSpecification(), cluon::SharedMemory::setTimeStamp(), stringtoolbox::split(), cluon::TCPConnection::TCPConnection(), cluon::TCPServer::TCPServer(), and cluon::UDPReceiver::UDPReceiver().
STRING_TO_DATATYPE_MAP
std::map<std::string, MetaMessage::MetaField::MetaFieldDataTypes> STRING_TO_DATATYPE_MAP
Initial value:
= {
                              {"bool", MetaMessage::MetaField::BOOL_T},
                              {"char", MetaMessage::MetaField::CHAR_T},
                              {"uint8", MetaMessage::MetaField::UINT8_T},
                              {"int8", MetaMessage::MetaField::INT8_T},
                              {"uint16", MetaMessage::MetaField::UINT16_T},
                              {"int16", MetaMessage::MetaField::INT16_T},
                              {"uint32", MetaMessage::MetaField::UINT32_T},
                              {"int32", MetaMessage::MetaField::INT32_T},
                              {"uint64", MetaMessage::MetaField::UINT64_T},
                              {"int64", MetaMessage::MetaField::INT64_T},
                              {"float", MetaMessage::MetaField::FLOAT_T},
                              {"double", MetaMessage::MetaField::DOUBLE_T},
                              {"string", MetaMessage::MetaField::STRING_T},
                              {"bytes", MetaMessage::MetaField::BYTES_T},
                          }
Referenced by if().
try
try
Initial value:
{
        const std::string MATCH_COMMENTS_REGEX = R"(/\*([\s\S]*?)\*/|//.*)"