stringtoolbox Namespace Reference
Functions
std::string & rtrim (std::string &str) noexcept
std::string & ltrim (std::string &str) noexcept
std::string & trim (std::string &str) noexcept
std::string replaceAll (const std::string &str, const char &FROM, const char &TO) noexcept
std::vector< std::string > split (const std::string &str, const char &delimiter) noexcept
Function Documentation
ltrim()
std::string & stringtoolbox::ltrim (std::string & str) [inline], [noexcept]
Returns
std::tring without leading whitespace characters.
                                                 {
  str.erase(0, str.find_first_not_of(" \t"));
  return str;
}
Referenced by trim().
replaceAll()
std::string stringtoolbox::replaceAll (const std::string & str, const char & FROM, const char & TO) [inline], [noexcept]
Returns
std:string where all occurrences of characters FROM are replaced with TO.
                                                       {
  std::string retVal{str};
  std::replace(retVal.begin(), retVal.end(), FROM, TO);
  return retVal;
}
References retVal.
rtrim()
std::string & stringtoolbox::rtrim (std::string & str) [inline], [noexcept]
Returns
std::string without trailing whitespace characters.
                                                 {
  str.erase(str.find_last_not_of(" \t") + 1);
  return str;
}
Referenced by trim().
split()
std::vector< std::string > stringtoolbox::split (const std::string & str, const char & delimiter) [inline], [noexcept]
Returns
std::vector<std:string> where the given string is split along delimiter.
                                                                      {
  std::vector<std::string> retVal{};
  std::string::size_type prev{0};
  for (std::string::size_type i{str.find_first_of(delimiter, prev)};
       i != std::string::npos;
       prev = i + 1, i = str.find_first_of(delimiter, prev)) {
    if (i != prev) {
      retVal.emplace_back(str.substr(prev, i - prev));
    }
    else {
      retVal.emplace_back("");
    }
  }
  if ((prev > 0) && (prev < str.size())) {
    retVal.emplace_back(str.substr(prev, str.size() - prev));
  }
  else if (prev > 0) {
    retVal.emplace_back("");
  }
  return retVal;
}
References retVal.
Referenced by cluon::FromJSONVisitor::readKeyValues().
trim()
std::string & stringtoolbox::trim (std::string & str) [inline], [noexcept]
Returns
std:string without leading and trailing whitespace characters.
                                                {
  return ltrim(rtrim(str));
}
References ltrim(), and rtrim().
Referenced by cluon::MessageParser::parse(), and cluon::FromJSONVisitor::readKeyValues().