cluon Namespace Reference
Namespaces
namespace data
namespace time
Classes
class EnvelopeConverter
class FromJSONVisitor
class FromLCMVisitor
class FromMsgPackVisitor
class FromProtoVisitor
class GenericMessage
class IndexEntry
class LCMToGenericMessage
class MessageParser
class MetaMessage
class NotifyingPipeline
class OD4Session
class Player
class SharedMemory
class TCPConnection
class TCPServer
class TerminateHandler
class ToCSVVisitor
class ToJSONVisitor
class ToLCMVisitor
class ToMsgPackVisitor
class ToODVDVisitor
class ToProtoVisitor
class UDPReceiver
class UDPSender
class UseUInt32ValueAsHashKey
Enumerations
enum class UDPPacketSizeConstraints : uint16_t { SIZE_IPv4_HEADER = 20
, SIZE_UDP_HEADER = 8
, MAX_SIZE_UDP_PACKET = 0xFFFF
 }
enum class ProtoConstants : uint8_t { VARINT = 0
, EIGHT_BYTES = 1
, LENGTH_DELIMITED = 2
, FOUR_BYTES = 5
 }
enum class MsgPackConstants : uint16_t {
IS_FALSE = 0xC2
, IS_TRUE = 0xC3
, FLOAT = 0xCA
, DOUBLE = 0xCB
,
UINT8 = 0xCC
, UINT16 = 0xCD
, UINT32 = 0xCE
, UINT64 = 0xCF
,
NEGFIXINT = 0xE0
, INT8 = 0xD0
, INT16 = 0xD1
, INT32 = 0xD2
,
INT64 = 0xD3
, FIXSTR = 0xA0
, FIXSTR_END = 0xBF
, STR8 = 0xD9
,
STR16 = 0xDA
, STR32 = 0xDB
, FIXMAP = 0x80
, FIXMAP_END = 0x8F
,
MAP16 = 0xDE
, MAP32 = 0xDF
, UNKNOWN_FORMAT = 0xFF00
, BOOL_FORMAT = 0xFF01
,
UINT_FORMAT = 0xFF02
, INT_FORMAT = 0xFF03
, FLOAT_FORMAT = 0xFF04
, STR_FORMAT = 0xFF05
,
MAP_FORMAT = 0xFF06
 }
enum class JSONConstants : uint16_t {
IS_FALSE = 0
, IS_TRUE = 1
, NUMBER = 2
, STRING = 3
,
OBJECT = 4
, UNDEFINED = 99
 }
Functions
std::map< std::string, std::string > getCommandlineArguments (int32_t argc, char **argv) noexcept
std::string getIPv4FromHostname (const std::string &hostname) noexcept
std::string serializeEnvelope (cluon::data::Envelope &&envelope) noexcept
std::pair< bool, cluon::data::Envelope > extractEnvelope (std::istream &in) noexcept
template<typename T >
T extractMessage (cluon::data::Envelope &&envelope) noexcept
else if (`CHARACTER`==f->name)
void cluon_handleExit ()
void cluon_handleSignal (int32_t)
Variables
else
Enumeration Type Documentation
JSONConstants
enum class cluon::JSONConstants : uint16_t [strong]
Enumerator
IS_FALSE
IS_TRUE
NUMBER
STRING
OBJECT
UNDEFINED
                             : uint16_t {
        IS_FALSE = 0,
        IS_TRUE = 1,
        NUMBER = 2,
        STRING = 3,
        OBJECT = 4, // Indicating nested types.
        UNDEFINED = 99,
   };
MsgPackConstants
enum class cluon::MsgPackConstants : uint16_t [strong]
Enumerator
IS_FALSE
IS_TRUE
FLOAT
DOUBLE
UINT8
UINT16
UINT32
UINT64
NEGFIXINT
INT8
INT16
INT32
INT64
FIXSTR
FIXSTR_END
STR8
STR16
STR32
FIXMAP
FIXMAP_END
MAP16
MAP32
UNKNOWN_FORMAT
BOOL_FORMAT
UINT_FORMAT
INT_FORMAT
FLOAT_FORMAT
STR_FORMAT
MAP_FORMAT
                                : uint16_t {
        IS_FALSE = 0xC2,
        IS_TRUE = 0xC3,
        FLOAT = 0xCA,
        DOUBLE = 0xCB,
        UINT8 = 0xCC,
        UINT16 = 0xCD,
        UINT32 = 0xCE,
        UINT64 = 0xCF,
        NEGFIXINT = 0xE0,
        INT8 = 0xD0,
        INT16 = 0xD1,
        INT32 = 0xD2,
        INT64 = 0xD3,
        FIXSTR = 0xA0,
        FIXSTR_END = 0xBF,
        STR8 = 0xD9,
        STR16 = 0xDA,
        STR32 = 0xDB,
        FIXMAP = 0x80,
        FIXMAP_END = 0x8F,
        MAP16 = 0xDE,
        MAP32 = 0xDF,
        UNKNOWN_FORMAT = 0xFF00,
        BOOL_FORMAT = 0xFF01,
        UINT_FORMAT = 0xFF02,
        INT_FORMAT = 0xFF03,
        FLOAT_FORMAT = 0xFF04,
        STR_FORMAT = 0xFF05,
        MAP_FORMAT = 0xFF06, // Indicating also nested types.
   };
ProtoConstants
enum class cluon::ProtoConstants : uint8_t [strong]
Enumerator
VARINT
EIGHT_BYTES
LENGTH_DELIMITED
FOUR_BYTES
                              : uint8_t {
        VARINT = 0,
        EIGHT_BYTES = 1,
        LENGTH_DELIMITED = 2,
        FOUR_BYTES = 5, };
UDPPacketSizeConstraints
enum class cluon::UDPPacketSizeConstraints : uint16_t [strong]
Enumerator
SIZE_IPv4_HEADER
SIZE_UDP_HEADER
MAX_SIZE_UDP_PACKET
                                        : uint16_t {
        SIZE_IPv4_HEADER = 20,
        SIZE_UDP_HEADER = 8,
        MAX_SIZE_UDP_PACKET = 0xFFFF, };
Function Documentation
cluon_handleExit()
void cluon::cluon_handleExit () [inline]
                               {
    TerminateHandler::instance().isTerminated.store(true);
}
References cluon::TerminateHandler::instance(), and cluon::TerminateHandler::isTerminated.
Referenced by cluon::TerminateHandler::TerminateHandler().
cluon_handleSignal()
void cluon::cluon_handleSignal (int32_t) [inline]
                                          { // LCOV_EXCL_LINE
    TerminateHandler::instance().isTerminated.store(true); // LCOV_EXCL_LINE
}
References cluon::TerminateHandler::instance(), and cluon::TerminateHandler::isTerminated.
Referenced by cluon::TerminateHandler::TerminateHandler().
extractEnvelope()
std::pair< bool, cluon::data::Envelope > cluon::extractEnvelope (std::istream & in) [inline], [noexcept]
This method extracts an Envelope from the given istream that holds bytes in format:
0x0D 0xA4 LEN0 LEN1 LEN2 Proto-encoded cluon::data::Envelope
0xA4 LEN0 LEN1 LEN2 are little Endian.
Parameters
in Stream to read from.
Returns
cluon::data::Envelope.
                                                                                 {
    bool retVal{false};
    cluon::data::Envelope env;
    if (in.good()) {
        constexpr uint8_t OD4_HEADER_SIZE{5};
        std::vector<char> buffer;
        buffer.reserve(OD4_HEADER_SIZE);
#ifdef WIN32 // LCOV_EXCL_LINE
        buffer.clear(); // LCOV_EXCL_LINE
        retVal = true; // LCOV_EXCL_LINE
        for (uint8_t i{0}; i < OD4_HEADER_SIZE; i++) { // LCOV_EXCL_LINE
            char c; // LCOV_EXCL_LINE
            in.get(c); // LCOV_EXCL_LINE
            retVal &= in.good(); // LCOV_EXCL_LINE
            buffer.push_back(c); // LCOV_EXCL_LINE
        }
        if (retVal) { // LCOV_EXCL_LINE
#else // LCOV_EXCL_LINE
        in.read(&buffer[0], OD4_HEADER_SIZE);
        if (OD4_HEADER_SIZE == in.gcount()) {
#endif
            if ((0x0D == static_cast<uint8_t>(buffer[0])) && (0xA4 == static_cast<uint8_t>(buffer[1]))) {
                const uint32_t LENGTH{le32toh(*reinterpret_cast<uint32_t *>(&buffer[1])) >> 8};
                buffer.reserve(LENGTH);
#ifdef WIN32 // LCOV_EXCL_LINE
                buffer.clear(); // LCOV_EXCL_LINE
                for (uint32_t i{0}; i < LENGTH; i++) { // LCOV_EXCL_LINE
                    char c; // LCOV_EXCL_LINE
                    in.get(c); // LCOV_EXCL_LINE
                    retVal &= in.good(); // LCOV_EXCL_LINE
                    buffer.push_back(c); // LCOV_EXCL_LINE
                }
#else // LCOV_EXCL_LINE
                in.read(&buffer[0], static_cast<std::streamsize>(LENGTH));
                retVal = static_cast<int32_t>(LENGTH) == in.gcount();
#endif
                if (retVal) {
                    std::stringstream sstr(std::string(buffer.begin(), buffer.begin() + static_cast<std::streamsize>(LENGTH)));
                    cluon::FromProtoVisitor protoDecoder;
                    protoDecoder.decodeFrom(sstr, env);
                }
            }
        }
    }
    return std::make_pair(retVal, env);
}
References cluon::FromProtoVisitor::decodeFrom(), and retVal.
Referenced by cluon::OD4Session::callback(), cluon::Player::fillEnvelopeCache(), cluon::EnvelopeConverter::getJSONFromProtoEncodedEnvelope(), and cluon::Player::initializeIndex().
extractMessage()
template<typename T >
T cluon::extractMessage (cluon::data::Envelope && envelope) [inline], [noexcept]
Returns
Extract a given Envelope's payload into the desired type.
                                                               {
    cluon::FromProtoVisitor decoder;
    std::stringstream sstr(envelope.serializedData());
    decoder.decodeFrom(sstr);
    T msg;
    msg.accept(decoder);
    return msg;
}
References cluon::FromProtoVisitor::decodeFrom().
getCommandlineArguments()
std::map< std::string, std::string > cluon::getCommandlineArguments (int32_t argc, char ** argv) [inline], [noexcept]
Returns
Map for command line parameters passed as --key=value into key->values.
                                                                                                {
    argh::parser commandline{argc, argv};
    std::map<std::string, std::string> retVal;
    for (auto &positionalArgument : commandline.pos_args()) { retVal[positionalArgument] = ""; }
    for (auto &flag : commandline.flags()) { retVal[flag] = "1"; }
    for (auto &parameter : commandline.params()) { retVal[parameter.first] = parameter.second; }
    return retVal;
}
References retVal.
Referenced by main().
getIPv4FromHostname()
std::string cluon::getIPv4FromHostname (const std::string & hostname) [inline], [noexcept]
Returns
IPv4-formatted string for the given hostname or the empty string.
                                                                         {
#ifdef WIN32
    // Load Winsock 2.2 DLL.
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        std::cerr << "[cluon::getIPv4FromHostname] Error while calling WSAStartUp: " << WSAGetLastError() << std::endl;
    }
#endif
    std::string result{""};
    if (!hostname.empty()) {
        struct addrinfo hint;
        {
            std::memset(&hint, 1, sizeof(struct addrinfo));
            hint.ai_flags = AI_CANONNAME;
            hint.ai_family = AF_INET;
            hint.ai_socktype = 0;
            hint.ai_protocol = 0;
            hint.ai_addrlen = 0;
            hint.ai_canonname = nullptr;
            hint.ai_addr = nullptr;
            hint.ai_next = nullptr;
        }
        struct addrinfo *listOfHosts{nullptr};
        if (0 == getaddrinfo(hostname.c_str(), nullptr, &hint, &listOfHosts)) {
            for(struct addrinfo *e = listOfHosts; nullptr != listOfHosts; listOfHosts = listOfHosts->ai_next) {
                if (nullptr != e) {
                    if (AF_INET == e->ai_family) {
                        struct sockaddr_in *sinp = reinterpret_cast<struct sockaddr_in*>(e->ai_addr);
                        char buf[INET_ADDRSTRLEN];
                        const char *addr = inet_ntop(AF_INET, &sinp->sin_addr, buf, INET_ADDRSTRLEN);
                        if ((nullptr != addr) && (result.empty())) {
                            result = std::string(addr);
                            break;
                        }
                    }
                }
            }
        }
        if (nullptr != listOfHosts) {
            freeaddrinfo(listOfHosts);
        }
    }
#ifdef WIN32
    WSACleanup();
#endif
    return result;
}
Referenced by cluon::TCPConnection::TCPConnection(), cluon::UDPReceiver::UDPReceiver(), and cluon::UDPSender::UDPSender().
if()
else cluon::if (`CHARACTER` = = f->name)
                                                                         {
                                          _fieldDefaultInitializerValue = "'" + f->token + "'";
                                      } else {
serializeEnvelope()
std::string cluon::serializeEnvelope (cluon::data::Envelope && envelope) [inline], [noexcept]
This method transforms a given Envelope to a string representation to be sent to an OpenDaVINCI session.
Parameters
envelope Envelope with payload to be sent.
Returns
String representation of the Envelope to be sent to OpenDaVINCI v4.
                                                                          {
    std::string dataToSend;
    {
        std::stringstream sstr;
        cluon::ToProtoVisitor protoEncoder;
        envelope.accept(protoEncoder);
        const std::string tmp{protoEncoder.encodedData()};
        uint32_t length{static_cast<uint32_t>(tmp.size())};
        length <<= 8;
        length = htole32(length);
        // Add OD4 header.
        constexpr unsigned char OD4_HEADER_BYTE0 = 0x0D;
        constexpr unsigned char OD4_HEADER_BYTE1 = 0xA4;
        sstr.put(static_cast<char>(OD4_HEADER_BYTE0));
        auto posByte1 = sstr.tellp();
        sstr.write(reinterpret_cast<char *>(&length), static_cast<std::streamsize>(sizeof(uint32_t)));
        auto posByte5 = sstr.tellp();
        sstr.seekp(posByte1);
        sstr.put(static_cast<char>(OD4_HEADER_BYTE1));
        sstr.seekp(posByte5);
        // Write payload.
        sstr.write(tmp.data(), static_cast<std::streamsize>(tmp.size()));
        dataToSend = sstr.str();
    }
    return dataToSend;
}
References cluon::ToProtoVisitor::encodedData().
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), and cluon::OD4Session::send().
Variable Documentation
else
cluon::else
Initial value:
{
                                          _fieldDefaultInitializerValue = f->token