cluon::time Namespace Reference
Functions
cluon::data::TimeStamp fromMicroseconds (int64_t tp) noexcept
int64_t toMicroseconds (const cluon::data::TimeStamp &tp) noexcept
int64_t deltaInMicroseconds (const cluon::data::TimeStamp &AFTER, const cluon::data::TimeStamp &BEFORE) noexcept
cluon::data::TimeStamp convert (const std::chrono::system_clock::time_point &tp) noexcept
cluon::data::TimeStamp now () noexcept
Function Documentation
convert()
cluon::data::TimeStamp cluon::time::convert (const std::chrono::system_clock::time_point & tp) [inline], [noexcept]
Parameters
tp to be converted to microseconds.
Returns
TimeStamp of converted chrono::time_point.
                                                                                      {
    cluon::data::TimeStamp timeStamp;
    // Transform chrono time representation to same behavior as gettimeofday.
    typedef std::chrono::duration<int32_t> seconds_type;
    typedef std::chrono::duration<int64_t, std::micro> microseconds_type;
    auto duration = tp.time_since_epoch();
    seconds_type s = std::chrono::duration_cast<seconds_type>(duration);
    microseconds_type us = std::chrono::duration_cast<microseconds_type>(duration);
    microseconds_type partial_us = us - std::chrono::duration_cast<microseconds_type>(s);
    timeStamp.seconds(s.count()).microseconds(static_cast<int32_t>(partial_us.count()));
    return timeStamp;
}
References cluon::data::TimeStamp::microseconds(), and cluon::data::TimeStamp::seconds().
Referenced by cluon::OD4Session::callback(), and now().
deltaInMicroseconds()
int64_t cluon::time::deltaInMicroseconds (const cluon::data::TimeStamp & AFTER, const cluon::data::TimeStamp & BEFORE) [inline], [noexcept]
Parameters
AFTER First time stamp.
BEFORE Second time stamp.
Returns
Delta (BEFORE - AFTER) between two TimeStamps in microseconds.
                                                                                                               {
    return toMicroseconds(AFTER) - toMicroseconds(BEFORE);
}
References toMicroseconds().
Referenced by cluon::Player::initializeIndex().
fromMicroseconds()
cluon::data::TimeStamp cluon::time::fromMicroseconds (int64_t tp) [inline], [noexcept]
Parameters
tp to be converted to TimeStamp.
Returns
TimeStamp converted from microseconds.
                                                                {
    cluon::data::TimeStamp ts;
    ts.seconds(static_cast<int32_t>(tp / static_cast<int64_t>(1000 * 1000))).microseconds(static_cast<int32_t>(tp % static_cast<int64_t>(1000 * 1000)));
    return ts;
}
References cluon::data::TimeStamp::microseconds(), and cluon::data::TimeStamp::seconds().
now()
cluon::data::TimeStamp cluon::time::now () [inline], [noexcept]
Returns
TimeStamp of now from std::chrono::system_clock.
                                         {
    return convert(std::chrono::system_clock::now());
}
References convert(), and now().
Referenced by cluon::EnvelopeConverter::getProtoEncodedEnvelopeFromJSON(), cluon::Player::initializeIndex(), main(), now(), cluon::UDPReceiver::readFromSocket(), cluon::TCPConnection::readFromSocket(), cluon::OD4Session::send(), and cluon::OD4Session::timeTrigger().
toMicroseconds()
int64_t cluon::time::toMicroseconds (const cluon::data::TimeStamp & tp) [inline], [noexcept]
Parameters
tp to be converted to microseconds.
Returns
TimeStamp converted to microseconds.
                                                                     {
    return static_cast<int64_t>(tp.seconds()) * static_cast<int64_t>(1000 * 1000) + static_cast<int64_t>(tp.microseconds());
}
Referenced by deltaInMicroseconds(), cluon::Player::initializeIndex(), main(), and cluon::OD4Session::timeTrigger().