peg Namespace Reference
Namespaces
namespace udl
Classes
class Action
class AndPredicate
class any
class AnyCharacter
struct AssignIDToDefinition
struct AstBase
struct AstOptimizer
class BackReference
class Capture
class CaptureScope
class Character
class CharacterClass
class Context
class Definition
struct DetectLeftRecursion
struct EmptyType
struct FindReference
class Holder
class Ignore
struct IsLiteralToken
struct IsPrioritizedChoice
struct LinkReferences
class LiteralString
class NotPredicate
class OneOrMore
class Ope
class Option
struct parse_error
class parser
class ParserGenerator
class PrioritizedChoice
class Reference
struct ReferenceChecker
struct scope_exit
struct SemanticValues
class Sequence
class TokenBoundary
struct TokenChecker
class User
class WeakHolder
class Whitespace
class ZeroOrMore
Typedefs
typedef std::function< void(const char *name, const char *s, size_t n, const SemanticValues &sv, const Context &c, const any &dt)> Tracer
typedef std::function< size_t(const char *s, size_t n, SemanticValues &sv, any &dt)> Parser
typedef std::unordered_map< std::string, Definition > Grammar
typedef std::unordered_map< std::string, std::shared_ptr< Ope > > Rules
typedef std::function< void(size_t, size_t, const std::string &)> Log
typedef AstBase< EmptyType > Ast
Functions
template<typename EF >
auto make_scope_exit (EF &&exit_function) -> scope_exit< EF >
size_t codepoint_length (const char *s8, size_t l)
size_t encode_codepoint (char32_t cp, char *buff)
std::string encode_codepoint (char32_t cp)
bool decode_codepoint (const char *s8, size_t l, size_t &bytes, char32_t &cp)
size_t decode_codepoint (const char *s8, size_t l, char32_t &out)
char32_t decode_codepoint (const char *s8, size_t l)
std::u32string decode (const char *s8, size_t l)
bool is_hex (char c, int &v)
bool is_digit (char c, int &v)
std::pair< int, size_t > parse_hex_number (const char *s, size_t n, size_t i)
std::pair< int, size_t > parse_octal_number (const char *s, size_t n, size_t i)
std::string resolve_escape_sequence (const char *s, size_t n)
std::pair< size_t, size_t > line_info (const char *start, const char *cur)
constexpr unsigned int str2tag (const char *str, int h=0)
template<typename R , typename F , typename std::enable_if< std::is_void< R >::value, std::nullptr_t >::type = nullptr, typename... Args>
any call (F fn, Args &&... args)
bool success (size_t len)
bool fail (size_t len)
template<typename... Args>
std::shared_ptr< Ope > seq (Args &&...args)
template<typename... Args>
std::shared_ptr< Ope > cho (Args &&...args)
std::shared_ptr< Ope > zom (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > oom (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > opt (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > apd (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > npd (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > lit (const std::string &s)
std::shared_ptr< Ope > liti (const std::string &s)
std::shared_ptr< Ope > cls (const std::string &s)
std::shared_ptr< Ope > cls (const std::vector< std::pair< char32_t, char32_t > > &ranges)
std::shared_ptr< Ope > chr (char dt)
std::shared_ptr< Ope > dot ()
std::shared_ptr< Ope > csc (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > cap (const std::shared_ptr< Ope > &ope, Capture::MatchAction ma)
std::shared_ptr< Ope > tok (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > ign (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > usr (std::function< size_t(const char *s, size_t n, SemanticValues &sv, any &dt)> fn)
std::shared_ptr< Ope > ref (const Grammar &grammar, const std::string &name, const char *s, bool is_macro, const std::vector< std::shared_ptr< Ope > > &args)
std::shared_ptr< Ope > wsp (const std::shared_ptr< Ope > &ope)
std::shared_ptr< Ope > bkr (const std::string &name)
size_t parse_literal (const char *s, size_t n, SemanticValues &sv, Context &c, any &dt, const std::string &lit, bool &init_is_word, bool &is_word, bool ignore_case)
template<typename T >
void ast_to_s_core (const std::shared_ptr< T > &ptr, std::string &s, int level, std::function< std::string(const T &ast, int level)> fn)
template<typename T >
std::string ast_to_s (const std::shared_ptr< T > &ptr, std::function< std::string(const T &ast, int level)> fn=nullptr)
Variables
static const char * WHITESPACE_DEFINITION_NAME = `%whitespace`
static const char * WORD_DEFINITION_NAME = `%word`
Typedef Documentation
Ast
typedef AstBase<EmptyType> peg::Ast
Grammar
typedef std::unordered_map<std::string, Definition> peg::Grammar
Log
typedef std::function<void (size_t, size_t, const std::string&)> peg::Log
Parser
typedef std::function<size_t (const char* s, size_t n, SemanticValues& sv, any& dt)> peg::Parser
Rules
typedef std::unordered_map<std::string, std::shared_ptr<Ope> > peg::Rules
Tracer
typedef std::function<void (const char* name, const char* s, size_t n, const SemanticValues& sv, const Context& c, const any& dt)> peg::Tracer
Function Documentation
apd()
std::shared_ptr< Ope > peg::apd (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<AndPredicate>(ope);
}
Referenced by peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
ast_to_s()
template<typename T >
std::string peg::ast_to_s (const std::shared_ptr< T > & ptr, std::function< std::string(const T &ast, int level)> fn = nullptr)
                                                                   {
    std::string s;
    ast_to_s_core(ptr, s, 0, fn);
    return s;
}
References ast_to_s_core().
ast_to_s_core()
template<typename T >
void peg::ast_to_s_core (const std::shared_ptr< T > & ptr, std::string & s, int level, std::function< std::string(const T &ast, int level)> fn)
                                                         {
    const auto& ast = *ptr;
    for (auto i = 0; i < level; i++) {
        s += " ";
    }
    auto name = ast.original_name;
    if (ast.original_choice_count > 0) {
        name += "/" + std::to_string(ast.original_choice);
    }
    if (ast.name != ast.original_name) {
        name += "[" + ast.name + "]";
    }
    if (ast.is_token) {
        s += "- " + name + " (" + ast.token + ")\n";
    } else {
        s += "+ " + name + "\n";
    }
    if (fn) {
      s += fn(ast, level + 1);
    }
    for (auto node : ast.nodes) {
        ast_to_s_core(node, s, level + 1, fn);
    }
}
References ast, and ast_to_s_core().
Referenced by ast_to_s(), and ast_to_s_core().
bkr()
std::shared_ptr< Ope > peg::bkr (const std::string & name) [inline]
                                                     {
    return std::make_shared<BackReference>(name);
}
Referenced by peg::ParserGenerator::setup_actions().
call()
template<typename R , typename F , typename std::enable_if< std::is_void< R >::value, std::nullptr_t >::type = nullptr, typename... Args>
any peg::call (F fn, Args &&... args)
                               {
    fn(std::forward<Args>(args)...);
    return any();
}
cap()
std::shared_ptr< Ope > peg::cap (const std::shared_ptr< Ope > & ope, Capture::MatchAction ma) [inline]
                                                                                    {
    return std::make_shared<Capture>(ope, ma);
}
Referenced by peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
cho()
template<typename... Args>
std::shared_ptr< Ope > peg::cho (Args &&... args)
                                       {
    return std::make_shared<PrioritizedChoice>(static_cast<std::shared_ptr<Ope>>(args)...);
}
Referenced by peg::ParserGenerator::make_grammar().
chr()
std::shared_ptr< Ope > peg::chr (char dt) [inline]
                                       {
    return std::make_shared<Character>(dt);
}
Referenced by peg::ParserGenerator::make_grammar().
cls() [1/2]
std::shared_ptr< Ope > peg::cls (const std::string & s) [inline]
                                                  {
    return std::make_shared<CharacterClass>(s);
}
cls() [2/2]
std::shared_ptr< Ope > peg::cls (const std::vector< std::pair< char32_t, char32_t > > & ranges) [inline]
                                                                                    {
    return std::make_shared<CharacterClass>(ranges);
}
Referenced by peg::ParserGenerator::make_grammar(), and peg::ParserGenerator::setup_actions().
codepoint_length()
size_t peg::codepoint_length (const char * s8, size_t l) [inline]
                                                         {
  if (l) {
    auto b = static_cast<uint8_t>(s8[0]);
    if ((b & 0x80) == 0) {
      return 1;
    } else if ((b & 0xE0) == 0xC0) {
      return 2;
    } else if ((b & 0xF0) == 0xE0) {
      return 3;
    } else if ((b & 0xF8) == 0xF0) {
      return 4;
    }
  }
  return 0;
}
Referenced by peg::AnyCharacter::parse().
csc()
std::shared_ptr< Ope > peg::csc (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<CaptureScope>(ope);
}
Referenced by peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
decode()
std::u32string peg::decode (const char * s8, size_t l) [inline]
                                                     {
  std::u32string out;
  size_t i = 0;
  while (i < l) {
    auto beg = i++;
    while (i < l && (s8[i] & 0xc0) == 0x80) {
      i++;
    }
    out += decode_codepoint(&s8[beg], (i - beg));
  }
  return out;
}
References decode_codepoint().
Referenced by peg::CharacterClass::CharacterClass().
decode_codepoint() [1/3]
char32_t peg::decode_codepoint (const char * s8, size_t l) [inline]
                                                           {
  char32_t out = 0;
  decode_codepoint(s8, l, out);
  return out;
}
References decode_codepoint().
Referenced by decode(), decode_codepoint(), peg::CharacterClass::parse(), and peg::ParserGenerator::setup_actions().
decode_codepoint() [2/3]
size_t peg::decode_codepoint (const char * s8, size_t l, char32_t & out) [inline]
                                                                        {
  size_t bytes;
  if (decode_codepoint(s8, l, bytes, out)) {
    return bytes;
  }
  return 0;
}
References decode_codepoint().
decode_codepoint() [3/3]
bool peg::decode_codepoint (const char * s8, size_t l, size_t & bytes, char32_t & cp) [inline]
                                           {
  if (l) {
    auto b = static_cast<uint8_t>(s8[0]);
    if ((b & 0x80) == 0) {
      bytes = 1;
      cp = b;
      return true;
    } else if ((b & 0xE0) == 0xC0) {
      if (l >= 2) {
        bytes = 2;
        cp = ((static_cast<char32_t>(s8[0] & 0x1F)) << 6) |
             (static_cast<char32_t>(s8[1] & 0x3F));
        return true;
      }
    } else if ((b & 0xF0) == 0xE0) {
      if (l >= 3) {
        bytes = 3;
        cp = ((static_cast<char32_t>(s8[0] & 0x0F)) << 12) |
             ((static_cast<char32_t>(s8[1] & 0x3F)) << 6) |
             (static_cast<char32_t>(s8[2] & 0x3F));
        return true;
      }
    } else if ((b & 0xF8) == 0xF0) {
      if (l >= 4) {
        bytes = 4;
        cp = ((static_cast<char32_t>(s8[0] & 0x07)) << 18) |
             ((static_cast<char32_t>(s8[1] & 0x3F)) << 12) |
             ((static_cast<char32_t>(s8[2] & 0x3F)) << 6) |
             (static_cast<char32_t>(s8[3] & 0x3F));
        return true;
      }
    }
  }
  return false;
}
dot()
std::shared_ptr< Ope > peg::dot () [inline]
                                {
    return std::make_shared<AnyCharacter>();
}
Referenced by peg::ParserGenerator::make_grammar(), and peg::ParserGenerator::setup_actions().
encode_codepoint() [1/2]
std::string peg::encode_codepoint (char32_t cp) [inline]
                                               {
  char buff[4];
  auto l = encode_codepoint(cp, buff);
  return std::string(buff, l);
}
References encode_codepoint().
Referenced by encode_codepoint(), and resolve_escape_sequence().
encode_codepoint() [2/2]
size_t peg::encode_codepoint (char32_t cp, char * buff) [inline]
                                                        {
  if (cp < 0x0080) {
    buff[0] = static_cast<char>(cp & 0x7F);
    return 1;
  } else if (cp < 0x0800) {
    buff[0] = static_cast<char>(0xC0 | ((cp >> 6) & 0x1F));
    buff[1] = static_cast<char>(0x80 | (cp & 0x3F));
    return 2;
  } else if (cp < 0xD800) {
    buff[0] = static_cast<char>(0xE0 | ((cp >> 12) & 0xF));
    buff[1] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
    buff[2] = static_cast<char>(0x80 | (cp & 0x3F));
    return 3;
  } else if (cp < 0xE000) {
    // D800 - DFFF is invalid...
    return 0;
  } else if (cp < 0x10000) {
    buff[0] = static_cast<char>(0xE0 | ((cp >> 12) & 0xF));
    buff[1] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
    buff[2] = static_cast<char>(0x80 | (cp & 0x3F));
    return 3;
  } else if (cp < 0x110000) {
    buff[0] = static_cast<char>(0xF0 | ((cp >> 18) & 0x7));
    buff[1] = static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
    buff[2] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
    buff[3] = static_cast<char>(0x80 | (cp & 0x3F));
    return 4;
  }
  return 0;
}
fail()
bool peg::fail (size_t len) [inline]
                             {
    return len == static_cast<size_t>(-1);
}
Referenced by peg::Sequence::parse(), peg::TokenBoundary::parse(), and parse_literal().
ign()
std::shared_ptr< Ope > peg::ign (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<Ignore>(ope);
}
Referenced by peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
is_digit()
bool peg::is_digit (char c, int & v) [inline]
                                     {
    if ('0' <= c && c <= '9') {
        v = c - '0';
        return true;
    }
    return false;
}
Referenced by parse_octal_number().
is_hex()
bool peg::is_hex (char c, int & v) [inline]
                                   {
    if ('0' <= c && c <= '9') {
        v = c - '0';
        return true;
    } else if ('a' <= c && c <= 'f') {
        v = c - 'a' + 10;
        return true;
    } else if ('A' <= c && c <= 'F') {
        v = c - 'A' + 10;
        return true;
    }
    return false;
}
Referenced by parse_hex_number().
line_info()
std::pair< size_t, size_t > peg::line_info (const char * start, const char * cur) [inline]
                                                                             {
    auto p = start;
    auto col_ptr = p;
    auto no = 1;
    while (p < cur) {
        if (*p == '\n') {
            no++;
            col_ptr = p + 1;
        }
        p++;
    }
    auto col = p - col_ptr + 1;
    return std::make_pair(no, col);
}
References p.
Referenced by peg::parser::enable_ast(), peg::SemanticValues::line_info(), peg::parser::output_log(), and peg::ParserGenerator::perform_core().
lit()
std::shared_ptr< Ope > peg::lit (const std::string & s) [inline]
                                                  {
    return std::make_shared<LiteralString>(s, false);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::BackReference::parse(), parse_literal(), and peg::ParserGenerator::setup_actions().
liti()
std::shared_ptr< Ope > peg::liti (const std::string & s) [inline]
                                                   {
    return std::make_shared<LiteralString>(s, true);
}
Referenced by peg::ParserGenerator::setup_actions().
make_scope_exit()
template<typename EF >
auto peg::make_scope_exit (EF && exit_function) -> scope_exit<EF>
                                                           {
    return scope_exit<typename std::remove_reference<EF>::type>(std::forward<EF>(exit_function));
}
Referenced by peg::Ignore::parse(), peg::Sequence::parse(), peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), peg::CaptureScope::parse(), peg::TokenBoundary::parse(), peg::Holder::parse(), peg::Reference::parse(), and peg::Whitespace::parse().
npd()
std::shared_ptr< Ope > peg::npd (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<NotPredicate>(ope);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
oom()
std::shared_ptr< Ope > peg::oom (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<OneOrMore>(ope);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
opt()
std::shared_ptr< Ope > peg::opt (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<Option>(ope);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::AstOptimizer::optimize(), peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
parse_hex_number()
std::pair< int, size_t > peg::parse_hex_number (const char * s, size_t n, size_t i) [inline]
                                                                                {
    int ret = 0;
    int val;
    while (i < n && is_hex(s[i], val)) {
        ret = static_cast<int>(ret * 16 + val);
        i++;
    }
    return std::make_pair(ret, i);
}
References is_hex().
Referenced by resolve_escape_sequence().
parse_literal()
size_t peg::parse_literal (const char * s, size_t n, SemanticValues & sv, Context & c, any & dt, const std::string & lit, bool & init_is_word, bool & is_word, bool ignore_case) [inline]
{
    size_t i = 0;
    for (; i < lit.size(); i++) {
        if (i >= n || (ignore_case ? (std::tolower(s[i]) != std::tolower(lit[i])) : (s[i] != lit[i]))) {
            c.set_error_pos(s);
            return static_cast<size_t>(-1);
        }
    }
    // Word check
    static Context dummy_c(nullptr, c.s, c.l, 0, nullptr, nullptr, false, nullptr);
    static SemanticValues dummy_sv;
    static any dummy_dt;
    if (!init_is_word) { // TODO: Protect with mutex
        if (c.wordOpe) {
            auto len = c.wordOpe->parse(lit.data(), lit.size(), dummy_sv, dummy_c, dummy_dt);
            is_word = success(len);
        }
        init_is_word = true;
    }
    if (is_word) {
        auto ope = std::make_shared<NotPredicate>(c.wordOpe);
        auto len = ope->parse(s + i, n - i, dummy_sv, dummy_c, dummy_dt);
        if (fail(len)) {
            return static_cast<size_t>(-1);
        }
        i += len;
    }
    // Skip whiltespace
    if (!c.in_token) {
        if (c.whitespaceOpe) {
            auto len = c.whitespaceOpe->parse(s + i, n - i, sv, c, dt);
            if (fail(len)) {
                return static_cast<size_t>(-1);
            }
            i += len;
        }
    }
    return i;
}
References fail(), peg::Context::in_token, peg::Context::l, lit(), peg::Context::s, peg::Context::set_error_pos(), success(), peg::Context::whitespaceOpe, and peg::Context::wordOpe.
Referenced by peg::LiteralString::parse(), and peg::BackReference::parse().
parse_octal_number()
std::pair< int, size_t > peg::parse_octal_number (const char * s, size_t n, size_t i) [inline]
                                                                                  {
    int ret = 0;
    int val;
    while (i < n && is_digit(s[i], val)) {
        ret = static_cast<int>(ret * 8 + val);
        i++;
    }
    return std::make_pair(ret, i);
}
References is_digit().
Referenced by resolve_escape_sequence().
ref()
std::shared_ptr< Ope > peg::ref (const Grammar & grammar, const std::string & name, const char * s, bool is_macro, const std::vector< std::shared_ptr< Ope > > & args) [inline]
                                                                                                                                                      {
    return std::make_shared<Reference>(grammar, name, s, is_macro, args);
}
Referenced by peg::ParserGenerator::setup_actions().
resolve_escape_sequence()
std::string peg::resolve_escape_sequence (const char * s, size_t n) [inline]
                                                                  {
    std::string r;
    r.reserve(n);
    size_t i = 0;
    while (i < n) {
        auto ch = s[i];
        if (ch == '\\') {
            i++;
            switch (s[i]) {
                case 'n': r += '\n'; i++; break;
                case 'r': r += '\r'; i++; break;
                case 't': r += '\t'; i++; break;
                case '\'': r += '\''; i++; break;
                case '"': r += '"'; i++; break;
                case '[': r += '['; i++; break;
                case ']': r += ']'; i++; break;
                case '\\': r += '\\'; i++; break;
                case 'x':
                case 'u': {
                    char32_t cp;
                    std::tie(cp, i) = parse_hex_number(s, n, i + 1);
                    r += encode_codepoint(cp);
                    break;
                }
                default: {
                    char32_t cp;
                    std::tie(cp, i) = parse_octal_number(s, n, i);
                    r += encode_codepoint(cp);
                    break;
                }
            }
        } else {
            r += ch;
            i++;
        }
    }
    return r;
}
References encode_codepoint(), parse_hex_number(), and parse_octal_number().
Referenced by peg::ParserGenerator::setup_actions().
seq()
template<typename... Args>
std::shared_ptr< Ope > peg::seq (Args &&... args)
                                       {
    return std::make_shared<Sequence>(static_cast<std::shared_ptr<Ope>>(args)...);
}
Referenced by peg::ParserGenerator::make_grammar().
str2tag()
constexpr unsigned int peg::str2tag (const char * str, int h = 0) [inline], [constexpr]
                                                                  {
    return !str[h] ? 5381 : (str2tag(str, h + 1) * 33) ^ static_cast<unsigned char>(str[h]);
}
References str2tag().
Referenced by peg::udl::operator``_(), and str2tag().
success()
bool peg::success (size_t len) [inline]
                                {
    return len != static_cast<size_t>(-1);
}
Referenced by peg::Context::packrat(), peg::PrioritizedChoice::parse(), peg::ZeroOrMore::parse(), peg::OneOrMore::parse(), peg::Option::parse(), peg::AndPredicate::parse(), peg::NotPredicate::parse(), peg::Capture::parse(), peg::TokenBoundary::parse(), peg::Holder::parse(), peg::Definition::parse_core(), and parse_literal().
tok()
std::shared_ptr< Ope > peg::tok (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<TokenBoundary>(ope);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::ParserGenerator::perform_core(), peg::ParserGenerator::setup_actions(), peg::SemanticValues::token(), and peg::FindReference::visit().
usr()
std::shared_ptr< Ope > peg::usr (std::function< size_t(const char *s, size_t n, SemanticValues &sv, any &dt)> fn) [inline]
                                                                                                             {
    return std::make_shared<User>(fn);
}
wsp()
std::shared_ptr< Ope > peg::wsp (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<Whitespace>(std::make_shared<Ignore>(ope));
}
Referenced by peg::ParserGenerator::perform_core(), and peg::FindReference::visit().
zom()
std::shared_ptr< Ope > peg::zom (const std::shared_ptr< Ope > & ope) [inline]
                                                             {
    return std::make_shared<ZeroOrMore>(ope);
}
Referenced by peg::ParserGenerator::make_grammar(), peg::ParserGenerator::setup_actions(), and peg::FindReference::visit().
Variable Documentation
WHITESPACE_DEFINITION_NAME
const char* peg::WHITESPACE_DEFINITION_NAME = `%whitespace` [static]
Referenced by peg::ParserGenerator::perform_core().
WORD_DEFINITION_NAME
const char* peg::WORD_DEFINITION_NAME = `%word` [static]
Referenced by peg::ParserGenerator::perform_core().