src/opendlv-standard-message-set.hpp File Reference
#include <cstdint>
#include <string>
#include <utility>
Classes
struct visitorSelector< b >
struct visitorSelector< true >
struct isVisitable< T >
struct tripletForwardVisitorSelector< b >
struct tripletForwardVisitorSelector< true >
struct isTripletForwardVisitable< T >
class opendlv::sim::Frame
struct isVisitable< opendlv::sim::Frame >
struct isTripletForwardVisitable< opendlv::sim::Frame >
class opendlv::sim::KinematicState
struct isVisitable< opendlv::sim::KinematicState >
struct isTripletForwardVisitable< opendlv::sim::KinematicState >
class opendlv::body::ComponentInfo
struct isVisitable< opendlv::body::ComponentInfo >
struct isTripletForwardVisitable< opendlv::body::ComponentInfo >
class opendlv::body::ActuatorInfo
struct isVisitable< opendlv::body::ActuatorInfo >
struct isTripletForwardVisitable< opendlv::body::ActuatorInfo >
class opendlv::body::SensorInfo
struct isVisitable< opendlv::body::SensorInfo >
struct isTripletForwardVisitable< opendlv::body::SensorInfo >
class opendlv::body::SignalInfo
struct isVisitable< opendlv::body::SignalInfo >
struct isTripletForwardVisitable< opendlv::body::SignalInfo >
class opendlv::proxy::AccelerationReading
struct isVisitable< opendlv::proxy::AccelerationReading >
struct isTripletForwardVisitable< opendlv::proxy::AccelerationReading >
class opendlv::proxy::AngularVelocityReading
struct isVisitable< opendlv::proxy::AngularVelocityReading >
struct isTripletForwardVisitable< opendlv::proxy::AngularVelocityReading >
class opendlv::proxy::MagneticFieldReading
struct isVisitable< opendlv::proxy::MagneticFieldReading >
struct isTripletForwardVisitable< opendlv::proxy::MagneticFieldReading >
class opendlv::proxy::AltitudeReading
struct isVisitable< opendlv::proxy::AltitudeReading >
struct isTripletForwardVisitable< opendlv::proxy::AltitudeReading >
class opendlv::proxy::PressureReading
struct isVisitable< opendlv::proxy::PressureReading >
struct isTripletForwardVisitable< opendlv::proxy::PressureReading >
class opendlv::proxy::TemperatureReading
struct isVisitable< opendlv::proxy::TemperatureReading >
struct isTripletForwardVisitable< opendlv::proxy::TemperatureReading >
class opendlv::proxy::TorqueReading
struct isVisitable< opendlv::proxy::TorqueReading >
struct isTripletForwardVisitable< opendlv::proxy::TorqueReading >
class opendlv::proxy::VoltageReading
struct isVisitable< opendlv::proxy::VoltageReading >
struct isTripletForwardVisitable< opendlv::proxy::VoltageReading >
class opendlv::proxy::AngleReading
struct isVisitable< opendlv::proxy::AngleReading >
struct isTripletForwardVisitable< opendlv::proxy::AngleReading >
class opendlv::proxy::DistanceReading
struct isVisitable< opendlv::proxy::DistanceReading >
struct isTripletForwardVisitable< opendlv::proxy::DistanceReading >
class opendlv::proxy::SwitchStateReading
struct isVisitable< opendlv::proxy::SwitchStateReading >
struct isTripletForwardVisitable< opendlv::proxy::SwitchStateReading >
class opendlv::proxy::PedalPositionReading
struct isVisitable< opendlv::proxy::PedalPositionReading >
struct isTripletForwardVisitable< opendlv::proxy::PedalPositionReading >
class opendlv::proxy::GroundSteeringReading
struct isVisitable< opendlv::proxy::GroundSteeringReading >
struct isTripletForwardVisitable< opendlv::proxy::GroundSteeringReading >
class opendlv::proxy::GroundSpeedReading
struct isVisitable< opendlv::proxy::GroundSpeedReading >
struct isTripletForwardVisitable< opendlv::proxy::GroundSpeedReading >
class opendlv::proxy::WheelSpeedReading
struct isVisitable< opendlv::proxy::WheelSpeedReading >
struct isTripletForwardVisitable< opendlv::proxy::WheelSpeedReading >
class opendlv::proxy::WeightReading
struct isVisitable< opendlv::proxy::WeightReading >
struct isTripletForwardVisitable< opendlv::proxy::WeightReading >
class opendlv::proxy::GeodeticHeadingReading
struct isVisitable< opendlv::proxy::GeodeticHeadingReading >
struct isTripletForwardVisitable< opendlv::proxy::GeodeticHeadingReading >
class opendlv::proxy::GeodeticWgs84Reading
struct isVisitable< opendlv::proxy::GeodeticWgs84Reading >
struct isTripletForwardVisitable< opendlv::proxy::GeodeticWgs84Reading >
class opendlv::proxy::ImageReading
struct isVisitable< opendlv::proxy::ImageReading >
struct isTripletForwardVisitable< opendlv::proxy::ImageReading >
class opendlv::proxy::ImageReadingShared
struct isVisitable< opendlv::proxy::ImageReadingShared >
struct isTripletForwardVisitable< opendlv::proxy::ImageReadingShared >
class opendlv::proxy::PointCloudReading
struct isVisitable< opendlv::proxy::PointCloudReading >
struct isTripletForwardVisitable< opendlv::proxy::PointCloudReading >
class opendlv::proxy::PointCloudReadingShared
struct isVisitable< opendlv::proxy::PointCloudReadingShared >
struct isTripletForwardVisitable< opendlv::proxy::PointCloudReadingShared >
class opendlv::proxy::PressureRequest
struct isVisitable< opendlv::proxy::PressureRequest >
struct isTripletForwardVisitable< opendlv::proxy::PressureRequest >
class opendlv::proxy::TemperatureRequest
struct isVisitable< opendlv::proxy::TemperatureRequest >
struct isTripletForwardVisitable< opendlv::proxy::TemperatureRequest >
class opendlv::proxy::TorqueRequest
struct isVisitable< opendlv::proxy::TorqueRequest >
struct isTripletForwardVisitable< opendlv::proxy::TorqueRequest >
class opendlv::proxy::VoltageRequest
struct isVisitable< opendlv::proxy::VoltageRequest >
struct isTripletForwardVisitable< opendlv::proxy::VoltageRequest >
class opendlv::proxy::AngleRequest
struct isVisitable< opendlv::proxy::AngleRequest >
struct isTripletForwardVisitable< opendlv::proxy::AngleRequest >
class opendlv::proxy::SwitchStateRequest
struct isVisitable< opendlv::proxy::SwitchStateRequest >
struct isTripletForwardVisitable< opendlv::proxy::SwitchStateRequest >
class opendlv::proxy::PedalPositionRequest
struct isVisitable< opendlv::proxy::PedalPositionRequest >
struct isTripletForwardVisitable< opendlv::proxy::PedalPositionRequest >
class opendlv::proxy::PulseWidthModulationRequest
struct isVisitable< opendlv::proxy::PulseWidthModulationRequest >
struct isTripletForwardVisitable< opendlv::proxy::PulseWidthModulationRequest >
class opendlv::proxy::GroundSteeringRequest
struct isVisitable< opendlv::proxy::GroundSteeringRequest >
struct isTripletForwardVisitable< opendlv::proxy::GroundSteeringRequest >
class opendlv::proxy::GroundSpeedRequest
struct isVisitable< opendlv::proxy::GroundSpeedRequest >
struct isTripletForwardVisitable< opendlv::proxy::GroundSpeedRequest >
class opendlv::proxy::GroundAccelerationRequest
struct isVisitable< opendlv::proxy::GroundAccelerationRequest >
struct isTripletForwardVisitable< opendlv::proxy::GroundAccelerationRequest >
class opendlv::proxy::GroundDecelerationRequest
struct isVisitable< opendlv::proxy::GroundDecelerationRequest >
struct isTripletForwardVisitable< opendlv::proxy::GroundDecelerationRequest >
class opendlv::proxy::WheelSpeedRequest
struct isVisitable< opendlv::proxy::WheelSpeedRequest >
struct isTripletForwardVisitable< opendlv::proxy::WheelSpeedRequest >
class opendlv::system::SignalStatusMessage
struct isVisitable< opendlv::system::SignalStatusMessage >
struct isTripletForwardVisitable< opendlv::system::SignalStatusMessage >
class opendlv::system::SystemOperationState
struct isVisitable< opendlv::system::SystemOperationState >
struct isTripletForwardVisitable< opendlv::system::SystemOperationState >
class opendlv::system::NetworkStatusMessage
struct isVisitable< opendlv::system::NetworkStatusMessage >
struct isTripletForwardVisitable< opendlv::system::NetworkStatusMessage >
class opendlv::logic::sensation::Direction
struct isVisitable< opendlv::logic::sensation::Direction >
struct isTripletForwardVisitable< opendlv::logic::sensation::Direction >
class opendlv::logic::sensation::Point
struct isVisitable< opendlv::logic::sensation::Point >
struct isTripletForwardVisitable< opendlv::logic::sensation::Point >
class opendlv::logic::sensation::Geolocation
struct isVisitable< opendlv::logic::sensation::Geolocation >
struct isTripletForwardVisitable< opendlv::logic::sensation::Geolocation >
class opendlv::logic::sensation::Equilibrioception
struct isVisitable< opendlv::logic::sensation::Equilibrioception >
struct isTripletForwardVisitable< opendlv::logic::sensation::Equilibrioception >
class opendlv::logic::perception::Object
struct isVisitable< opendlv::logic::perception::Object >
struct isTripletForwardVisitable< opendlv::logic::perception::Object >
class opendlv::logic::perception::ObjectType
struct isVisitable< opendlv::logic::perception::ObjectType >
struct isTripletForwardVisitable< opendlv::logic::perception::ObjectType >
class opendlv::logic::perception::ObjectProperty
struct isVisitable< opendlv::logic::perception::ObjectProperty >
struct isTripletForwardVisitable< opendlv::logic::perception::ObjectProperty >
class opendlv::logic::perception::ObjectDirection
struct isVisitable< opendlv::logic::perception::ObjectDirection >
struct isTripletForwardVisitable< opendlv::logic::perception::ObjectDirection >
class opendlv::logic::perception::ObjectDistance
struct isVisitable< opendlv::logic::perception::ObjectDistance >
struct isTripletForwardVisitable< opendlv::logic::perception::ObjectDistance >
class opendlv::logic::perception::ObjectAngularBlob
struct isVisitable< opendlv::logic::perception::ObjectAngularBlob >
struct isTripletForwardVisitable< opendlv::logic::perception::ObjectAngularBlob >
class opendlv::logic::perception::GroundSurface
struct isVisitable< opendlv::logic::perception::GroundSurface >
struct isTripletForwardVisitable< opendlv::logic::perception::GroundSurface >
class opendlv::logic::perception::GroundSurfaceType
struct isVisitable< opendlv::logic::perception::GroundSurfaceType >
struct isTripletForwardVisitable< opendlv::logic::perception::GroundSurfaceType >
class opendlv::logic::perception::GroundSurfaceProperty
struct isVisitable< opendlv::logic::perception::GroundSurfaceProperty >
struct isTripletForwardVisitable< opendlv::logic::perception::GroundSurfaceProperty >
class opendlv::logic::perception::GroundSurfaceArea
struct isVisitable< opendlv::logic::perception::GroundSurfaceArea >
struct isTripletForwardVisitable< opendlv::logic::perception::GroundSurfaceArea >
class opendlv::logic::action::AimDirection
struct isVisitable< opendlv::logic::action::AimDirection >
struct isTripletForwardVisitable< opendlv::logic::action::AimDirection >
class opendlv::logic::action::AimPoint
struct isVisitable< opendlv::logic::action::AimPoint >
struct isTripletForwardVisitable< opendlv::logic::action::AimPoint >
class opendlv::logic::action::PreviewPoint
struct isVisitable< opendlv::logic::action::PreviewPoint >
struct isTripletForwardVisitable< opendlv::logic::action::PreviewPoint >
class opendlv::logic::cognition::GroundSteeringLimit
struct isVisitable< opendlv::logic::cognition::GroundSteeringLimit >
struct isTripletForwardVisitable< opendlv::logic::cognition::GroundSteeringLimit >
class opendlv::logic::cognition::GroundSpeedLimit
struct isVisitable< opendlv::logic::cognition::GroundSpeedLimit >
struct isTripletForwardVisitable< opendlv::logic::cognition::GroundSpeedLimit >
Namespaces
namespace opendlv
namespace opendlv::sim
namespace opendlv::body
namespace opendlv::proxy
namespace opendlv::system
namespace opendlv::logic
namespace opendlv::logic::sensation
namespace opendlv::logic::perception
namespace opendlv::logic::action
namespace opendlv::logic::cognition
Macros
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define OPENDLV_SIM_FRAME_HPP
#define LIB_API
#define OPENDLV_SIM_KINEMATICSTATE_HPP
#define LIB_API
#define OPENDLV_BODY_COMPONENTINFO_HPP
#define LIB_API
#define OPENDLV_BODY_ACTUATORINFO_HPP
#define LIB_API
#define OPENDLV_BODY_SENSORINFO_HPP
#define LIB_API
#define OPENDLV_BODY_SIGNALINFO_HPP
#define LIB_API
#define OPENDLV_PROXY_ACCELERATIONREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_ANGULARVELOCITYREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_MAGNETICFIELDREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_ALTITUDEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_PRESSUREREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_TEMPERATUREREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_TORQUEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_VOLTAGEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_ANGLEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_DISTANCEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_SWITCHSTATEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_PEDALPOSITIONREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDSTEERINGREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDSPEEDREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_WHEELSPEEDREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_WEIGHTREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_GEODETICHEADINGREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_GEODETICWGS84READING_HPP
#define LIB_API
#define OPENDLV_PROXY_IMAGEREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_IMAGEREADINGSHARED_HPP
#define LIB_API
#define OPENDLV_PROXY_POINTCLOUDREADING_HPP
#define LIB_API
#define OPENDLV_PROXY_POINTCLOUDREADINGSHARED_HPP
#define LIB_API
#define OPENDLV_PROXY_PRESSUREREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_TEMPERATUREREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_TORQUEREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_VOLTAGEREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_ANGLEREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_SWITCHSTATEREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_PEDALPOSITIONREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_PULSEWIDTHMODULATIONREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDSTEERINGREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDSPEEDREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDACCELERATIONREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_GROUNDDECELERATIONREQUEST_HPP
#define LIB_API
#define OPENDLV_PROXY_WHEELSPEEDREQUEST_HPP
#define LIB_API
#define OPENDLV_SYSTEM_SIGNALSTATUSMESSAGE_HPP
#define LIB_API
#define OPENDLV_SYSTEM_SYSTEMOPERATIONSTATE_HPP
#define LIB_API
#define OPENDLV_SYSTEM_NETWORKSTATUSMESSAGE_HPP
#define LIB_API
#define OPENDLV_LOGIC_SENSATION_DIRECTION_HPP
#define LIB_API
#define OPENDLV_LOGIC_SENSATION_POINT_HPP
#define LIB_API
#define OPENDLV_LOGIC_SENSATION_GEOLOCATION_HPP
#define LIB_API
#define OPENDLV_LOGIC_SENSATION_EQUILIBRIOCEPTION_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECT_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECTTYPE_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECTPROPERTY_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECTDIRECTION_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECTDISTANCE_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_OBJECTANGULARBLOB_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACE_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACETYPE_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEPROPERTY_HPP
#define LIB_API
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEAREA_HPP
#define LIB_API
#define OPENDLV_LOGIC_ACTION_AIMDIRECTION_HPP
#define LIB_API
#define OPENDLV_LOGIC_ACTION_AIMPOINT_HPP
#define LIB_API
#define OPENDLV_LOGIC_ACTION_PREVIEWPOINT_HPP
#define LIB_API
#define OPENDLV_LOGIC_COGNITION_GROUNDSTEERINGLIMIT_HPP
#define LIB_API
#define OPENDLV_LOGIC_COGNITION_GROUNDSPEEDLIMIT_HPP
#define LIB_API
Functions
template<typename T , class Visitor >
void doVisit (uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor)
template<typename T , class PreVisitor , class Visitor , class PostVisitor >
void doTripletForwardVisit (uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit)
Macro Definition Documentation
LIB_API [1/63]
#define LIB_API
LIB_API [2/63]
#define LIB_API
LIB_API [3/63]
#define LIB_API
LIB_API [4/63]
#define LIB_API
LIB_API [5/63]
#define LIB_API
LIB_API [6/63]
#define LIB_API
LIB_API [7/63]
#define LIB_API
LIB_API [8/63]
#define LIB_API
LIB_API [9/63]
#define LIB_API
LIB_API [10/63]
#define LIB_API
LIB_API [11/63]
#define LIB_API
LIB_API [12/63]
#define LIB_API
LIB_API [13/63]
#define LIB_API
LIB_API [14/63]
#define LIB_API
LIB_API [15/63]
#define LIB_API
LIB_API [16/63]
#define LIB_API
LIB_API [17/63]
#define LIB_API
LIB_API [18/63]
#define LIB_API
LIB_API [19/63]
#define LIB_API
LIB_API [20/63]
#define LIB_API
LIB_API [21/63]
#define LIB_API
LIB_API [22/63]
#define LIB_API
LIB_API [23/63]
#define LIB_API
LIB_API [24/63]
#define LIB_API
LIB_API [25/63]
#define LIB_API
LIB_API [26/63]
#define LIB_API
LIB_API [27/63]
#define LIB_API
LIB_API [28/63]
#define LIB_API
LIB_API [29/63]
#define LIB_API
LIB_API [30/63]
#define LIB_API
LIB_API [31/63]
#define LIB_API
LIB_API [32/63]
#define LIB_API
LIB_API [33/63]
#define LIB_API
LIB_API [34/63]
#define LIB_API
LIB_API [35/63]
#define LIB_API
LIB_API [36/63]
#define LIB_API
LIB_API [37/63]
#define LIB_API
LIB_API [38/63]
#define LIB_API
LIB_API [39/63]
#define LIB_API
LIB_API [40/63]
#define LIB_API
LIB_API [41/63]
#define LIB_API
LIB_API [42/63]
#define LIB_API
LIB_API [43/63]
#define LIB_API
LIB_API [44/63]
#define LIB_API
LIB_API [45/63]
#define LIB_API
LIB_API [46/63]
#define LIB_API
LIB_API [47/63]
#define LIB_API
LIB_API [48/63]
#define LIB_API
LIB_API [49/63]
#define LIB_API
LIB_API [50/63]
#define LIB_API
LIB_API [51/63]
#define LIB_API
LIB_API [52/63]
#define LIB_API
LIB_API [53/63]
#define LIB_API
LIB_API [54/63]
#define LIB_API
LIB_API [55/63]
#define LIB_API
LIB_API [56/63]
#define LIB_API
LIB_API [57/63]
#define LIB_API
LIB_API [58/63]
#define LIB_API
LIB_API [59/63]
#define LIB_API
LIB_API [60/63]
#define LIB_API
LIB_API [61/63]
#define LIB_API
LIB_API [62/63]
#define LIB_API
LIB_API [63/63]
#define LIB_API
OPENDLV_BODY_ACTUATORINFO_HPP
#define OPENDLV_BODY_ACTUATORINFO_HPP
OPENDLV_BODY_COMPONENTINFO_HPP
#define OPENDLV_BODY_COMPONENTINFO_HPP
OPENDLV_BODY_SENSORINFO_HPP
#define OPENDLV_BODY_SENSORINFO_HPP
OPENDLV_BODY_SIGNALINFO_HPP
#define OPENDLV_BODY_SIGNALINFO_HPP
OPENDLV_LOGIC_ACTION_AIMDIRECTION_HPP
#define OPENDLV_LOGIC_ACTION_AIMDIRECTION_HPP
OPENDLV_LOGIC_ACTION_AIMPOINT_HPP
#define OPENDLV_LOGIC_ACTION_AIMPOINT_HPP
OPENDLV_LOGIC_ACTION_PREVIEWPOINT_HPP
#define OPENDLV_LOGIC_ACTION_PREVIEWPOINT_HPP
OPENDLV_LOGIC_COGNITION_GROUNDSPEEDLIMIT_HPP
#define OPENDLV_LOGIC_COGNITION_GROUNDSPEEDLIMIT_HPP
OPENDLV_LOGIC_COGNITION_GROUNDSTEERINGLIMIT_HPP
#define OPENDLV_LOGIC_COGNITION_GROUNDSTEERINGLIMIT_HPP
OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACE_HPP
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACE_HPP
OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEAREA_HPP
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEAREA_HPP
OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEPROPERTY_HPP
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACEPROPERTY_HPP
OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACETYPE_HPP
#define OPENDLV_LOGIC_PERCEPTION_GROUNDSURFACETYPE_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECT_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECT_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECTANGULARBLOB_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECTANGULARBLOB_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECTDIRECTION_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECTDIRECTION_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECTDISTANCE_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECTDISTANCE_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECTPROPERTY_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECTPROPERTY_HPP
OPENDLV_LOGIC_PERCEPTION_OBJECTTYPE_HPP
#define OPENDLV_LOGIC_PERCEPTION_OBJECTTYPE_HPP
OPENDLV_LOGIC_SENSATION_DIRECTION_HPP
#define OPENDLV_LOGIC_SENSATION_DIRECTION_HPP
OPENDLV_LOGIC_SENSATION_EQUILIBRIOCEPTION_HPP
#define OPENDLV_LOGIC_SENSATION_EQUILIBRIOCEPTION_HPP
OPENDLV_LOGIC_SENSATION_GEOLOCATION_HPP
#define OPENDLV_LOGIC_SENSATION_GEOLOCATION_HPP
OPENDLV_LOGIC_SENSATION_POINT_HPP
#define OPENDLV_LOGIC_SENSATION_POINT_HPP
OPENDLV_PROXY_ACCELERATIONREADING_HPP
#define OPENDLV_PROXY_ACCELERATIONREADING_HPP
OPENDLV_PROXY_ALTITUDEREADING_HPP
#define OPENDLV_PROXY_ALTITUDEREADING_HPP
OPENDLV_PROXY_ANGLEREADING_HPP
#define OPENDLV_PROXY_ANGLEREADING_HPP
OPENDLV_PROXY_ANGLEREQUEST_HPP
#define OPENDLV_PROXY_ANGLEREQUEST_HPP
OPENDLV_PROXY_ANGULARVELOCITYREADING_HPP
#define OPENDLV_PROXY_ANGULARVELOCITYREADING_HPP
OPENDLV_PROXY_DISTANCEREADING_HPP
#define OPENDLV_PROXY_DISTANCEREADING_HPP
OPENDLV_PROXY_GEODETICHEADINGREADING_HPP
#define OPENDLV_PROXY_GEODETICHEADINGREADING_HPP
OPENDLV_PROXY_GEODETICWGS84READING_HPP
#define OPENDLV_PROXY_GEODETICWGS84READING_HPP
OPENDLV_PROXY_GROUNDACCELERATIONREQUEST_HPP
#define OPENDLV_PROXY_GROUNDACCELERATIONREQUEST_HPP
OPENDLV_PROXY_GROUNDDECELERATIONREQUEST_HPP
#define OPENDLV_PROXY_GROUNDDECELERATIONREQUEST_HPP
OPENDLV_PROXY_GROUNDSPEEDREADING_HPP
#define OPENDLV_PROXY_GROUNDSPEEDREADING_HPP
OPENDLV_PROXY_GROUNDSPEEDREQUEST_HPP
#define OPENDLV_PROXY_GROUNDSPEEDREQUEST_HPP
OPENDLV_PROXY_GROUNDSTEERINGREADING_HPP
#define OPENDLV_PROXY_GROUNDSTEERINGREADING_HPP
OPENDLV_PROXY_GROUNDSTEERINGREQUEST_HPP
#define OPENDLV_PROXY_GROUNDSTEERINGREQUEST_HPP
OPENDLV_PROXY_IMAGEREADING_HPP
#define OPENDLV_PROXY_IMAGEREADING_HPP
OPENDLV_PROXY_IMAGEREADINGSHARED_HPP
#define OPENDLV_PROXY_IMAGEREADINGSHARED_HPP
OPENDLV_PROXY_MAGNETICFIELDREADING_HPP
#define OPENDLV_PROXY_MAGNETICFIELDREADING_HPP
OPENDLV_PROXY_PEDALPOSITIONREADING_HPP
#define OPENDLV_PROXY_PEDALPOSITIONREADING_HPP
OPENDLV_PROXY_PEDALPOSITIONREQUEST_HPP
#define OPENDLV_PROXY_PEDALPOSITIONREQUEST_HPP
OPENDLV_PROXY_POINTCLOUDREADING_HPP
#define OPENDLV_PROXY_POINTCLOUDREADING_HPP
OPENDLV_PROXY_POINTCLOUDREADINGSHARED_HPP
#define OPENDLV_PROXY_POINTCLOUDREADINGSHARED_HPP
OPENDLV_PROXY_PRESSUREREADING_HPP
#define OPENDLV_PROXY_PRESSUREREADING_HPP
OPENDLV_PROXY_PRESSUREREQUEST_HPP
#define OPENDLV_PROXY_PRESSUREREQUEST_HPP
OPENDLV_PROXY_PULSEWIDTHMODULATIONREQUEST_HPP
#define OPENDLV_PROXY_PULSEWIDTHMODULATIONREQUEST_HPP
OPENDLV_PROXY_SWITCHSTATEREADING_HPP
#define OPENDLV_PROXY_SWITCHSTATEREADING_HPP
OPENDLV_PROXY_SWITCHSTATEREQUEST_HPP
#define OPENDLV_PROXY_SWITCHSTATEREQUEST_HPP
OPENDLV_PROXY_TEMPERATUREREADING_HPP
#define OPENDLV_PROXY_TEMPERATUREREADING_HPP
OPENDLV_PROXY_TEMPERATUREREQUEST_HPP
#define OPENDLV_PROXY_TEMPERATUREREQUEST_HPP
OPENDLV_PROXY_TORQUEREADING_HPP
#define OPENDLV_PROXY_TORQUEREADING_HPP
OPENDLV_PROXY_TORQUEREQUEST_HPP
#define OPENDLV_PROXY_TORQUEREQUEST_HPP
OPENDLV_PROXY_VOLTAGEREADING_HPP
#define OPENDLV_PROXY_VOLTAGEREADING_HPP
OPENDLV_PROXY_VOLTAGEREQUEST_HPP
#define OPENDLV_PROXY_VOLTAGEREQUEST_HPP
OPENDLV_PROXY_WEIGHTREADING_HPP
#define OPENDLV_PROXY_WEIGHTREADING_HPP
OPENDLV_PROXY_WHEELSPEEDREADING_HPP
#define OPENDLV_PROXY_WHEELSPEEDREADING_HPP
OPENDLV_PROXY_WHEELSPEEDREQUEST_HPP
#define OPENDLV_PROXY_WHEELSPEEDREQUEST_HPP
OPENDLV_SIM_FRAME_HPP
#define OPENDLV_SIM_FRAME_HPP
OPENDLV_SIM_KINEMATICSTATE_HPP
#define OPENDLV_SIM_KINEMATICSTATE_HPP
OPENDLV_SYSTEM_NETWORKSTATUSMESSAGE_HPP
#define OPENDLV_SYSTEM_NETWORKSTATUSMESSAGE_HPP
OPENDLV_SYSTEM_SIGNALSTATUSMESSAGE_HPP
#define OPENDLV_SYSTEM_SIGNALSTATUSMESSAGE_HPP
OPENDLV_SYSTEM_SYSTEMOPERATIONSTATE_HPP
#define OPENDLV_SYSTEM_SYSTEMOPERATIONSTATE_HPP
TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
Function Documentation
doTripletForwardVisit()
template<typename T , class PreVisitor , class Visitor , class PostVisitor >
void doTripletForwardVisit (uint32_t fieldIdentifier, std::string && typeName, std::string && name, T & value, PreVisitor && preVisit, Visitor && visit, PostVisitor && postVisit)
                                                                                                                                                                        {
    tripletForwardVisitorSelector<isTripletForwardVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, std::move(preVisit), std::move(visit), std::move(postVisit)); // NOLINT
}
References fieldIdentifier().
Referenced by opendlv::sim::Frame::accept(), opendlv::sim::KinematicState::accept(), opendlv::body::ComponentInfo::accept(), opendlv::body::ActuatorInfo::accept(), opendlv::body::SensorInfo::accept(), opendlv::body::SignalInfo::accept(), opendlv::proxy::AccelerationReading::accept(), opendlv::proxy::AngularVelocityReading::accept(), opendlv::proxy::MagneticFieldReading::accept(), opendlv::proxy::AltitudeReading::accept(), opendlv::proxy::PressureReading::accept(), opendlv::proxy::TemperatureReading::accept(), opendlv::proxy::TorqueReading::accept(), opendlv::proxy::VoltageReading::accept(), opendlv::proxy::AngleReading::accept(), opendlv::proxy::DistanceReading::accept(), opendlv::proxy::SwitchStateReading::accept(), opendlv::proxy::PedalPositionReading::accept(), opendlv::proxy::GroundSteeringReading::accept(), opendlv::proxy::GroundSpeedReading::accept(), opendlv::proxy::WheelSpeedReading::accept(), opendlv::proxy::WeightReading::accept(), opendlv::proxy::GeodeticHeadingReading::accept(), opendlv::proxy::GeodeticWgs84Reading::accept(), opendlv::proxy::ImageReading::accept(), opendlv::proxy::ImageReadingShared::accept(), opendlv::proxy::PointCloudReading::accept(), opendlv::proxy::PointCloudReadingShared::accept(), opendlv::proxy::PressureRequest::accept(), opendlv::proxy::TemperatureRequest::accept(), opendlv::proxy::TorqueRequest::accept(), opendlv::proxy::VoltageRequest::accept(), opendlv::proxy::AngleRequest::accept(), opendlv::proxy::SwitchStateRequest::accept(), opendlv::proxy::PedalPositionRequest::accept(), opendlv::proxy::PulseWidthModulationRequest::accept(), opendlv::proxy::GroundSteeringRequest::accept(), opendlv::proxy::GroundSpeedRequest::accept(), opendlv::proxy::GroundAccelerationRequest::accept(), opendlv::proxy::GroundDecelerationRequest::accept(), opendlv::proxy::WheelSpeedRequest::accept(), opendlv::system::SignalStatusMessage::accept(), opendlv::system::SystemOperationState::accept(), opendlv::system::NetworkStatusMessage::accept(), opendlv::logic::sensation::Direction::accept(), opendlv::logic::sensation::Point::accept(), opendlv::logic::sensation::Geolocation::accept(), opendlv::logic::sensation::Equilibrioception::accept(), opendlv::logic::perception::Object::accept(), opendlv::logic::perception::ObjectType::accept(), opendlv::logic::perception::ObjectProperty::accept(), opendlv::logic::perception::ObjectDirection::accept(), opendlv::logic::perception::ObjectDistance::accept(), opendlv::logic::perception::ObjectAngularBlob::accept(), opendlv::logic::perception::GroundSurface::accept(), opendlv::logic::perception::GroundSurfaceType::accept(), opendlv::logic::perception::GroundSurfaceProperty::accept(), opendlv::logic::perception::GroundSurfaceArea::accept(), opendlv::logic::action::AimDirection::accept(), opendlv::logic::action::AimPoint::accept(), opendlv::logic::action::PreviewPoint::accept(), opendlv::logic::cognition::GroundSteeringLimit::accept(), and opendlv::logic::cognition::GroundSpeedLimit::accept().
doVisit()
template<typename T , class Visitor >
void doVisit (uint32_t fieldIdentifier, std::string && typeName, std::string && name, T & value, Visitor & visitor)
                                                                                                           {
    visitorSelector<isVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, visitor);
}
References fieldIdentifier().
Referenced by opendlv::sim::Frame::accept(), opendlv::sim::KinematicState::accept(), opendlv::body::ComponentInfo::accept(), opendlv::body::ActuatorInfo::accept(), opendlv::body::SensorInfo::accept(), opendlv::body::SignalInfo::accept(), opendlv::proxy::AccelerationReading::accept(), opendlv::proxy::AngularVelocityReading::accept(), opendlv::proxy::MagneticFieldReading::accept(), opendlv::proxy::AltitudeReading::accept(), opendlv::proxy::PressureReading::accept(), opendlv::proxy::TemperatureReading::accept(), opendlv::proxy::TorqueReading::accept(), opendlv::proxy::VoltageReading::accept(), opendlv::proxy::AngleReading::accept(), opendlv::proxy::DistanceReading::accept(), opendlv::proxy::SwitchStateReading::accept(), opendlv::proxy::PedalPositionReading::accept(), opendlv::proxy::GroundSteeringReading::accept(), opendlv::proxy::GroundSpeedReading::accept(), opendlv::proxy::WheelSpeedReading::accept(), opendlv::proxy::WeightReading::accept(), opendlv::proxy::GeodeticHeadingReading::accept(), opendlv::proxy::GeodeticWgs84Reading::accept(), opendlv::proxy::ImageReading::accept(), opendlv::proxy::ImageReadingShared::accept(), opendlv::proxy::PointCloudReading::accept(), opendlv::proxy::PointCloudReadingShared::accept(), opendlv::proxy::PressureRequest::accept(), opendlv::proxy::TemperatureRequest::accept(), opendlv::proxy::TorqueRequest::accept(), opendlv::proxy::VoltageRequest::accept(), opendlv::proxy::AngleRequest::accept(), opendlv::proxy::SwitchStateRequest::accept(), opendlv::proxy::PedalPositionRequest::accept(), opendlv::proxy::PulseWidthModulationRequest::accept(), opendlv::proxy::GroundSteeringRequest::accept(), opendlv::proxy::GroundSpeedRequest::accept(), opendlv::proxy::GroundAccelerationRequest::accept(), opendlv::proxy::GroundDecelerationRequest::accept(), opendlv::proxy::WheelSpeedRequest::accept(), opendlv::system::SignalStatusMessage::accept(), opendlv::system::SystemOperationState::accept(), opendlv::system::NetworkStatusMessage::accept(), opendlv::logic::sensation::Direction::accept(), opendlv::logic::sensation::Point::accept(), opendlv::logic::sensation::Geolocation::accept(), opendlv::logic::sensation::Equilibrioception::accept(), opendlv::logic::perception::Object::accept(), opendlv::logic::perception::ObjectType::accept(), opendlv::logic::perception::ObjectProperty::accept(), opendlv::logic::perception::ObjectDirection::accept(), opendlv::logic::perception::ObjectDistance::accept(), opendlv::logic::perception::ObjectAngularBlob::accept(), opendlv::logic::perception::GroundSurface::accept(), opendlv::logic::perception::GroundSurfaceType::accept(), opendlv::logic::perception::GroundSurfaceProperty::accept(), opendlv::logic::perception::GroundSurfaceArea::accept(), opendlv::logic::action::AimDirection::accept(), opendlv::logic::action::AimPoint::accept(), opendlv::logic::action::PreviewPoint::accept(), opendlv::logic::cognition::GroundSteeringLimit::accept(), and opendlv::logic::cognition::GroundSpeedLimit::accept().