src/steering.cpp File Reference
#include `steering-angle-generator.hpp`
Functions
void steer ()
the primary function to return the computed steering angle
void do_magic ()
your a wizard, you can do magic here
std::string get_timestamp (std::pair< bool, cluon::data::TimeStamp > ts, time_t now)
returns the timestamp of the current frame
Function Documentation
do_magic()
void do_magic ()
your a wizard, you can do magic here
{
}
Referenced by steer().
get_timestamp()
std::string get_timestamp (std::pair< bool, cluon::data::TimeStamp > ts, time_t now)
returns the timestamp of the current frame
Parameters
ts
now
Returns
std::string
{
  char buf[60];
  std::stringstream s;
  if (ts.first)
  {
    strftime(buf, 60, "%Y-%m-%dT%H:%M:%SZ", gmtime(&now));
    s << "Now: " << buf << ", ts: "
      << ts.second.seconds() << "."
      << ts.second.microseconds();
  }
  else
  {
    std::stringstream ss;
    s << "No timestamp available.";
  }
  return s.str();
}
Referenced by main().
steer()
void steer ()
the primary function to return the computed steering angle
{
  do_magic();
}
References do_magic().