peg::Ope::Visitor Struct Reference
#include <cluon-complete.hpp>
Public Member Functions
virtual ~Visitor ()
virtual void visit (Sequence &)
virtual void visit (PrioritizedChoice &)
virtual void visit (ZeroOrMore &)
virtual void visit (OneOrMore &)
virtual void visit (Option &)
virtual void visit (AndPredicate &)
virtual void visit (NotPredicate &)
virtual void visit (LiteralString &)
virtual void visit (CharacterClass &)
virtual void visit (Character &)
virtual void visit (AnyCharacter &)
virtual void visit (CaptureScope &)
virtual void visit (Capture &)
virtual void visit (TokenBoundary &)
virtual void visit (Ignore &)
virtual void visit (User &)
virtual void visit (WeakHolder &)
virtual void visit (Holder &)
virtual void visit (Reference &)
virtual void visit (Whitespace &)
virtual void visit (BackReference &)
Constructor & Destructor Documentation
 Visitor()
virtual peg::Ope::Visitor::~Visitor () [inline], [virtual]
{}
Member Function Documentation
visit() [1/21]
virtual void peg::Ope::Visitor::visit (AndPredicate &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [2/21]
virtual void peg::Ope::Visitor::visit (AnyCharacter &) [inline], [virtual]
Reimplemented in peg::DetectLeftRecursion, and peg::FindReference.
{}
visit() [3/21]
virtual void peg::Ope::Visitor::visit (BackReference &) [inline], [virtual]
Reimplemented in peg::DetectLeftRecursion.
{}
visit() [4/21]
virtual void peg::Ope::Visitor::visit (Capture &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [5/21]
virtual void peg::Ope::Visitor::visit (CaptureScope &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [6/21]
virtual void peg::Ope::Visitor::visit (Character &) [inline], [virtual]
Reimplemented in peg::DetectLeftRecursion, and peg::FindReference.
{}
visit() [7/21]
virtual void peg::Ope::Visitor::visit (CharacterClass &) [inline], [virtual]
Reimplemented in peg::DetectLeftRecursion, and peg::FindReference.
{}
visit() [8/21]
virtual void peg::Ope::Visitor::visit (Holder &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [9/21]
virtual void peg::Ope::Visitor::visit (Ignore &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [10/21]
virtual void peg::Ope::Visitor::visit (LiteralString &) [inline], [virtual]
Reimplemented in peg::IsLiteralToken, peg::DetectLeftRecursion, and peg::FindReference.
{}
visit() [11/21]
virtual void peg::Ope::Visitor::visit (NotPredicate &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [12/21]
virtual void peg::Ope::Visitor::visit (OneOrMore &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [13/21]
virtual void peg::Ope::Visitor::visit (Option &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [14/21]
virtual void peg::Ope::Visitor::visit (PrioritizedChoice &) [inline], [virtual]
Reimplemented in peg::IsPrioritizedChoice, peg::AssignIDToDefinition, peg::IsLiteralToken, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [15/21]
virtual void peg::Ope::Visitor::visit (Reference &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [16/21]
virtual void peg::Ope::Visitor::visit (Sequence &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
Referenced by peg::Sequence::accept(), peg::PrioritizedChoice::accept(), peg::ZeroOrMore::accept(), peg::OneOrMore::accept(), peg::Option::accept(), peg::AndPredicate::accept(), peg::NotPredicate::accept(), peg::LiteralString::accept(), peg::CharacterClass::accept(), peg::Character::accept(), peg::AnyCharacter::accept(), peg::CaptureScope::accept(), peg::Capture::accept(), peg::TokenBoundary::accept(), peg::Ignore::accept(), peg::User::accept(), peg::WeakHolder::accept(), peg::Holder::accept(), peg::Reference::accept(), peg::Whitespace::accept(), and peg::BackReference::accept().
visit() [17/21]
virtual void peg::Ope::Visitor::visit (TokenBoundary &) [inline], [virtual]
Reimplemented in peg::TokenChecker, peg::AssignIDToDefinition, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [18/21]
virtual void peg::Ope::Visitor::visit (User &) [inline], [virtual]
Reimplemented in peg::DetectLeftRecursion.
{}
visit() [19/21]
virtual void peg::Ope::Visitor::visit (WeakHolder &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [20/21]
virtual void peg::Ope::Visitor::visit (Whitespace &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
visit() [21/21]
virtual void peg::Ope::Visitor::visit (ZeroOrMore &) [inline], [virtual]
Reimplemented in peg::AssignIDToDefinition, peg::TokenChecker, peg::DetectLeftRecursion, peg::ReferenceChecker, peg::LinkReferences, and peg::FindReference.
{}
The documentation for this struct was generated from the following file:
src/cluon-complete.hpp