peg::FindReference Struct Reference
#include <cluon-complete.hpp>
Public Member Functions
FindReference (const std::vector< std::shared_ptr< Ope > > &args, const std::vector< std::string > &params)
void visit (Sequence &ope) override
void visit (PrioritizedChoice &ope) override
void visit (ZeroOrMore &ope) override
void visit (OneOrMore &ope) override
void visit (Option &ope) override
void visit (AndPredicate &ope) override
void visit (NotPredicate &ope) override
void visit (LiteralString &ope) override
void visit (CharacterClass &ope) override
void visit (Character &ope) override
void visit (AnyCharacter &ope) override
void visit (CaptureScope &ope) override
void visit (Capture &ope) override
void visit (TokenBoundary &ope) override
void visit (Ignore &ope) override
void visit (WeakHolder &ope) override
void visit (Holder &ope) override
void visit (Reference &ope) override
void visit (Whitespace &ope) override
Public Attributes
std::shared_ptr< Ope > found_ope
Private Attributes
const std::vector< std::shared_ptr< Ope > > & args_
const std::vector< std::string > & params_
Constructor & Destructor Documentation
FindReference()
peg::FindReference::FindReference (const std::vector< std::shared_ptr< Ope > > & args, const std::vector< std::string > & params) [inline]
        : args_(args), params_(params) {}
Member Function Documentation
visit() [1/19]
void peg::FindReference::visit (AndPredicate & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = apd(found_ope); }
References peg::apd(), and peg::AndPredicate::ope_.
visit() [2/19]
void peg::FindReference::visit (AnyCharacter & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ found_ope = ope.shared_from_this(); }
visit() [3/19]
void peg::FindReference::visit (Capture & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = cap(found_ope, ope.match_action_); }
References peg::cap(), peg::Capture::match_action_, and peg::Capture::ope_.
visit() [4/19]
void peg::FindReference::visit (CaptureScope & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = csc(found_ope); }
References peg::csc(), and peg::CaptureScope::ope_.
visit() [5/19]
void peg::FindReference::visit (Character & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ found_ope = ope.shared_from_this(); }
visit() [6/19]
void peg::FindReference::visit (CharacterClass & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ found_ope = ope.shared_from_this(); }
visit() [7/19]
void peg::FindReference::visit (Holder & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); }
References peg::Holder::ope_.
visit() [8/19]
void peg::FindReference::visit (Ignore & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = ign(found_ope); }
References peg::ign(), and peg::Ignore::ope_.
visit() [9/19]
void peg::FindReference::visit (LiteralString & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ found_ope = ope.shared_from_this(); }
visit() [10/19]
void peg::FindReference::visit (NotPredicate & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = npd(found_ope); }
References peg::npd(), and peg::NotPredicate::ope_.
visit() [11/19]
void peg::FindReference::visit (OneOrMore & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = oom(found_ope); }
References peg::oom(), and peg::OneOrMore::ope_.
visit() [12/19]
void peg::FindReference::visit (Option & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = opt(found_ope); }
References peg::Option::ope_, and peg::opt().
visit() [13/19]
void peg::FindReference::visit (PrioritizedChoice & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
                                                {
        std::vector<std::shared_ptr<Ope>> opes;
        for (auto o: ope.opes_) {
            o->accept(*this);
            opes.push_back(found_ope);
        }
        found_ope = std::make_shared<PrioritizedChoice>(opes);
    }
References peg::PrioritizedChoice::opes_.
visit() [14/19]
void peg::FindReference::visit (Reference & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
                                               {
    for (size_t i = 0; i < args_.size(); i++) {
        const auto& name = params_[i];
        if (name == ope.name_) {
            found_ope = args_[i];
            return;
        }
    }
    found_ope = ope.shared_from_this();
}
References peg::Reference::name_.
visit() [15/19]
void peg::FindReference::visit (Sequence & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
                                       {
        std::vector<std::shared_ptr<Ope>> opes;
        for (auto o: ope.opes_) {
            o->accept(*this);
            opes.push_back(found_ope);
        }
        found_ope = std::make_shared<Sequence>(opes);
    }
References peg::Sequence::opes_.
visit() [16/19]
void peg::FindReference::visit (TokenBoundary & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = tok(found_ope); }
References peg::TokenBoundary::ope_, and peg::tok().
visit() [17/19]
void peg::FindReference::visit (WeakHolder & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.weak_.lock()->accept(*this); }
References peg::WeakHolder::weak_.
visit() [18/19]
void peg::FindReference::visit (Whitespace & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = wsp(found_ope); }
References peg::Whitespace::ope_, and peg::wsp().
visit() [19/19]
void peg::FindReference::visit (ZeroOrMore & ope) [inline], [override], [virtual]
Reimplemented from peg::Ope::Visitor.
{ ope.ope_->accept(*this); found_ope = zom(found_ope); }
References peg::ZeroOrMore::ope_, and peg::zom().
Member Data Documentation
args_
const std::vector<std::shared_ptr<Ope> >& peg::FindReference::args_ [private]
found_ope
std::shared_ptr<Ope> peg::FindReference::found_ope
Referenced by peg::Reference::parse().
params_
const std::vector<std::string>& peg::FindReference::params_ [private]
The documentation for this struct was generated from the following file:
src/cluon-complete.hpp