linb::any::vtable_stack< T > Struct Template Reference
VTable for stack allocated storage.
Static Public Member Functions
static const std::type_info & type () noexcept
static void destroy (storage_union &storage) noexcept
static void copy (const storage_union &src, storage_union &dest)
static void move (storage_union &src, storage_union &dest) noexcept
static void swap (storage_union &lhs, storage_union &rhs) noexcept
Detailed Description
template<typename T>
struct linb::any::vtable_stack< T >
VTable for stack allocated storage.
Member Function Documentation
copy()
template<typename T >
static void linb::any::vtable_stack< T >::copy (const storage_union & src, storage_union & dest) [inline], [static]
        {
            new (&dest.stack) T(reinterpret_cast<const T&>(src.stack));
        }
References linb::any::storage_union::stack.
destroy()
template<typename T >
static void linb::any::vtable_stack< T >::destroy (storage_union & storage) [inline], [static], [noexcept]
        {
            reinterpret_cast<T*>(&storage.stack)->~T();
        }
References linb::any::storage_union::stack, and linb::any::storage.
Referenced by linb::any::vtable_stack< T >::move().
move()
template<typename T >
static void linb::any::vtable_stack< T >::move (storage_union & src, storage_union & dest) [inline], [static], [noexcept]
        {
            // one of the conditions for using vtable_stack is a nothrow move constructor,
            // so this move constructor will never throw a exception.
            new (&dest.stack) T(std::move(reinterpret_cast<T&>(src.stack)));
            destroy(src);
        }
References linb::any::vtable_stack< T >::destroy().
Referenced by linb::any::vtable_stack< T >::swap().
swap()
template<typename T >
static void linb::any::vtable_stack< T >::swap (storage_union & lhs, storage_union & rhs) [inline], [static], [noexcept]
        {
            storage_union tmp_storage;
            move(rhs, tmp_storage);
            move(lhs, rhs);
            move(tmp_storage, lhs);
        }
References linb::any::vtable_stack< T >::move().
type()
template<typename T >
static const std::type_info & linb::any::vtable_stack< T >::type () [inline], [static], [noexcept]
        {
            return typeid(T);
        }
The documentation for this struct was generated from the following file:
src/cluon-complete.hpp